. /usr/lib/ybs/funcs

post_install() {
	gnome2_install_schema /etc/gconf/schemas/desktop_gnome_url_handlers.schemas
	gnome2_install_schema /etc/gconf/schemas/desktop_default_applications.schemas
	gnome2_install_schema /etc/gconf/schemas/system_dns_sd.schemas
	gnome2_install_schema /etc/gconf/schemas/system_smb.schemas
	gnome2_install_schema /etc/gconf/schemas/system_http_proxy.schemas
	gnome2_mime_database_update
	gnome2_gconfd_reload
}
