#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Javascript bindings for Webkit-GTK and GNOME libraries"
HOMEPAGE="http://live.gnome.org/Seed"
LICENSE="LGPL"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/seed/2.30/"$N-$V$R".tar.bz2"

RDEPEND="gobject-introspection mpfr webkitgtk"
BDEPEND="gnome-js-common"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_patch() {
	dopatch Fix-build-with-latest-GI.patch
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

