. /usr/lib/ybs/funcs

files=" /etc/gconf/schemas/gthumb_webalbums.schemas
    /etc/gconf/schemas/gthumb-slideshow.schemas
    /etc/gconf/schemas/gthumb.schemas
    /etc/gconf/schemas/gthumb_resize_options.schemas
    /etc/gconf/schemas/gthumb_resize_images.schemas
    /etc/gconf/schemas/gthumb_rename_series.schemas
    /etc/gconf/schemas/gthumb-pixbuf-savers.schemas
    /etc/gconf/schemas/gthumb-picasaweb.schemas
    /etc/gconf/schemas/gthumb_photo_importer.schemas
    /etc/gconf/schemas/gthumb-importer.schemas
    /etc/gconf/schemas/gthumb-image-viewer.schemas
    /etc/gconf/schemas/gthumb_image_print.schemas
    /etc/gconf/schemas/gthumb-gstreamer.schemas
    /etc/gconf/schemas/gthumb_crop_options.schemas
    /etc/gconf/schemas/gthumb_convert_format.schemas
    /etc/gconf/schemas/gthumb-comments.schemas "

post_install() {
    gnome2_install_schema "$files"
    gnome2_desktop_database_update
    gnome2_icon_cache_update 
    gnome2_mime_database_update
}

pre_remove() {
    gnome2_uninstall_schema "$files"
}

post_remove() {
    gnome2_desktop_database_update
    gnome2_icon_cache_update
    gnome2_mime_database_update
}

post_upgrade() {
    post_install
}

post_downgrade() {
    post_install
}

