#
# Ylmf OS package build script
#

DESCRIPTION="libzip is a C library for reading, creating, and modifying zip archives."
HOMEPAGE="http://www.nih.at/libzip/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.nih.at/"$N"/"$N-$V".tar.bz2"

RDEPEND="glibc zlib"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	cd "$destdir"
	doln /usr/lib/libzip/include/zipconf.h  usr/include/zipconf.h
}

