#
# YLmf_OS package build script
#

DESCRIPTION="libzip is a C library for reading, creating, and modifying zip archives."
HOMEPAGE="http://www.nih.at/libzip/"
REPO=""
LICENSE="GPL"
#PRIORITY="required"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.nih.at/"$N"/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
