#
# Ylmf OS package build script
#

DESCRIPTION="Small but powerful ftp client"
HOMEPAGE="http://lftp.yar.ru/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.yars.free.net/pub/source/"$N"/"$N-$V".tar.xz"

RDEPEND="expat gcc-lib glibc gnutls libgcrypt libgpg-error libtasn1 ncurses readline zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

