#
# YLmf_OS package build script
#

DESCRIPTION="Compiz Fusion Window Decorator Plugins"
HOMEPAGE="http://www.compiz.org/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"
REPO="testing"

SRC_URI="http://releases.compiz-fusion.org/"$V$R"/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" compiz pango cairo mesa compiz-bcop"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--enable-schemas --disable-schemas-install"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

pbs_postinst() {
	SCHEMAS="/etc/gconf/schemas/compiz-3d.schemas
	 	 /etc/gconf/schemas/compiz-showmouse.schemas
	  	 /etc/gconf/schemas/compiz-scalefilter.schemas
	         /etc/gconf/schemas/compiz-notification.schemas
	         /etc/gconf/schemas/compiz-group.schemas
	         /etc/gconf/schemas/compiz-cubeaddon.schemas
	         /etc/gconf/schemas/compiz-animationaddon.schemas
	         /etc/gconf/schemas/compiz-wallpaper.schemas
	         /etc/gconf/schemas/compiz-widget.schemas
		 /etc/gconf/schemas/compiz-trailfocus.schemas
		 /etc/gconf/schemas/compiz-splash.schemas
		 /etc/gconf/schemas/compiz-showdesktop.schemas
		 /etc/gconf/schemas/compiz-shelf.schemas
		 /etc/gconf/schemas/compiz-reflex.schemas
		 /etc/gconf/schemas/compiz-mblur.schemas
		 /etc/gconf/schemas/compiz-maximumize.schemas
		 /etc/gconf/schemas/compiz-loginout.schemas
		 /etc/gconf/schemas/compiz-grid.schemas
		 /etc/gconf/schemas/compiz-gears.schemas
		 /etc/gconf/schemas/compiz-firepaint.schemas
		 /etc/gconf/schemas/compiz-fadedesktop.schemas
		 /etc/gconf/schemas/compiz-extrawm.schemas
		 /etc/gconf/schemas/compiz-crashhandler.schemas
		 /etc/gconf/schemas/compiz-bicubic.schemas
		 /etc/gconf/schemas/compiz-bench.schemas
		 /etc/gconf/schemas/compiz-addhelper.schemas"
        for schema in $SCHEMAS; do
		gnome2_install_schema "$schema"
        done																        
	gnome2_desktop_database_update
	gnome2_gconfd_reload
}
