#
# YLmf_OS package build script
#

DESCRIPTION="A set of programs to assemble and manipulate binary and object files (mingw)"
HOMEPAGE="http://www.mingw.org/"
LICENSE="GPL"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://nchc.dl.sourceforge.net/project/mingw/MinGW/BaseSystem/GNU-Binutils/binutils-2.21/binutils-2.21-2-mingw32-src.tar.lzma"

RDEPEND="glibc zlib"
BDEPEND=""
RECOMMENDED=""

NOTES="assembler, linker and library management tools; these
       must be built for the i386-mingw32 target, and should be
       installed prior to building GCC itself."

pbs_unpack() {
	ypkg_unpack
}

pbs_config() {
	YPB_CONFIG=" --target=i486-mingw32
	             --host=$CHOST
		     --build=$CHOST
		     --prefix=/usr
		     --disable-nls 
	             --enable-shared "
	ypkg_config
}

pbs_build() {
	ypkg_make 
}

pbs_install() {
	ypkg_mkinstall
        rm -rf "$YPPATH_DEST"/usr/lib
        rm -rf "$YPPATH_DEST"/usr/share/{info,man}
}	
