#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="application logo icon collection"
HOMEPAGE="http://www.startos.org/"
LICENSE="custom"
PACKAGER="StartOS Developers"
YARCH="any"

SRC_URI="git://git.ylmf.com/app-info.git"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_install() {
    docp icon ads "$PKGDIR"/usr/share/app-info/
}

