#
# YLmf_OS package build script
#

DESCRIPTION="xfs filesystem utilities"
HOMEPAGE="http://oss.sgi.com/projects/xfs/"
LICENSE="GPL"
PACKAGER="YLmf OS Developers <ylmfos@115.com>"

SRC_URI="git://oss.sgi.com/xfs/cmds/"$N""

RDEPEND="glibc util-linux-ng "
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export DEBUG=-DNDEBUG
	config+="--enable-gettext"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	make DIST_ROOT="$destdir" install install-dev
}

