#
# YLmf_OS package build script
#

DESCRIPTION="X.Org XRes library"
HOMEPAGE="http://www.x.org/wiki/"
 
SRCURL="http://www.x.org/releases/X11R7.5/src/lib"
SRC_URI="$SRCURL/libXres-1.0.4.tar.bz2"

RDEPEND="libX11 libXext libxcb libXau libXdmcp"
BDEPEND=""

pbs_unpack()
{
        dounpack
}

pbs_config()
{
	
	config+=" --sysconfdir=/etc --mandir=/usr/share/man --localstatedir=/var "
	doconfig
}

pbs_build()
{
	domake
}

pbs_install()
{
	domkinstall
}
