#
# YLmf_OS package build script
#

DESCRIPTION="Microcode for the Intel PRO/Wireless 3945ABG miniPCI express adapter"
HOMEPAGE="http://www.bughost.org/ipw3945/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://www.bughost.org/ipw3945/ucode/ipw3945-ucode-"$V".tgz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_install() {
	ypkg_docp *.ucode "$YPPATH_DEST"/lib/firmware/
	ypkg_dodoc README* LICENSE* 
}

