#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Utility to apply diffs to files"
HOMEPAGE="http://savannah.gnu.org/projects/patch"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="ftp://ftp.gnu.org/gnu/"$N"/"$N-$V".tar.bz2"

RDEPEND="glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

