#
# YLmf_OS package build script
#

DESCRIPTION="libfolks is a library that aggregates people from multiple sources"
HOMEPAGE="http://telepathy.freedesktop.org/wiki/Folks"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.acc.umu.se/pub/gnome/sources/"$N"/0.3/"$N-$V".tar.bz2"

RDEPEND="dbus dbus-glib glib2 glibc libgee libxml2 telepathy-glib zlib"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

