#
# YLmf_OS package build script
#

DESCRIPTION="a simple http server class"
HOMEPAGE="http://search.cpan.org/"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"CKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YVERSION="1"
YARCH="any"

SRC_URI="http://mirror.osqdu.org/CPAN/authors/id/G/GA/GAAS/HTTP-Daemon-"$V".tar.gz"

RDEPEND="perl http-date-perl http-message-perl lwp-mediatypes"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

