#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="a simple http server class"
HOMEPAGE="http://search.cpan.org/"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"CKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://mirror.osqdu.org/CPAN/authors/id/G/GA/GAAS/HTTP-Daemon-"$V".tar.gz"

RDEPEND="perl http-date-perl http-message-perl lwp-mediatypes"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

