#
# Ylmf OS package build script
#

DESCRIPTION="Parses streams to create MIME entities"
HOMEPAGE="http://search.cpan.org/dist/MIME-tools"
LICENSE="GPL PerlArtistic"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
YARCH="any"

SRC_URI="http://mirrors.163.com/cpan/authors/id/D/DS/DSKOLL/MIME-tools-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

