#
# Ylmf OS package build script
#

DESCRIPTION="Thin library on top of the Linux framebuffer devices"
HOMEPAGE="http://www.directfb.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
 
SRC_URI="http://www.directfb.org/downloads/Core/DirectFB-1.4/DirectFB-"$V".tar.gz"

RDEPEND="freetype gcc-lib glibc libdrm libjpeg-turbo libpng libX11 libXau libxcb libXdamage libXdmcp libXext libXfixes libXxf86vm mesa sysfsutils zlib"
BDEPEND="libsdl-dev"
RECOMMENDED="libsdl"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-mmx --disable-sse"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

