#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A graph based image processing framework"
HOMEPAGE="http://www.gegl.org/"
 
SRC_URI="ftp://ftp.gimp.org/pub/"$N"/0.1/"$N-$V$R".tar.bz2"

RDEPEND="babl glib2 gdk-pixbuf2 gtk2 pango cairo libjpeg-turbo "
BDEPEND=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
