#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Linux Key Management Utilities"
HOMEPAGE="http://www.kernel.org/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://people.redhat.com/dhowells/"$N"/"$N-$V".tar.bz2"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}


