. /usr/lib/ybs/funcs

post_install() {
	/usr/lib/vlc/vlc-cache-gen -f /usr/lib/vlc/plugins
	gnome2_desktop_database_update
	gnome2_icon_cache_update
}

pre_remove() {
	rm -f /usr/lib/vlc/plugins/plugins-*.dat ||return 0		
}

post_remove() {
	gnome2_desktop_database_update
	gnome2_icon_cache_update
}
	
post_upgrade() {
	/usr/lib/vlc/vlc-cache-gen -f /usr/lib/vlc/plugins
	post_remove
}

post_downgrade() {	
	post_upgrade
}
