#
# YLmf_OS package build script
#

DESCRIPTION="Bruce's C compiler - Simple C compiler to generate 8086 code"
HOMEPAGE="http://www.debath.co.uk/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://homepage.ntlworld.com/robert.debath/"$N"/Dev86src-"$V$R".tar.gz"

RDEPEND="bin86 glibc"
BDEPEND=" dev-util/gperf"
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	dopatch "$N"-pic.patch
	dopatch "$N-$V$R"-fortify.patch
	sed -i -e "s:-O2 -g:${CFLAGS} ${CPPFLAGS}:" -e '/INEXE=/s:-s::' makefile.in
	sed -i -e '/INSTALL_OPTS=/s:-s::' bin86/Makefile
	sed -i -e '/install -m 755 -s/s:-s::' dis88/Makefile
}

pbs_build() {
	make -j1 DIST="$destdir"
}

pbs_install() {
	make -j1 install-all DIST="$destdir"
	dodoc COPYING README
	domv "$destdir"/usr/man "$destdir"/usr/share
}
