#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Simple C compiler to generate 8086 code"
HOMEPAGE="http://www.debath.co.uk/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://www.debath.co.uk/dev86/Dev86src-"$V".tar.gz"

RDEPEND="bin86 glibc"
BDEPEND="gperf"
RECOMMENDED=""

OPTIONS="nostrip"

pbs_unpack() {
        dounpack
}

pbs_patch() {
    dopatch dev86-pic.patch dev86-0.16.17-fortify.patch
}

pbs_config() {
    if [ "${ARCH}" = "x86_64" ]; then
        # x86_64 fix
        sed -i.orig -e 's,alt-libs elksemu,alt-libs,' \
             -e 's,install-lib install-emu,install-lib,' \
            makefile.in
        sed -i -e "s/-O2 -g/-O2 -g -m32/" makefile.in
        sed -i 's|^LDFLAGS.*=$|LDFLAGS=-m32|' makefile.in
    fi

}

pbs_build() {
    unset CFLAGS
    unset LDFLAGS
    unset CPPFLAGS
    unset CXXFLAGS
    make PREFIX=/usr DIST="$destdir"
}

pbs_install() {
    make install-all DIST="$destdir"
    dodoc COPYING README

    cd "$destdir"
    domv usr/man usr/share

    # Remove all the stuff supplied by bin86
    rm usr/bin/{as,ld,nm,objdump,size}86
    rm usr/share/man/man1/{as,ld}86.1
}

