#
# Ylmf OS package build script
#

DESCRIPTION="X.Org Xxf86dga library"
HOMEPAGE="http://www.x.org/wiki/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://xorg.freedesktop.org/archive/individual/lib/"$N-$V".tar.bz2"
CHECKSUM="bbd5fdf63d4c107c8cb710d4df2012b4"

RDEPEND="glibc libX11 libXau libxcb libXdmcp libXext"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

