#
# YLmf_OS package build script
#

DESCRIPTION="X.Org Xxf86dga library"
HOMEPAGE="http://www.x.org/wiki/"
 
SRC_URI="http://www.x.org/releases/X11R7.6/src/lib/"$N-$V$R".tar.bz2"

RDEPEND="glibc libX11 libXau libxcb libXdmcp libXext"
BDEPEND="glibc-dev libX11-dev libXau-dev libxcb-dev libXdmcp-dev libXext-dev"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
