#
# YLmf_OS package build script
#

DESCRIPTION="X.Org Xxf86dga library"
HOMEPAGE="http://www.x.org/wiki/"
 
SRCURL="http://www.x.org/releases/X11R7.5/src/lib"
SRC_URI="$SRCURL/libXxf86dga-1.1.1.tar.bz2"

RDEPEND="libXext libX11 libxcb libXau libXdmcp"
BDEPEND=""

pbs_unpack()
{
        dounpack
}

pbs_config()
{
	
	config+=" --sysconfdir=/etc --mandir=/usr/share/man --localstatedir=/var "
	doconfig
}

pbs_build()
{
	domake
}

pbs_install()
{
	domkinstall
}
