#!/bin/bash
#

convert() {
	local input="$1"
	local output="$2"
	mpg321 $input -w - | oggenc -q 10 -o $output -
}

if [ x$@ = x ];then
	echo "$0 input.mp3 output.ogg"
	exit 1
fi

if [ x$1 != x ] && [ x$2 = x ];then
	output=${1%.*}.ogg
fi

if [ x$1 != x ] && [ x$2 != x ];then
	output=$2	

fi

input="$1"
convert "$input"  "$output"
