#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The ASN.1 library used in GNUTLS"
HOMEPAGE="http://www.gnu.org/software/libtasn1/"
LICENSE="GPL3,LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://ftp.gnu.org/gnu/"$N"/"$N-$V".tar.gz"
CHECKSUM="1b07629163025b9693aae9b8957842b2"

RDEPEND="glibc texinfo"
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--with-packager=StartOS"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

