#
# YLmf_OS package build script
#

DESCRIPTION="The ASN.1 library used in GNUTLS"
HOMEPAGE="http://www.gnu.org/software/libtasn1/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://mirrors.kernel.org/gnu/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND="gtk-doc"

INSTALL="$N.install"

NOTES="
If you did not pass the --enable-gtk-doc parameter to the configure script, install the API documentation using the following command as the root user:
make -C doc/reference install-data-local
"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}


