#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The ASN.1 library used in GNUTLS"
HOMEPAGE="http://www.gnu.org/software/libtasn1/"
LICENSE="GPL3,LGPL"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gnu.org/gnu/"$N"/"$N-$V".tar.gz"
CHECKSUM="a3c713c41a9a73851235dc37051be46f"

RDEPEND="glibc"
BDEPEND="gtk-doc"

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_patch() {
	# corrected possible buffer overflow in parser errors.
	# http://git.savannah.gnu.org/gitweb/?p=libtasn1.git;a=commit;h=aa6e97f68d6c8d06f531d9b6bb462dc1c0720f77
	dopatch buffer_overflow_fix.diff
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

