#
# Ylmf OS package build script
#

DESCRIPTION="Common modules for GNOME JavaScript interpreters"
HOMEPAGE="http://ftp.gnome.org/pub/GNOME/sources/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/"$N"/0.1/"$N-$V".tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

