#
# YLmf_OS package build script
#

DESCRIPTION="a tool for installing Ylmf OS under linux distributions."
HOMEPAGE="http://www.ylmf.com"
REPO="testing"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_install() {
	ypkg_mkinstall
}
