#
# YLmf_OS package build script
#

DESCRIPTION="event logging framework"
HOMEPAGE="http://zeitgeist-project.com/download/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://edge.launchpad.net/"$N"/0.5/"$V"/+download/"$N-$V".tar.gz"

RDEPEND="python raptor2 rdflib"
BDEPEND="rdflib"
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

