#
# YLmf_OS package build script
#

DESCRIPTION="HTTP and WebDAV client library"
HOMEPAGE="http://www.webdav.org/neon/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.webdav.org/"$N"/"$N-$V".tar.gz"

RDEPEND="expat glibc keyutils krb5 libproxy openssl zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--with-ssl"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

