#
# YLmf_OS package build script
#

DESCRIPTION="HTTP and WebDAV client library"
HOMEPAGE="http://www.webdav.org/neon/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://www.webdav.org/"$N"/"$N-$V$R".tar.gz"

RDEPEND="zlib openssl expat"
BDEPEND="${RDEPEND} expat|libxml2 "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--with-ssl"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
