#
# YLmf_OS package build script
#

DESCRIPTION="HTTP and WebDAV client library"
HOMEPAGE="http://www.webdav.org/neon/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.webdav.org/"$N"/"$N-$V$R".tar.gz"

RDEPEND="zlib openssl expat"
BDEPEND=" libxml2-dev  "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--with-ssl"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
