#
# YLmf_OS package build script
#

DESCRIPTION="Cross platform Make"
HOMEPAGE="http://www.cmake.org"
 
SRC_URI="http://www.cmake.org/files/v2.8/"$N-$V$R".tar.gz"

RDEPEND="glibc ncurses gcc"
BDEPEND="jdk"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	#./bootstrap --prefix=/usr --docdir=/share/doc/"$N-$V$R" --mandir=/share/man
	YPB_CONFIG+="--prefix=/usr
	             --docdir=/share/doc/"$N-$V$R" 
		     --mandir=/share/man"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
