#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Cross platform Make"
HOMEPAGE="http://www.cmake.org"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://www.cmake.org/files/v2.8/"$N-$V".tar.gz"
CHECKSUM="097278785da7182ec0aea8769d06860c"

RDEPEND="curl libarchive shared-mime-info"
BDEPEND=""
OPTIONAL="qt: cmake-gui
          emacs: "

pbs_unpack() {
    dounpack
}

pbs_config() {
    ./bootstrap --prefix=/usr \
                --mandir=/share/man \
                --docdir=/share/doc/cmake \
                --system-libs \
                --parallel=$(getconf _NPROCESSORS_ONLN)
                # --qt-gui
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    docp Docs/cmake-indent.vim "$destdir"/usr/share/vim/vimfiles/indent/
    docp Docs/cmake-syntax.vim "$destdir"/usr/share/vim/vimfiles/syntax/
    dodoc Copyright.txt
    #For emacs
    #install -Dm644 Docs/cmake-mode.el "${destdir}"/usr/share/emacs/site-lisp/cmake-mode.el
    #emacs -batch -f batch-byte-compile "${destdir}"/usr/share/emacs/site-lisp/cmake-mode.el
}

