#
# Ylmf OS package build script
#

DESCRIPTION="Single process stack of various system monitors"
COMMENTS="GKrellM is a single process stack of system monitors which supports applying themes to match its appearance to your window manager, Gtk, or any other theme."
HOMEPAGE="http://www.gkrellm.net/"
LICENSE="GPLv3"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://members.dslextreme.com/users/billw/"$N"/"$N-$V".tar.bz2"
CHECKSUM="e43a9416a6975e3be63d591bdeb33b04"

RDEPEND="atk cairo expat fontconfig freetype gcc-lib gdk-pixbuf glib2 glibc gtk+ libICE libpng libSM libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender lm_sensors openssl pango pixman util-linux-ng zlib"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake LOCALEDIR=/usr/share/locale
}

pbs_install() {
	domkinstall PREFIX=/usr
	docp_rename "server/gkrellmd.conf" "$destdir"/etc/gkrellmd.conf
	dodoc COPYING
}


