#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python bindings for the Nautilus file manager"
COMMENTS="Nautilus-python is a C extension for the Nautilus File Manager that provides access to the Nautilus extension API for python scripts."
HOMEPAGE="http://projects.gnome.org/nautilus-python/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/"$N"/1.1/"$N-$V".tar.bz2"
CHECKSUM="b32ebf22e8d60b04337b13047be8326b"

RDEPEND="pygobject(>=2.28.2) nautilus(>2.32) python(>=2.3.5) atk cairo expat fontconfig freetype gcc-lib gdk-pixbuf glib2 glibc gtk+ libffi libpng libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXinerama libXrandr libXrender pango pixman zlib"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}


