#
# YLmf_OS package build script
#

DESCRIPTION="CORBA tree builder"
HOMEPAGE="http://projects.gnome.org/orbit"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.acc.umu.se/pub/gnome/platform/2.32/2.32.1/sources/libIDL-"$V".tar.bz2"

RDEPEND="glib2 glibc"
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

