#
# Ylmf OS package build script
#

DESCRIPTION="A ASCII-Graphics Library"
HOMEPAGE="http://aa-project.sourceforge.net/aalib/"
LICENSE="LGPL"
MAINTAINER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://downloads.sourceforge.net/aa-project/"$N-$V"rc5.tar.gz"

RDEPEND="glibc libX11 libXau libxcb libXdmcp slang"
BDEPEND=""

INSTALL="$N.install"

pbs_unpack(){
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

