#
# Ylmf OS package build script
#

DESCRIPTION="ubuntu gont family"
HOMEPAGE="http://font.ubuntu.com/"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://font.ubuntu.com/download/"$N"-sources_"$V$R".orig.tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_install() {
	docp *.ttf "$destdir"/usr/share/fonts/truetype/"$N"
	dodoc *.txt 
}

