#
# Ylmf OS package build script
#

DESCRIPTION="Free Chinese Input Toy for X"
HOMEPAGE="http://code.google.com/p/fcitx/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://fcitx.googlecode.com/files/"$N-$V$R".tar.bz2"

RDEPEND="libXft libXrender fontconfig freetype libX11 glibc zlib expat libxcb glibc libXau libXdmcp"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}


