#
# Ylmf OS package build script
#

DESCRIPTION="Free Chinese Input Toy for X"
HOMEPAGE="http://www.fcitx.org/"
 
SRC_URI="http://www.fcitx.org/download/$N-$V.tar.bz2"

RDEPEND="libXft libXrender fontconfig freetype libX11 glibc zlib expat libxcb glibc libXau libXdmcp"
BDEPEND=""

pbs_unpack()
{
        dounpack
}

pbs_config()
{
	
	doconfig
}

pbs_build()
{
	domake
}

pbs_install()
{
	domkinstall
}
