#
# Ylmf OS package build script
#

DESCRIPTION="Perl interface to the 2.x series of the GNOME VFS library"
HOMEPAGE="http://search.cpan.org/~tsch/Gnome2-VFS-1.081/VFS.pm"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
LICENSE="GPL PerlArtistic"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/Gnome2-VFS-"$V".tar.gz"

RDEPEND="gtk2-perl perl gnome-vfs"
BDEPEND="extutils-depends extutils-pkgconfig"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

