#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl interface to the 2.x series of the GNOME VFS library"
HOMEPAGE="http://search.cpan.org/~tsch/Gnome2-VFS-1.081/VFS.pm"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/Gnome2-VFS-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
