#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="X11 Apps"
HOMEPAGE="http://www.x.org/wiki/"
 
SRCURL="http://www.x.org/releases/X11R7.5/src/app"
SRC_URI="$SRCURL/xrandr-1.3.2.tar.bz2"

RDEPEND="libXrandr libXrender libX11 libXext libxcb libXau libXdmcp"
BDEPEND=""

pbs_unpack()
{
        dounpack
}

pbs_config()
{
	
	doconfig
}

pbs_build()
{
	domake
}

pbs_install()
{
	domkinstall
}
