#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A somewhat comprehensive collection of Linux man pages"
HOMEPAGE="http://www.kernel.org/doc/man-pages"
YARCH="any"
PACKAGER="StartOS Developers"

SRC_URI="http://www.kernel.org/pub/linux/docs/"$N"/Archive/"$N-$V".tar.bz2"

RDEPEND=""
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_install() {
	domkinstall
}

