#
# YLmf_OS package build script
#

DESCRIPTION="Scheme interpreter"
HOMEPAGE="http://www.gnu.org/software/guile/"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YVERSION="1"

SRC_URI="http://ftp.gnu.org/pub/gnu/"$N"/"$N-$V$R".tar.gz"

RDEPEND="glibc gmp libtool ncurses readline"
BDEPEND="    "
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_patch guile-1.8.7-multilib.patch guile-1.8.7-testsuite.patch guile-1.8.8-deplibs.patch
	YPB_CONFIG+="--disable-static
	             --disable-error-on-warning"
	ypkg_config
}

pbs_build() {
	ypkg_make LDFLAGS+="-lpthread"
}

pbs_install() {
	ypkg_mkinstall
}
