#
# Ylmf OS package build script
#

DESCRIPTION="Scheme interpreter"
HOMEPAGE="http://www.gnu.org/software/guile/"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnu.org/pub/gnu/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc gmp libtool ncurses readline"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	dopatch guile-1.8.7-multilib.patch \
	           guile-1.8.7-testsuite.patch \
		   guile-1.8.8-deplibs.patch
	config+="--disable-static
	             --disable-error-on-warning"
	doconfig
}

pbs_build() {
	domake LDFLAGS+="-lpthread"
}

pbs_install() {
	domkinstall
}

