#
# YLmf_OS package build script
#

DESCRIPTION="Scheme interpreter"
HOMEPAGE="http://www.gnu.org/software/guile/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://ftp.gnu.org/pub/gnu/"$N"/"$N-$V$R".tar.gz"

RDEPEND="glibc gmp libtool ncurses readline"
BDEPEND="    "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-static
	             --disable-error-on-warning"
	ypkg_config
}

pbs_build() {
	ypkg_make LDFLAGS+="-lpthread"
}

pbs_install() {
	ypkg_mkinstall
}

pbs_postinst() {
	[ -x /usr/bin/install-info ] || return 0
	infodir=/usr/share/info
	files="r5rs.info guile-tut.info guile.info-7 guile.info-6 guile.info-5 guile.info-4 guile.info-3 guile.info-2 guile.info-1 guile.info goops.info"
	for file in $files; do
		install-info $infodir/$file.gz $infodir/dir 2>/dev/null
	done
}

pbs_postrm() {
	[ -x /usr/bin/install-info ] || return 0
	infodir=/usr/share/info
	files="r5rs.info guile-tut.info guile.info-7 guile.info-6 guile.info-5 guile.info-4 guile.info-3 guile.info-2 guile.info-1 guile.info goops.info"
	for file in $files; do
		install-info --delete $infodir/$file.gz $infodir/dir 2>/dev/null
	done
}
