diff -ur exaile-0.3.2.2/INSTALL exaile-0.3.2.2.new//INSTALL
--- exaile-0.3.2.2/INSTALL	2011-07-19 08:32:50.690850000 +0800
+++ exaile-0.3.2.2.new//INSTALL	2011-08-01 10:27:50.677097304 +0800
@@ -17,7 +17,7 @@
     Default: /lib
   PREFIX
     The installation prefix. 
-    Default: /usr/local
+    Default: /usr/
     Note: If this default is changed, you may need to set the XDG_DATA_DIRS
       environment variable to include the changed path. See [1].
   XDGCONFDIR
diff -ur exaile-0.3.2.2/Makefile exaile-0.3.2.2.new//Makefile
--- exaile-0.3.2.2/Makefile	2011-07-19 08:32:50.690850000 +0800
+++ exaile-0.3.2.2.new//Makefile	2011-08-01 10:28:33.921963890 +0800
@@ -1,4 +1,4 @@
-PREFIX 		?= /usr/local
+PREFIX 		?= /usr/
 LIBINSTALLDIR 	?= /lib
 XDGCONFDIR 	?= /etc/xdg
 
diff -ur exaile-0.3.2.2/plugins/Makefile exaile-0.3.2.2.new//plugins/Makefile
--- exaile-0.3.2.2/plugins/Makefile	2011-07-19 08:32:50.690850000 +0800
+++ exaile-0.3.2.2.new//plugins/Makefile	2011-08-01 10:31:05.510339982 +0800
@@ -1,4 +1,4 @@
-PREFIX ?= /usr/local
+PREFIX ?= /usr/
 PLUGINSDIR = /share/exaile/plugins/
 
 INSTALL_PLUGINS = `python list.py main`
diff -ur exaile-0.3.2.2/tools/generate-launcher exaile-0.3.2.2.new//tools/generate-launcher
--- exaile-0.3.2.2/tools/generate-launcher	2011-07-19 08:32:50.690850000 +0800
+++ exaile-0.3.2.2.new//tools/generate-launcher	2011-08-01 10:29:27.693808064 +0800
@@ -5,7 +5,7 @@
 printf "Generating launcher script\n"
 
 DESTDIR=${1:-}
-PREFIX=${2:-/usr/local}
+PREFIX=${2:-/usr}
 LIBDIR=${3:-/lib}
 
 if (which realpath > /dev/null); then
