#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Scientific tools for Python"
HOMEPAGE="http://numpy.scipy.org"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://downloads.sourceforge.net/"$N"/"$N-$V"b2.tar.gz"
CHECKSUM="1b62cf0e34e2db58b0241b00d603df24"

RDEPEND="python lapack"
BDEPEND="distribute nose"
RECOMMENDED=""
OPTIONAL="nose: testsuite"

pbs_unpack() {
    dounpack
}

pbs_build() {
    export Atlas=None
    export LDFLAGS="$LDFLAGS -shared"
    domake config_fc --fcompiler=gnu95
}

pbs_install() {
    domkinstall config_fc --fcompiler=gnu95
    dodoc LICENSE.txt 
}

