#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Fast array and numerical python library"
HOMEPAGE="http://cairographics.org/pycairo/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://downloads.sourceforge.net/project/numpy/NumPy/"$V"/"$N-$V".tar.gz"

RDEPEND="glibc python"
BDEPEND=" "
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc LICENSE.txt 
}

