#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A blending of the wxWindows C++ class library with Python"
HOMEPAGE="http://www.wxpython.org/"
LICENSE="custom:wxWindows"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://downloads.sourceforge.net/wxpython/wxPython-src-"$V".tar.bz2"
CHECKSUM="05688dc03d61631750f5904273122bb40a2115f5"

RDEPEND="python wxgtk"
RECOMMENDED=""
BDEPEND="mesa"
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_patch() {
    mv wxPython/wx/tools/Editra/editra wxPython/wx/tools/Editra/Editra
}

pbs_config() {
	./configure $DEFAULT_CONFIG \
                --with-gtk=2 \
                --with-opengl \
                --enable-unicode \
                --enable-graphics_ctx \
                --disable-optimize \
                --enable-mediactrl \
                --with-regex=sys \
                --with-libpng=sys \
                --with-libxpm=sys \
                --with-libjpeg=sys \
                --with-libtiff=sys \
                --disable-precomp-headers
}

pbs_build() {
	cd wxPython
	dopatch wxpython-cairo.patch || die "wxpython-cairo.patch patch failed"  
    dopatch wxpython-fpb_default_style.patch || die "wxpython-fpb_default_style.patch patch failed"
    domake WXPORT=gtk2 UNICODE=1
}

pbs_install() {
    domkinstall WXPORT=gtk2 UNICODE=1
	dodoc ../docs/licence.txt
}

