#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A blending of the wxWindows C++ class library with Python"
HOMEPAGE="http://www.wxpython.org/"
LICENSE="custom:wxWindows"
PACKAGER="StartOS Developers"

SRC_URI="http://downloads.sourceforge.net/wxpython/wxPython-src-"$V".tar.bz2"
CHECKSUM="402e0b81e06f596d849e221a7a76acc6"

RDEPEND="atk cairo expat fontconfig freetype gcc-lib gconf gdk-pixbuf glib2 glibc gst-plugins-base gstreamer gtk+ libdrm libffi libICE libjpeg-turbo libpng libSM libtiff libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXinerama libxml2 libXrandr libXrender libXxf86vm mesa orbit pango pixman python util-linux-ng wxWidgets zlib"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	mv wxPython/wx/tools/Editra/editra wxPython/wx/tools/Editra/Editra
	./configure --prefix=/usr \
	            --libdir=/usr/lib \
		    --with-gtk=2 \
		    --with-opengl \
		    --enable-unicode \
	     	    --enable-graphics_ctx \
	            --disable-optimize \
		    --enable-mediactrl \
	            --with-regex=sys \
		    --with-libpng=sys \
		    --with-libxpm=sys \
		    --with-libjpeg=sys \
		    --with-libtiff=sys \
		    --disable-precomp-headers
}

pbs_build() {
	cd wxPython
	dopatch wxpython-cairo.patch
	python setup.py WXPORT=gtk2 UNICODE=1 build
}

pbs_install() {
	python setup.py WXPORT=gtk2 UNICODE=1 install --root="${destdir}"
	dodoc ../docs/licence.txt
}

