#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="115 upload plugin for firefox"
COMMENTS=""
HOMEPAGE="www.115.com"
LICENSE="custom"
PACKAGER="StartOS Developers"

SRC_URI="http://115.com/static/install/"${N}"_v"$V"_x86.tar.gz"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_install() {
	docp 115upload.so "$destdir"/usr/lib/mozilla/plugins/
}

