#
# Ylmf OS package build script
#

DESCRIPTION="Fast lightweight tabbed filemanager"
HOMEPAGE="http://pcmanfm.sourceforge.net/"
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
SRC_URI="http://downloads.sourceforge.net/project/$N/pcmanfm-legacy/PCManFM%20$V/$N-$V.tar.bz2 "

RDEPEND=""
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	patch -p1 -i $filesdir/"$N-$V$R"-fix-ca-translation.patch
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
