#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An implementation of the OBEX protocol used for transferring data to mobile devices"
HOMEPAGE="http://sourceforge.net/projects/openobex/"
REPO=""
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://www.kernel.org/pub/linux/bluetooth/"$N-$V$R".tar.gz"

RDEPEND="glibc libusb libusb-compat"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

