#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="ntdiskmap"
HOMEPAGE="http://www.startos.com"
LICENSE="GPL"
PACKAGER="StartOS Developers"

INSTALL="$N.install"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="dbus-glib polkit"
BDEPEND=""

pbs_unpack() {
    dounpack
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

