#
# YLmf_OS package build script
#

DESCRIPTION="mingw32 run-time library"
HOMEPAGE="http://www.mingw.org/"
LICENSE="LGPL"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://nchc.dl.sourceforge.net/project/mingw/MinGW/BaseSystem/RuntimeLibrary/MinGW-RT/mingwrt-3.18/mingwrt-3.18-mingw32-src.tar.gz"

RDEPEND=""
BDEPEND="mingw32-w32api"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	 sed -i "s%\r%%g" `find . -type f`
	 sed -i -e "s%^W32API_INCLUDE=.*%W32API_INCLUDE=-I/usr/i586-mingw32msvc/include%" `find -type f -name 'configure'`
	 #unset CFLAGS CXXFLAGS CC CXX
	 export CFLAGS="-mms-bitfields"
	 ./configure \
	 	 --prefix=/usr/i586-mingw32msvc \
	 	 --target=i586-mingw32msvc \
		 --host=i586-mingw32msvc 
		 #--build=$CHOST
}

pbs_build() {
	make
}

pbs_install() {
	mkdir -p "$YPPATH_DEST"/usr/i586-mingw32msvc/bin
	make install prefix="$YPPATH_DEST"/usr/i586-mingw32msvc
	cd "$YPPATH_DEST"
	rm -rf usr/i586-mingw32msvc/{doc,man}
	find . -name '*.a' | xargs -rtl1 i586-mingw32msvc-strip -g
}
