#
# YLmf_OS package build script
#

DESCRIPTION="mingw32 run-time library"
HOMEPAGE="http://www.mingw.org/"
LICENSE="LGPL"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://nchc.dl.sourceforge.net/project/mingw/MinGW/BaseSystem/RuntimeLibrary/MinGW-RT/mingwrt-3.18/mingwrt-3.18-mingw32-src.tar.gz"

RDEPEND=""
BDEPEND="mingw32-w32api"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	target="i586-mingw32msvc"
        sed -i "s%\r%%g" `find . -type f`
        sed -i -e "s%^W32API_INCLUDE=.*%W32API_INCLUDE=-I/usr/i586-mingw32msvc/include%" `find -type f -name 'configure'`
	export CFLAGS="-mms-bitfields"
	./configure --prefix=/usr/$target --target=$target  #--host=$target #--build=$CHOST
}

pbs_build() {
	ypkg_make
}

pbs_install() {
        #ypkg_mkinstall
	mkdir -p "$YPPATH_DEST"/usr/$target/bin
	make install prefix="$YPPATH_DEST"/usr/$target
        mv "$YPPATH_DEST"/usr/$target/bin/*.dll "$YPPATH_DEST"/usr/$target/lib/
	#rm -rf "$YPPATH_DEST"/usr/$target/{doc,man}
	#find $YPPATH_DEST -name '*.a' | xargs -rtl1 $target-strip -g
}
