#!/bin/sh
#
# Distributed under the terms of the GNU General Public License v2

. /etc/sysconfig/rc
. $rc_functions

ftpd_pidfile="/var/run/pure-ftpd.pid"

#depend() {
#	need net
#}

start() {
	boot_mesg "* Starting Pure-FTPd Server..."
	loadproc /usr/sbin/pure-ftpd --pidfile ${ftpd_pidfile} &
}

stop() {
	boot_mesg "* Stopping Pure-FTPd"
	killproc /usr/sbin/pure-ftpd
	rm -rf $ftpd_pidfile
}

#main
case "$1" in
        start)	
		start ;;
	stop)	
		stop ;;
	restart)
                $0 stop
		sleep 1
		$0 start ;;
        status)
	        statusproc /usr/sbin/pure-ftpd ;;
        *)
                echo "Usage: $0 {start|stop|restart|status}"
                exit 1 			     ;;
esac

# End of file
