#
# YLmf_OS package build script
#

DESCRIPTION=" makes X.509 certificates and CMS easily accessible to applications"
HOMEPAGE="http://www.gnupg.org/related_software/libksba"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"
 
SRC_URI="ftp://ftp.gnupg.org/gcrypt/libksba/$N-$V.tar.bz2"

RDEPEND=""
BDEPEND="${RDEPEND} libgpg-error"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	YPB_CONFIG+=" --prefix=/usr --sysconfdir=/etc --localstatedir=/var \
	               --infodir=/usr/share/info --mandir=/usr/share/man \
	               --disable-static --enable-shared "
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	install -m755 -d "$YPPATH_DEST"/usr/share/doc/"$N-$V$R"
	cp -a AUTHORS ChangeLog COPYING INSTALL NEWS README   "$YPPATH_DEST"/usr/share/doc/"$N-$V$R"
}

pbs_postinst()
{
	ldconfig
}
