#
# YLmf_OS package build script
#

DESCRIPTION="Playlist parsing library"
HOMEPAGE="http://www.gnome.org/projects/totem/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.32/2.32.1/sources/"$N-$V".tar.bz2"

RDEPEND="dbus gconf glib2 glibc gmime gnutls libgcrypt libgnome-keyring libgpg-error libproxy libsoup libtasn1 libxml2 orbit sqlite zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

