#
# YLmf_OS package build script
#

DESCRIPTION="Playlist parsing library"
HOMEPAGE="http://www.gnome.org/projects/totem/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.32/2.32.1/sources/"$N-$V".tar.bz2"

RDEPEND="glib2 gdk-pixbuf glibc gmime libxml2 zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

