#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Analyze Python programs and detect various errors. "
HOMEPAGE="https://pypi.python.org/pypi/pyflakes"
LICENSE="MIT"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"
YARCH="any"

SRC_URI="https://pypi.python.org/packages/source/p/pyflakes/pyflakes-$V.tar.gz"
CHECKSUM="00debd2280b962e915dfee552a675915"

RDEPEND="python"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
    dounpack
}

pbs_install() {
    domkinstall
}
