#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Library for arithmetic on arbitrary precision integers, rational numbers, and floating-point numbers"
HOMEPAGE="http://gmplib.org/"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="ftp://ftp.gmplib.org/pub/$N-$V/$N-$V.tar.xz"
CHECKSUM="8aef50959acec2a1ad41d144ffe0f3b5"

RDEPEND="gcc-libs"
BDEPEND=""

# pidgin require libgmp.so.la for compiling.
OPTIONS="nolibtool"

INSTALL="$N.install"

pbs_unpack() {
    dounpack
}

pbs_config() {
    case "$ARCH" in
        i?86) export ABI=32
	esac	
	config+="--enable-cxx"
	doconfig
}

pbs_build() {
	domake 
}

pbs_install() {
	domkinstall
}

