#
# YLmf_OS package build script
#

DESCRIPTION="A library for applications dealing with netlink socket"
HOMEPAGE="http://people.suug.ch/~tgr/libnl/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://people.suug.ch/~tgr/"$N"/files/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	sed -i "/^#include.*<stdlib.h>/a\#include <limits.h>" include/netlink-local.h
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

