#
# YLmf_OS package build script
#

DESCRIPTION="Perl module Probe-Perl"
HOMEPAGE="http://search.cpan.org/~kwilliams/Probe-Perl-0.01/"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://search.cpan.org/CPAN/authors/id/K/KW/KWILLIAMS/Probe-Perl-"$V".tar.gz"

RDEPEND="perl"
BDEPEND="test-script"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

