#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl module Probe-Perl"
HOMEPAGE="http://search.cpan.org/~kwilliams/Probe-Perl-0.01/"
LICENSE="GPL-2"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/K/KW/KWILLIAMS/Probe-Perl-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" test-script"

pbs_unpack() {
        dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
        perl_cleanup
}
