#
# Ylmf OS package build script
#

DESCRIPTION="X.Org Fixes protocol headers"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://xorg.freedesktop.org/archive/individual/proto/"$N-$V".tar.bz2"
CHECKSUM="e7431ab84d37b2678af71e29355e101d"

RDEPEND=""
BDEPEND=""
OPTIONS="nodev"

pbs_unpack() {
        dounpack
}

pbs_config() {	
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

