#
# YLmf_OS package build script
#

DESCRIPTION="Rendering engine for complex non-Roman writing systems"
HOMEPAGE="http://graphite.sil.org/"
REPO=""
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://nchc.dl.sourceforge.net/project/silgraphite/"$N"/"$N-$V$R".tgz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}


