#
# YLmf_OS package build script
#

DESCRIPTION="Fast, multi-threaded malloc() and nifty performance analysis tools"
HOMEPAGE="http://code.google.com/p/google-perftools/"
LICENSE="New BSD License"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://google-perftools.googlecode.com/files/"$N-$V".tar.gz"

RDEPEND="gcc glibc"
RECOMMENDED=""
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}


