#
# YLmf_OS package build script
#

DESCRIPTION="Simple GNOME menu editor"
HOMEPAGE="http://live.gnome.org/"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.32/2.32.1/sources/"$N-$V".tar.bz2"

RDEPEND=""
BDEPEND="pygtk gnome-menus"
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

