#
# YLmf_OS package build script
#

DESCRIPTION="perl module"
HOMEPAGE="http://search.cpan.org/~rjbs/String-Truncate-1.100570/"
REPO=""
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/String-Truncate-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" sub-exporter"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
