#
# YLmf_OS package build script
#

DESCRIPTION="perl module"
HOMEPAGE="http://search.cpan.org/~rjbs/String-Truncate-1.100570/"
REPO=""
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/String-Truncate-"$V$R".tar.gz"

RDEPEND=""
BDEPEND="${RDEPEND} sub-exporter"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
