#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Open Source Search Engine Library"
HOMEPAGE="http://xapian.org"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://oligarchy.co.uk/xapian/$V/$N-$V.tar.gz"
CHECKSUM=""

RDEPEND="util-linux-libs gcc-libs zlib glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

