#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A ELF object file access library"
HOMEPAGE="http://www.mr511.de/software/"
LICENSE="GPL"
PACKAGER="StartOS Developers"
 
SRC_URI="http://www.mr511.de/software/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	make prefix="$destdir"/usr libdir="$destdir"/usr/lib  \
             includedir="$destdir"/usr/include \
	     install  install-compat 
}


