#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Pure python memcached client"
HOMEPAGE="http://pypi.python.org/pypi/python-memcached"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"

SRC_URI="ftp://ftp.tummy.com/pub/python-memcached/python-memcached-$V.tar.gz"
CHECKSUM="58f8c328304df6aca1f8b60170e98932"

RDEPEND="python"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodoc README
}
