#
# YLmf_OS package build script
#

DESCRIPTION="a library for getting and setting POSIX.1e"
HOMEPAGE="http://www.kernel.org/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/"$N-$V$R".tar.bz2"

RDEPEND="attr glibc"
BDEPEND="gperf attr-dev glibc-dev"
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc README
}
