#
# YLmf_OS package build script
#

DESCRIPTION="uu, xx, base64, binhex decoder"
HOMEPAGE="http://www.fpx.de/fp/Software/UUDeview/"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.fpx.de/fp/Software/UUDeview/download/uudeview-0.5.20.tar.gz"

RDEPEND="expat fontconfig freetype glibc libX11 libXau libxcb libXdmcp libXext libXft libXrender libXScrnSaver tcl tk zlib"
BDEPEND="              "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	patches="uudeview-0.5.20-bugfixes.patch
	        uudeview-0.5.20-CVE-2004-2265.patch
		uudeview-0.5.20-CVE-2008-2266.patch
		uudeview-0.5.20-man.patch
		uudeview-0.5.20-rename.patch"
	ypkg_patch $patches
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall MANDIR="$YPPATH_DEST/usr/share/man/" BINDIR="$YPPATH_DEST/usr/bin/"
	ypkg_dodoc  HISTORY INSTALL README
}
