#
# YLmf_OS package build script
#

DESCRIPTION="S3 Savage video driver"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.x.org/releases/X11R7.6/src/driver/"$N-$V".tar.bz2"

RDEPEND="glibc"
BDEPEND="xorg-server-dev"

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

