#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl interface to the sexy widget collection  "
HOMEPAGE="http://search.cpan.org/~flora/Gtk2-Sexy-0.05/"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="GPL,PerlArtistic"

SRC_URI="http://mirrors.xmu.edu.cn/CPAN/authors/id/F/FL/FLORA/Gtk2-Sexy-"$V".tar.gz"

RDEPEND="gtk+ libsexy"
BDEPEND="extutils-depends extutils-pkgconfig gtk2-perl"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

