#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="X.Org Xcursor library"
HOMEPAGE="http://www.x.org/wiki/"
LICENSE="custom"
PACKAGER="StartOS Developers"

SRC_URI="http://xorg.freedesktop.org/archive/individual/lib/"$N-$V".tar.bz2"
CHECKSUM="a93b5a6f5b05976d2c0d3f8a07f6ac6a"

RDEPEND="glibc libX11 libXau libxcb libXdmcp libXfixes libXrender"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

