#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="X.Org Xcursor library"
HOMEPAGE="http://www.x.org/wiki/"
 
SRCURL="http://www.x.org/releases/X11R7.5/src/lib"
SRC_URI="$SRCURL/libXcursor-1.1.10.tar.bz2"

RDEPEND="libXrender libXfixes libX11 libxcb libXau libXdmcp "
BDEPEND=""

pbs_unpack()
{
        dounpack
}

pbs_config()
{
	
	config+=" --sysconfdir=/etc --mandir=/usr/share/man --localstatedir=/var "
	doconfig
}

pbs_build()
{
	domake
}

pbs_install()
{
	domkinstall
}
