#
# YLmf_OS package build script
#

DESCRIPTION="general purpose crypto library based on the code used in GnuPG"
HOMEPAGE="http://www.gnupg.org/"
 
SRC_URI="ftp://ftp.gnupg.org/gcrypt/libgcrypt/$N-$V.tar.bz2"

RDEPEND=""
BDEPEND=" dev-libs/libgpg-error"
OPIONAL="pth libcap2"

pbs_unpack()
{
        dounpack
}

pbs_config()
{
	
	config+=" --prefix=/usr  --disable-static "
	doconfig
}

pbs_build()
{
	domake
}

pbs_install()
{
	domkinstall
}
