#
# YLmf_OS package build script
#

DESCRIPTION="general purpose crypto library based on the code used in GnuPG"
HOMEPAGE="http://www.gnupg.org/"
 
SRC_URI="ftp://ftp.gnupg.org/gcrypt/libgcrypt/$N-$V.tar.bz2"

RDEPEND=""
BDEPEND="${RDEPEND} dev-libs/libgpg-error"
OPIONAL="pth libcap2"

pbs_unpack()
{
        ypkg_unpack
}

pbs_config()
{
	
	YPB_CONFIG+=" --prefix=/usr  --disable-static "
	ypkg_config
}

pbs_build()
{
	ypkg_make
}

pbs_install()
{
	ypkg_mkinstall
}
