#
# Ylmf OS package build script
#

DESCRIPTION="RPM Package Manager"
HOMEPAGE="http://rpm5.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://rpm5.org/files/rpm/rpm-5.3/"$N-$V".tar.gz"
CHECKSUM="7a5112fd208bfda7a1cab20b9ce17a02"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

