#
# YLmf_OS package build script
#

DESCRIPTION="Portable Network Graphics library"
HOMEPAGE="http://www.libpng.org/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://prdownloads.sourceforge.net/"$N"/"$N-$V$R".tar.gz"

RDEPEND="glibc zlib"
BDEPEND="glibc-dev zlib-dev"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_patch "$N-$V$R"-apng.patch
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
