#
# Ylmf OS package build script
#

DESCRIPTION="Portable Network Graphics library"
HOMEPAGE="http://www.libpng.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://prdownloads.sourceforge.net/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc zlib"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	dopatch "$N-$V"-apng.patch
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

