#
# YLmf_OS package build script
#

DESCRIPTION="create an index of X font files in a directory"
HOMEPAGE="http://www.x.org/wiki/"
 
SRC_URI="http://www.x.org/releases/X11R7.6/src/app/"$N-$V$R".tar.bz2"

RDEPEND="libfontenc freetype zlib glibc"
BDEPEND="libfontenc-dev freetype-dev zlib-dev glibc-dev"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
