#
# Ylmf OS package build script
#

DESCRIPTION="A library providing GLib serialization and deserialization support for the JSON format"
HOMEPAGE="http://live.gnome.org/JsonGlib"
REPO=""
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/"$N"/0.12/"$N-$V$R".tar.bz2"

RDEPEND="glib2 gdk-pixbuf glibc zlib"
BDEPEND="  "
RECOMMENDED=""
NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
