#
# Ylmf OS package build script
#

DESCRIPTION="Ylmf OS Build System utilities"
HOMEPAGE="http://www.ylmf.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
PRIORITY="required"

INSTALL="$N.install"

SRC_URI="git://git.ylmf.com/ypkg.git"

RDEPEND="gawk cpio xz-utils sed coreutils git findutils procps psmisc bash bc glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
	dounpack
}

pbs_build() {
	make
}

pbs_install() {
	domkinstall
}

