#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python bindings for the Nautilus file manager"
COMMENTS="Nautilus-python is a C extension for the Nautilus File Manager that provides access to the Nautilus extension API for python scripts."
HOMEPAGE="http://projects.gnome.org/nautilus-python/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/nautilus-python/1.1/nautilus-python-$V.tar.bz2"
CHECKSUM="b32ebf22e8d60b04337b13047be8326b"

RDEPEND="py-gobject(>=2.28.2) nautilus-libs"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
