#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Provides simple control over terminal driver modes"
HOMEPAGE="http://search.cpan.org/~stsi/TermReadKey/"
LICENSE="custom"
GROUP="perl"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://cpan.wenzk.com/authors/id/S/ST/STSI/TermReadKey-$V.tar.gz"
CHECKSUM="69b92c8ddca8691c83823c683cd9838a"

RDEPEND="perl glibc"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1 PERL5LIB="" \
           PERL_AUTOINSTALL=--skipdeps \
           PERL_MM_OPT="INSTALLDIRS=vendor" \
           PERL_MB_OPT="--installdirs vendor" \
           MODULEBUILDRC=/dev/null
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}
