#
# YLmf_OS package build script
#

DESCRIPTION="ODBC Interface for Linux."
HOMEPAGE="http://www.iodbc.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.iodbc.org/downloads/iODBC/"$N-$V$R".tar.gz"

RDEPEND="glibc"
BDEPEND="chrpath"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-gui
		     --disable-libodbc"
	ypkg_config
}

pbs_build() {
	make
}

pbs_install() {
	ypkg_mkinstall
	# 
	cd "$YPPATH_DEST"
	chrpath -d usr/bin/iodbctest{,w}
	rm -rf usr/share/libiodbc/
}

