#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="ODBC Interface for Linux."
HOMEPAGE="http://www.iodbc.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://www.iodbc.org/downloads/iODBC/"$N-$V$R".tar.gz"

RDEPEND="glibc"
BDEPEND="chrpath"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-gui
		     --disable-libodbc"
	doconfig
}

pbs_build() {
	make
}

pbs_install() {
	domkinstall
	# 
	cd "$destdir"
	chrpath -d usr/bin/iodbctest{,w}
	rm -rf usr/share/libiodbc/
}

