#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="ODBC Interface for Linux."
HOMEPAGE="http://www.iodbc.org/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://downloads.sourceforge.net/iodbc/$N-$V.tar.gz"
CHECKSUM="9889f95f632f10895ff53b8a22162810"

RDEPEND="glibc"
BDEPEND="chrpath"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    config+="--disable-gui --disable-libodbc --disable-static"
    doconfig
}

pbs_build() {
    make
}

pbs_install() {
    domkinstall
    cd "$destdir"
    chrpath -d usr/bin/iodbctest{,w}
    rm -rf usr/share/libiodbc/
}

