#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A library which provides a highly usable object-oriented C++/Qt4 framework for RDF data"
HOMEPAGE="http://soprano.sourceforge.net/"
LICENSE="GPL,LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://downloads.sourceforge.net/"$N"/"$N-$V".tar.bz2"
CHECKSUM="90134eaaf40b6663dd01cfaefdaba7fb"

RDEPEND="qt redland libiodbc virtuoso"
BDEPEND="cmake doxygen jdk"

pbs_unpack() {
    dounpack
}

pbs_config() {
    . /etc/profile.d/jdk.sh
    doconfig -DCMAKE_BUILD_TYPE=Release \
             -DCMAKE_SKIP_RPATH=OFF \
             -DSOPRANO_DISABLE_CLUCENE_INDEX=ON
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
