#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl module Provide a simple wrapper around Getopt::Long"
HOMEPAGE="http://search.cpan.org/~rsavage/Getopt-Simple-1.52/"
REPO=""
LICENSE="GPL-2"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/R/RS/RSAVAGE/Getopt-Simple-"$V$R".tgz"

RDEPEND="perl"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
        perl_cleanup
}
