#
# YLmf_OS package build script
#

DESCRIPTION="Perl module Provide a simple wrapper around Getopt::Long"
HOMEPAGE="http://search.cpan.org/~rsavage/Getopt-Simple-1.52/"
REPO=""
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://search.cpan.org/CPAN/authors/id/R/RS/RSAVAGE/Getopt-Simple-"$V$R".tgz"

RDEPEND="perl"
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
