#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The Oild Runtime Compiler"
HOMEPAGE="http://code.entropywave.com/projects/orc"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://code.entropywave.com/download/"$N"/"$N-$V".tar.gz"
CHECKSUM="e482932e544c847761449b106ecbc483"

RDEPEND="glibc"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--disable-static"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodoc COPYING
}

