#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The Libee is an event expression library."
HOMEPAGE="http://www.libee.org/"
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://www.libee.org/files/download/"$N-$V".tar.gz"
CHECKSUM="257a23d5cc8f211fb99464a462bc92cd"

RDEPEND="glibc libestr"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	make
}

pbs_install() {
	domkinstall
}

