#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="lxde desktop login manager"
HOMEPAGE="http://lxde.org"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://nchc.dl.sourceforge.net/project/"$N"/"$N"/LXDM%200.4.1/"$N-$V".tar.gz"

RDEPEND="consolekit gtk2"
BDEPEND=""

pbs_unpack() {
	dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

