#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION=" software-based implementation of the codec specified in the JPEG-2000 Part-1 standard"
HOMEPAGE="http://www.ece.uvic.ca/~mdadams/jasper/"
LICENSE="JasPer2.0"
PACKAGER="StartOS Developers"

SRC_URI="http://www.ece.uvic.ca/~mdadams/"$N"/software/"$N-$V".zip"

RDEPEND="freeglut libjpeg-turbo libXmu glu"
BDEPEND="unzip"
RECOMMENDED=""

pbs_unpack() {
	dounpack
}

pbs_patch() {
	dopatch jpc_dec.c.patch patch-libjasper-stepsizes-overflow.diff \
            jasper-1.900.1-CVE-2008-3520.patch \
            jasper-1.900.1-CVE-2008-3522.patch 
}

pbs_config() {
    config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
    dodoc LICENSE
}

