
post_install() {
    update-desktop-database 2>/dev/null
    gtk-update-icon-cache -f -q -t 2>/dev/null
    systemctl enable wicd.service
    start wicd ||true
}

pre_remove() {
    stop wicd
    systemctl disable wicd.service ||true
}

post_remove() {
    update-desktop-database 2>/dev/null
    gtk-update-icon-cache -f -q -t 2>/dev/null ||true
}

post_upgrade() {
    systemctl --system daemon-reload
    post_install
}

post_downgrade() {
    post_upgrade
}
