. /usr/lib/ybs/funcs

post_install() {
	gnome2_install_defaut_gconf "string" "/apps/ymenu/orientation" "bottom"
	gnome2_install_defaut_gconf "string" "/apps/ymenu/Y_Center" "softwarecenter"
	gnome2_install_defaut_gconf "int" "/apps/ymenu/IconSize" "32"
	gnome2_install_defaut_gconf "string" "/apps/ymenu/Button_Name" "startos"
}

post_upgrade() {
	post_install
}

post_downgrade() {
	post_install
}

