. /usr/lib/ybs/funcs

files="/etc/gconf/schemas/gnome-power-manager.schemas"

post_install() {
    gnome2_install_schema $files
    #set default backlight
    gnome2_install_defaut_gconf "int" "/apps/gnome-power-manager/backlight/brightness_ac" "85"
    gnome2_install_defaut_gconf "int" "/apps/gnome-power-manager/backlight/brightness_dim_battery" "60"
    #
    update-desktop-database
    gtk-update-icon-cache -f -q -t  /usr/share/gnome-power-manager/icons/hicolor
}

pre_remove() {
    gnome2_install_schema $files
}

post_remove() {
    update-desktop-database
    gtk-update-icon-cache -f -q -t /usr/share/gnome-power-manager/icons/hicolor
}

post_upgrade() {
    post_remove
}

post_downgrade() {
    post_remove
}

