#
# YLmf_OS package build script
#

DESCRIPTION="An asynchronous networking framework written in Python"
HOMEPAGE="http://pypi.python.org/pypi/Twisted"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://pypi.python.org/packages/source/T/Twisted/Twisted-"$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
