#
# Ylmf OS package build script
#

DESCRIPTION="X.Org XExt protocol headers"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://xorg.freedesktop.org/archive/individual/proto/"$N-$V".tar.bz2"
CHECKSUM="220732210ceffb01bf1caf970e3b1bfb"

RDEPEND=""
BDEPEND=""
OPTIONS="nodev"

pbs_unpack() {
        dounpack
}

pbs_config() {	
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

