#
# YLmf_OS package build script
#

DESCRIPTION="X.Org XExt protocol headers"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://www.x.org/releases/X11R7.6/src/proto/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {	
	

	               
		       
		      
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
