#
# YLmf_OS package build script
#

DESCRIPTION=" binaries used by initramfs-tools "
HOMEPAGE="www.ylmf.net"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="initramfs-tools glibc udev"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_docp wait-for-root  "$YPPATH_DEST"/usr/lib/initramfs-tools/bin
}

