#
# Ylmf OS package build script
#

DESCRIPTION=" binaries used by initramfs-tools "
HOMEPAGE="www.ylmf.net"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="initramfs-tools glibc udev"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	docp wait-for-root  "$destdir"/usr/lib/initramfs-tools/bin
}

