#
# Ylmf OS package build script
#

DESCRIPTION="perl module"
HOMEPAGE="http://search.cpan.org/~ferreira/Module-Which-0.0207/"
REPO=""
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/F/FE/FERREIRA/Module-Which-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" string-truncate"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
