#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="perl module"
HOMEPAGE="http://search.cpan.org/~ferreira/Module-Which-0.0207/"
REPO=""
LICENSE="GPL-2"
PACKAGER="StartOS Developers"

SRC_URI="http://search.cpan.org/CPAN/authors/id/F/FE/FERREIRA/Module-Which-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" string-truncate"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
