#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An open-source memory debugger for GNU/Linux"
HOMEPAGE="http://www.valgrind.org"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://valgrind.org/downloads/"$N-$V".tar.bz2"
CHECKSUM="288758010b271119a0ffc0183f1d6e38"

RDEPEND="glibc perl"
BDEPEND="gdb"
RECOMMENDED=""

NOTES="Valgrind will not work if glibc does not have debug symbols."

pbs_unpack() {
    dounpack
}

pbs_config() {
	case "${ARCH}" in 
		x86_64) config+="--enable-only64bit " ;;
		 i686)  config+="--enable-only32bit "
	esac
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

