#
# YLmf_OS package build script
#

DESCRIPTION="GLib's GObject library bindings for Python"
HOMEPAGE="http://www.pygtk.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
SRC_URI="http://ftp.gnome.org/pub/gnome/sources/pygobject/2.20/$N-$V.tar.bz2"

RDEPEND="python glib2 gdk-pixbuf"
BDEPEND=""
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/pygobject"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	YPB_CONFIG+=" --prefix=/usr  "
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
