#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GLib's GObject library bindings for Python"
HOMEPAGE="http://www.pygtk.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI=" http://ftp.gnome.org/pub/gnome/bindings/2.30/2.30.2/sources/python/"$N-$V$R".tar.bz2"

RDEPEND="glib2 gdk-pixbuf glibc libffi zlib"
BDEPEND="   "
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/pygobject"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-static"
	doconfig
}

pbs_build() {
	domake make
}

pbs_install() {
	domkinstall make
}
