#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GLib's GObject library bindings for Python"
HOMEPAGE="http://www.pygtk.org/"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.acc.umu.se/pub/gnome/bindings/2.32/2.32.1/sources/python/"$N-$V".tar.bz2"

RDEPEND="cairo expat fontconfig freetype glib2 glibc libffi libpng libX11 libXau libxcb libXdmcp libXrender pixman zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	dopatch ylmfos_disable-pygobject_register_sinkfunc-msg-2.26.0.patch
	config+="--disable-static"
	doconfig
}

pbs_build() {
	make $MAKEOPTS
}

pbs_install() {
	make DESTDIR="$destdir" install
}

