#
# Ylmf OS package build script
#

DESCRIPTION="GLib's GObject library bindings for Python"
HOMEPAGE="http://www.pygtk.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/bindings/2.30/2.30.2/sources/python/"$N-$V".tar.bz2"

RDEPEND="glib2 gdk-pixbuf glibc libffi zlib"
BDEPEND="   "
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	dopatch ylmfos_disable-pygobject_register_sinkfunc-msg.patch
	config+="--disable-static"
	doconfig
}

pbs_build() {
	domake make
}

pbs_install() {
	domkinstall make
}
