#
# YLmf_OS package build script
#

DESCRIPTION="A C and C++ cross-compilers for building Windows executables on Linux"
HOMEPAGE="http://mingw.sf.net http://sourceforge.net/projects/mingw/"
LICENSE="LGPL"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://nchc.dl.sourceforge.net/project/mingw/MinGW/BaseSystem/GCC/Version4/gcc-4.5.2-1/gcc-4.5.2-1-mingw32-src.tar.lzma
http://switch.dl.sf.net/sourceforge/mingw/w32api-3.14-mingw32-src.tar.gz
http://switch.dl.sf.net/sourceforge/mingw/mingwrt-3.18-mingw32-src.tar.gz "

RDEPEND=""
BDEPEND="mingw32-binutils mingw32-w32api"
RECOMMENDED=""
CONFLICTS="mingw32-gcc"

NOTES=""

pbs_unpack() {
	mkdir "$N-$V$R"
	cd "$N-$V$R"
	workdir="$(pwd)"
	#prepare headers
	mkdir -p mingw/include/
	tar xf "$YPPATH_SOURCE"/w32api-3.14-mingw32-src.tar.gz
	tar xf "$YPPATH_SOURCE"/mingwrt-3.18-mingw32-src.tar.gz
	cp -r w32api-3.14-mingw32/include/* \
	      mingwrt-3.18-mingw32/include/* \
	      mingw/include/

	tar xf "$YPPATH_SOURCE"/gcc-4.5.2-1-mingw32-src.tar.lzma
	tar xf gcc-4.5.2.tar.bz2
	ln -sf gcc-4.5.2 gcc
}

pbs_config() {
	mkdir -p build 
	cd build
	unset CFLAGS CXXFLAGS 
	chmod ugo+x ../gcc/configure
	chmod ugo+x ../gcc/move-if-change
	#
	YPB_CONFIG="--target=i486-mingw32 \
	            --host=$CHOST \
	            --build=$CHOST \
		    --prefix=/usr \
		    --enable-languages=c \
		    --enable-sjlj-exceptions \
		    --enable-hash-synchronization \
		    --disable-nls \
		    --disable-shared \
		    --disable-libssp \
		    --disable-libgomp \
		    --with-build-sysroot=$workdir \
		    --with-headers=$workdir/mingw/include "

	../gcc/configure $YPB_CONFIG
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	cd "$YPPATH_DEST"
	rm -rf usr/bin/i486-mingw32-{gcov,gccbug,gcc-*} \
	       usr/{include,lib/libiberty.a} \
	       usr/share/{info,man} \
	       usr/share/gcc-4.5.2/python
        
	strip usr/bin/*
        strip usr/libexec/gcc/i486-mingw32/4.5.2/{cc1*,collect2} 
	i486-mingw32-strip -g usr/lib/gcc/i486-mingw32/4.5.2/*.a
}
