#
# Ylmf OS package build script
#

DESCRIPTION="Multiple GNOME terminals in one window"
HOMEPAGE="http://www.tenshu.net/terminator/"
LICENSE="GPL"
YARCH="any"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://launchpadlibrarian.net/54318913/"$N-$V".tar.gz"

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
