#
# YLmf_OS package build script
#

DESCRIPTION="Multiple GNOME terminals in one window"
HOMEPAGE="http://www.tenshu.net/terminator/"
LICENSE="GPL"
YARCH="any"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://launchpadlibrarian.net/54318913/"$N-$V".tar.gz"

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
