#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A library designed to interconvert between many file formats used in molecular modeling and computational chemistry"
HOMEPAGE="http://openbabel.org/wiki/Main_Page"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://downloads.sourceforge.net/"$N"/"$N-$V".tar.gz"
CHECKSUM="1f029b0add12a3b55582dc2c832b04f8"

RDEPEND="wxWidgets"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig -DCMAKE_BUILD_TYPE=Release
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

