#
# YLmf_OS package build script
#

DESCRIPTION="list interned atoms defined on server"
HOMEPAGE="http://xorg.freedesktop.org/"
REPO=""
LICENSE=""
PACKAGER="Zhongxin Huang, hzx@115.com"
 
SRC_URI="http://www.x.org/releases/X11R7.6/src/app/"$N-$V$R".tar.bz2"

RDEPEND="glibc libXau libxcb libXdmcp"
BDEPEND="glibc-dev libXau-dev libxcb-dev libXdmcp-dev"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
