#
# Ylmf OS package build script
#

DESCRIPTION="webqq client (AIR)"
HOMEPAGE="www.qq.com"
REPO=""
LICENSE=""
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://dl_dir.qq.com/qqfile/web/webqq/WebQQ.air"

RDEPEND="adobe-air-sdk"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_install() {
	docp      "$YPPATH_SOURCE"/WebQQ.air  "$destdir"/usr/lib/"$N"
	dodesktop "$N.desktop"      "$N.png"
}

