#
# Ylmf OS package build script
#

DESCRIPTION="Visual Basic .NET Runtime and Class Libraries"
HOMEPAGE="http://www.go-mono.com"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://download.mono-project.com/sources/"$N"/"$N-$V".tar.bz2"

RDEPEND="mono"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config="--prefix=/usr"
	doconfig
}

pbs_build() {
	domake libdir=/usr/lib
}

pbs_install() {
	domkinstall libdir=/usr/lib
}


