#
# YLmf_OS package build script
#

DESCRIPTION="Visual Basic .NET Runtime and Class Libraries"
HOMEPAGE="http://www.go-mono.com"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://download.mono-project.com/sources/"$N"/"$N-$V".tar.bz2"

RDEPEND="mono"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG="--prefix=/usr"
	ypkg_config
}

pbs_build() {
	ypkg_make libdir=/usr/lib
}

pbs_install() {
	ypkg_mkinstall libdir=/usr/lib

	#
	#cat <<EOF >%{buildroot}/%{_libdir}/pkgconfig/mono-basic.pc
	#prefix=%{_prefix}
	#exec_prefix=%{_prefix}
	#libdir=%{_libdir}
}

