. /usr/lib/ybs/funcs

post_install() {
	gnome2_install_schema "/etc/gconf/schemas/gnome-screensaver.schemas"
        gnome2_install_defaut_gconf "bool" "/apps/gnome-screensaver/idle_activation_enabled"  "false"
        gnome2_install_defaut_gconf "bool" "/apps/gnome-screensaver/lock_enabled"  "false"
        gnome2_rarian_sk_update
        gnome2_desktop_database_update
        gnome2_icon_cache_update
        gnome2_gconfd_reload
}       

