#
# YLmf_OS package build script
#

DESCRIPTION="Meta build which provides python interfacing modules for some GNOME libraries"
HOMEPAGE="http://pygtk.org/"
REPO=""
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/"$N"/2.25/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

