#
# YLmf_OS package build script
#

DESCRIPTION="Fluendo mp3 decoder GStreamer plugin"
HOMEPAGE="http://www.fluendo.com/resources/fluendo_mp3.php"
REPO=""
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://core.fluendo.com/gstreamer/src/"$N"/"$N-$V$R".tar.bz2"

RDEPEND="gstreamer"
BDEPEND="${RDEPEND} "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
