#!/bin/bash

. /usr/lib/ybs/funcs

SCHEMAS="
    /etc/gconf/schemas/compiz-workarounds.schemas
    /etc/gconf/schemas/compiz-winrules.schemas
    /etc/gconf/schemas/compiz-wall.schemas
    /etc/gconf/schemas/compiz-vpswitch.schemas
    /etc/gconf/schemas/compiz-titleinfo.schemas
    /etc/gconf/schemas/compiz-thumbnail.schemas
    /etc/gconf/schemas/compiz-text.schemas
    /etc/gconf/schemas/compiz-staticswitcher.schemas
    /etc/gconf/schemas/compiz-snap.schemas
    /etc/gconf/schemas/compiz-shift.schemas
    /etc/gconf/schemas/compiz-session.schemas
    /etc/gconf/schemas/compiz-scaleaddon.schemas
    /etc/gconf/schemas/compiz-ring.schemas
    /etc/gconf/schemas/compiz-resizeinfo.schemas
    /etc/gconf/schemas/compiz-put.schemas
    /etc/gconf/schemas/compiz-opacify.schemas
    /etc/gconf/schemas/compiz-neg.schemas
    /etc/gconf/schemas/compiz-mousepoll.schemas
    /etc/gconf/schemas/compiz-mag.schemas
    /etc/gconf/schemas/compiz-kdecompat.schemas
    /etc/gconf/schemas/compiz-imgjpeg.schemas
    /etc/gconf/schemas/compiz-ezoom.schemas
    /etc/gconf/schemas/compiz-expo.schemas
    /etc/gconf/schemas/compiz-colorfilter.schemas
    /etc/gconf/schemas/compiz-animation.schemas"

post_install() {
    gnome2_install_schema "$SCHEMAS"
    gnome2_desktop_database_update
    gnome2_gconfd_reload
}

pre_remove() {
        gnome2_uninstall_schema "$SCHEMAS"
}

post_install() {
    gnome2_desktop_database_update
        gnome2_gconfd_reload
}

post_upgrade() {
    post_install
}

post_downgrade() {
    post_install
}

