#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An implementation of basic iCAL protocols from citadel, previously known as aurore"
HOMEPAGE="http://freeassociation.sourceforge.net"
LICENSE="GPL"
PACKAGER="StartOS Developers"
 
SRC_URI="http://switch.dl.sourceforge.net/sourceforge/freeassociation/"$N-$V".tar.gz"

RDEPEND="gcc-lib glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--enable-python --enable-cxx --with-bdb4"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

