#
# YLmf_OS package build script
#

DESCRIPTION="Foomatic wrapper script"
HOMEPAGE="http://www.linuxprinting.org/foomatic.html"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://www.openprinting.org/download/foomatic/"$N-$V".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README
}
