. /usr/lib/ybs/funcs

post_install() {
    # Nautilus
    gnome2_install_defaut_gconf "string" "/desktop/gnome/interface/toolbar_style" "icons"
    
    # Gnome panel
    gnome2_install_defaut_gconf "string" "/apps/panel/toplevels/top_panel_screen0/background/type" "image"
    gnome2_install_defaut_gconf "string" "/apps/panel/toplevels/top_panel_screen0/background/image" "/usr/share/themes/startos-black/gtk-2.0/Panel/panel-bg.png"
    #gnome2_install_defaut_gconf "int"    "/apps/panel/toplevels/top_panel_screen0/size" "40"
    #gnome2_install_defaut_gconf "string" "/apps/panel/toplevels/top_panel_screen0/background/type" "color"
    #gnome2_install_defaut_gconf "string" "/apps/panel/toplevels/top_panel_screen0/background/color" "#000000"
    #gnome2_install_defaut_gconf "string" "/apps/panel/toplevels/top_panel_screen0/background/opacity" "39321"
    
    # nautilus
    gnome2_install_defaut_gconf "int" "/apps/nautilus/preferences/sidebar_width"  "200"

    # Themes
    gnome2_install_defaut_gconf "string" "/apps/metacity/general/theme"        "startos-black"
    gnome2_install_defaut_gconf "string" "/desktop/gnome/interface/gtk_theme"  "startos-black"
    gnome2_install_defaut_gconf "string" "/desktop/gnome/interface/icon_theme" "startos"
    
    gnome2_install_defaut_gconf "int"    "/apps/compiz/plugins/decoration/allscreens/options/shadow_x_offset" "0"
    gnome2_install_defaut_gconf "int"    "/apps/compiz/plugins/decoration/allscreens/options/shadow_y_offset" "0"
    gnome2_install_defaut_gconf "float"  "/apps/compiz/plugins/decoration/allscreens/options/shadow_radius"   "0.0"
    gnome2_install_defaut_gconf "float"  "/apps/compiz/plugins/decoration/allscreens/options/shadow_opacity"  "1.0"
}

post_upgrade() {
    post_install
}

