#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Virtuoso, high-performance object-relational SQL database"
HOMEPAGE="http://virtuoso.openlinksw.com/wiki/main/Main"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://sourceforge.net/projects/"$N"/files/"$N"/"$V"/"$N"-opensource-"$V".tar.gz"
CHECKSUM="3991149c570f3738c3e819ce603e487f"

RDEPEND="openldap libxml2"
BDEPEND="bison flex gperf net-tools"

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--with-layout=debian
             --program-transform-name=\'s/isql$$/isql-vt/;s/isqlw/isqlw-vt/\'
             --with-readline"
    doconfig                 
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    # Confilct against unixodbc
    mv "$destdir"/usr/bin/{isql,isql-vt}  
}

