#
# YLmf_OS package build script
#

DESCRIPTION="Sun's java runtime environment"
HOMEPAGE="http://java.sun.com"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://download.java.net/dlj/binaries/jdk-6u25-dlj-linux-i586.bin"

RDEPEND="glibc libXtst"
BDEPEND=""
RECOMMENDED=""
CONFLICT="sun-jre"

INSTALL="$N.install"

pbs_unpack() {
	mkdir -p "$N-$V$R"
	cd "$N-$V$R"
	mkdir -p unbundle-jdk
	cd unbundle-jdk
	sh "$YPPATH_SOURCE"/jdk-6u25-dlj-linux-i586.bin --accept-license
	cd ../
	sh $filesdir/construct.sh unbundle-jdk linux-jdk linux-jre

}

pbs_install() {
	docp linux-jdk/jre "$destdir"/opt/java/
	install -Dm755 $filesdir/jre.profile "$destdir"/etc/profile.d/jre.sh

	cd "$destdir"
	#if [ "$CARCH" = "i686" ]; then
	doln /opt/java/jre/lib/i386/libnpjp2.so usr/lib/mozilla/plugins/libnpjp2.so
	#else ln -s /opt/java/jre/lib/amd64/libnpjp2.so ${pkgdir}/usr/lib/mozilla/plugins
	#fi
	docp opt/java/jre/{COPYRIGHT,LICENSE,THIRDPARTYLICENSEREADME.txt}  usr/share/licenses/jre/
	# Fix system prefs folder (FS#18872)
	install -dm755 etc/.java/.systemPrefs
	#
	dodesktop "opt/java/jre/lib/desktop/applications/sun-java.desktop" \
	               "opt/java/jre/lib/images/icons/sun-java.png"
}

