#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A hardware-independent library for executing real-mode x86 code"
HOMEPAGE="http://www.codon.org.uk/~mjg59/libx86"
LICENSE="custom"
PACKAGER="StartOS Developers"

SRC_URI="http://www.codon.org.uk/~mjg59/"$N"/downloads/"$N-$V".tar.gz"
CHECKSUM="41bee1f8e22b82d82b5f7d7ba51abc2a"

RDEPEND="glibc"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
        dounpack
}

pbs_patch() {
	dopatch libx86-ifmask.patch
}

pbs_build() {
	[ "$ARCH" = "x86_64" ] && domake BACKEND=x86emu || domake
}

pbs_install() {
	domkinstall
	chmod 644 "$destdir"/usr/lib/libx86.a
	dodoc COPYRIGHT
}

