#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="database of robots.txt-derived permissions  "
HOMEPAGE="http://search.cpan.org/"
PACKAGER="StartOS Developers"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://cpan.communilink.net/authors/id/G/GA/GAAS/WWW-RobotRules-"$V".tar.gz"

RDEPEND="perl uri-perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

