#
# YLmf_OS package build script
#

DESCRIPTION="Low-level HTTP connection (client)  "
HOMEPAGE="http://search.cpan.org/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://mirror.osqdu.org/CPAN/authors/id/G/GA/GAAS/Net-HTTP-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}
