#
# Ylmf OS package build script
#

DESCRIPTION="Fetion protocol library powered by ofetion project."
HOMEPAGE="http://code.google.com/p/ofetion/"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ofetion.googlecode.com/files/"$N-$V".tar.gz"
CHECKSUM="95003d5f68addad39a23ed5b2894f2c51c53b713"

RDEPEND="glibc zlib sqlite openssl libxml2"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
