#
# YLmf_OS package build script
#

DESCRIPTION="Fetion protocol library powered by ofetion project."
HOMEPAGE="http://code.google.com/p/ofetion/"
REPO=""
LICENSE="GPLv2"
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://ofetion.googlecode.com/files/"$N-$V$R".tar.gz"

RDEPEND=""
BDEPEND="${RDEPEND} "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
