#
# YLmf_OS package build script
#

DESCRIPTION="Advanced Linux Sound Architecture kernel module"
HOMEPAGE="http://www.alsa-project.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="ftp://ftp.alsa-project.org/pub/driver/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

OPINION="nodev"

pbs_unpack() {
        ypkg_unpack
}

pbs_install() {
	ypkg_dosrc *
}

