#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Docbook DTD for XML"
HOMEPAGE="http://docbook.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://www.docbook.org/sgml/"$V$R"/"$N-$V".zip"

RDEPEND=""
BDEPEND="unzip sgml-common"
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
	dounpack
}

pbs_install() {
	sed -i -e '/ISO 8879/d' -e '/gml/d' docbook.cat
	docp_rename docbook.cat "$destdir"/usr/share/sgml/docbook/sgml-dtd-"$V$R"/catalog
	docp *.dtd *.mod *.dcl  "$destdir"/usr/share/sgml/docbook/sgml-dtd-"$V$R"
}

