#
# YLmf_OS package build script
#

DESCRIPTION="Docbook DTD for XML"
HOMEPAGE="http://docbook.org"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://www.docbook.org/sgml/"$V$R"/"$N-$V$R".zip"

RDEPEND=""
BDEPEND="${RDEPEND} unzip sgml-common"
RECOMMENDED=""

pbs_unpack() {
	ypkg_unpack
}

pbs_install() {
	sed -i -e '/ISO 8879/d' -e '/gml/d' docbook.cat
	ypkg_docp_rename docbook.cat "$YPPATH_DEST"/usr/share/sgml/docbook/sgml-dtd-"$V$R"/catalog
	ypkg_docp *.dtd *.mod *.dcl  "$YPPATH_DEST"/usr/share/sgml/docbook/sgml-dtd-"$V$R"
	cd "$YPPATH_DEST"/usr/share/sgml/docbook/sgml-dtd-"$V$R"
}

pbs_postinst() {
	install-catalog --add /etc/sgml/sgml-docbook-dtd-"$V$R".cat /usr/share/sgml/docbook/sgml-dtd-"$V$R"/catalog
	install-catalog --add /etc/sgml/sgml-docbook-dtd-"$V$R".cat /etc/sgml/sgml-docbook.cat
	cat >> /usr/share/sgml/docbook/sgml-dtd-$V$R/catalog << "EOF"
-- Begin Single Major Version catalog changes --
PUBLIC "-//OASIS//DTD DocBook V4.4//EN" "docbook.dtd"
PUBLIC "-//OASIS//DTD DocBook V4.3//EN" "docbook.dtd"
PUBLIC "-//OASIS//DTD DocBook V4.2//EN" "docbook.dtd"
PUBLIC "-//OASIS//DTD DocBook V4.1//EN" "docbook.dtd"
PUBLIC "-//OASIS//DTD DocBook V4.0//EN" "docbook.dtd"
-- End Single Major Version catalog changes --
EOF
}
