#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Check for POD errors in files"
HOMEPAGE="http://search.cpan.org/dist/$N"
LICENSE="GPL,PerlArtistic"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://search.cpan.org/CPAN/authors/id/D/DW/DWHEELER/$N-$V.tar.gz"
CHECKSUM="089c8f272931df82f6c4d11a74f04628"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
    perl_cleanup
}

