#
# YLmf_OS package build script
#

DESCRIPTION="gtk widget for displaying rasterized maps"
HOMEPAGE="http://projects.gnome.org/libchamplain/"
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/"$N"/0.8/"$N-$V".tar.gz"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="" #--enable-vala"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}


