#
# YLmf_OS package build script
#

DESCRIPTION="gtk widget for displaying rasterized maps"
HOMEPAGE="http://projects.gnome.org/libchamplain/"
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/"$N"/0.8/"$N-$V".tar.gz"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="" #--enable-vala"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}


