#
# YLmf_OS package build script
#

DESCRIPTION="IJ Printer Driver Ver. 2.70 for cannon ip1800series printers"
HOMEPAGE="http://support-asia.canon-asia.com/contents/ASIA/EN/0900718601.html"
REPO=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://gdlp01.c-wss.com/gds/6/0900007186/01/cnijfilter-ip1800series-2.70-1.i386.rpm"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_install() {
	ypkg_docp data/*  "$YPPATH_DEST"
}
