#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Database for the m17n library"
HOMEPAGE="http://www.m17n.org/m17n-lib/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://www.m17n.org/m17n-lib-download/"$N-$V".tar.gz"
CHECKSUM="0c4723d0e6f6f5b2e8f40705ad5ab7d3"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

