#
# Ylmf OS package build script
#
HOMEPAGE="http://www.x.org/wiki/"
 
SRCURL="http://www.x.org/releases/X11R7.5/src/lib"
SRC_URI="$SRCURL/libXt-1.0.7.tar.bz2"

RDEPEND="libSM libICE libX11 util-linux-ng libxcb libXau libXdmcp"
BDEPEND=" x11-libs/libSM"

pbs_unpack()
{
        dounpack
}

pbs_config()
{
	
	config+=" --sysconfdir=/etc --mandir=/usr/share/man --localstatedir=/var "
	doconfig
}

pbs_build()
{
	domake
}

pbs_install()
{
	domkinstall
}
