#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Allows a perl developer to use the GnomeCanvas widget with Gtk2-Perl. "
HOMEPAGE="http://search.cpan.org/~tsch/Glib-1.223/Glib.pm"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/Gnome2-Canvas-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
