#
# YLmf_OS package build script
#

DESCRIPTION="Allows a perl developer to use the GnomeCanvas widget with Gtk2-Perl. "
HOMEPAGE="http://search.cpan.org/~tsch/Glib-1.223/Glib.pm"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/Gnome2-Canvas-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
