#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Database independent interface for Perl"
HOMEPAGE="http://search.cpan.org/dist/DBI"
LICENSE="GPL,PerlArtistic"
GROUP="perl"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://www.cpan.org/authors/id/T/TI/TIMB/DBI-$V.tar.gz"
CHECKSUM="9836bcf1b9acc842089aa10b16736909"

RDEPEND="glibc perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}
