#!/bin/bash
#
#

# make 
# modinfo ./os/linux/rt5370sta.ko
#

echo "package rt5370sta-driver"
echo "module rt5370sta.ko"
echo "description RT2870 Wireless Lan Linux Driver"
echo "alias usb:v13D3p3329d*dc*dsc*dp*ic*isc*ip*
alias usb:v13D3p3365d*dc*dsc*dp*ic*isc*ip*
alias usb:v148Fp5372d*dc*dsc*dp*ic*isc*ip*
alias usb:v148Fp5370d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DF6p0050d*dc*dsc*dp*ic*isc*ip*
alias usb:v148Fp3370d*dc*dsc*dp*ic*isc*ip*
alias usb:v1EDAp2012d*dc*dsc*dp*ic*isc*ip*
alias usb:v0586p343Ed*dc*dsc*dp*ic*isc*ip*
alias usb:v0586p341Ed*dc*dsc*dp*ic*isc*ip*
alias usb:v0586p341Ad*dc*dsc*dp*ic*isc*ip*
alias usb:v0789p0166d*dc*dsc*dp*ic*isc*ip*
alias usb:v07FAp7712d*dc*dsc*dp*ic*isc*ip*
alias usb:v13D3p3321d*dc*dsc*dp*ic*isc*ip*
alias usb:v13D3p3307d*dc*dsc*dp*ic*isc*ip*
alias usb:v083ApA703d*dc*dsc*dp*ic*isc*ip*
alias usb:v5A57p0282d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p821Ad*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p3821d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p822Ad*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p871Ad*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p3871d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p3822d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p6899d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p870Ad*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p3870d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p899Ad*dc*dsc*dp*ic*isc*ip*
alias usb:v203Dp14A9d*dc*dsc*dp*ic*isc*ip*
alias usb:v0B05p1784d*dc*dsc*dp*ic*isc*ip*
alias usb:v20B8p8888d*dc*dsc*dp*ic*isc*ip*
alias usb:v203Dp1480d*dc*dsc*dp*ic*isc*ip*
alias usb:v04BBp0948d*dc*dsc*dp*ic*isc*ip*
alias usb:v04BBp0947d*dc*dsc*dp*ic*isc*ip*
alias usb:v04BBp0945d*dc*dsc*dp*ic*isc*ip*
alias usb:v5A57p0283d*dc*dsc*dp*ic*isc*ip*
alias usb:v5A57p5257d*dc*dsc*dp*ic*isc*ip*
alias usb:v1D4Dp0011d*dc*dsc*dp*ic*isc*ip*
alias usb:v1D4Dp000Ed*dc*dsc*dp*ic*isc*ip*
alias usb:v1D4Dp000Cd*dc*dsc*dp*ic*isc*ip*
alias usb:v07D1p3C17d*dc*dsc*dp*ic*isc*ip*
alias usb:v07D1p3C16d*dc*dsc*dp*ic*isc*ip*
alias usb:v07D1p3C0Fd*dc*dsc*dp*ic*isc*ip*
alias usb:v07D1p3C0Ed*dc*dsc*dp*ic*isc*ip*
alias usb:v07D1p3C0Dd*dc*dsc*dp*ic*isc*ip*
alias usb:v07D1p3C0Ad*dc*dsc*dp*ic*isc*ip*
alias usb:v1EDAp2310d*dc*dsc*dp*ic*isc*ip*
alias usb:v1A32p0304d*dc*dsc*dp*ic*isc*ip*
alias usb:v7392p4085d*dc*dsc*dp*ic*isc*ip*
alias usb:v7392p7711d*dc*dsc*dp*ic*isc*ip*
alias usb:v07B8p3072d*dc*dsc*dp*ic*isc*ip*
alias usb:v07B8p3071d*dc*dsc*dp*ic*isc*ip*
alias usb:v07B8p3070d*dc*dsc*dp*ic*isc*ip*
alias usb:v2019p5201d*dc*dsc*dp*ic*isc*ip*
alias usb:v2019pAB25d*dc*dsc*dp*ic*isc*ip*
alias usb:v1044p800Dd*dc*dsc*dp*ic*isc*ip*
alias usb:v13D3p3305d*dc*dsc*dp*ic*isc*ip*
alias usb:v13D3p3273d*dc*dsc*dp*ic*isc*ip*
alias usb:v1740p9709d*dc*dsc*dp*ic*isc*ip*
alias usb:v1740p9708d*dc*dsc*dp*ic*isc*ip*
alias usb:v1740p9707d*dc*dsc*dp*ic*isc*ip*
alias usb:v1740p9706d*dc*dsc*dp*ic*isc*ip*
alias usb:v1740p9705d*dc*dsc*dp*ic*isc*ip*
alias usb:v1740p9703d*dc*dsc*dp*ic*isc*ip*
alias usb:v083ApA702d*dc*dsc*dp*ic*isc*ip*
alias usb:v083ApA701d*dc*dsc*dp*ic*isc*ip*
alias usb:v083Ap7511d*dc*dsc*dp*ic*isc*ip*
alias usb:v18C5p0012d*dc*dsc*dp*ic*isc*ip*
alias usb:v14B2p3C12d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DF6p005Fd*dc*dsc*dp*ic*isc*ip*
alias usb:v0DF6p0047d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DF6p0048d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DF6p0042d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DF6p003Ed*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p822Bd*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p871Bd*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p822Cd*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p871Cd*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p3820d*dc*dsc*dp*ic*isc*ip*
alias usb:v148Fp3072d*dc*dsc*dp*ic*isc*ip*
alias usb:v148Fp3071d*dc*dsc*dp*ic*isc*ip*
alias usb:v148Fp3070d*dc*dsc*dp*ic*isc*ip*"
