#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The World-Wide Web library for Perl"
HOMEPAGE="https://metacpan.org/release/$N"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="GPL,PerlArtistic"
YARCH="any"

SRC_URI="http://search.cpan.org/CPAN/authors/id/G/GA/GAAS/"$N-$V".tar.gz"
CHECKSUM="24acf2fe33b2295f048f8859e9665ee3"

RDEPEND="Encode-Locale File-Listing HTML-Parser HTTP-Cookies HTTP-Daemon HTTP-Date HTTP-Message HTTP-Negotiate LWP-MediaTypes Net-HTTP URI WWW-RobotRules "
BDEPEND=" "
RECOMMENDED="LWP-Protocol-https"
CONFLICT=""
OPTIONA="LWP-Protocol-https: for https:// url schemes'"

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1 PERL5LIB="" \
           PERL_AUTOINSTALL=--skipdeps \
           PERL_MM_OPT="INSTALLDIRS=vendor DESTDIR='$destdir'"  \
           PERL_MB_OPT="--installdirs vendor --destdir '$destdir'" \
           MODULEBUILDRC=/dev/null
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}

