#
# Ylmf OS package build script
#

DESCRIPTION="Facilitates the creation and modification of PDF files"
HOMEPAGE="http://search.cpan.org/~ssimms/PDF-API2-2.019/"
LICENSE="GPL PerlArtistic"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://mirrors.xmu.edu.cn/CPAN/authors/id/S/SS/SSIMMS/PDF-API2-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

