#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A language for writing Python extension modules"
HOMEPAGE="http://www.cosc.canterbury.ac.nz/greg.ewing/python/Pyrex/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"
YARCH="any"

SRC_URI="http://www.cosc.canterbury.ac.nz/greg.ewing/python/Pyrex/Pyrex-"$V".tar.gz"

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
