#
# YLmf_OS package build script
#

DESCRIPTION="Terminal Emulator for X Windows"
HOMEPAGE="http://invisible-island.net/xterm/xterm.html"
 
SRC_URI="http://invisible-island.net/datafiles/release/"$N".tar.gz"

RDEPEND="expat fontconfig freetype glibc libICE libSM libX11 libXau libXaw libxcb libXdmcp libXext libXft libXmu libXpm libXrender libXt ncurses util-linux-ng zlib"
BDEPEND="expat-dev fontconfig-dev freetype-dev glibc-dev libICE-dev libSM-dev libX11-dev libXau-dev libXaw-dev libxcb-dev libXdmcp-dev libXext-dev libXft-dev libXmu-dev libXpm-dev libXrender-dev libXt-dev ncurses-dev util-linux-ng-dev zlib-dev"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
