#
# Ylmf OS package build script
#

DESCRIPTION="C++ bindings for gnome-vfs"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/bindings/2.32/2.32.1/sources/c++/"$N-$V".tar.bz2"

RDEPEND="avahi dbus dbus-glib gcc-lib gconf glib2 glibc glibmm gnome-vfs libsigc++ libxml2 openssl orbit zlib"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

