#
# YLmf_OS package build script
#

DESCRIPTION="Compizconfig Settings Manager"
HOMEPAGE="http://www.compiz.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://releases.compiz.org/"$V$R"/"$N-$V".tar.bz2"

RDEPEND="compiz compiz-bcop libcompizconfig compizconfig-python"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

