#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="windows 7 theme for plymouth"
HOMEPAGE="www.ylmf.net"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
YARCH="any"

SRC_URI="$N-$V.tar.bz2"

RDEPEND="plymouth"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_install() {
	docp lib "$destdir"
}

