#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="windows 7 theme for plymouth"
HOMEPAGE="http://www.startos.org"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="$N-$V.tar.bz2"

RDEPEND="plymouth"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_install() {
    docp lib "$PKGDIR"
}

