#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A versatile IDE for GNOME"
HOMEPAGE="http://www.anjuta.org"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/"$N"/2.32/"$N-$V".tar.bz2"

RDEPEND="devhelp gdl glade libgda subversion vte"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--enable-introspection=no
	         --disable-schemas-install
		 --disable-vala" # needs vala-1.10
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

