#
# Ylmf OS package build script
#

DESCRIPTION="A versatile IDE for GNOME"
HOMEPAGE="http://www.anjuta.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/"$N"/2.32/"$N-$V".tar.bz2"

RDEPEND="apr apr-util atk cairo cyrus-sasl dbus dbus-glib devhelp enchant expat fontconfig freetype gail gcc-lib gconf gdk-pixbuf gdl glade glib2 glibc gnutls gst-plugins-base gstreamer gtk+ gtksourceview icu keyutils krb5 libgcrypt libgda libgnome-keyring libgpg-error libICE libjpeg-turbo libpng libproxy libSM libsoup libtasn1 libunique libwnck libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libxml2 libXrandr libXrender libXres libxslt libXt ncurses neon openssl orbit pango pixman python sqlite startup-notification util-linux-ng vte webkitgtk zlib"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--enable-introspection=no 
	         --disable-schemas-install
		 --disable-vala"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

