#
# YLmf_OS package build script
#

DESCRIPTION="A versatile IDE for GNOME"
HOMEPAGE="http://www.anjuta.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/anjuta/2.32/"$N-$V".tar.bz2"

RDEPEND="apr apr-util atk cairo cyrus-sasl dbus dbus-glib e2fsprogs expat fontconfig freetype gcc gconf gconf-dbus gdk-pixbuf gdl glade glib2 glibc gtk+ gtksourceview keyutils krb5 libgcrypt libgda libgnome-keyring libgpg-error libpng libunique libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libxml2 libXrandr libXrender libxslt lunar-calendar lunar-date ncurses neon openssl orbit pango pixman sqlite util-linux-ng vala vte zlib"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--enable-introspection=no --disable-schemas-install"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}


