#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="a toolkit to convert between various different translation formats"
HOMEPAGE="http://translate.sourceforge.net/"
LICENSE="GPL"
PACKAGER="StartOS Developers"
YARCH="any"

SRC_URI="http://sourceforge.net/projects/translate/files/Translate%20Toolkit/"$V"/"$N-$V".tar.bz2"

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodoc COPYING LICENSE
}

