#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Generating 'patchset' information from a CVS repository"
HOMEPAGE="http://www.cobite.com/cvsps/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://www.catb.org/~esr/$N/$N-$V.tar.gz"
CHECKSUM="5bdcc9e49e1837e8016cdd139fe05ce7"

RDEPEND="zlib"
RECOMMENDED=""
BDEPEND="asciidoc"
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake prefix=/usr
}

pbs_install() {
    make prefix="$destdir"/usr install
}
