#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Generating 'patchset' information from a CVS repository"
HOMEPAGE="http://www.cobite.com/cvsps/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://www.cobite.com/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc zlib"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake prefix=/usr
}

pbs_install() {
	make prefix="$destdir"/usr install
}


