#
# YLmf_OS package build script
#

DESCRIPTION="themes for smplayer"
HOMEPAGE="http://smplayer.berlios.de/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

REPO="testing"
SRC_URI="http://download.berlios.de/smplayer/"$N-$V$R".tar.bz2"

RDEPEND="smplayer"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake PREFIX=/usr
}

pbs_install() {
	domkinstall PREFIX=/usr
}


