#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="HTTP style messages"
HOMEPAGE="http://search.cpan.org/dist/HTTP-Message"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="GPL,PerlArtistic"
GROUP="perl"
YARCH="any"

SRC_URI="http://search.cpan.org/CPAN/authors/id/G/GA/GAAS/HTTP-Message-$V.tar.gz"
CHECKSUM="d41b22c7c01b974f2b4e85d401a6b552"

RDEPEND="perl-encode-locale perl-html-parser perl-http-date perl-lwp-mediatypes perl-uri perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1 PERL5LIB="" \
           PERL_AUTOINSTALL=--skipdeps \
           PERL_MM_OPT="INSTALLDIRS=vendor" \
           PERL_MB_OPT="--installdirs vendor" \
           MODULEBUILDRC=/dev/null
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}
