#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An interface compiler that connects programs written in C and C++ with scripting languages"
HOMEPAGE="http://www.swig.org"
LICENSE="custom"
PACKAGER="StartOS Developers"

SRC_URI="http://prdownloads.sourceforge.net/"$N"/"$N-$V".tar.gz"

RDEPEND="gcc-lib glibc libpcre zlib"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc LICENSE LICENSE-UNIVERSITIES
}

