#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GTK+2 bindings for Python"
HOMEPAGE="http://www.pygtk.org/"
LICENSE="GPL-2"
PACKAGER="StartOS Developers"
SRC_URI="http://ftp.gnome.org/pub/gnome/sources/pygtksourceview/2.8/$N-$V.tar.bz2"

RDEPEND=""
BDEPEND=" gtksourceview pygtk"
RECOMMENDED="docbook-xml"

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/pygtksourceview"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=" --prefix=/usr"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
