#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GTK bindings for Python"
HOMEPAGE="http://www.pygtk.org/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/$N/2.10/$N-$V.tar.bz2"
CHECKSUM="b4b47c5aeb67a26141cb03663091dfdf5c15c8a8aae4d69c46a6a943ca4c5974"

RDEPEND="gtksourceview2 pygtk"
BDEPEND="intltool pkgconfig"
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--disable-static --disable-docs"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

