#
# YLmf_OS package build script
#

DESCRIPTION="GTK+2 bindings for Python"
HOMEPAGE="http://www.pygtk.org/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.30/2.30.2/sources/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND="${RDEPEND} gtksourceview pygtk"
RECOMMENDED="docbook-xml"

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/pygtksourceview"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-docs --disable-gtk-doc"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
