#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="HSQLDB Java libraries"
HOMEPAGE="http://hsqldb.org/"
REPO=""
LICENSE="custom"
PACKAGER="StartOS Developers"

SRC_URI="http://nchc.dl.sourceforge.net/project/hsqldb/hsqldb/hsqldb_1_8_0/hsqldb_1_8_0_10.zip"

RDEPEND=""
BDEPEND="jdk apache-ant"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_install() {
	. /etc/profile.d/jdk.sh
	. /etc/profile.d/jre.sh
	. /etc/profile.d/apache-ant.sh

	cd build && ant jar && cd ..

	docp lib/hsqldb.jar "$destdir"/"$JAVA_HOME"
	dodoc doc/hsqldb_lic.txt
}
