#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="HSQLDB Java libraries"
HOMEPAGE="http://hsqldb.org/"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://nchc.dl.sourceforge.net/project/hsqldb/hsqldb/hsqldb_1_8_0/hsqldb_1_8_0_10.zip"

RDEPEND=""
BDEPEND="jdk apache-ant"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_install() {
    . /etc/profile.d/jdk.sh
    . /etc/profile.d/jre.sh
    . /etc/profile.d/apache-ant.sh

    cd build && ant jar && cd ..

    docp lib/hsqldb.jar "$PKGDIR"/"$JAVA_HOME"
    dodoc doc/hsqldb_lic.txt
}
