#
# Ylmf OS package build script
#

DESCRIPTION="driver manager for ylmfos"
HOMEPAGE="www.ylmf.net"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="git://10.0.0.11/"$N".git"

RDEPEND="python boost gcc-lib glibc lm_sensors" 
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

