#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="C++ bindings for libglade"
HOMEPAGE="http://gtkmm.sourceforge.net"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/$N/2.6/$N-$V.tar.bz2"
CHECKSUM="f9ca5b67f6c551ea98790ab5f21c19d0"

RDEPEND="gtkmm libglade"
BDEPEND="pkgconfig"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

