#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="C++ bindings for libglade"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="ftp://lug.mtu.edu/gentoo/distfiles/"$N-$V".tar.bz2"

RDEPEND="gtkmm libglade"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
