#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="a collection of ylmfos bug fixed scripts"
HOMEPAGE="www.ylmf.org"
LICENSE="GPL"
PRIORITY="required"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
YARCH="any"

SRC_URI=""

INSTALL="$N.install"

RDEPEND=""
BDEPEND=""
RECOMMENDED="imagemagick app-logo app-desktop"
CONFLICT=""

pbs_install() {
	dodoc "$filesdir"/readme
}

