#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="a collection of startos bug fixed scripts"
HOMEPAGE="http://www.startos.org"
LICENSE="GPL"
PACKAGER="StartOS Developers"
YARCH="any"

SRC_URI=""

INSTALL="$N.install"

RDEPEND=""
BDEPEND=""
RECOMMENDED="imagemagick app-logo app-desktop startos-bug-fix"
CONFLICT="startos-bug-fix"

pbs_install() {
	dodoc "$filesdir"/readme
}

