#
# Ylmf OS package build script
#

DESCRIPTION="a collection of ylmfos bug fixed scripts"
HOMEPAGE="www.ylmf.org"
LICENSE="GPL"
PRIORITY="required"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI=""

INSTALL="$N.install"

RDEPEND=""
BDEPEND=""
RECOMMENDED="libbluray enca lzo a52dec nas mplayer-svn systemd"
CONFLICT=""

pbs_install() {
	mkdir -p "$destdir"/usr/share/"$N"
	touch "$destdir"/usr/share/"$N"/Readme
}

