#
# Ylmf OS package build script
#

DESCRIPTION="A in-process library that implements SQL database engine"
HOMEPAGE="http://www.sqlite.org"
SRC_URI=" http://www.sqlite.org/"$N-$V$R".tar.gz "

RDEPEND="readline ncurses"
BDEPEND=" dev-lang/tcl"
OPIONAL="dev-lang/tcl"

pbs_unpack() {
        dounpack
}

pbs_config() {
	dopatch "$N-$V$R"-build_fix-1.patch
	config+=" --prefix=/usr            
	              --sysconfdir=/etc        
	              --localstatedir=/var 	
	              --enable-threadsafe      
		      --enable-cross-thread-connections
		      --enable-tempstore=yes   
		      --enable-load-extension 
		      --enable-static=no "
	if ! doconfig;then
		autoconf
		doconfig
	fi
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	install -m755 -d           "$destdir"/usr/share/{man,doc}/"$N-$V$R"
	install -m 0644 sqlite3.1  "$destdir"/usr/share/man/"$N-$V$R"
	dodoc README* VERSION
}

