#
# Ylmf OS package build script
#

DESCRIPTION="Integrated version control support for your desktop"
HOMEPAGE="RabbitVCS is a set of graphical tools written to provide simple and straightforward access to the version control systems you use."
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://rabbitvcs.googlecode.com/files/"$N-$V".tar.bz2"
CHECKSUM="a9e1e741a3e665e3ce2769b2730fafde26955b53"

RDEPEND="nautilus-python(>=0.5.0) pygtk(>=2.12.1) pygobject(>=2.14.1) configobj(>=4.4.0) dbus-python(>=0.80) meld(>=1.1.2) simplejson dulwich subversion(>=1.4.6) pysvn(>=1.5.2)"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_install() {
	python setup.py install --root="$destdir" --optimize=1	

	# cli
	cd "$srcdir"/clients/cli
	docp rabbitvcs "$destdir"/usr/bin/

	# gedit
	cd "$srcdir"/clients/gedit
	docp rabbitvcs.gedit-plugin rabbitvcs-plugin.py "$destdir"/usr/lib/gedit-2/plugins/

	# nautilus
	cd "$srcdir"/clients/nautilus
	docp RabbitVCS.py "$destdir"/usr/lib/nautilus/extensions-2.0/python

	# thunar
	cd "$srcdir"/clients/thunar
	docp RabbitVCS.py "$destdir"/usr/lib/thunarx-2/python
}


