#
# YLmf_OS package build script
#

DESCRIPTION="Advanced version control system"
HOMEPAGE="http://subversion.apache.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI=" http://subversion.tigris.org/downloads/"$N-$V$R".tar.bz2 "

RDEPEND="zlib sqlite apr-util expat apr util-linux-ng neon"
BDEPEND=" apr apr-util sqlite"
RECOMMENDED=""

NOTES="
Python
Apache Required for mod_dav_svn
JDK
JUnit
Dante
Jikes
pkg-config
expat or libXML2
OpenSSL Add --with-ssl to configure
MIT krb5 or Heimdal
Berkeley DB or GDBM Add --with-berkeley-db or --with-gdbm to configure
SWIG
Ruby
Neon
"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_patch "$N-$V$R"-build_fix-1.patch
	YPB_CONFIG+="--enable-maintainer-mode --disable-shared --with-neon=/usr/bin/neon-config"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc doc/*
}
