#
# YLmf_OS package build script
#

DESCRIPTION="Advanced version control system"
HOMEPAGE="http://subversion.apache.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://subversion.tigris.org/downloads/"$N-$V$R".tar.bz2"

RDEPEND="zlib sqlite apr-util expat apr util-linux-ng"
BDEPEND=" apr apr-util sqlite"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	wget http://www.webdav.org/neon/neon-0.28.4.tar.gz
	tar xf neon-0.28.4.tar.gz
	mv neon-0.28.4 neon
	config+="--disable-shared"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	#dodoc doc/*
}
