#
# YLmf_OS package build script
#

DESCRIPTION="Advanced version control system"
HOMEPAGE="http://subversion.apache.org/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://subversion.tigris.org/downloads/"$N-$V$R".tar.bz2"

RDEPEND="zlib sqlite apr-util expat apr util-linux-ng"
BDEPEND="${RDEPEND} apr apr-util sqlite"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--with-neon=/usr/bin/neon-config
	             --disable-shared"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc doc/*
}
