#
# Ylmf OS package build script
#

DESCRIPTION="Python wrapper for cairo vector graphics library"
HOMEPAGE="http://cairographics.org/pycairo/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://cairographics.org/releases/"$N-$V".tar.gz"

RDEPEND="cairo expat fontconfig freetype glibc libpng libX11 libXau libxcb libXdmcp libXrender pixman python zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	make DESTDIR="$destdir" install
}

