#
# YLmf_OS package build script
#

DESCRIPTION="Python wrapper for cairo vector graphics library"
HOMEPAGE="http://cairographics.org/pycairo/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://cairographics.org/releases/"$N-$V".tar.gz"

RDEPEND="cairo expat fontconfig freetype glibc libpng libX11 libXau libxcb libXdmcp libXrender pixman python zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	make DESTDIR="$YPPATH_DEST" install
}

