#
# YLmf_OS package build script
#

DESCRIPTION="nautilus reload"
HOMEPAGE="www.ylmf.com"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="git://192.168.1.58/"$N".git"

RDEPEND="nautilus"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
