#
# YLmf_OS package build script
#

DESCRIPTION="A command to eject a disc from the CD-ROM drive"
HOMEPAGE="http://eject.sourceforge.net/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://tx-us.lunar-linux.org/lunar/mirrors/"$N-$V$R".tar.gz"

RDEPEND="glibc"
BDEPEND="${RDEPEND} "
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README
}
