#
# Ylmf OS package build script
#

DESCRIPTION="GtkSharp's gconf module of the gnome-sharp tarball"
HOMEPAGE="http://www.mono-project.com/GtkSharp"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.novell.com/pub/mono/sources/gnome-sharp2/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	dopatch "donot-build-sample.patch"
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
