#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The open source, cross platform, free C++ IDE."
HOMEPAGE="http://www.codeblocks.org/"
LICENSE="GPLv3"
PACKAGER="StartOS Developers"

SRC_URI="http://download.berlios.de/codeblocks/"$N-$V"-src.tar.bz2"

RDEPEND="wxWidgets"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--with-contrib-plugins=all"
	./bootstrap
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

