#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The open source, cross platform, free C++ IDE."
HOMEPAGE="http://www.codeblocks.org/"
REPO=""
LICENSE=""
PACKAGER="StartOS Developers"

SRC_URI="http://download.berlios.de/codeblocks/"$N-$V$R"-src.tar.bz2"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""

INSTALL="$N.install"

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

