#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GNU Portable Threads"
HOMEPAGE="http://www.gnu.org/software/pth/"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="ftp://ftp.gnu.org/gnu/"$N"/"$N-$V".tar.gz"
CHECKSUM="9a71915c89ff2414de69fe104ae1016d513afeee"

RDEPEND="gawk glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--disable-static 
             --enable-shared 
             --with-pic"
    doconfig
}

pbs_build() {
    make
}

pbs_install() {
    domkinstall
}


