#
# Ylmf OS package build script
#

DESCRIPTION="GNU Portable Threads"
HOMEPAGE="http://www.gnu.org/software/pth/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="ftp://ftp.gnu.org/gnu/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	dopatch pth-2.0.5-parallelfix.patch
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README 
}

