#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A generic framework for creating extensible applications"
HOMEPAGE="http://www.mono-project.com/Mono.Addins"
LICENSE="custom:MIT"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://download.mono-project.com/sources/"$N"/"$N-$V".tar.bz2"

RDEPEND="gtk-sharp mono"
BDEPEND="pkgconfig"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--enable-gui"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

