#
# YLmf_OS package build script
#

DESCRIPTION="Vorbis codec library"
HOMEPAGE="http://xiph.org/vorbis"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://downloads.xiph.org/releases/vorbis/"$N-$V".tar.bz2"

RDEPEND="glibc libogg"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

