#
# Ylmf OS package build script
#

DESCRIPTION="Vorbis codec library"
HOMEPAGE="http://xiph.org/vorbis"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://downloads.xiph.org/releases/vorbis/"$N-$V".tar.bz2"

RDEPEND="glibc libogg"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

