#
# YLmf_OS package build script
#

DESCRIPTION="graphical boot animation and logger"
HOMEPAGE="http://cgit.freedesktop.org/plymouth/ http://www.freedesktop.org/software/plymouth/releases/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="https://launchpad.net/ubuntu/lucid/+source/"$N"/0.8.2-2ubuntu2/+files/"${N}_$V".orig.tar.bz2"

RDEPEND="atk cairo expat fontconfig freetype gcc glib2 glibc gtk+ libdrm libpng libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender pango pixman zlib"
BDEPEND="                         "
RECOMMENDED="plymouth-theme-ylmf-logo"

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	#ypkg_patch debian-changes.patch
	ypkg_docp "$FILES_PATH"/files/ubuntu-logo/*.png themes/ubuntu-logo
	patches=" ubuntu_details.patch
		  details_removeSeparator.patch
		  misc-changes.patch
		  vga16fb-renderer.patch
		  lbm-nouveau.patch
		  nouveau-framebuffer.patch
		  ubuntu-logo.patch
		  ubuntu-text.patch
		  kubuntu-text.patch
		  gcc45-arith-workaround.patch
		  debug-fixes.patch
		  avoid-sigpipe.patch
		  upstream-event-loop-reference.patch
		  upstream-event-loop-number.patch
	  	  upstream-terminal-force-newline.patch
		  upstream-terminal-OPOST.patch
		  upstream-terminal-no-ISTRIP.patch
		  autoreconf.patch "
	ypkg_patch $patches
	YPB_CONFIG+="--libdir=/lib 
		     --enable-gdm-transition
		     --datarootdir=/lib"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README
	#for initramfs-tools
	cd "$YPPATH_DEST" 
	ypkg_docp   "$FILES_PATH"/files/initramfs-tools 	    usr/share/
	ypkg_docp   "$FILES_PATH"/files/ylmfos-logo.png        lib/plymouth
	#
	#install -d -m755 etc/rc3.d
	#ln -sf /etc/init.d/"$N"  etc/rc3.d/K02"$N"
	#ln -sf /etc/init.d/"$N"  etc/rc3.d/S01"$N"
	ypkg_doinit "$FILES_PATH"/files/plymouth
	#ypkg_dounit  "$N"-start.service "$N"-halt.service
	#ypkg_dounit  "$N"-halt.service
	ypkg_docp "$FILES_PATH"/files/systemd/*  lib/systemd/system/
	#ypkg_doln   ../"$N"-start.service lib/systemd/system/basic.target.wants/"$N"-start.service
	ypkg_doln   ../"$N"-halt.service  lib/systemd/system/shutdown.target.wants/"$N"-halt.service
	rm -rf lib/plymouth/plymouthd.defaults lib/plymouth/themes/ubuntu-text \
	       lib/plymouth/themes/ubuntu-logo lib/plymouth/themes/kubuntu-text lib/plymouth/ubuntu-text.so
	ypkg_doln /lib/plymouth/themes/text/text.plymouth  lib/plymouth/themes/text.plymouth
}
