#
# Ylmf OS package build script
#

DESCRIPTION="graphical boot animation and logger"
HOMEPAGE="http://cgit.freedesktop.org/plymouth/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="https://launchpad.net/ubuntu/lucid/+source/"$N"/"$V"-2ubuntu2/+files/"${N}_$V".orig.tar.bz2"

RDEPEND="atk cairo expat fontconfig freetype gcc-lib gdk-pixbuf glib2 glibc gtk+ libdrm libpciaccess libpng libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender pango pixman zlib"
BDEPEND=""
RECOMMENDED="plymouth-theme-ylmf-logo"

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	# dopatch debian-changes.patch
	docp "$filesdir"/ubuntu-logo/*.png themes/ubuntu-logo
	patches=" ubuntu_details.patch
		  details_removeSeparator.patch
		  misc-changes.patch
		  vga16fb-renderer.patch
		  lbm-nouveau.patch
		  nouveau-framebuffer.patch
		  ubuntu-logo.patch
		  ubuntu-text.patch
		  kubuntu-text.patch
		  gcc45-arith-workaround.patch
		  debug-fixes.patch
		  avoid-sigpipe.patch
		  upstream-event-loop-reference.patch
		  upstream-event-loop-number.patch
	  	  upstream-terminal-force-newline.patch
		  upstream-terminal-OPOST.patch
		  upstream-terminal-no-ISTRIP.patch
		  autoreconf.patch 
		  ylmfos_default-theme.patch
		  ylmfos_plymouth-0.8.2.patch"
	dopatch $patches

	config+="--libdir=/lib 
		 --enable-gdm-transition
		 --datarootdir=/lib"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	
	# For initramfs-tools
	cd "$destdir" 
	docp "$filesdir"/initramfs-tools usr/share/
	
	#
	rm -rf lib/plymouth/plymouthd.defaults  \
	       lib/plymouth/themes/ubuntu-text  \
	       lib/plymouth/themes/ubuntu-logo  \
	       lib/plymouth/themes/kubuntu-text \
	       lib/plymouth/ubuntu-text.so
	doln /lib/plymouth/themes/text/text.plymouth  lib/plymouth/themes/text.plymouth
}

