#
# YLmf_OS package build script
#

DESCRIPTION="graphical boot animation and logger"
HOMEPAGE="http://cgit.freedesktop.org/plymouth/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="https://launchpad.net/ubuntu/lucid/+source/"$N"/0.8.2-2ubuntu2/+files/"${N}_$V$R".orig.tar.bz2"

RDEPEND="atk cairo expat fontconfig freetype gcc glib2 gdk-pixbuf glibc gtk+ libdrm libpng libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender pango pixman zlib"
BDEPEND="                         "
RECOMMENDED="plymouth-theme-ylmf-logo"

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	dopatch debian-changes.patch
	docp $filesdir/ubuntu_logo/*.png themes/ubuntu-logo
	config+="--libdir=/lib 
	             --enable-libkms
		     --enable-gdm-transition
		     --datarootdir=/lib"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README
	#for initramfs-tools
	cd "$destdir" 
	docp_rename $filesdir/hook_plymouth	    usr/share/initramfs-tools/hooks/plymouth
	docp_rename $filesdir/init-top_plymouth      usr/share/initramfs-tools/scripts/init-top/plymouth
	docp_rename $filesdir/init-bottom_plymouth   usr/share/initramfs-tools/scripts/init-bottom/plymouth
	docp_rename $filesdir/panic_plymouth         usr/share/initramfs-tools/scripts/panic/plymouth
	docp        $filesdir/ylmfos-logo.png        lib/plymouth
	#
	#install -d -m755 etc/rc3.d
	#ln -sf /etc/init.d/"$N"  etc/rc3.d/K02"$N"
	#ln -sf /etc/init.d/"$N"  etc/rc3.d/S01"$N"
	doinit $filesdir/plymouth
	#dounit  "$N"-start.service "$N"-halt.service
	#dounit  "$N"-halt.service
	docp $filesdir/systemd/*  lib/systemd/system/
	#doln   ../"$N"-start.service lib/systemd/system/basic.target.wants/"$N"-start.service
	doln   ../"$N"-halt.service  lib/systemd/system/shutdown.target.wants/"$N"-halt.service
	rm  lib/plymouth/plymouthd.defaults
}
