#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A tool for generating C-based recognizers from regular expressions."
HOMEPAGE="http://re2c.sourceforge.net/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://downloads.sourceforge.net/"$N"/"$N-$V".tar.gz"
CHECKSUM="4a97d8f77ed6d2c76c8bd840a43f5633"

RDEPEND="gcc-lib glibc"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

