#
# Ylmf OS package build script
#

DESCRIPTION="Change or delete the rpath or runpath in ELF files"
HOMEPAGE="http://directory.fsf.org/project/chrpath/"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.tux.org/pub/X-Windows/ftp.hungry.com/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}


