#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A small library for rendering Postscript documents"
HOMEPAGE="http://www.freedesktop.org/wiki/Software/libspectre"
LICENSE="GPLv2"
PACKAGER="chenqixing@ivali.com
          Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://libspectre.freedesktop.org/releases/"$N-$V".tar.gz"
CHECKSUM="a7efd97b82b84ff1bb7a0d88c7e35ad10cc84ea8"

RDEPEND="ghostscript(>=9.00)"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--disable-static"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

