#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Small library for rendering Postscript documents"
HOMEPAGE="http://libspectre.freedesktop.org/wiki/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://libspectre.freedesktop.org/releases/"$N-$V".tar.gz"
CHECKSUM="819475c7e34a1e9bc2e876110fee530b42aecabd"

RDEPEND="avahi cups dbus e2fsprogs expat fontconfig freetype gcc-lib ghostscript glibc gnutls jasper keyutils krb5 libgcrypt libgpg-error libidn libjpeg-turbo libpng libtasn1 libtiff zlib"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

