#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Small library for rendering Postscript documents"
HOMEPAGE="http://libspectre.freedesktop.org/wiki/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://libspectre.freedesktop.org/releases/"$N-$V".tar.gz"
CHECKSUM="819475c7e34a1e9bc2e876110fee530b42aecabd"

RDEPEND="ghostscript"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

