#
# YLmf_OS package build script
#

DESCRIPTION="GNOME GUI Builder"
HOMEPAGE="http://glade.gnome.org/"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/glade3/3.6/"$N"3-"$V$R".tar.bz2"

RDEPEND="gtk+"
BDEPEND="${RDEPEND} "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

pbs_postinst() {
	gnome2_rarian_sk_update
	gnome2_desktop_database_update
	gnome2_icon_cache_update
	gnome2_gconfd_reload
}
