#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="User interface builder for GTK+ and GNOME."
HOMEPAGE="http://glade.gnome.org/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/$N/${V%.*}/$N-$V.tar.xz"
CHECKSUM="d2e6b5a20cfdbc0a5ed49122ac7b4e3a10ba140ccfcaba60082e6e2b52a62ac6"

RDEPEND="gtk3 libxml2 desktop-file-utils"
BDEPEND="intltool python gtk-doc gobject-introspection itstool docbook-xsl"
RECOMMENDED=""
CONFLICT=""
OPTIONAL="python: Python widgets support
          devhelp: help browser"

INSTALL="$N.install"

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--disable-static"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

