#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GNOME GUI Builder"
HOMEPAGE="http://glade.gnome.org/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/glade3/3.6/"$N"3-"$V".tar.bz2"

RDEPEND="libgnomeui python"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

