#
# YLmf_OS package build script
#

DESCRIPTION="The libunique package contains a library for writing single instance applications."
HOMEPAGE="http://live.gnome.org/LibUnique"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/"$N"/1.1/"$N-$V".tar.bz2"

RDEPEND="atk cairo dbus dbus-glib expat fontconfig freetype gcc gdk-pixbuf glib2 glibc gtk+ libpng libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender pango pixman zlib"
BDEPEND="" 
RECOMMENDED="" 

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--enable-introspection=no 
	             --enable-silent-rules"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	cd "$destdir"/usr/include
	ln -sf  /usr/include/unique-1.0/unique unique
}

