#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python bindings for the Enchant spellchecking system"
HOMEPAGE="http://pyenchant.sourceforge.net http://pypi.python.org/pypi/pyenchant"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://pypi.python.org/packages/source/p/"$N"/"$N-$V".tar.gz"
CHECKSUM="565014a14a52fb0195d152dd492ea948"

RDEPEND="python(>=2.7.2) distribute"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

