#!/bin/bash
#
# This task unloads the kernel modules specified in the /etc/module-unload.d/*.conf file.
#

ls -1d /etc/modules-unload /etc/modules-unload.d/*.conf 2>/dev/null |while read line; do
	grep '^[^#]' $line |while read module; do
		[ "$module" ] || continue
  		rmmod $module || :
	done
done

exit 0

