#
# YLmf_OS package build script
#

DESCRIPTION="IPC library used by GnuPG and GPGME"
HOMEPAGE="http://www.gnupg.org/related_software/libassuan.en.html"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="ftp://ftp.gnupg.org/gcrypt/"$N"/"$N-$V$R".tar.bz2"

RDEPEND="glibc libgpg-error"
BDEPEND=" "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README
}

pbs_postinst() {
	[ -x /usr/bin/install-info ] || return 0
	infodir=/usr/share/info
	install-info $infodir/assuan.info.gz $infodir/dir 2>/dev/null
}

pbs_postrm() {
	[ -x /usr/bin/install-info ] || return 0
	infodir=/usr/share/info
	install-info --delete $infodir/assuan.info.gz $infodir/dir 2>/dev/null
}
