#
# YLmf_OS package build script
#

DESCRIPTION="wav2mp3 wav2ogg utils"
HOMEPAGE="http://wav2mp3.sourceforge.net/"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://downloads.sourceforge.net/project/wav2mp3/wav2mp3_wav2ogg/"$V"/WAV2-"$V".tar.gz"

RDEPEND="file-which vorbis-tools"
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

