#
# YLmf_OS package build script
#

DESCRIPTION="wav2mp3 wav2ogg utils"
HOMEPAGE="http://wav2mp3.sourceforge.net/"
REPO=""
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://downloads.sourceforge.net/project/wav2mp3/wav2mp3_wav2ogg/"$V"/WAV2-"$V$R".tar.gz"

RDEPEND="file-which vorbis-tools"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
