#!/bin/bash
#
#

# make 
# modinfo ./os/linux/rt3572sta.ko

echo "module rt3572sta.ko"
echo "description RT2870 Wireless Lan Linux Driver"
echo "alias usb:v0930p0A07d*dc*dsc*dp*ic*isc*ip*
alias usb:v167Bp4001d*dc*dsc*dp*ic*isc*ip*
alias usb:v5A57p0284d*dc*dsc*dp*ic*isc*ip*
alias usb:v1690p0744d*dc*dsc*dp*ic*isc*ip*
alias usb:v1690p0740d*dc*dsc*dp*ic*isc*ip*
alias usb:v04BBp0944d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DF6p0042d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DF6p0041d*dc*dsc*dp*ic*isc*ip*
alias usb:v1740p9801d*dc*dsc*dp*ic*isc*ip*
alias usb:v148Fp3572d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DB0p6899d*dc*dsc*dp*ic*isc*ip*
alias usb:v100Dp9031d*dc*dsc*dp*ic*isc*ip*
alias usb:v050Dp815Cd*dc*dsc*dp*ic*isc*ip*
alias usb:v0411p00E8d*dc*dsc*dp*ic*isc*ip*
alias usb:v1737p0071d*dc*dsc*dp*ic*isc*ip*
alias usb:v1737p0070d*dc*dsc*dp*ic*isc*ip*
alias usb:v7392p7717d*dc*dsc*dp*ic*isc*ip*
alias usb:v7392p7718d*dc*dsc*dp*ic*isc*ip*
alias usb:v5A57p0282d*dc*dsc*dp*ic*isc*ip*
alias usb:v5A57p0280d*dc*dsc*dp*ic*isc*ip*
alias usb:v1690p0740d*dc*dsc*dp*ic*isc*ip*
alias usb:v04E8p2018d*dc*dsc*dp*ic*isc*ip*
alias usb:v14B2p3C09d*dc*dsc*dp*ic*isc*ip*
alias usb:v1482p3C09d*dc*dsc*dp*ic*isc*ip*
alias usb:v050Dp815Cd*dc*dsc*dp*ic*isc*ip*
alias usb:v050Dp805Cd*dc*dsc*dp*ic*isc*ip*
alias usb:v157Ep300Ed*dc*dsc*dp*ic*isc*ip*
alias usb:v129Bp1828d*dc*dsc*dp*ic*isc*ip*
alias usb:v0E66p0003d*dc*dsc*dp*ic*isc*ip*
alias usb:v0E66p0001d*dc*dsc*dp*ic*isc*ip*
alias usb:v15C5p0008d*dc*dsc*dp*ic*isc*ip*
alias usb:v083Ap6618d*dc*dsc*dp*ic*isc*ip*
alias usb:v13D3p3247d*dc*dsc*dp*ic*isc*ip*
alias usb:v14B2p3C25d*dc*dsc*dp*ic*isc*ip*
alias usb:v0471p200Fd*dc*dsc*dp*ic*isc*ip*
alias usb:v1740p9702d*dc*dsc*dp*ic*isc*ip*
alias usb:v1740p9701d*dc*dsc*dp*ic*isc*ip*
alias usb:v0CDEp0025d*dc*dsc*dp*ic*isc*ip*
alias usb:v0586p3416d*dc*dsc*dp*ic*isc*ip*
alias usb:v0CDEp0022d*dc*dsc*dp*ic*isc*ip*
alias usb:v083Ap7522d*dc*dsc*dp*ic*isc*ip*
alias usb:v083Ap8522d*dc*dsc*dp*ic*isc*ip*
alias usb:v083ApA618d*dc*dsc*dp*ic*isc*ip*
alias usb:v083ApB522d*dc*dsc*dp*ic*isc*ip*
alias usb:v15A9p0006d*dc*dsc*dp*ic*isc*ip*
alias usb:v1044p800Bd*dc*dsc*dp*ic*isc*ip*
alias usb:v07AAp003Fd*dc*dsc*dp*ic*isc*ip*
alias usb:v07AAp003Cd*dc*dsc*dp*ic*isc*ip*
alias usb:v07AAp002Fd*dc*dsc*dp*ic*isc*ip*
alias usb:v14B2p3C27d*dc*dsc*dp*ic*isc*ip*
alias usb:v14B2p3C23d*dc*dsc*dp*ic*isc*ip*
alias usb:v050Dp8053d*dc*dsc*dp*ic*isc*ip*
alias usb:v14B2p3C07d*dc*dsc*dp*ic*isc*ip*
alias usb:v07D1p3C11d*dc*dsc*dp*ic*isc*ip*
alias usb:v07D1p3C09d*dc*dsc*dp*ic*isc*ip*
alias usb:v2019pED06d*dc*dsc*dp*ic*isc*ip*
alias usb:v14B2p3C28d*dc*dsc*dp*ic*isc*ip*
alias usb:v14B2p3C06d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DF6p002Dd*dc*dsc*dp*ic*isc*ip*
alias usb:v0DF6p002Cd*dc*dsc*dp*ic*isc*ip*
alias usb:v0DF6p002Bd*dc*dsc*dp*ic*isc*ip*
alias usb:v0DF6p0017d*dc*dsc*dp*ic*isc*ip*
alias usb:v0B05p1742d*dc*dsc*dp*ic*isc*ip*
alias usb:v0B05p1732d*dc*dsc*dp*ic*isc*ip*
alias usb:v0B05p1731d*dc*dsc*dp*ic*isc*ip*
alias usb:v177Fp0302d*dc*dsc*dp*ic*isc*ip*
alias usb:v0789p0164d*dc*dsc*dp*ic*isc*ip*
alias usb:v0789p0163d*dc*dsc*dp*ic*isc*ip*
alias usb:v0789p0162d*dc*dsc*dp*ic*isc*ip*
alias usb:v083Ap7512d*dc*dsc*dp*ic*isc*ip*
alias usb:v0DF6p003Fd*dc*dsc*dp*ic*isc*ip*
alias usb:v0DF6p0039d*dc*dsc*dp*ic*isc*ip*
alias usb:v07B8p2770d*dc*dsc*dp*ic*isc*ip*
alias usb:v07B8p2870d*dc*dsc*dp*ic*isc*ip*
alias usb:v148Fp2870d*dc*dsc*dp*ic*isc*ip*
alias usb:v148Fp2770d*dc*dsc*dp*ic*isc*ip*"
