#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The cross platform Python binding to OpenGL and related APIs"
HOMEPAGE="http://pyopengl.sourceforge.net"
LICENSE="BSD"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"
YARCH="any"

SRC_URI="http://pypi.python.org/packages/source/P/PyOpenGL/PyOpenGL-$V.tar.gz"
CHECKSUM=""

RDEPEND="freeglut py-distribute"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
