#
# Ylmf OS package build script
#

DESCRIPTION="X.Org Xdamage library"
HOMEPAGE="http://www.x.org/wiki/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://xorg.freedesktop.org/archive/individual/lib/"$N-$V".tar.bz2"
CHECKSUM="44774e1a065158b52f1a0da5100cebec"

RDEPEND="glibc libX11 libXau libxcb libXdmcp libXfixes"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

