#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Utility for network discovery and security auditing"
HOMEPAGE="http://nmap.org"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://nmap.org/dist/$N-$V.tar.bz2"
CHECKSUM="769943a1a5c10f67bf9738e26da42b3312db752f"

RDEPEND="pcre openssl libpcre lua"
RECOMMENDED=""
BDEPEND="pygtk"
OPTIONAL="pygtk: zenmap" 
CONFLICT=""
REPLACE=""

pbs_unpack() {
    dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
    dodoc COPYING
    rm "$destdir"/usr/bin/uninstall_zenmap
}
