#! /bin/sh
# Updates the immodules in /etc/gtk-2.0/$host

umask 022

FILE=/etc/gtk-3.0/gtk.immodules

if [ -x /usr/bin/gtk-query-immodules-3.0 ]; then
     /usr/bin/gtk-query-immodules-3.0 > $FILE
fi

