#
# Ylmf OS package build script
#

DESCRIPTION="Perl wrappers for the GConf configuration engine. "
HOMEPAGE="http://search.cpan.org/~tsch/Gnome2-GConf-1.044/GConf.pm"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
LICENSE="GPL PerlArtistic"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/Gnome2-GConf-"$V".tar.gz"

RDEPEND="perl pango-perl gtk+"
BDEPEND="extutils-depends extutils-pkgconfig"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

