#
# YLmf_OS package build script
#

DESCRIPTION="Crypt::SSLeay module for perl"
HOMEPAGE="http://search.cpan.org/dist/Crypt-SSLeay/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://mirrors.163.com/cpan/authors/id/N/NA/NANIS/Crypt-SSLeay-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	perl Makefile.PL --default
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}
