#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Crypt::SSLeay module for perl"
HOMEPAGE="http://search.cpan.org/dist/Crypt-SSLeay/"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
LICENSE="GPL PerlArtistic"

SRC_URI="http://mirrors.163.com/cpan/authors/id/N/NA/NANIS/Crypt-SSLeay-"$V".tar.gz"

RDEPEND="perl openssl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

