#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Crypt::SSLeay module for perl"
HOMEPAGE="http://search.cpan.org/dist/$N"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="GPL,PerlArtistic"

SRC_URI="http://www.cpan.org/CPAN/authors/id/N/NA/NANIS/"$N-$V".tar.gz"
CHECKSUM="4812f14d6e8c71714a26c0ad733666dc"

RDEPEND="LWP-Protocol-https Try-Tiny"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}

