#
# YLmf_OS package build script
#

DESCRIPTION="Tools necessary to build programs"
HOMEPAGE="http://www.gnu.org/software/binutils/"
 
SRC_URI="http://ftp.gnu.org/gnu/"$N"/"$N-$V$R".tar.bz2"

RDEPEND="glibc zlib"
BDEPEND=" gcc-dev "

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	make tooldir=/usr
}

pbs_install() {
	domkinstall tooldir=/usr
	docp include/libiberty.h "$destdir"/usr/include
}
