#
# YLmf_OS package build script
#

DESCRIPTION="X.Org Xaw library"
HOMEPAGE="http://www.x.org/wiki/"
 
SRC_URI="http://www.x.org/releases/X11R7.6/src/lib/"$N-$V$R".tar.bz2"

RDEPEND="glibc libICE libSM libX11 libXau libxcb libXdmcp libXext libXmu libXpm libXt util-linux-ng"
BDEPEND="           util-linux-ng.-dev"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
