#
# YLmf_OS package build script
#

DESCRIPTION="X C-language Bindings library"
HOMEPAGE="http://xcb.freedesktop.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.x.org/releases/X11R7.6/src/xcb/"$N-$V".tar.bz2"

RDEPEND="glibc libXau libXdmcp"
BDEPEND="xcb-proto libpthread-stubs"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

