#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python bindings for libsmbclient"
HOMEPAGE="http://pypi.python.org/pypi/pysmbc/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://pypi.python.org/packages/source/p/"$N"/"$N-$V".tar.bz2"
CHECKSUM="019dbb3bc6ee217f7389a2330cda9fe0"

RDEPEND="python samba"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

