#
# YLmf_OS package build script
#

DESCRIPTION="GtkSharp's gtk module of the gtk-sharp-beans tarball"
HOMEPAGE="http://www.mono-project.com/GtkSharp"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="git://github.com/mono/gtk-sharp-beans.git"

RDEPEND="gio-sharp"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	make
}

pbs_install() {
	domkinstall
}

