#
# YLmf_OS package build script
#

DESCRIPTION="GtkSharp's gtk module of the gtk-sharp-beans tarball"
HOMEPAGE="http://www.mono-project.com/GtkSharp"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://github.com/mono/gtk-sharp-beans.git"

RDEPEND=""
BDEPEND="gio-sharp"
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	make
}

pbs_install() {
	domkinstall
}
