#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GtkSharp's gtk module of the gtk-sharp-beans tarball"
HOMEPAGE="http://www.mono-project.com/GtkSharp"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
YARCH="any"

SRC_URI="git://github.com/mono/gtk-sharp-beans.git"

RDEPEND="gio-sharp"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	make
}

pbs_install() {
	domkinstall
}

