#
# Ylmf OS package build script
#

DESCRIPTION="Ogg bitstream and framing library"
HOMEPAGE="http://www.annodex.net/software/liboggz"
LICENSE="BSD"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://downloads.xiph.org/releases/ogg/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

