#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Statistics generator for git"
HOMEPAGE="http://gitstats.sourceforge.net/"
LICENSE="GPL"
YARCH="any"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="git://repo.or.cz/gitstats.git"

RDEPEND="python"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	dopatch ylmfos-makefile.patch
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}


