#!/bin/bash
#
#./configure --prefix=/usr
#make 
#modinfo

echo "package alsa-driver-module"

echo "
module snd-seq-oss.ko
description    OSS-compatible sequencer module
alias          sound-service-?-8
alias          sound-service-?-1

module snd-hda-codec-ca0132.ko
description    Creative CA0132, CA0132 HD-audio codec
alias          snd-hda-codec-id:11020011

module snd-pdplus.ko
description    SekD/Marian Prodif Plus
alias          pci:v00001382d00002048sv*sd*bc*sc*i*
"
