#
# YLmf_OS package build script
#

DESCRIPTION="GNU regular expression matcher"
HOMEPAGE="http://www.gnu.org/software/grep/"
 
SRC_URI="ftp://ftp.gnu.org/gnu/"$N"/"$N-$V$R".tar.gz"

RDEPEND="glibc libpcre"
BDEPEND=" "
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--bindir=/bin"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

