
fontfile="/usr/share/fonts/wenquanyi/wqy-microhei/wqy-microhei.ttc"
fallbackdir="/opt/java/jre/lib/fonts/fallback"

post_install() {
    echo "The jre package is licensed software."
    echo "You MUST read and agree to the license stored in"
    echo "/opt/java/jre/LICENSE before using it."
    
    if [ -f /etc/mailcap ] ; then
        sed -e '/application\/x-java-jnlp-file/d' -i /etc/mailcap
        echo 'application/x-java-jnlp-file;/opt/java/jre/bin/javaws %s' >>/etc/mailcap
    fi

    # For messy-code zh_CN
    mkdir -p "$fallbackdir"
    cd "$fallbackdir"

    if [ -f "$fontfile" ]; then
        ln -sf "$fontfile" 
        mkfontdir
        mkfontscale
    fi

    return 0
}       

post_remove() {
    mailcap=$(grep -v 'application/x-java-jnlp-file' /etc/mailcap)

    if [ "$mailcap" != "" ] ; then
        sed -e '/application\/x-java-jnlp-file/d' -i /etc/mailcap
    else
        rm /etc/mailcap
    fi
    
    rm -rf "$fallbackdir" ||true
}

post_upgrade() {
    post_install
}

post_downgrade() {
    post_install
}

