#
# YLmf_OS package build script
#

DESCRIPTION="Firmware for the Intel PRO/Wireless 2100 3B miniPCI adapter"
HOMEPAGE="http://ipw2100.sourceforge.net/"
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://bughost.org/firmware/ipw2100-fw-1.3.tgz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_install() {
	ypkg_docp ../*.fw "$YPPATH_DEST"/lib/firmware/
	ypkg_dodoc LICENSE
}

