#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="eio office suit"
HOMEPAGE="http://www.yozosoft.com/indexch.jsp"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://packages.linuxdeepin.com/pool/main/e/eio/eio_6.0.1011.101ZH-1deepin3.tar.gz"

RDEPEND="alsa-lib glibc libX11 libXau libxcb libXdmcp libXext libXi libXtst libXp"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

DESKTOPFILE="eio.desktop"
ICONFILE="/usr/share/eiofileicon/eioicon.png"

pbs_unpack() {
        dounpack
}

pbs_install() {
	docp usr etc "$destdir"
	cd "$destdir"
	chmod -R 755 usr/local/Evermore/EIOffice
	chmod -R 777 usr/local/Evermore/EIOffice/Config
	chmod -R 777 usr/local/Evermore/EIOffice/System
	# Register our X Desktop Group Shared MIME-info Database info
	doln /usr/share/eiofileicon/eio.ico       usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-x-eio.png 
	doln /usr/share/eiofileicon/eit.ico       usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-x-eit.png
	doln /usr/share/eiofileicon/eiw.ico       usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-x-eiw.png
	doln /usr/share/eiofileicon/ees.ico       usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-x-ees.png
	doln /usr/share/eiofileicon/ese.ico       usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-x-ese.png
	doln /usr/share/eiofileicon/uof.ico       usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-x-uof.png
	doln /usr/share/eiofileicon/msdocicon.ico usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-msword.png
	doln /usr/share/eiofileicon/msxlsicon.ico usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.ms-excel.png
	doln /usr/share/eiofileicon/msppticon.ico usr/share/icons/gnome/48x48/mimetypes/gnome-mime-application-vnd.ms-powerpoint.png
}

