#
# YLmf_OS package build script
#

DESCRIPTION="Perl interface to the 2.x series of the Gimp Toolkit library"
HOMEPAGE="http://search.cpan.org/~flora/Gtk2-1.223/Gtk2.pm"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YVERSION="1"

SRC_URI="http://search.cpan.org/CPAN/authors/id/F/FL/FLORA/Gtk2-"$V".tar.gz"

RDEPEND="pango-perl"
BDEPEND="extutils-depends extutils-pkgconfig"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

