#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl interface to the 2.x series of the Gimp Toolkit library"
HOMEPAGE="http://search.cpan.org/~flora/Gtk2-1.223/Gtk2.pm"
LICENSE="GPL"
PRIORITY=""
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/F/FL/FLORA/Gtk2-"$V$R".tar.gz"

RDEPEND="pango-perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
        perl_cleanup
}
