#
# YLmf_OS package build script
#

DESCRIPTION="Perl interface to the 2.x series of the Gimp Toolkit library"
HOMEPAGE="http://search.cpan.org/~flora/Gtk2-1.223/Gtk2.pm"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/F/FL/FLORA/Gtk2-"$V$R".tar.gz"

RDEPEND="pango-perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
