#
# YLmf_OS package build script
#

DESCRIPTION="Compiz Option code Generator"
HOMEPAGE="http://www.compiz.org/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://releases.compiz-fusion.org/0.8.4/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" libxslt"
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README
}
