#
# Ylmf OS package build script
#

DESCRIPTION="Compiz Option code Generator"
HOMEPAGE="http://www.compiz.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://releases.compiz.org/"$V"/"$N-$V".tar.bz2"

RDEPEND="libxslt compiz"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README
}

