#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="a fast C/C++ compiler cache"
HOMEPAGE="http://ccache.samba.org/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://samba.org/ftp/"$N"/"$N-$V".tar.bz2"
CHECKSUM="0e0f25fb342dcb1196d9c2986a7323cf"

RDEPEND="zlib"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	cd "$destdir"
	for i in cc gcc g++ cpp c++; do
		doln /usr/bin/ccache usr/lib/ccache/bin/"${i}" 
	done	
}

