#
# Ylmf OS package build script
#

DESCRIPTION="a fast C/C++ compiler cache"
HOMEPAGE="http://ccache.samba.org/"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://samba.org/ftp/"$N"/"$N-$V$R".tar.bz2"

RDEPEND="glibc zlib"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES="To use the symlinks method, do something like this:
ln -s ccache /usr/bin/gcc-lib
ln -s ccache /usr/bin/g++
ln -s ccache /usr/bin/cc
ln -s ccache /usr/bin/c++"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
