#
# YLmf_OS package build script
#

DESCRIPTION="a fast C/C++ compiler cache"
HOMEPAGE="http://ccache.samba.org/"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://samba.org/ftp/"$N"/"$N-$V$R".tar.bz2"

RDEPEND="glibc zlib"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES="To use the symlinks method, do something like this:
ln -s ccache /usr/bin/gcc
ln -s ccache /usr/bin/g++
ln -s ccache /usr/bin/cc
ln -s ccache /usr/bin/c++"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
