#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="a fast C/C++ compiler cache"
HOMEPAGE="http://ccache.samba.org/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://samba.org/ftp/"$N"/"$N-$V".tar.xz"
CHECKSUM="80a698c22d0b06b19c88ac58e8d8b632"

RDEPEND="glibc zlib"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES="To use the symlinks method, do something like this:
ln -s ccache /usr/bin/gcc-lib
ln -s ccache /usr/bin/g++
ln -s ccache /usr/bin/cc
ln -s ccache /usr/bin/c++"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	cd "$destdir"
	
	for i in cc gcc g++ cpp c++; do
		doln /usr/bin/ccache usr/lib/ccache/bin/"${i}" 
	done	
}


