. /usr/lib/ybs/funcs

files="/etc/mateconf/schemas/system_smb.schemas
       /etc/mateconf/schemas/system_http_proxy.schemas
       /etc/mateconf/schemas/system_dns_sd.schemas
       /etc/mateconf/schemas/desktop_mate_url_handlers.schemas
       /etc/mateconf/schemas/desktop_default_applications.schemas"

post_install() {
	mate_install_schema $files
}

pre_remove() {
	mate_uninstall_schema $files
}

post_upgrade() {
	post_install
}

post_downgrade() {
	post_install
}

