. /usr/lib/ybs/funcs

files="/etc/gconf/schemas/empathy.schemas"

post_install() {
	gnome2_install_schema $files
	gnome2_install_defaut_gconf "bool" "/apps/empathy/notifications/notifications_focus" "True"
	gnome2_install_defaut_gconf "bool" "/apps/empathy/ui/show_offline" "True"
	gnome2_desktop_database_update
	gnome2_icon_cache_update
}

pre_remove() {
        gnome2_uninstall_schema $files
}

post_upgrade() {
	post_install
}

