#
# Ylmf OS package build script
#

DESCRIPTION="A library to raise flags on DBus for other components of the desktop to pick up and visualize"
HOMEPAGE="http://launchpad.net/libindicate"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="https://launchpad.net/libindicate/0.4/0.4.4/+download/libindicate-0.4.4.tar.gz"
CHECKSUM="6d42a710ddd5466263d244e05a273c45"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}



