#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl-compatible regular expression library"
HOMEPAGE="http://www.pcre.org/"
LICENSE="BSD"
PACKAGER="StartOS Develpers"

SRC_URI="ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-"$V".tar.bz2"
CHECKSUM="1c9a276af932b5599157f96e945391f0"

RDEPEND="bzip2 gcc-lib zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=" --enable-pcre16 --enable-jit --enable-utf8 --enable-unicode-properties"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc LICENCE
}

