#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl-compatible regular expression library"
HOMEPAGE="http://www.pcre.org/"
LICENSE="GPLv2"
PACKAGER="StartOS Develpers"

SRC_URI="ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-"$V".tar.bz2"

RDEPEND="bzip2 gcc-lib glibc zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=" --enable-utf8 
		      --enable-unicode-properties
		      --enable-pcregrep-libz
		      --enable-pcregrep-libbz2 "
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

