#
# YLmf_OS package build script
#

DESCRIPTION="Perl-compatible regular expression library"
HOMEPAGE="http://www.pcre.org/"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Develpers <ylmfos@115.com>"

SRC_URI="ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-"$V".tar.bz2"

RDEPEND="bzip2 gcc glibc zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=" --enable-utf8 
		      --enable-unicode-properties
		      --enable-pcregrep-libz
		      --enable-pcregrep-libbz2 "
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

