#
# Ylmf OS package build script
#

DESCRIPTION="Raptor RDF parser and serializer utilities"
HOMEPAGE="http://librdf.org/raptor/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://download.librdf.org/source/"$N-$V$R".tar.gz"

RDEPEND="curl cyrus-sasl glibc libxml2 libxslt openldap openssl zlib"
BDEPEND="       "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
