#
# YLmf_OS package build script
#

DESCRIPTION="Raptor RDF parser and serializer utilities"
HOMEPAGE="http://librdf.org/raptor/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://download.librdf.org/source/"$N-$V$R".tar.gz"

RDEPEND="curl cyrus-sasl glibc libxml2 libxslt openldap-client openssl zlib"
BDEPEND="curl-dev cyrus-sasl-dev glibc-dev libxml2-dev libxslt-dev openldap-client-dev openssl-dev zlib-dev"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
