#
# YLmf_OS package build script
#

DESCRIPTION="Advanced Linux Sound Architecture Library"
HOMEPAGE=" http://www.alsa-project.org/"
 
SRC_URI="ftp://ftp.alsa-project.org/pub/utils/"$N-$V".tar.bz2"

RDEPEND="alsa-lib glibc libsamplerate ncurses"
BDEPEND="alsa-lib-dev glibc-dev libsamplerate-dev ncurses-dev"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-xmlto"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
