#
# YLmf_OS package build script
#

DESCRIPTION="GNU locale utilities"
HOMEPAGE="http://www.gnu.org/software/gettext/gettext.html"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://ftp.gnu.org/pub/gnu/"$N"/"$N-$V$R".tar.gz"

RDEPEND="glibc ncurses"
BDEPEND="${RDEPEND}"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
