#
# YLmf_OS package build script
#

DESCRIPTION="GNU locale utilities"
HOMEPAGE="http://www.gnu.org/software/gettext/gettext.html"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
SRC_URI="http://ftp.gnu.org/pub/gnu/$N/"$N-$V$R".tar.gz"

RDEPEND="glibc ncurses"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	patch -p1 -i $filesdir/"$N-$V$R"-upstream_fixes-2.patch
	config+=" --prefix=/usr "
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
