#
# Ylmf OS package build script
#

DESCRIPTION="GNU locale utilities"
HOMEPAGE="http://www.gnu.org/software/gettext/gettext.html"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnu.org/pub/gnu/"$N"/"$N-$V".tar.gz"

RDEPEND="acl attr gcc-lib glib2 glibc libcroco libunistring libxml2 ncurses zlib"
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

