#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Boost Libraries for C++ - Runtime"
HOMEPAGE="http://www.boost.org/"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://sourceforge.net/projects/boost/files/boost/"$V"/boost_"${V//./_}".tar.bz2"
CHECKSUM="52dd00be775e689f55a987baebccc462"

RDEPEND="glibc gcc-libs icu bzip2 zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_build() {
    _stagedir="$SRCDIR"/stagedir

    cd "$SRCDIR"/tools
    echo "using python : 2.7 : /usr/bin/python ;" >> build/v2/user-config.jam
    #XXX
    #echo "using mpi ;" >> build/v2/user-config.jam

    # Step 1、Build bjam
    cd "$SRCDIR"/tools/build/v2/engine
    /bin/bash ./build.sh gcc || die "Step 1: build bjam failed."

    _bindir="bin.linuxx86"
    [ "$ARCH" = "x86_64" ] && _bindir="bin.linuxx86_64"
    install -d "$_stagedir"/usr/bin
    install "$_bindir"/bjam "$_stagedir"/usr/bin/bjam

    # Step 2、Build tools
    cd "$SRCDIR"/tools
    "$_stagedir"/usr/bin/bjam --toolset=gcc || die "Step 2, build tools failed."

    cd "$SRCDIR"/dist/bin
    for i in *;do
        install -m755 "$i" "$_stagedir"/usr/bin/"$i"
    done

    # Boostbook needed by quickbook
    cd "$SRCDIR"/dist
    cp -r share "$_stagedir"

    # Step 3、Build libs
    cd "$SRCDIR"

    # default "minimal" install: "release link=shared,static
    # runtime-link=shared threading=single,multi"
    # --layout=tagged will add the "-mt" suffix for multithreaded libraries
    # and installs includes in /usr/include/boost.
    # --layout=system no longer adds the -mt suffix for multi-threaded libs.
    # install to $_stagedir in preparation for split packaging

    "$_stagedir"/usr/bin/bjam \
        release debug-symbols=off threading=multi \
        runtime-link=shared link=shared,static \
        cflags=-fno-strict-aliasing \
        toolset=gcc \
        --prefix="$_stagedir"/usr \
        --libdir="$_stagedir"/usr/lib"${LIBDIRSUFFIX}" \
        --includedir="$_stagedir"/usr/include \
        -sTOOLS=gcc \
        --layout=system \
        "$MAKEOPTS" \
    install
}

pbs_install() {
    cd "$_stagedir"
    # Shared libs
    docp usr/lib"$LIBDIRSUFFIX"/*.so{,.*} "$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/
    # License
    dodoc "$SRCDIR"/LICENSE_1_0.txt
}
