#
# YLmf_OS package build script
#

DESCRIPTION="a cross platform Zero Configuration Networking library for Mono and .NET."
HOMEPAGE="http://www.mono-project.com/Mono.Zeroconf"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://download.banshee-project.org/"$N"/"$N-$V".tar.bz2"

RDEPEND="mono avahi"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES="build avahi with mono"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-docs --disable-mdnsresponder"
	doconfig
}

pbs_build() {
	make hicolordir=/usr/share/icons/hicolor
}

pbs_install() {
	domkinstall hicolordir=/usr/share/icons/hicolor GCONF_DISABLE_MAKEFILE_SCHEMA_INSTALL=1
}

