#!/bin/bash
#

device_id () {
	ids=$(grep PCI_VENDOR_ID_REALTEK, $1 |while read line;do line=${line#*,};echo ${line%)*};done)
	for id in $ids; do
		printf "alias pci:v%08Xd%08Xsv*sd*bc*sc*i* %s %s\n" 0x10EC "$id"
	done
	return 0
}

echo "package rtl8101-driver"
echo "module r8101.ko"
echo "description RealTek RTL-8101 Fast Ethernet driver"
device_id src/r8101_n.c

exit 0

