#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Qt wrapper for libindicate library"
HOMEPAGE="https://launchpad.net/libindicate-qt/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="https://launchpadlibrarian.net/40678788/"$N-$V".tar.bz2"
CHECKSUM=""

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
OPTIONAL="a: support a 
          b: support b"
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
    dounpack
}

pbs_patch() {
    dopatch
}

pbs_config() {
    #config+=" --prefix=/usr
    #          --sysconfdir=/etc
    #          --localstatedir=/var
    #             --infodir=/usr/share/info
    #          --mandir=/usr/share/man
    #              --disable-static
    #          --enable-shared "
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    #make DESTDIR="$PKGDIR" install
    domkinstall
    #doinit "$N"
    #dounit "N".service
    #dodesktop "*.desktop" "*.png"
    #dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README 
    #docp "$FILESDIR/XXXX" "dirname"
    #domv "$FILESDIR/XXXX" "dirname"
    #docp_rename "$1" "$2"
    #domv_rename "$1" "$2"
    #doln "$1 "$2"
    #doman a.1 b.2 c.3
    #*****************
    #when SRC_URI is deb or rpm package
    #docp data/*  "$PKGDIR"
}

#split package
foo_install () {
    :
}


