#
# Ylmf OS package build script
#

DESCRIPTION="ypk package builder based on ypkg"
HOMEPAGE="http://code.google.com/p/debbuilder-cn/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
YARCH="any"

REPO="testing"

SRC_URI="http://debbuilder-cn.googlecode.com/files/"$N-$V".tar.gz"
CHECKSUM="c3af4314f2b1227118d4890d0a1056fe6bb448ac"

RDEPEND="jre"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_install() {
	docp config-cn/* "$destdir"/etc/
	docp AppFiles/*  "$destdir"/opt/debbuildercn
	find "$destdir" -type f -name "*~" -exec rm {} \;
	dodesktop "$N.desktop" "$N.png"
}

