#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="ypk package builder based on ypkg"
HOMEPAGE="http://code.google.com/p/debbuilder-cn/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
YARCH="any"

REPO="testing"

SRC_URI="http://debbuilder-cn.googlecode.com/files/YpkBuilder"$V".tar.gz"
CHECKSUM="184b173aae2c9287020a1d98183d89fc98b5dbec"

RDEPEND="jdk jre"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_install() {
	docp config-cn/* "$destdir"/etc/
	docp AppFiles/*  "$destdir"/opt/debbuildercn
	docp "$filesdir"/"$N" "$destdir"/usr/bin/
	find "$destdir" -type f -name "*~" -exec rm {} \;
	dodesktop "$N.desktop" "IconFiles/debbuilderico.png"
}

