#
# YLmf_OS package build script
#

DESCRIPTION="A standards-compliant graphical Web browser"
HOMEPAGE="http://www.opera.com/"
REPO=""
LICENSE=""
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://get.opera.com/pub/opera/linux/1110/"$N"_"$V$R"_i386.deb"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

DESKTOPFILE="opera-browser.desktop"

INSTALL="$N.install"

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_install() {
	ypkg_docp data/*  "$YPPATH_DEST"/
}

