#!/bin/sh
cd "/opt/chromium.org/chrome-linux"
if [ -n "/opt/chromium.org/nss-nspr:/opt/chromium.org/chrome-linux" ] ; then
	if [ "${LD_LIBRARY_PATH+set}" = "set" ] ; then
		export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/chromium.org/nss-nspr:/opt/chromium.org/chrome-linux"
	else
		export LD_LIBRARY_PATH="/opt/chromium.org/nss-nspr:/opt/chromium.org/chrome-linux"
	fi
fi
exec ./chrome "$@"
