#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="StartOS Tutorials"
HOMEPAGE="http://www.startos.org"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="xdg-utils" 
BDEPEND=""

pbs_unpack() {
    dounpack
}

pbs_install() {
    dodesktop startos-tutorials.desktop startos-tutorials.svg
    docp www.startos.org "$PKGDIR"/usr/share/"$N"
}

