#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GTK+ Documentation Generator"
HOMEPAGE="http://www.gtk.org/gtk-doc/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/mobile/2.30/2.30.2/sources/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" docbook-xml docbook-xsl libxslt docbook"
CONFLICT="gtk-doc-dev"

OPTIONS="nodev"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-scrollkeeper --disable-static"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
