#
# Ylmf OS package build script
#

DESCRIPTION="GTK+ Documentation Generator"
HOMEPAGE="http://www.gtk.org/gtk-doc/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
YARCH="any"

SRC_URI="http://ftp.gnome.org/pub/gnome/mobile/2.32/2.32.1/sources/"$N-$V".tar.bz2"

RDEPEND="gnome-doc-utils perl"
BDEPEND="docbook-xml docbook-xsl libxslt docbook"
CONFLICT="gtk-doc-dev"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-scrollkeeper --disable-static"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

