#
# Ylmf OS package build script
#

DESCRIPTION="bsdiff: Binary Differencer using a suffix alg"
HOMEPAGE="http://www.daemonology.net/bsdiff/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.daemonology.net/"$N"/"$N-$V$R".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	gcc -o bsdiff  bsdiff.c -lbz2
	gcc -o bspatch bspatch.c -lbz2
}

pbs_install() {
	docp bsdiff bspatch "$destdir"/usr/bin/

}


