. /usr/lib/ybs/funcs

files="/etc/mateconf/schemas/mate-control-center.schemas /etc/mateconf/schemas/fontilus.schemas /etc/mateconf/schemas/control-center.schemas"

post_install() {
	mate_install_schema $files
	gnome2_icon_cache_update
	gnome2_desktop_database_update
	gnome2_mime_database_update
}

pre_remove() {
	mate_uninstall_schema $files
}

post_remove() {
	gnome2_mime_database_update
}

post_upgrade() {
	post_install
}

post_downgrade() {
	post_install
}

