#
# YLmf_OS package build script
#

DESCRIPTION="Simple config file reader and writer"
HOMEPAGE="http://pypi.python.org/pypi/configobj"
LICENSE="OSI Approved/BSD License"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://pypi.python.org/packages/source/c/"$N"/"$N-$V".tar.gz"

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

