#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Compiz Configuration System"
HOMEPAGE="http://www.compiz.org/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://releases.compiz-fusion.org/"$V"/"$N-$V".tar.bz2"

RDEPEND="libX11 libxml2 protobuf"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}


