#
# YLmf_OS package build script
#

DESCRIPTION="Library to handle, display and manipulate GIF images"
HOMEPAGE="http://sourceforge.net/projects/giflib/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://downloads.sourceforge.net/"$N"/"$N-$V".tar.bz2"

RDEPEND="glibc libICE libSM libX11 libXau libxcb libXdmcp util-linux-ng"
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

