#
# YLmf_OS package build script
#

DESCRIPTION="XSLT libraries and tools"
HOMEPAGE="http://www.xmlsoft.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="ftp://xmlsoft.org/libxml2/"$N-$V".tar.gz"

RDEPEND="glibc libgcrypt libgpg-error libxml2 zlib"
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

