#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="XSLT libraries and tools"
HOMEPAGE="http://www.xmlsoft.org/"
LICENSE="custom"
PACKAGER="StartOS Developers"

SRC_URI="ftp://xmlsoft.org/libxml2/"$N-$V".tar.gz"

RDEPEND="glibc libgcrypt libgpg-error libxml2 zlib"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

