#
# Ylmf OS package build script
#

DESCRIPTION="XSLT libraries and tools"
HOMEPAGE="http://www.xmlsoft.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="ftp://xmlsoft.org/libxml2/"$N-$V".tar.gz"

RDEPEND="glibc libgcrypt libgpg-error libxml2 zlib"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

