#
# YLmf_OS package build script
#

DESCRIPTION="XSLT libraries and tools"
HOMEPAGE="http://www.xmlsoft.org/"
REPO=""
LICENSE=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="ftp://xmlsoft.org/libxml2/"$N-$V$R".tar.gz"

RDEPEND="libxml2 zlib"
BDEPEND="${RDEPEND}"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-gtk-doc"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
