#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="fcitx skin edited by thinkmind"
HOMEPAGE="http://www.ylmf.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="fcitx(>=fcitx_4.2.4)"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_install() {
	docp tdark "$destdir"/usr/share/fcitx/skin/
}

