#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Lightweight library used to easily extract data from files archived in a single zip file"
HOMEPAGE="http://zziplib.sourceforge.net/"
LICENSE="LGPL/MPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://downloads.sourceforge.net/"$N"/"$N-$V".tar.bz2"
CHECKSUM="5fe874946390f939ee8f4abe9624b96c"

RDEPEND="glibc zlib"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

