. /usr/lib/ybs/funcs

unit="virtualbox.service"

post_install() {
    depmod -a "$KERNEL_DIST" ||true
    for ko in vboxpci vboxnetflt vboxnetadp vboxdrv; do
        rmmod $ko 2>/dev/null
        modprobe $ko
    done
    systemctl enable $unit || true        
}

post_remove() {
    post_install
}

post_upgrade() {
    systemctl --system daemon-reload
    restart $unit ||return 0
}

post_downgrade() {
    post_upgrade $1 $2
}

pre_remove() {
    systemctl disable $unit
    stop $unit ||return 0
}
