#! /bin/sh -e

PREREQ="kernelextras"

prereqs () {
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

. /usr/share/initramfs-tools/hook-functions

# Console utilities needed for console-setup
for i in setfont kbd_mode loadkeys; do
	copy_exec $(which ${i}) /bin
done

exit 0
