#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="In-circuit programming (ISP) tool for the NXP (Philips) ARM microcontrollers"
HOMEPAGE="http://sourceforge.net/projects/lpc21isp/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://downloads.sourceforge.net/project/"$N"/"$N"/"$V"/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	docp lpc21isp "$destdir"/usr/bin/
	chmod 755 "$destdir"/usr/bin/lpc21isp
}

