#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="In-circuit programming (ISP) tool for the NXP (Philips) ARM microcontrollers"
HOMEPAGE="http://sourceforge.net/projects/lpc21isp/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://downloads.sourceforge.net/project/"$N"/"$N"/"$V"/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_build() {
    domake
}

pbs_install() {
    docp lpc21isp "$PKGDIR"/usr/bin/
    chmod 755 "$PKGDIR"/usr/bin/lpc21isp
}

