#
# Ylmf OS package build script
#

DESCRIPTION="C preprocessor interface to the make utility"
HOMEPAGE="http://xorg.freedesktop.org/"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.x.org/pub/individual/util/"$N-$V$R".tar.bz2"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
