#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="XSLT processor for transforming XML documents into HTML, text, or other XML document types"
HOMEPAGE="http://xml.apache.org/xalan-j"
REPO=""
LICENSE="APACHE"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://www.apache.org/dist/xml/xalan-j/xalan-j_2_7_1-bin-2jars.tar.gz"

RDEPEND="jdk xerces2-java"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_install() {
	. /etc/profile.d/jdk.sh
	docp xalan.jar xsltc.jar "$destdir"/"$JAVA_HOME"/
}

