#
# Ylmf OS package build script
#

DESCRIPTION="Murrine GTK+2 Cairo Engine"
HOMEPAGE="http://www.cimitan.com/murrine/"
REPO=""
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.acc.umu.se/pub/GNOME/sources/"$N"/0.98/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	make DESTDIR=$destdir install
}
