#
# YLmf_OS package build script
#

DESCRIPTION="Lean and small library for ATA S.M.A.R.T. hard disks"
HOMEPAGE="http://0pointer.de/blog/projects/being-smart.html"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"
 
SRC_URI="http://0pointer.de/public/"$N-$V$R".tar.gz"

RDEPEND="udev glibc"
BDEPEND="udev-dev glibc-dev"
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/libatasmart"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
