#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Lean and small library for ATA S.M.A.R.T. hard disks"
HOMEPAGE="http://0pointer.de/blog/projects/being-smart.html"
LICENSE="GPL"
PACKAGER="StartOS Developers"
 
SRC_URI="http://0pointer.de/public/"$N-$V".tar.gz"

RDEPEND="udev"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

