#
# YLmf_OS package build script
#

DESCRIPTION="This module provides a way to process XML documents. It is build on top of XML::Parser"
HOMEPAGE="http://search.cpan.org/dist/XML-Twig/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="ftp://lug.mtu.edu/gentoo/distfiles/XML-Twig-"$V$R".tar.gz"

RDEPEND=""
BDEPEND="expat-dev"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
