#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="This module provides a way to process XML documents. It is build on top of XML::Parser"
HOMEPAGE="http://search.cpan.org/dist/XML-Twig/"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="GPL,PerlArtistic"
YARCH="any"

SRC_URI="ftp://lug.mtu.edu/gentoo/distfiles/XML-Twig-"$V".tar.gz"

RDEPEND="perl xml-parser glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
        perl_cleanup
}

