#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="This module provides a way to process XML documents. It is build on top of XML::Parser"
HOMEPAGE="http://search.cpan.org/dist/XML-Twig/"
LICENSE="GPL-2"
PACKAGER="StartOS Developers"

SRC_URI="ftp://lug.mtu.edu/gentoo/distfiles/XML-Twig-"$V$R".tar.gz"

RDEPEND=""
BDEPEND="expat-dev"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
