#
# YLmf_OS package build script
#

DESCRIPTION="This module provides a way to process XML documents. It is build on top of XML::Parser"
HOMEPAGE="http://search.cpan.org/dist/XML-Twig/"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="ftp://lug.mtu.edu/gentoo/distfiles/XML-Twig-"$V".tar.gz"

RDEPEND="perl xml-parser glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

