#
# YLmf_OS package build script
#

DESCRIPTION="Typesafe callback system for standard C++"
HOMEPAGE="http://libsigc.sourceforge.net/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/libsigc++/2.2/libsigc++-2.2.10.tar.xz"

RDEPEND="gcc glibc"
BDEPEND=" "

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
