#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A Perl extension interface to James Clark's XML parser, expat"
HOMEPAGE="http://search.cpan.org/~msergeant/"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="GPL,PerlArtistic"
GROUP="perl"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TO/TODDR/XML-Parser-$V.tar.gz"

RDEPEND="perl expat"
BDEPEND=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}
