#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Utilities for handling IEEE 754 floating point special values"
HOMEPAGE="http://pypi.python.org/pypi/fpconst"
LICENSE="APACHE"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://downloads.sourceforge.net/rsoap/$N-$V.tar.gz"
CHECKSUM="13884b81da3335b2ec4b6ea1dc26b6fa"

RDEPEND="python"
BDEPEND="" 
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}



