#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="groovy little assembler"
HOMEPAGE="http://nasm.sourceforge.net/"
 
SRC_URI="http://www.nasm.us/pub/"$N"/releasebuilds/"$V$R"/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	make INSTALLROOT=$destdir install
}
