#
# Ylmf OS package build script
#

DESCRIPTION="Perl module for the X Window System Protocol, version 11 "
HOMEPAGE="http://search.cpan.org/~smccam/X11-Protocol-0.56/Protocol.pm"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://search.cpan.org/CPAN/authors/id/S/SM/SMCCAM/X11-Protocol-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
