#
# Ylmf OS package build script
#

DESCRIPTION="Perl module for the X Window System Protocol, version 11 "
HOMEPAGE="http://search.cpan.org/~smccam/X11-Protocol-0.56/Protocol.pm"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/S/SM/SMCCAM/X11-Protocol-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
