#
# Ylmf OS package build script
#

DESCRIPTION="GIT - the stupid content tracker, the revision control system"
HOMEPAGE="http://www.git-scm.com/"
 
SRC_URI="http://kernel.org/pub/software/scm/git/$N-$V.tar.bz2"

RDEPEND=""
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=" --sysconfdir=/etc --libexecdir=/usr/lib/git "
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

