#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A proven industry-strength PDF generating solution"
HOMEPAGE="http://www.chipx86.com/wiki/Libsexy"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://www.reportlab.org/ftp/"$N-$V".tar.gz"

RDEPEND="freetype python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-static --enable-shared"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc LICENSE.txt
}

