#
# Ylmf OS package build script
#

DESCRIPTION="A set of backgrounds packaged with the GNOME desktop"
HOMEPAGE=" http://www.gnome.org/ "
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.32/2.32.1/sources/"$N-$V".tar.bz2"

RDEPEND=""
BDEPEND="desktop-file-utils gnome-desktop"
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

