#
# Ylmf OS package build script
#

DESCRIPTION="A set of backgrounds packaged with the GNOME desktop"
HOMEPAGE=" http://www.gnome.org/ "
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI=" http://ftp.gnome.org/pub/gnome/desktop/2.30/2.30.2/sources/"$N-$V$R".tar.bz2 "

RDEPEND=""
BDEPEND=" desktop-file-utils gnome-desktop"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
