#
# YLmf_OS package build script
#

DESCRIPTION="A set of backgrounds packaged with the GNOME desktop"
HOMEPAGE=" http://www.gnome.org/ "
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI=" http://ftp.gnome.org/pub/gnome/desktop/2.30/2.30.2/sources/"$N-$V$R".tar.bz2 "

RDEPEND=""
BDEPEND="${RDEPEND} desktop-file-utils gnome-desktop"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
