#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A Post-Processor for SGMLS and NSGMLS"
HOMEPAGE="http://search.cpan.org/dist/$N"
LICENSE="GPL,PerlArtistic"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://www.cpan.org/authors/id/D/DM/DMEGG/"$N-$V"ii.tar.gz"
CHECKSUM="5bcb197fd42e67d51c739b1414d514a7"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_patch() {
    mkdir -p "$destdir"/usr/bin \
             "$destdir"/usr/lib"$LIBDIRSUFFIX"/perl5/vendor_perl \
             "$destdir"/usr/share/doc/perl-sgmls
}

pbs_install() {
    make install \
         BINDIR="$destdir"/usr/bin \
         PERL5DIR="$destdir"/usr/lib"$LIBDIRSUFFIX"/perl5/vendor_perl \
         HTMLDIR="$destdir"/usr/share/doc/perl-sgmls
    perl_cleanup
}

