#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A tool for reverse engineering 3rd party, closed, binary Android apps."
HOMEPAGE="http://code.google.com/p/android-apktool/"
LICENSE="Apache License 2.0"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://android-apktool.googlecode.com/files/"$N$V".tar.bz2"
CHECKSUM="2dd828cf79467730c7406aa918f1da1bd21aaec8"

RDEPEND="jdk"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_install() {
    docp apktool.jar "$PKGDIR"/opt/"$N"/
    docp "$FILESDIR"/apktool "$PKGDIR"/usr/bin
}

