#
# YLmf_OS package build script
#

DESCRIPTION="A fully functional X client library for Python, written in Python"
HOMEPAGE="http://python-xlib.sourceforge.net/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://downloads.sourceforge.net/project/"$N"/"$N"/"$Vrc1"/"$N-$V"rc1.tar.bz2 "

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	python setup.py build
}

pbs_install() {
	python setup.py install --prefix=/usr --root="$destdir"
	dodoc COPYING NEWS README
}

