#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A fully functional X client library for Python, written in Python"
HOMEPAGE="http://python-xlib.sourceforge.net/"
LICENSE="GPL"
PACKAGER="StartOS Developers"
YARCH="any"

SRC_URI="http://downloads.sourceforge.net/project/"$N"/"$N"/"$Vrc1"/"$N-$V"rc1.tar.bz2 "

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_build() {
    python setup.py build
}

pbs_install() {
    python setup.py install --prefix=/usr --root="$PKGDIR"
    dodoc COPYING
}

