#
# YLmf_OS package build script
#

DESCRIPTION="A powerful light-weight programming language designed for extending applications"
HOMEPAGE="http://www.lua.org/docs.html"
LICENSE="MIT license"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="http://www.lua.org/ftp/"$N-$V$R".tar.gz"

RDEPEND="glibc readline ncurses"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake linux
}

pbs_install() {
	make INSTALL_TOP="$destdir"/usr install
	domv "$destdir"/usr/man  "$destdir"/usr/share
	docp etc/*.pc "$destdir"/usr/lib/pkgconfig
}
