#
# Ylmf OS package build script
#

DESCRIPTION="A droid derived Sans-Serif style CJK font"
HOMEPAGE="http://wqy.sourceforge.net/"
LICENSE="Apache 2.0,GPL v3"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
YARCH="any"

SRC_URI="http://nchc.dl.sourceforge.net/project/wqy/wqy-microhei/0.2.0-beta/"$N-$V$R".tar.gz"

RDEPEND=""
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_install() {
	docp *.ttc "$destdir"/usr/share/fonts/wenquanyi/wqy-microhei
}

