#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl Module:  Easy manipulation of IPv4 and IPv6 addresses"
HOMEPAGE="http://search.cpan.org/dist/$N"
LICENSE="GPL,PerlArtistic"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://www.cpan.org/authors/id/M/MA/MANU/$N-$V.tar.gz"
CHECKSUM="a49c0b02a9b793ff60191cdafc0c202e"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}

