. /usr/lib/ybs/funcs

SCHEMAS="
	/etc/gconf/schemas/compiz-widget.schemas
	/etc/gconf/schemas/compiz-wallpaper.schemas
	/etc/gconf/schemas/compiz-trailfocus.schemas
	/etc/gconf/schemas/compiz-splash.schemas
	/etc/gconf/schemas/compiz-showmouse.schemas
	/etc/gconf/schemas/compiz-showdesktop.schemas
	/etc/gconf/schemas/compiz-shelf.schemas
	/etc/gconf/schemas/compiz-scalefilter.schemas
	/etc/gconf/schemas/compiz-reflex.schemas
	/etc/gconf/schemas/compiz-notification.schemas
	/etc/gconf/schemas/compiz-mblur.schemas
	/etc/gconf/schemas/compiz-maximumize.schemas
	/etc/gconf/schemas/compiz-loginout.schemas
	/etc/gconf/schemas/compiz-group.schemas
	/etc/gconf/schemas/compiz-grid.schemas
	/etc/gconf/schemas/compiz-gears.schemas
	/etc/gconf/schemas/compiz-firepaint.schemas
	/etc/gconf/schemas/compiz-fadedesktop.schemas
	/etc/gconf/schemas/compiz-extrawm.schemas
	/etc/gconf/schemas/compiz-cubeaddon.schemas
	/etc/gconf/schemas/compiz-crashhandler.schemas
	/etc/gconf/schemas/compiz-bicubic.schemas
	/etc/gconf/schemas/compiz-bench.schemas
	/etc/gconf/schemas/compiz-animationaddon.schemas
	/etc/gconf/schemas/compiz-addhelper.schemas
	/etc/gconf/schemas/compiz-3d.schemas"
	
post_install() {
	gnome2_install_schema "$SCHEMAS"
	gnome2_desktop_database_update
	gnome2_gconfd_reload
}

pre_remove() {
	gnome2_uninstall_schema "$SCHEMAS"
}

post_install() {
	gnome2_desktop_database_update
	gnome2_gconfd_reload
}

post_upgrade() {
	post_install
}

post_downgrade() {
	post_install
}

