#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GooCanvas python bindings"
HOMEPAGE="http://developer.berlios.de/projects/pygoocanvas"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/pygoocanvas/0.14/pygoocanvas-$V.tar.bz2"
CHECKSUM="e0e7b694af2f81a78b0838555d150252"

RDEPEND="python goocanvas1 py-gtk"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--disable-docs"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
