#
# Ylmf OS package build script
#

DESCRIPTION="OSS compatibility library"
HOMEPAGE="http://www.alsa-project.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="ftp://ftp.alsa-project.org/pub/oss-lib/"$N-$V".tar.bz2"

RDEPEND="alsa-lib glibc"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

