#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python bindings for the Qt framework"
HOMEPAGE="http://www.pyside.org/"
LICENSE="LGPL"
PACKAGER="StartOS Developers"

SRC_URI="http://www.pyside.org/files/"$N"-qt4.8+"$V".tar.bz2"
CHECKSUM="59c8653734b020b0128b82adc98ee704"

RDEPEND="alsa-lib attr bzip2 dbus expat flac fontconfig freetype gcc-lib glib2 glibc gst-plugins-base gstreamer json-c libcap libdrm libffi libICE libogg libpng libqzeitgeist libSM libsndfile libvorbis libX11 libXau libxcb libXdamage libXdmcp libXext libXfixes libXi libxml2 libXrender libXtst libXxf86vm mesa openssl phonon pulseaudio python qt-core shiboken sqlite util-linux-ng zlib"
RECOMMENDED=""
BDEPEND="cmake"
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig -DCMAKE_BUILD_TYPE=Release
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

