#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="International Components for Unicode"
HOMEPAGE="http://www.icu-project.org/"
LICENSE="custom,icu"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
 
SRC_URI="http://download.icu-project.org/files/"$N"4c/"$V"/"$N"4c-"${V//./_}"-src.tgz"
CHECKSUM="c721c2e0c8f86975ccea620d09aedc81"

RDEPEND="gcc-libs"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    cd source
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodoc ../license.html
}

