#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="International Components for Unicode"
HOMEPAGE="http://www.icu-project.org/"
LICENSE="custom,icu"
PACKAGER="StartOS Developers"
 
SRC_URI="http://download.icu-project.org/files/"$N"4c/"$V"/"$N"4c-"${V//./_}"-src.tgz"
CHECKSUM="cf7bf9e56aa6c2057a8b6f464046483e"

RDEPEND="gcc-lib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_patch() {
	cd source
	# Fix building clients without c++11 http://bugs.icu-project.org/trac/changeset/32780
	dopatch changeset_32780.diff
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc ../license.html
}

