#
# YLmf_OS package build script
#

DESCRIPTION=" International Components for Unicode"
HOMEPAGE="http://www.icu-project.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="http://download.icu-project.org/files/"$N"4c/"$V"/"$N"4c-4_2_1-src.tgz"

RDEPEND="gcc glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	cd source 
	for x in CFLAGS CXXFLAGS CPPFLAGS LDFLAGS; do
		sed -i -e "/^${x} =.*/s:@${x}@::" config/Makefile.inc.in
        done
	config+="--disable-debug --disable-samples"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

