#!/bin/sh

#
device_ids() {
  local filename="$1"

  local list_prev="$(mktemp)"
  local list_cur="$(mktemp)"

  # Find the symbols of the .rodata section...
  objdump --section=.rodata --syms "$filename" |
  sed -nr '/SYMBOL TABLE/,/^$/ {
    s/^([0-9a-f]+)\s+l\s+O\s+\S+\s+([0-9a-f]+)\s+\S+.*/\1 \2/p
  }' |
  while read start length; do
    objdump --section=.rodata --full-contents \
      --start-address="0x$start" \
      --stop-address="$((0x$start+0x$length))" "$filename" |
    sed -nr 's/^ [0-9a-f]+ ([0-9a-f]{2})([0-9a-f]{2}).*/\2\1/p' |
    sort | uniq | grep -vx "0000" >"$list_cur"

    # The consistent thing between different releases has been that there are
    # two subsequent symbols with the same PCI ID list near the beginning. Find
    # them.
    if [ -s "$list_prev" -a -s "$list_cur" ] &&
       cmp -s "$list_prev" "$list_cur"; then
      cat "$list_cur"
      break
    fi

    cp "$list_cur" "$list_prev"
  done

  rm -f "$list_prev" "$list_cur"
}

seen_ids=' '

main () {
  filename="$1";

  orig_ids="$(device_ids "$filename")"
  if [ -z "$orig_ids" ]; then
    echo "WARNING: No IDs were found from $filename" >&2
  fi
  echo 'package nvidia-graphic-173-driver'
  echo 'module nvidia.ko'
  echo 'description Video driver for the NVIDIA graphics accelerators'

  for id in $orig_ids; do
    case "$seen_ids" in
      *" $id "*)
        # Already seen the ID.
        ;;
      *)
        # Not seen it yet.
        seen_ids="${seen_ids}${id} "
        printf "alias pci:v%08Xd%08Xsv*sd*bc03sc*i* %s %s\n" \
          0x10de "0x$id" "$modname" "$pkgname"
        ;;
    esac
  done |sort
}

#
main  nv-kernel.o

