#
# YLmf_OS package build script
#

DESCRIPTION="ylmfos start menu"
HOMEPAGE="www.ylmf.com"
REPO="testing"
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://git.ylmf.com/ymenu.git"

RDEPEND="python numpy gst-python python-xlib zeitgeist configobj gnome-panel"
BDEPEND=""
RECOMMENDED="psyco"

INSTALL="$N.install"

NOTES=""

pbs_unpack() {
	ypkg_unpack
}

pbs_install() {
	ypkg_mkinstall
}
