#
# YLmf_OS package build script
#

DESCRIPTION="WavPack audio compression tools"
HOMEPAGE="http://www.wavpack.com"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://www.wavpack.com/"$N-$V$R".tar.bz2"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS ChangeLog NEWS README
}
