#
# YLmf_OS package build script
#

DESCRIPTION="Linux kernel module for (but not limited to) HP Omnibook support"
HOMEPAGE="http://www.sourceforge.net/projects/omnibook"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://omnibook.git.sourceforge.net/gitroot/omnibook/omnibook"

RDEPEND=""
BDEPEND=""
RECOMMENDED="mingw32-build"
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_install() {
	ypkg_dosrc *
}

