#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Interface to Bzip2 compression library"
HOMEPAGE="http://search.cpan.org/dist/$_realname"
LICENSE="GPL PerlArtistic"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://mirror.osqdu.org/CPAN/authors/id/A/AR/ARJAY/Compress-Bzip2-"$V".tar.gz"

RDEPEND="perl bzip2"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

