#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="kill a list of pids, and all their sub-children "
HOMEPAGE="http://search.cpan.org/~durist/Proc-ProcessTable-0.45/Killfam.pm"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="GPL,PerlArtistic"

SRC_URI="http://search.cpan.org/CPAN/authors/id/D/DU/DURIST/Proc-ProcessTable-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
        perl_cleanup
}

