#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Hyperfast and lightweight templating for the Python2 platform."
HOMEPAGE="http://www.makotemplates.org"
LICENSE="MIT"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"
YARCH="any"

SRC_URI="http://www.makotemplates.org/downloads/Mako-"$V".tar.gz"
CHECKSUM="e3c0a677aa4216da9e89ef8fa76cbafb"

RDEPEND="python py-markupsafe py-beaker"
BDEPEND="py-distribute"
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall --optimize=1
    dodoc LICENSE
}
