#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Integrated Development Environment for professional JavaScript and front-end Web developers."
HOMEPAGE="http://www.jetbrains.com/products.html"
LICENSE="custom"
PACKAGER="StartOS Developers"
YARCH="any"

SRC_URI="http://download-ln.jetbrains.com/webide/WebStorm-"$V".tar.gz"
CHECKSUM="fc14334401c4766718de248002e7a44a"

RDEPEND="jdk jre"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_install() {
	docp * "$destdir"/usr/share/"$N"/
	dodesktop "$N".desktop bin/webide.png
	doln /usr/share/"$N"/bin/webstorm.sh "$destdir"/usr/bin/"$N"
}

