#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A collection of different plugins for Geany"
HOMEPAGE="http://plugins.geany.org/geany-plugins"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://plugins.geany.org/"$N"/"$N-$V".tar.bz2"

RDEPEND="geany gtkspell libxml2"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
