#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A Python HTML/XML parser designed for quick turnaround projects like screen-scraping"
HOMEPAGE="http://www.crummy.com/software/BeautifulSoup/index.html"
LICENSE="PSF"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"
YARCH="any"

SRC_URI="http://www.crummy.com/software/BeautifulSoup/download/3.x/BeautifulSoup-$V.tar.gz"
CHECKSUM="5ad1a8550a19bfc945baac23eb8293ed"

RDEPEND="python"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
