# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */
user_pref("browser.startup.homepage", "http://www.114la.com/?linux");
user_pref("browser.search.defaultenginename", "baidu");
user_pref("browser.search.order.1", "baidu");
user_pref("network.protocol-handler.app.ed2k", "/usr/bin/ed2k");
user_pref("network.protocol-handler.expose.ed2k", false);
user_pref("network.protocol-handler.external.ed2k", true);
user_pref("network.protocol-handler.warn-external.ed2k", true);
