#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A C library for parsing configuration files"
HOMEPAGE="https://github.com/williamh/dotconf"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="git://github.com/williamh/dotconf.git"

RDEPEND="glibc"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	git checkout v1.3
	autoreconf -i
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

