. /usr/lib/ybs/funcs

files="/etc/gconf/schemas/mousetweaks.schemas /etc/gconf/schemas/pointer-capture-applet.schemas"

post_install() {
	gnome2_install_schema $files
	gnome2_rarian_sk_update
	gnome2_gconfd_reload
}

pre_remove() {
        gnome2_uninstall_schema $files
}

post_remove() {
	gnome2_rarian_sk_update
	gnome2_gconfd_reload
}

post_upgrade() {
	gnome2_rarian_sk_update 
	gnome2_gconfd_reload
}

post_downgrade() {
	post_upgrade
}

