#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Simple, fast, extensible JSON encoder/decoder for Python"
HOMEPAGE="https://github.com/simplejson"
LICENSE="MIT"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="git://github.com/$N/$N.git"

RDEPEND="python"
RECOMMENDED=""
BDEPEND="distribute git"
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_patch() {
    git checkout v"$V"
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodoc LICENSE.txt
}
