#
# Ylmf OS package build script
#

DESCRIPTION="ATI Mach64 video driver"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://xorg.freedesktop.org/archive/individual/driver/"$N-$V".tar.bz2"
CHECKSUM="ae62936e11af4fc0fac9f2db601a844f"

RDEPEND="glibc xorg-server(>=1.10.4)"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

