#
# YLmf_OS package build script
#

DESCRIPTION="A small sample cross-platform networking library"
HOMEPAGE="http://www.libsdl.org/projects/SDL_net/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.libsdl.org/projects/SDL_net/release/SDL_net-"$V".tar.gz"

RDEPEND="libsdl"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

