#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Determine the locale encoding  "
HOMEPAGE="http://search.cpan.org/~gaas/Encode-Locale-1.02/"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://mirror.osqdu.org/CPAN/authors/id/G/GA/GAAS/Encode-Locale-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor PERL5LIB=""
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

