#
# Ylmf OS package build script
#

DESCRIPTION="Determine the locale encoding  "
HOMEPAGE="http://search.cpan.org/~gaas/Encode-Locale-1.02/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://mirror.osqdu.org/CPAN/authors/id/G/GA/GAAS/Encode-Locale-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
