#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Object interface for AF_INET|AF_INET6 domain sockets"
HOMEPAGE="http://search.cpan.org/dist/$N"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="GPL,PerlArtistic"
YARCH="any"

SRC_URI="http://search.cpan.org/CPAN/authors/id/S/SH/SHLOMIF/"$N-$V".tar.gz"
CHECKSUM="12a80a5164a775294a9bf9c812fc3257"

RDEPEND="Socket6"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1 PERL5LIB="" \
           PERL_AUTOINSTALL=--skipdeps  \
           PERL_MM_OPT="INSTALLDIRS=vendor DESTDIR='$PKGDIR'" \
           PERL_MB_OPT="--installdirs vendor --destdir '$PKGDIR'" \
           MODULEBUILDRC=/dev/null
    perl Makefile.PL
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}

