#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Parse Options - Command line parser"
HOMEPAGE="http://rpm5.org/"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://rpm5.org/files/"$N"/"$N-$V".tar.gz"
CHECKSUM="cfe94a15a2404db85858a81ff8de27c8ff3e235e"

RDEPEND="glibc"
BDEPEND=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    doconfig
}

pbs_build(){
    domake
}

pbs_install() {
    domkinstall pkgconfigdir=/usr/lib"$LIBDIRSUFFIX"/pkgconfig
    dodoc COPYING
}

