#
# Ylmf OS package build script
#

DESCRIPTION="A JSON implementation in C"
HOMEPAGE="http://oss.metaparadigm.com/json-c/"
LICENSE="MIT"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://oss.metaparadigm.com/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc"
RECOMMENDED=""
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

