#!/bin/sh

OPTION=FRAMEBUFFER
PREREQ="framebuffer console_setup brltty"
[ -f /scripts/functions ] && . /scripts/functions

prereqs()
{
        echo "$PREREQ"
}

case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

is_runinvm && ln -sf /lib/plymouth/themes/*ramfs/*ramfs.plymouth /lib/plymouth/themes/default.plymouth

# ylmf, vga16fb lost?
modprobe -q vga16fb

printf '\033[?25l' > /dev/tty7
/sbin/plymouthd --mode=boot --attach-to-session --pid-file=/dev/.initramfs/plymouth.pid
/bin/plymouth show-splash
