#
# Ylmf OS package build script
#

DESCRIPTION="Locale and ISO 2022 support for Unicode terminals"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.x.org/releases/X11R7.6/src/app/"$N-$V".tar.bz2"

RDEPEND="glibc libfontenc zlib"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

