#
# YLmf_OS package build script
#

DESCRIPTION="A high-quality and portable font engine"
HOMEPAGE="http://www.freetype.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://downloads.sourceforge.net/project/"$N"/"$N"2/"$V"/"$N-$V".tar.bz2"

RDEPEND="glibc zlib"
BDEPEND=" "

pbs_unpack(){
        dounpack
}

pbs_config() {
	dopatch "freetype_2.4.2-2.1.patch"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

