#
# Ylmf OS package build script
#

DESCRIPTION="Thin/fast CORBA ORB"
HOMEPAGE="http://www.gnome.org/projects/orbit"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.acc.umu.se/pub/gnome/platform/2.32/2.32.1/sources/ORBit2-"$V".tar.bz2"

RDEPEND="glib2 glibc libIDL"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}		    	

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

