#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="the audio output library"
HOMEPAGE="http://www.xiph.org/ao/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://downloads.xiph.org/releases/ao/"$N-$V".tar.gz"

RDEPEND="nas pulseaudio"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

