#
# YLmf_OS package build script
#

DESCRIPTION="the audio output library"
HOMEPAGE="http://www.xiph.org/ao/"
REPO=""
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://downloads.xiph.org/releases/ao/libao-1.1.0.tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
