#
# YLmf_OS package build script
#

DESCRIPTION="X.Org Video protocol headers"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://www.x.org/releases/X11R7.6/src/proto/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""
OPINION="nodev"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {	
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
