#
# Ylmf OS package build script
#

DESCRIPTION="C# implementation of D-Bus."
HOMEPAGE="http://www.ndesk.org/DBusSharp"
REPO=""
LICENSE=""
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.ndesk.org/archive/dbus-sharp/"$N-$V$R".tar.gz"

RDEPEND=""
BDEPEND="ndesk-dbus"
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
