#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="a Python library for working with RDF, a simple yet powerful language for representing information."
HOMEPAGE="http://rdflib.net/"
LICENSE="BSD"
PACKAGER="chenqixing@ivali.com
          Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://rdflib.googlecode.com/files/${N}-${V}.tar.gz"
CHECKSUM="ab3d3a5f71ebb6fe4fd33539f5d5768e"

RDEPEND="python"
BDEPEND="distribute"
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall --optimize=1 
	dodoc LICENSE
}

