#
# YLmf_OS package build script
#

DESCRIPTION="a Python library for working with RDF, a simple yet powerful language for representing information."
HOMEPAGE="http://rdflib.net/"
LICENSE="New BSD License"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="$N-$V.tar.gz"

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
