#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="a Python library for working with RDF, a simple yet powerful language for representing information."
HOMEPAGE="http://rdflib.net/"
LICENSE="New BSD License"
PACKAGER="chenqixing@ivali.com"
YARCH="any"
SRC_URI="http://rdflib.googlecode.com/files/${N}-${V}.tar.gz"

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_install() {
	python ./setup.py build
    python ./setup.py install --root=${destdir}
	dodoc LICENSE
}

