#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A comprehensive HTTP client library that supports many features left out of other HTTP libraries."
HOMEPAGE="http://code.google.com/p/httplib2/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://httplib2.googlecode.com/files/httplib2-0.7.1.tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}


