#
# YLmf_OS package build script
#

DESCRIPTION="A comprehensive HTTP client library that supports many features left out of other HTTP libraries."
HOMEPAGE="http://code.google.com/p/httplib2/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://httplib2.googlecode.com/files/httplib2-0.7.1.tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}


