#
# Ylmf OS package build script
#

DESCRIPTION="A comprehensive HTTP client library that supports many features left out of other HTTP libraries."
HOMEPAGE="http://code.google.com/p/httplib2/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://httplib2.googlecode.com/files/httplib2-0.7.1.tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}


