#
# YLmf_OS package build script
#

DESCRIPTION="A URI Perl Module"
HOMEPAGE="http://search.cpan.org/dist/URI/"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/G/GA/GAAS/URI-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}
