#
# YLmf_OS package build script
#

DESCRIPTION="A C and C++ cross-compilers for building Windows executables on Linux"
HOMEPAGE="http://mingw.sf.net"
LICENSE="LGPL"
PACKAGER="hzx@115.com"
SRC_URI="http://sourceforge.net/projects/mingw/files/MinGW/BaseSystem/GCC/Version4/Previous%20Testing_%20gcc-$V$R-mingw-src-2/gcc-$V$R-2-src.tar.gz"

RDEPEND=""
BDEPEND="${RDEPEND} "
RECOMMENDED=""

NOTES="
"$V$R" is gcc core's version
"

pbs_unpack() {
	mkdir "$N-$V$R"
	
        ypkg_unpack
	ln -sf gcc-"$V$R"-2-src gcc
}

pbs_config() {
	target="i586-mingw32msvc"
	mkdir build
	cd build
	unset CFLAGS CXXFLAGS
	chmod ugo+x ../gcc/configure
	chmod ugo+x ../gcc/move-if-change
	
	#
	YPB_CONFIG+=" --prefix=/usr
		      --target="$target"
		      --enable-languages=c,c++
		      --enable-threads
		      --enable-sjlj-exceptions
		      --enable-hash-synchronization
		      --disable-nls
		      --disable-libssp
		      --disable-multilib
		      --enable-version-specific-runtime-libs	
		      --mandir=/usr/share/man "
	../gcc/configure -v $YPB_CONFIG
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	make -j1 -C "$target"/libgcc DESTDIR="$YPPATH_DEST" libgcc_eh.a install
	make -j1 -C "$target"/libstdc++-v3 DESTDIR="$YPPATH_DEST" install 
	
	mv "$YPPATH_DEST"/usr/bin/*.dll "$YPPATH_DEST"/*.dll "$YPPATH_DEST"/usr/"$target"/lib/
	cd "$target"
	rm -rf usr/bin/$target-{gcov,gccbug,gcc-*} usr/{include,lib/libiberty.a} usr/share/{info,man} usr/share/gcc-"$V$R"/python
        strip usr/bin/*
        strip usr/libexec/gcc/"$target"/"$V$R"/{cc1*,collect2} 
	"$target-strip" -g usr/lib/gcc/"$target"/"$V$R"/*.a
	# remove some non-cross stuff that will clash with other packages
	# and shuffle things about as required.
	#rm -rf "$YPPATH_DEST"/usr/include "$YPPATH_DEST"/usr/info "$YPPATH_DEST"/usr/share/locale "$YPPATH_DEST"/usr/lib/*a "$YPPATH_DEST"/usr/share/man/man7
	#
	#install -m755 -d "$YPPATH_DEST"/usr/share/doc/"$N-$V$R"
	#cp -a AUTHORS ChangeLog COPYING INSTALL NEWS README   "$YPPATH_DEST"/usr/share/doc/"$N-$V$R" |true 
	# install symlinks to enable compilercache use.
	# This first one is just missing from the gcc install.
	#ln -sf /usr/bin/$target-gcc "$YPPATH_DEST"/usr/bin/$target-cc				  
	#ln -sf /usr/lib/compilercache/compilercache /usr/lib/compilercache/$target-c++ 
	#ln -sf /usr/lib/compilercache/compilercache /usr/lib/compilercache/$target-cc  
	#ln -sf /usr/lib/compilercache/compilercache /usr/lib/compilercache/$target-g++ 
	#ln -sf /usr/lib/compilercache/compilercache /usr/lib/compilercache/$target-gcc
	#dh_strip -Xusr/$(target)/lib -Xusr/lib/gcc/$(target)/$(version)/lib
	#$target-strip --strip-debug "$YPPATH_DEST"/usr/$target/lib/*.a
	#$target-strip --strip-debug "$YPPATH_DEST"/usr/lib/gcc/$target/*/*.a
	#$target-strip --strip-debug "$YPPATH_DEST"/usr/lib/gcc/$target/*/*.o
	# Ugh, the source package was built on a billbox.  Fix some stray executables.
	#find "$YPPATH_DEST"/usr/lib/gcc/$target/*/include -type f -exec chmod 644 {} \;
}
