#
# YLmf_OS package build script
#

DESCRIPTION=="X.Org SM library"
HOMEPAGE="http://www.x.org/wiki/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.x.org/releases/X11R7.6/src/lib/"$N-$V".tar.bz2"

RDEPEND="glibc libICE util-linux-ng"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

