#
# Ylmf OS package build script
#

DESCRIPTION="GNU Flash movie player"
HOMEPAGE="http://www.gnu.org/software/gnash/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="ftp://ftp.gnu.org/gnu/"$N"/"$V"/"$N-$V".tar.bz2"
CHECKSUM="63e9f79c41d93d48c5a2fa94856548c4"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

