#
# Ylmf OS package build script
#

DESCRIPTION="GNOME end user documentation"
HOMEPAGE="http://www.gnome.org"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.acc.umu.se/pub/gnome/sources/"$N"/2.30/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND="gnome-doc-utils which"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
