#
# YLmf_OS package build script
#

DESCRIPTION="GNOME end user documentation"
HOMEPAGE="http://www.gnome.org"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://ftp.acc.umu.se/pub/gnome/sources/"$N"/2.30/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND="gnome-doc-utils which"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
