#
# YLmf_OS package build script
#

DESCRIPTION="Compiler for the GObject type system"
HOMEPAGE="http://live.gnome.org/Vala"
REPO=""
LICENSE="LGPL"
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://hammurabi.acc.umu.se/pub/GNOME/sources/vala/0.10/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND="${RDEPEND} "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-unversioned"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ln -sf /usr/bin/valac-0.10  "$YPPATH_DEST"/usr/bin/valac
}
