#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An image viewer that uses OpenGL"
HOMEPAGE="http://guichaz.free.fr/gliv/"
 
SRC_URI="http://guichaz.free.fr/gliv/files/gliv-$V.tar.bz2"

RDEPEND=""
BDEPEND=" x11-libs/gtkglext"

pbs_unpack()
{
        dounpack
}

pbs_config()
{
	
	config+=" --prefix=/usr "
	doconfig
}

pbs_build()
{
	domake
}

pbs_install()
{
	domkinstall
}
