#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="CD-ROM image (B6T/CCD/CDI/CUE/ISO/MDS/NRG/TOC) access library"
HOMEPAGE="http://cdemu.sourceforge.net/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://sourceforge.net/projects/cdemu/files/"$N"/"$N-$V".tar.bz2"
CHECKSUM="b60d9baa754efee6e0f6a584ec033fff"

RDEPEND="glib2 libsndfile"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--disable-static"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

