#
# YLmf_OS package build script
#

DESCRIPTION="parse directory listing"
HOMEPAGE="http://search.cpan.org/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://mirrors.ustc.edu.cn/CPAN/authors/id/G/GA/GAAS/File-Listing-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
