diff -ur qiv-2.2.4/Makefile qiv-2.2.4.new//Makefile
--- qiv-2.2.4/Makefile	2011-05-13 21:11:24.000000000 +0800
+++ qiv-2.2.4.new//Makefile	2012-03-12 11:01:24.354624960 +0800
@@ -4,7 +4,7 @@
 #######################################################################
 
 # Directory where qiv will be installed under.
-PREFIX = /usr/local
+PREFIX = $(DESTDIR)/usr/
 
 # Font to use for statusbar in fullscreen mode
 STATUSBAR_FONT = "fixed"
@@ -138,6 +138,8 @@
 	fi
 	install -m 0644 $(PROGRAM).1 $(PREFIX)/man/man1
 	$(COMPRESS_PROG) $(PREFIX)/man/man1/$(PROGRAM).1
+
+check: $(PROGRAM)	
 	@if ./qiv -f ./intro.jpg ; \
 	then echo "-- Test Passed --" ; \
 	else echo "-- Test Failed --" ; \
