#
# Ylmf OS package build script
#

DESCRIPTION="Perl interface to the GooCanvas "
HOMEPAGE="http://search.cpan.org/~yewenbin/Goo-Canvas-0.06/lib/Goo/Canvas.pm"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/Y/YE/YEWENBIN/Goo-Canvas-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
