#
# YLmf_OS package build script
#

DESCRIPTION="Perl interface to the GooCanvas "
HOMEPAGE="http://search.cpan.org/~yewenbin/Goo-Canvas-0.06/lib/Goo/Canvas.pm"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/Y/YE/YEWENBIN/Goo-Canvas-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}
