#
# YLmf_OS package build script
#

DESCRIPTION="Displays info about your card's VDPAU support"
HOMEPAGE="http://www.freedesktop.org/wiki/Software/VDPAU"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://anongit.freedesktop.org/~aplattner/vdpauinfo"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
