#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="VTE based terminator"
HOMEPAGE="http://lilyterm.luna.com.tw/index_cht.html"
LICENSE="GPLv2+"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://lilyterm.luna.com.tw/file/"$N-$V".tar.gz"

RDEPEND="vte"
BDEPEND=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
