#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GNOME Terminal"
HOMEPAGE="http://www.gnome.org/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.32/2.32.1/sources/"$N-$V".tar.bz2 "

RDEPEND="gconf libSM vte"
BDEPEND="libgnome-dev startup-notification-dev"
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-schemas-install"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	install -m755 $filesdir/gnome-terminal.wrapper "$destdir"/usr/bin
	rm -fr "$destdir"/var/lib/scrollkeeper
	rm -fr "$destdir"/var/lib/log
}	

