#
# Ylmf OS package build script
#

DESCRIPTION="GNOME Terminal"
HOMEPAGE="http://www.gnome.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.30/2.30.2/sources/"$N-$V$R".tar.bz2 "

RDEPEND="atk cairo dbus dbus-glib expat fontconfig freetype gcc-lib gconf glib2 gdk-pixbuf glibc gtk+ libICE libpng libSM libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender ncurses orbit pango pixman util-linux-ng vte zlib"
BDEPEND=" libgnome-dev startup-notification-dev"
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-schemas-install"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	install -m755 $filesdir/gnome-terminal.wrapper "$destdir"/usr/bin
	rm -fr "$destdir"/var/lib/scrollkeeper
	rm -fr "$destdir"/var/lib/log
}	

