#
# YLmf_OS package build script
#

DESCRIPTION="GNOME Terminal"
HOMEPAGE="http://www.gnome.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.32/2.32.1/sources/"$N-$V".tar.bz2 "

RDEPEND="atk cairo expat fontconfig freetype gcc gconf gdk-pixbuf glib2 glibc gtk+ libICE libpng libSM libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender ncurses orbit pango pixman util-linux-ng vte zlib"
BDEPEND="libgnome-dev startup-notification-dev"
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-schemas-install"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	install -m755 "$FILES_PATH"/files/gnome-terminal.wrapper "$YPPATH_DEST"/usr/bin
	rm -fr "$YPPATH_DEST"/var/lib/scrollkeeper
	rm -fr "$YPPATH_DEST"/var/lib/log
}	

