#
# YLmf_OS package build script
#

DESCRIPTION="GNOME Terminal"
HOMEPAGE="http://www.gnome.org/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.30/2.30.2/sources/"$N-$V$R".tar.bz2 "

RDEPEND="atk cairo dbus dbus-glib expat fontconfig freetype gcc gconf glib2 glibc gtk+ libICE libpng libSM libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender ncurses orbit pango pixman util-linux-ng vte zlib"
BDEPEND=" libgnome-dev startup-notification-dev atk-dev cairo-dev dbus-dev dbus-glib-dev expat-dev fontconfig-dev freetype-dev gcc-dev gconf-dev glib2-dev glibc-dev gtk+-dev libICE-dev libpng-dev libSM-dev libX11-dev libXau-dev libxcb-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXi-dev libXrandr-dev libXrender-dev ncurses-dev orbit-dev pango-dev pixman-dev util-linux-ng-dev vte-dev zlib-dev"
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-schemas-install"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	install -m755 "$FILES_PATH"/files/gnome-terminal.wrapper "$YPPATH_DEST"/usr/bin
	rm -fr "$YPPATH_DEST"/var/lib/scrollkeeper
	rm -fr "$YPPATH_DEST"/var/lib/log
}	

pbs_postinst() {
	gnome2_install_schema "/etc/gconf/schemas/gnome-terminal.schemas"
	gnome2_install_defaut_gconf "string" "/apps/gnome-terminal/profiles/Default/background_color"    "#000000000000"
	gnome2_install_defaut_gconf "float"  "/apps/gnome-terminal/profiles/Default/background_darkness" "0.5"
	gnome2_install_defaut_gconf "string" "/apps/gnome-terminal/profiles/Default/bold_color"          "#000000000000"
	gnome2_install_defaut_gconf "string" "/apps/gnome-terminal/profiles/Default/foreground_color"    "#AAAAAAAAAAAA"
	gnome2_install_defaut_gconf "string" "/apps/gnome-terminal/profiles/Default/cursor_shape"        "ibeam"
	gnome2_install_defaut_gconf "string" "/apps/gnome-terminal/profiles/Default/font"                "Bitstream Vera Sans Mono 11"
	gnome2_install_defaut_gconf "bool"   "/apps/gnome-terminal/profiles/Default/use_system_font"     "false"
	gnome2_install_defaut_gconf "bool"   "/apps/gnome-terminal/profiles/Default/use_theme_colors"    "false"
	gnome2_rarian_sk_update
	gnome2_desktop_database_update
	gnome2_gconfd_reload
}
