#
# Ylmf OS package build script
#

DESCRIPTION="The GNOME Terminal package contains the console"
HOMEPAGE="http://www.gnome.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
SRC_URI="ftp://ftp.gnome.org/pub/gnome/sources/$N/2.28/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" gconf gnome-doc-utils startup-notification vte"
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/gnome-terminal"

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	config+=" --prefix=$(pkg-config --variable=prefix ORBit-2.0)
	              --sysconfdir=/etc/gnome/2.28.2
		      --localstatedir=/var"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
