#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="HTML form validation, generation, and conversion"
HOMEPAGE="http://formencode.org"
LICENSE="PSF"
PACKAGER="StartOS Developers"
ARCH="any"

SRC_URI="http://pypi.python.org/packages/source/F/FormEncode/FormEncode-"$V".tar.gz"

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	#echo /usr/lib/python2.7/site-packages/FormEncode-"$V"-py2.6.egg >"$destdir"/usr/lib/python2.7/site-packages/$pkgname.pth"
}

