#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="HTML documentation for PostgreSQL"
HOMEPAGE="http://www.postgresql.org/"
LICENSE="custom:PostgreSQL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="ftp://ftp.postgresql.org/pub/source/v"$V"/postgresql-"$V".tar.bz2"
CHECKSUM="1cc388988e69bf75c6b55d59070100f6"

BDEPEND="krb5 libxml2 python perl tcl openssl"

pbs_unpack() {
    dounpack
}

pbs_patch() {
    dopatch postgresql-run-socket.patch
}

pbs_config() {
    config+="--datadir=/usr/share/postgresql 
             --with-krb5 
             --with-libxml 
             --with-openssl 
             --with-perl 
             --with-tcl 
             --with-pam 
             --with-system-tzdata=/usr/share/zoneinfo 
             --enable-nls 
             --enable-thread-safety"
    doconfig
}

pbs_build() {
    domake world
}

pbs_install() {
    make -C doc/src/sgml DESTDIR="$destdir" install-html
    chown -R root:root "$destdir"/usr/share/doc/postgresql/html/
    dodoc COPYRIGHT
    # clean up
    rmdir "$destdir"/usr/share/man/man{1,3,7}
    rmdir "$destdir"/usr/share/man
}

