#
# YLmf_OS package build script
#

DESCRIPTION="Perl wrappers for the GLib utility and Object libraries "
HOMEPAGE="http://search.cpan.org/~tsch/Glib-1.223/Glib.pm"
LICENSE="GPL PerlArtistic"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/Glib-"$V".tar.gz"

RDEPEND="perl glib2 gdk-pixbuf"
BDEPEND="extutils-depends extutils-pkgconfig"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
