#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl wrappers for the GLib utility and Object libraries "
HOMEPAGE="http://search.cpan.org/~tsch/Glib-1.223/Glib.pm"
LICENSE="GPL"
PRIORITY=""
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/Glib-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
        perl_cleanup
}
