#
# Ylmf OS package build script
#

DESCRIPTION="sina weibo client (AIR)"
HOMEPAGE="http://airweibo.sinaapp.com/"
REPO=""
LICENSE=""
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://airweibo.sinaapp.com/download/airweibo.air"

RDEPEND="adobe-air-sdk"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

NOTES=""

pbs_install() {
	docp      "$YPPATH_SOURCE"/airweibo.air  "$destdir"/usr/lib/"$N"
	dodesktop "sinaweibo-air.desktop"         "sinaweibo-air.png"
}

