#
# Ylmf OS package build script
#

DESCRIPTION="Screenlets are small owner-drawn applications"
HOMEPAGE="http://www.screenlets.org"
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="https://code.launchpad.net/screenlets/trunk/0.1.2/+download/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" gnome-keyring "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
