#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="I/O on in-core objects like strings/arrays"
HOMEPAGE="http://search.cpan.org/dist/$N"
LICENSE="GPL,PerlArtistic"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://www.cpan.org/authors/id/D/DS/DSKOLL/"$N-$V".tar.gz"
CHECKSUM="2e6a976cfa5521e815c1fdf4006982de"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}

