#
# YLmf_OS package build script
#

DESCRIPTION="A wrist friendly language for the CLI"
HOMEPAGE="http://boo.codehaus.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.novell.com/pub/mono/sources/"$N"/"$N-$V".tar.bz2"

RDEPEND="mono shared-mime-info"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

OPINION="nostrip"

pbs_unpack() {
        dounpack
}

pbs_config() {
	sed -i -e 's|/lib|/lib/mono|' extras/boo.pc.in
	config="--prefix=/usr --libdir=/usr/lib"
	doconfig
}

pbs_build() {
	domake VERBOSE=1
}

pbs_install() {
	domkinstall
}

