#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="perl module"
HOMEPAGE="http://search.cpan.org/~rjbs/Sub-Exporter-0.982/"
REPO=""
LICENSE="GPL-2"
PACKAGER="StartOS Developers"

SRC_URI="http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/Sub-Exporter-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
