#
# YLmf_OS package build script
#

DESCRIPTION="Google's Protocol Buffers -- an efficient method of encoding structured data"
HOMEPAGE="http://code.google.com/p/protobuf/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://protobuf.googlecode.com/files/"$N-$V$R".tar.bz2"

RDEPEND="gcc glibc zlib"
BDEPEND="gcc-dev glibc-dev zlib-dev"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--program-prefix="
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
