#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Remote desktop viewer use VNC protocol"
HOMEPAGE="http://www.gnome.org/projects/vinagre/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>
          chenqixing@ivali.com"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/$N/${V%.*}/$N-$V.tar.xz"
CHECKSUM="dec4b24de9c372cef3efc0d3e80514c85250e01ce01325d07a4e4e956b4a8f3c"

RDEPEND="libsecret gtk-vnc vte3 telepathy-glib avahi desktop-file-utils dconf shared-mime-info"
BDEPEND="docbook-xsl intltool rdesktop openssh itstool"
RECOMMENDED=""
OPTIONAL="openssh: SSH plugin
          rdesktop: RDP plugin"

NOTES="* gtk-vnc must be compiled with the argument '--with-gtk=3.0' to the configure script
       * vte3 must be compiled with the argument '--with-gtk=3.0' to the configure script"

INSTALL="$N.install"

pbs_unpack() {
    dounpack
}

pbs_config() {
	config+="--disable-schemas-install --enable-rdp --disable-spice"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
    dodoc COPYING
}

