. /usr/lib/ybs/funcs

files=" /etc/gconf/schemas/python-plugin-properties.schemas
	/etc/gconf/schemas/preferences.schemas
	/etc/gconf/schemas/file-manager.schemas
	/etc/gconf/schemas/anjuta-terminal-plugin.schemas
	/etc/gconf/schemas/anjuta-symbol-db.schemas
	/etc/gconf/schemas/anjuta-message-manager-plugin.schemas
	/etc/gconf/schemas/anjuta-language-cpp-java.schemas
	/etc/gconf/schemas/anjuta-editor-sourceview.schemas
	/etc/gconf/schemas/anjuta-document-manager.schemas
	/etc/gconf/schemas/anjuta-debug-manager.schemas
	/etc/gconf/schemas/anjuta-cvs-plugin.schemas
	/etc/gconf/schemas/anjuta-build-basic-autotools-plugin.schemas"

post_install() {
	gnome2_install_schema $files
	gnome2_icon_cache_update /usr/share/icons/gnome /usr/share/icons/hicolor
	gnome2_desktop_database_update
	gnome2_mime_database_update
	glib_compile_schemas
	gnome2_gconfd_reload
}

pre_remove() {
	gnome2_uninstall_schema $files
}

post_remove() {
	gnome2_icon_cache_update /usr/share/icons/gnome /usr/share/icons/hicolor
	gnome2_desktop_database_update
	gnome2_mime_database_update
	glib_compile_schemas
	gnome2_gconfd_reload
}

post_upgrade() {
	post_remove
}

post_downgrade() {
	post_remove
}

