#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Advanced Linux Sound Architecture Library"
HOMEPAGE=" http://www.alsa-project.org/"
 
SRC_URI="ftp://ftp.alsa-project.org/pub/lib/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
