#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A proven industry-strength PDF generating solution"
HOMEPAGE="http://www.reportlab.org/rl_toolkit.html"
LICENSE="custom"
PACKAGE="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://www.reportlab.com/ftp/reportlab-$V.tar.gz"

RDEPEND="freetype python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodoc LICENSE.txt
}
