#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="YAML parser and emitter in C++, written around the YAML 1.2 spe"
HOMEPAGE="http://code.google.com/p/yaml-cpp"
LICENSE="MIT"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.co>"

SRC_URI="http://yaml-cpp.googlecode.com/files/"$N-$V".tar.gz"
CHECKSUM="9aa519205a543f9372bf4179071c8ac6"

RDEPEND="gcc-libs"
RECOMMENDED=""
BDEPEND="cmake"
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    doconfig -DBUILD_SHARED_LIBS=ON
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
