#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="PHP-GTK is an extension for the PHP programming language that implements language bindings for GTK+. "
COMMENTS="It provides an object-oriented interface to GTK+ classes and functions and greatly simplifies writing client-side cross-platform GUI applications."
HOMEPAGE="http://gtk.php.net/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://gtk.php.net/distributions/"$N-$V".tar.gz"
CHECKSUM="d57ce885f32749320765e01c079e113b"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
    dounpack
}

pbs_config() {
    ./buildconf
    config+=""
    doconfig
}

pbs_build() {
    make
}

pbs_install() {
    domkinstall
}

