#
# Ylmf OS package build script
#

DESCRIPTION="Simple Direct Media Layer"
HOMEPAGE="http://www.libsdl.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://www.libsdl.org/release/SDL-"$V".tar.gz"

RDEPEND="alsa-lib audiofile directfb glibc libICE libSM libX11 libXau libxcb libXdmcp libXt nas util-linux-ng zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

