#
# YLmf_OS package build script
#

DESCRIPTION="Simple Direct Media Layer"
HOMEPAGE="http://www.libsdl.org/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://www.libsdl.org/release/SDL-"$V$R".tar.gz"

RDEPEND="alsa-lib audiofile directfb esound glibc zlib"
BDEPEND="     "
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc docs/html/*.html
}
