#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="C# GLib implementation of D-Bus"
HOMEPAGE="https://github.com/mono/dbus-sharp"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="https://github.com/downloads/mono/dbus-sharp/"$N-$V".tar.gz"

RDEPEND="dbus-sharp"
RECOMMENDED=""
BDEPEND="pkgconfig"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

