#
# YLmf_OS package build script
#

DESCRIPTION="dbus-sharp-glib"
HOMEPAGE="C# GLib implementation of D-Bus"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="https://github.com/downloads/mono/dbus-sharp/"$N-$V".tar.gz"

RDEPEND="dbus-sharp"
RECOMMENDED=""
BDEPEND="pkgconfig"

pbs_unpack() {
        dounpack
}

pbs_config() {
	export MONO_SHARED_DIR="${PWD}/.wabi"
	mkdir -p "${MONO_SHARED_DIR}"
	
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

