#
# Ylmf OS package build script
#

DESCRIPTION="hdparm - get/set ATA/SATA drive parameters under Linux"
HOMEPAGE="http://sourceforge.net/projects/hdparm/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://nchc.dl.sourceforge.net/project/hdparm/hdparm/hdparm-9.37.tar.gz"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

