#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="libwps is a Microsoft Works file format import filter based on top of the libwpd"
HOMEPAGE="http://sourceforge.net/projects/libwps/"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://downloads.sourceforge.net/project/$N/$N/$N-$V/$N-$V.tar.bz2"
CHECKSUM="d197bd6211669a2fa4ca648faf04bcb1"

RDEPEND="libwpd"
BDEPEND="boost"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--disable-static --disable-werror"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
