#
# Ylmf OS package build script
#

DESCRIPTION="Common files for development of Gnome package"
HOMEPAGE="http://www.gnome.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/"$N"/2.28/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
