#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="C++ bindings for the gdl library"
HOMEPAGE="http://git.gnome.org/browse/gdlmm"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/$N/3.3/$N-$V.tar.xz"
CHECKSUM="cf3253be052737332b2b6e9dbd6f62d79cbc3f3398497158c0099dbc45741a46"

RDEPEND="gdl gtkmm"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
    dounpack
}

pbs_patch() {
    # Fix build with gdl 3.6
    dopatch 0001-Don-t-wrap-gdl_dock_layout_get_layouts_ui.patch
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    make
}

pbs_install() {
    domkinstall
    dodoc COPYING
}

