#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A graphical diff and merge tool"
HOMEPAGE="http://meldmerge.org/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/"$N"/1.5/"$N-$V".tar.xz"
CHECKSUM="30e70ecd0689f2ae29a10656cdf33056"

RDEPEND="pygtk"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_build() {
    make prefix=/usr
}

pbs_install() {
    make prefix=/usr DESTDIR="${destdir}" install
}

