#
# YLmf_OS package build script
#

DESCRIPTION="encrypt stuff simply "
HOMEPAGE="http://search.cpan.org/~kasei/Crypt-Simple-0.06/"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://mirrors.xmu.edu.cn/CPAN/authors/id/K/KA/KASEI/Crypt-Simple-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
        export PERL_MM_USE_DEFAULT=1
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

