#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="encrypt stuff simply "
HOMEPAGE="http://search.cpan.org/~kasei/Crypt-Simple-0.06/"
REPO=""
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://mirrors.xmu.edu.cn/CPAN/authors/id/K/KA/KASEI/Crypt-Simple-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

