#
# YLmf_OS package build script
#

DESCRIPTION="Spellchecker wrapping library"
HOMEPAGE="http://www.abisource.com/enchant/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"
 
SRC_URI="http://www.abisource.com/downloads/"$N"/"$V$R"/"$N-$V$R".tar.gz"

RDEPEND="aspell dbus dbus-glib gcc glib2 gdk-pixbuf glibc"
BDEPEND="     "
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
