#
# Ylmf OS package build script
#

DESCRIPTION="Liboobs is a wrapping library to the System Tools Backends."
HOMEPAGE="http://www.gnome.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.32/2.32.2/sources/"$N-$V".tar.bz2"

RDEPEND="dbus dbus-glib gcc-lib glib2 glibc hal libsmbios"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--without-hal"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README
}

