#
# YLmf_OS package build script
#

DESCRIPTION="Liboobs is a wrapping library to the System Tools Backends."
HOMEPAGE="http://www.gnome.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.32/2.32.2/sources/"$N-$V".tar.bz2"

RDEPEND="dbus dbus-glib gcc glib2 glibc hal libsmbios"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--without-hal"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README
}

