#
# YLmf_OS package build script
#

DESCRIPTION="Liboobs is a wrapping library to the System Tools Backends."
HOMEPAGE="http://www.gnome.org"
REPO=""
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.30/2.30.2/sources/"$N-$V$R".tar.bz2"

RDEPEND="dbus dbus-glib glib2 glibc hal"
BDEPEND="system-tools-backends-dev dbus-dev dbus-glib-dev glib2-dev glibc-dev hal-dev"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README
}
