#
# Ylmf OS package build script
#

DESCRIPTION="GTK+ & GNOME Accessibility Toolkit"
HOMEPAGE="http://library.gnome.org/devel/atk/stable/"
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/mobile/2.30/2.30.2/sources/"$N-$V$R".tar.bz2"

RDEPEND="glib2 gdk-pixbuf glibc"
BDEPEND=" "

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
