#
# Ylmf OS package build script
#

DESCRIPTION="GTK+ & GNOME Accessibility Toolkit"
HOMEPAGE="http://library.gnome.org/devel/atk/stable/"
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

REPO="testing"

SRC_URI="http://ftp.acc.umu.se/pub/gnome/sources/"$N"/2.2/"$N-$V".tar.xz"
CHECKSUM="8b22f0e7803dd3734c676ccd68ea999ff1156ca49d99c3de5c1d269ad0c3739d"

RDEPEND="glib2 glibc libffi"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

