#
# YLmf_OS package build script
#

DESCRIPTION="GTK+ & GNOME Accessibility Toolkit"
HOMEPAGE="http://library.gnome.org/devel/atk/stable/"
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/mobile/2.32/2.32.1/sources/"$N-$V".tar.bz2"

RDEPEND="glib2 glibc"
BDEPEND=" "

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

