#
# Ylmf OS package build script
#

DESCRIPTION="Python bindings for the Qt toolkit"
HOMEPAGE="http://pypi.python.org/pypi/PyQt"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.riverbankcomputing.com/static/Downloads/PyQt4/PyQt-x11-gpl-4.8.4.tar.gz"

RDEPEND="sip"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	#python configure.py --confirm-license --qsci-api
	#find -name 'Makefile' | xargs sed -i 's|-Wl,-rpath,/usr/lib||g;s|-Wl,-rpath,.* ||g'
	#make
	### Python2 version ###
	python configure.py --confirm-license -v /usr/share/sip --qsci-api
	find -name 'Makefile' | xargs sed -i 's|-Wl,-rpath,/usr/lib||g;s|-Wl,-rpath,.* ||g'
}

pbs_build() {
	domake
}

pbs_install() {
	#INSTALL_ROOT is needed for the QtDesigner module, the other Makefiles use DESTDIR
	domkinstall INSTALL_ROOT="$destdir"
}

