#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Telepathy Python base classes for use in connection managers, and proxy classes for use in clients."
HOMEPAGE="http://telepathy.freedesktop.org/"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@iliva.com>"
GROUP="python"
YARCH="any"

SRC_URI="http://telepathy.freedesktop.org/releases/telepathy-python/telepathy-python-$V.tar.gz"

RDEPEND="py-dbus"
BDEPEND="python telepathy-glib libxslt"
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config=${config/--enable-shared/}
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
