#
# YLmf_OS package build script
#

DESCRIPTION="Internationalization Tool Collection"
HOMEPAGE=" http://edge.launchpad.net/intltool/ "
 
SRC_URI="http://ftp.gnome.org/pub/gnome/sources/$N/0.40/$N-$V.tar.bz2"

RDEPEND="xml-parser"
BDEPEND=""

pbs_unpack()
{
        dounpack
}

pbs_config()
{
	
	doconfig
}

pbs_build()
{
	domake
}

pbs_check()
{
	make check
}

pbs_install()
{
	domkinstall
	mkdir -p "$destdir"/usr/share/doc/$N-$V
	install -m644 -D doc/I18N-HOWTO \
	    "$destdir"/usr/share/doc/$N-$V/I18N-HOWTO
}
