#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python binding to the GUDev systemd helper library"
HOMEPAGE="http://github.com/nzjrs/python-gsystemd"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="git://git.debian.org/collab-maint/python-gsystemd.git"

RDEPEND="systemd"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

