#
# Ylmf OS package build script
#

DESCRIPTION="A free library for encoding X264/AVC streams"
HOMEPAGE="http://www.videolan.org/developers/x264.html"
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="ftp://ftp.videolan.org/pub/videolan/"$N"/snapshots/"$N"-snapshot-"$V$R"-2245.tar.bz2"

BDEPEND="dev-lang/yasm"
RDEPEND="${BDEPEND}"
RECOMMENDED="dev-lang/yasm"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
