#
# Ylmf OS package build script
#

DESCRIPTION="A free library for encoding X264/AVC streams"
HOMEPAGE="http://www.videolan.org/developers/x264.html"
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://git.videolan.org/"$N".git"

RDEPEND="alsa-lib ffmpeg glibc jack-audio-connection-kit libva zlib"
BDEPEND="yasm"
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

