#
# Ylmf OS package build script
#

DESCRIPTION="VNC Client for the GNOME Desktop"
HOMEPAGE="http://www.gnome.org/projects/vinagre/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.32/2.32.1/sources/"$N-$V".tar.bz2"

RDEPEND="atk avahi cairo cyrus-sasl dbus dbus-glib expat fontconfig freetype gail gcc gconf gdbm gdk-pixbuf glib2 glibc gnome-panel gnome-vfs gnutls gtk+ gtk-vnc libart_lgpl libbonobo libbonoboui libcanberra libgcrypt libgnome libgnomecanvas libgnome-keyring libgpg-error libICE libogg libpng libSM libtasn1 libtool libvorbis libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libxml2 libXrandr libXrender ncurses openssl orbit pango pixman popt tdb util-linux-ng vte zlib"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-schemas-install 
	             --enable-ssh 
		     --enable-telepathy=no"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc AUTHORS COPYING NEWS README
	
	# Keep clean for rarian
	rm -fr "$destdir"/var/lib/scrollkeeper
	rm -fr "$destdir"/var/lib/log
}

