#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="VNC Client for the GNOME Desktop"
HOMEPAGE="http://www.gnome.org/projects/vinagre/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.32/2.32.1/sources/"$N-$V".tar.bz2"
CHECKSUM="28bfc70a816bc3f1e71ada82e260c39ee2dac693cb7859323b06c8b1452a39f4"

RDEPEND="atk avahi cairo cyrus-sasl dbus dbus-glib expat fontconfig freetype gail gcc-lib gconf gdbm gdk-pixbuf glib2 glibc gnome-panel gnome-vfs gnutls gtk+ gtk-vnc libart_lgpl libbonobo libbonoboui libcanberra libffi libgcrypt libgnome libgnomecanvas libgnome-keyring libgpg-error libICE libogg libpng libSM libtasn1 libtool libvorbis libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXinerama libxml2 libXrandr libXrender ncurses openssl orbit pango pixman popt tdb telepathy-glib util-linux-ng vte zlib"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=" --disable-schemas-install 
	          --enable-ssh "
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

