#
# YLmf_OS package build script
#

DESCRIPTION="VNC Client for the GNOME Desktop"
HOMEPAGE="http://www.gnome.org/projects/vinagre/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.30/2.30.2/sources/"$N-$V$R".tar.bz2"

RDEPEND="pixman directfb libpng libxcb libXrender expat orbit eggdbus libgcrypt libgpg-error zlib
	 libxcb libXau libXdmcp gconf libgnome-keyring libxml2 dbus-glib dbus libX11 avahi gtk+ pango cairo
	 freetype fontconfig gdbm libXi libXrandr libXcursor libXcomposite libXext libXdamage libXfixes"
BDEPEND=" gconf gtk-vnc avahi vte libxml2"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-schemas-install --enable-ssh --enable-telepathy=no"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS COPYING NEWS README
	# keep clean for rarian
	rm -fr "$YPPATH_DEST"/var/lib/scrollkeeper
	rm -fr "$YPPATH_DEST"/var/lib/log
}

pbs_postinst() {
	gnome2_install_schema "/etc/gconf/schemas/vinagre.schemas"
	gnome2_rarian_sk_update
	gnome2_desktop_database_update
	gnome2_icon_cache_update "hicolor"
	gnome2_gconfd_reload
}
