#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="PyPy is a fast, compliant alternative implementation of the Python language"
HOMEPAGE="http://pypy.org/"
LICENSE="custom/MIT"
PACKAGER="StartOS Developers"

SRC_URI="https://bitbucket.org/pypy/pypy/get/release-"$V".tar.bz2"
CHECKSUM="661be06978fdc907d84f0ee1f1228c8b"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""

pbs_unpack() {
        dounpack
}

pbs_build() {
    cd pypy/translator/goal
    python translate.py -Ojit
}

pbs_install() {
    install -Dm755 pypy-c        "$PKGDIR"/opt/pypy/pypy-c
    cd "$SRCDIR"
    docp lib-python/2.7          "$PKGDIR"/opt/pypy/lib-python/
    docp lib-python/modified-2.7 "$PKGDIR"/opt/pypy/lib-python/
    docp lib_pypy                "$PKGDIR"/opt/pypy/
    docp include                 "$PKGDIR"/opt/pypy/
    doln /opt/pypy/pypy-c        "$PKGDIR"/usr/bin/pypy
}

