--- Makefile.in	2008-07-05 00:35:03.000000000 +0000
+++ Makefile.in	2012-06-18 05:51:58.849270819 +0000
@@ -25,7 +25,7 @@
 RANLIB=@RANLIB@
 
 # Installation paths
-prefix=@prefix@
+prefix=$(DESTDIR)/@prefix@
 exec_prefix=@exec_prefix@
 bindir=@bindir@
 libdir=@libdir@
@@ -99,6 +99,7 @@
 	[ -d libieee1284 ] && (cd libieee1284 ; make clean) || true
 
 install: all
+	mkdir -p $(bindir)
 	$(INSTALL) ijs_server_epsonepl$(EXE) -c $(bindir)/ijs_server_epsonepl$(EXE)
 
 uninstall:
