#
# Ylmf OS package build script
#

DESCRIPTION="A fork from google pinyin on android ibus wrapper"
HOMEPAGE="http://code.google.com/p/libgooglepinyin"
LICENSE="Apache License 2.0"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://libgooglepinyin.googlecode.com/files/"$N-$V$R".tar.bz2"

RDEPEND="libgooglepinyin"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

