#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="C++ string template engine based on the Django template system"
HOMEPAGE="http://www.gitorious.org/grantlee/pages/Home"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://downloads.grantlee.org/"$N-$V".tar.gz"
CHECKSUM="0622ed30630a44b5fac0bfa7e176d3fe"

RDEPEND="expat fontconfig freetype gcc-lib glib2 glibc libffi libICE libpng libSM libX11 libXau libxcb libXdmcp libXext libXrender qt-core util-linux-ng zlib"
RECOMMENDED=""
BDEPEND="cmake"
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig -DCMAKE_BUILD_TYPE=Release
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

