#
# YLmf_OS package build script
#

DESCRIPTION="X.Org Bigelow & Holmes TrueType fonts"
HOMEPAGE="http://www.x.org/wiki/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.x.org/releases/X11R7.6/src/font/"$N-$V".tar.bz2"

RDEPEND=""
BDEPEND="mkfontdir mkfontscale"

pbs_unpack() {	
        dounpack
}

pbs_config() {
	config+="--with-fontrootdir=/usr/share/fonts"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

