#
# Ylmf OS package build script
#

DESCRIPTION="text based web browser."
HOMEPAGE="http://lynx.isc.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://lynx.isc.org/release/"$N$V".tar.bz2"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--with-zlib --with-bzlib"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
