#
# YLmf_OS package build script
#

DESCRIPTION="text based web browser."
HOMEPAGE="http://lynx.isc.org/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://lynx.isc.org/release/"$N$V".tar.bz2"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--with-zlib --with-bzlib"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
