#
# YLmf_OS package build script
#

DESCRIPTION="Controls host and/or user access to a running X server."
HOMEPAGE="http://xorg.freedesktop.org/"
REPO=""
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="http://www.x.org/releases/X11R7.6/src/app/"$N-$V$R".tar.bz2"

RDEPEND="glibc libX11 libXau libxcb libXdmcp libXmu"
BDEPEND="     "

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
