#
# Ylmf OS package build script
#

DESCRIPTION="Simple and Efficient Reading/Writing/Modifying of Complete Files"
HOMEPAGE="http://search.cpan.org/~uri/File-Slurp-9999.19/"
LICENSE="GPL PerlArtistic"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://cpan.wenzk.com/authors/id/U/UR/URI/File-Slurp-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

