#
# Ylmf OS package build script
#

DESCRIPTION="High performance fully compliant Java XML parser"
HOMEPAGE="http://xml.apache.org/xerces2-j"
REPO=""
LICENSE="APACHE"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://www.apache.org/dist/xerces/j/Xerces-J-bin.2.11.0.tar.gz"

RDEPEND="jdk"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_install() {
	. /etc/profile.d/jdk.sh
	rm -f xercesSamples.jar
	docp *.jar "$destdir"/"$JAVA_HOME"/
}

