. /usr/lib/ybs/funcs

files="/etc/gconf/schemas/simple-scan.schemas"

post_install() {
    gnome2_install_schema $files
    gnome2_rarian_sk_update
    gnome2_desktop_database_update
    gnome2_icon_cache_update
}

pre_remove() {
    gnome2_uninstall_schema $files
}

post_remove() {
    gnome2_rarian_sk_update
    gnome2_desktop_database_update
    gnome2_icon_cache_update
}

post_upgrade() {
    post_remove
}

post_downgrade() {
    post_remove
}
                
