#
# YLmf_OS package build script
#

DESCRIPTION="An Interactive Data Language compatible incremental compiler"
HOMEPAGE="http://gnudatalanguage.sourceforge.net/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/$N/${V%.*}/$N-$V.tar.xz"
CHECKSUM="e772319f1b133047f54e3c1b7e95a718168071cfef972f981337f6bf570ddf1c"

RDEPEND="gtk3 libxml2"
RECOMMENDED=""
BDEPEND="gtk-doc intltool gobject-introspection"
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--disable-static"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

