#
# Ylmf OS package build script
#

DESCRIPTION="C++ interface for glib2"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/sources/glib2mm/2.22/$N-$V.tar.bz2"

RDEPEND="glib2 gdk-pixbuf libsigc++"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	config+=" --prefix=/usr "
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
