#
# YLmf_OS package build script
#

DESCRIPTION="C++ interface for glib22"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"
 
SRC_URI=" http://ftp.gnome.org/pub/gnome/sources/"$N"/2.24/"$N-$V$R".tar.bz2 "

RDEPEND="zlib libsigc++ "
BDEPEND="${RDEPEND} glib2 libsigc++"
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/glib2mm"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-documentation"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
