#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="C++ interface for glib2"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="LGPL"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/"$N"/2.30/"$N-$V".tar.xz"
CHECKSUM="69582b584666cab1dc4253faffee548054730bc058e28466871e6a954d7ff897"

RDEPEND="glib2 libsigc++"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

