#
# YLmf_OS package build script
#

DESCRIPTION="C++ interface for glib2"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/sources/glib2mm/2.22/$N-$V.tar.bz2"

RDEPEND="glib2 gdk-pixbuf libsigc++"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	YPB_CONFIG+=" --prefix=/usr "
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
