#
# Ylmf OS package build script
#

DESCRIPTION="Perl/CPAN Module Authen::SASL : SASL authentication framework"
HOMEPAGE="http://search.cpan.org/dist/Authen-SASL"
LICENSE="GPL PerlArtistic"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://cpan.communilink.net/authors/id/G/GB/GBARR/Authen-SASL-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

