#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Mono bindings for GLib’s GKeyFile"
HOMEPAGE="http://github.com/mono/gkeyfile-sharp"
LICENSE="LGPL"
PACKAGER="StartOS Developers"
YARCH="any"

SRC_URI="git://github.com/mono/gkeyfile-sharp.git"

RDEPEND="gtk-sharp"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	make
}

pbs_install() {
	domkinstall
}

