#
# YLmf_OS package build script
#

DESCRIPTION="Mono bindings for GLib’s GKeyFile"
HOMEPAGE="http://github.com/mono/gkeyfile-sharp"
REPO=""
LICENSE="LGPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://github.com/mono/gkeyfile-sharp.git"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	make
}

pbs_install() {
	domkinstall
}
