#
# Ylmf OS package build script
#

DESCRIPTION="Mono bindings for GLib’s GKeyFile"
HOMEPAGE="http://github.com/mono/gkeyfile-sharp"
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="git://github.com/mono/gkeyfile-sharp.git"

RDEPEND="gtk-sharp"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	make
}

pbs_install() {
	domkinstall
}

