--- Makefile	2011-10-24 15:12:29.528760168 +0800
+++ Makefile.new	2011-10-24 15:12:52.549217007 +0800
@@ -729,7 +729,7 @@
 %.schemas:   %.schemas.in   $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; LC_ALL=C $(INTLTOOL_MERGE) -s -u -c $(top_builddir)/po/.intltool-merge-cache $(top_srcdir)/po $< $@
 
 install-data-local:
-        if test -z "$(DESTDIR)" ; then \
+	if test -z "$(DESTDIR)" ; then \
           for p in $(schemas_DATA) ; do \
             GCONF_CONFIG_SOURCE=$(GCONF_SCHEMA_CONFIG_SOURCE) $(GCONFTOOL) --makefile-install-rule $(srcdir)/$$p ; \
           done \
