#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="X C-language Bindings protocol headers"
HOMEPAGE="http://xcb.freedesktop.org/"
REPO=""
LICENSE=""
PACKAGER="StartOS Developers"

SRC_URI="http://xcb.freedesktop.org/dist/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
