#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="a wrapper around the various text markup languages, such as Markdown and reStructuredText"
HOMEPAGE="https://pypi.python.org/pypi/Markups"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"
YARCH="any"

SRC_URI="https://pypi.python.org/packages/source/M/Markups/Markups-$V.tar.gz"
CHECKSUM="3cc6587285337d8ac77331dd1c640f7e"

RDEPEND="python"
RECOMMENDED=""
BDEPEND="py-distribute"
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
