#
# YLmf_OS package build script
#

DESCRIPTION="A Python Interface to GStreamer"
HOMEPAGE="http://gstreamer.freedesktop.org"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://gstreamer.freedesktop.org/src/"$N"/"$N-$V$R".tar.bz2"

RDEPEND="glib2 gdk-pixbuf glibc gst-plugins-base gstreamer libxml2 python zlib"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-static"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}


