#
# YLmf_OS package build script
#

DESCRIPTION="A graphics library for fast image creation"
HOMEPAGE="http://libgd.org/"
 
SRC_URI="http://www.libgd.org/releases/"$N-$V"RC1.tar.bz2"

RDEPEND="fontconfig libjpeg-turbo libpng zlib freetype libXpm libXt"
BDEPEND="${RDEPEND}"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
