#
# Ylmf OS package build script
#

DESCRIPTION="A graphics library for fast image creation"
HOMEPAGE="http://libgd.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://www.libgd.org/releases/"$N-$V"RC1.tar.bz2"

RDEPEND="expat fontconfig freetype glibc libjpeg-turbo libpng libX11 libXau libxcb libXdmcp libXpm zlib"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

