#
# YLmf_OS package build script
#

DESCRIPTION="A font management application for the GNOME desktop"
HOMEPAGE="http://code.google.com/p/font-manager/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://font-manager.googlecode.com/files/"$N-$V$R".tar.bz2"

RDEPEND="gtk+"
BDEPEND=" "
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

