#
# Ylmf OS package build script
#

DESCRIPTION="A free implementation of the unicode bidirectional algorithm"
HOMEPAGE="http://fribidi.org/"
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://fribidi.org/download/"$N-$V".tar.gz"
CHECKSUM="626db17d2d99b43615ad9d12500f568a"

RDEPEND="glibc"
BDEPEND=" "

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

