#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A free implementation of the unicode bidirectional algorithm"
HOMEPAGE="http://fribidi.org/"
LICENSE="LGPL"
PACKAGER="StartOS Developers"

SRC_URI="http://fribidi.org/download/"$N-$V".tar.gz"
CHECKSUM="626db17d2d99b43615ad9d12500f568a"

RDEPEND="glibc"
BDEPEND=" "

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

