#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="C# implementation of D-Bus"
HOMEPAGE="http://github.com/mono/dbus-sharp/"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="https://github.com/downloads/mono/"$N"/"$N-$V".tar.gz"

RDEPEND="mono"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodoc COPYING
}    

