#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An HTML library for GTK"
HOMEPAGE="http://www.gnome.org"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/$N/2.11/$N-$V.tar.bz2"
CHECKSUM="a1d1a197dcff8c4571659deef5495e24"

RDEPEND="gtk2 libxml2"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}


