#
# YLmf_OS package build script
#

DESCRIPTION="A C++ library that lets developers create applications"
HOMEPAGE="http://wxwidgets.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://downloads.sourceforge.net/project/wxwindows/"$V"/"$N-$V".tar.bz2"

RDEPEND="atk cairo expat fontconfig freetype gcc gdk-pixbuf glib2 glibc gtk+ libICE libjpeg-turbo libpng libSM libtiff libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXinerama libXrandr libXrender libXxf86vm pango pixman util-linux-ng wxGTK zlib"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--enable-unicode"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

