#
# YLmf_OS package build script
#

DESCRIPTION="A C++ library that lets developers create applications"
HOMEPAGE="http://wxwidgets.org/"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://downloads.sourceforge.net/project/wxwindows/"$V$R"/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND="${RDEPEND} "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--enable-unicode"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
