#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Libraries/utilities to handle ELF objects (drop in replacement for libelf)"
HOMEPAGE="https://fedorahosted.org/elfutils/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="https://fedorahosted.org/releases/e/l/"$N"/"$V"/"$N-$V".tar.bz2"
CHECKSUM="289a146182bc29f0236eaa15d8ebdf98"

RDEPEND="bzip2 gcc-lib glibc xz-utils zlib"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT="libelf"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--program-prefix="eu-""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

