#
# Ylmf OS package build script
#

DESCRIPTION="converting Perl structures to strings and back.  "
HOMEPAGE="http://search.cpan.org/~ilyaz/FreezeThaw-0.5001/"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://mirrors.163.com/cpan/authors/id/I/IL/ILYAZ/modules/FreezeThaw-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
