#
# YLmf_OS package build script
#

DESCRIPTION="converting Perl structures to strings and back.  "
HOMEPAGE="http://search.cpan.org/~ilyaz/FreezeThaw-0.5001/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://mirrors.163.com/cpan/authors/id/I/IL/ILYAZ/modules/FreezeThaw-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
