#
# YLmf_OS package build script
#

DESCRIPTION="GNU Unifont - a Pan-Unicode X11 bitmap iso10646 font"
HOMEPAGE="http://unifoundry.com/unifont.html"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://unifoundry.com/"$N-$V".ttf.gz"

RDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_install() {
	cp "$YPPATH_SOURCE"/"$N-$V".ttf.gz .
	gunzip "$N-$V".ttf.gz
	ypkg_docp unifont-5.1.20080907.ttf "$YPPATH_DEST"/usr/share/fonts/unifont
}

