#
# YLmf_OS package build script
#

DESCRIPTION="Basepack of plugins for gstreamer"
HOMEPAGE="http://gstreamer.net/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/"$N"/0.10/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" gst-plugins-base gconf libsoup"
RECOMMENDED="gconf libsoup libcddb  taglib"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
