#
# YLmf_OS package build script
#

DESCRIPTION="A low-latency audio server"
HOMEPAGE="http://jackaudio.org/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://jackaudio.org/downloads/"$N-$V$R".tar.gz"

RDEPEND="glibc ncurses readline"
BDEPEND="${RDEPEND} "
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS COPYING README
}
