#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="guess media type for a file or a URL  "
HOMEPAGE="http://search.cpan.org/"
REPO=""
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://cpan.communilink.net/authors/id/G/GA/GAAS/LWP-MediaTypes-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
