#
# Ylmf OS package build script
#

DESCRIPTION="A lightweight, speed optimized color management engine"
HOMEPAGE="http://www.littlecms.com/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://downloads.sourceforge.net/project/"$N"/"$N"/"$V"/"$N-$V".tar.gz"

RDEPEND="glibc libjpeg-turbo libtiff zlib"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

