#
# YLmf_OS package build script
#

DESCRIPTION="A lightweight, speed optimized color management engine"
COMMENTS=""
HOMEPAGE="http://www.littlecms.com/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://downloads.sourceforge.net/project/"$N"/"$N"/"$V"/"$N-$V".tar.gz"

RDEPEND="glibc libjpeg-turbo libtiff zlib"
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

