#
# YLmf_OS package build script
#

DESCRIPTION="Tools to deal with shar archives"
HOMEPAGE="http://www.gnu.org/software/sharutils/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"
 
SRC_URI="ftp://ftp.gnu.org/gnu/"$N"/REL-4.7/"$N-$V$R".tar.bz2"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

