#
# Ylmf OS package build script
#

DESCRIPTION="library for multiple-precision floating-point computations with exact rounding"
HOMEPAGE="http://www.mpfr.org"
LICENSE="LGPL" 
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.mpfr.org/"$N-$V"/"$N-$V".tar.bz2"

RDEPEND="glibc gmp"
BDEPEND=" "

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--enable-thread-safe"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

