#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="library for multiple-precision floating-point computations with exact rounding"
HOMEPAGE="http://www.mpfr.org"
LICENSE="LGPL" 
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://www.mpfr.org/mpfr-current/"$N-$V".tar.xz"
CHECKSUM="91d51c41fcf2799e4ee7a7126fc95c17"

RDEPEND="gmp"
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--enable-thread-safe"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

