#
# YLmf_OS package build script
#

DESCRIPTION="library for multiple-precision floating-point computations with exact rounding"
HOMEPAGE="http://www.mpfr.org"
 
SRC_URI="http://www.mpfr.org/"$N-$V$R"/"$N-$V$R".tar.bz2"

RDEPEND="glibc gmp"
BDEPEND=" "

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--enable-thread-safe"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
