#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A Perl wrapper for SDL"
HOMEPAGE="http://search.cpan.org/SDL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="LGPL"
GROUP="perl"

SRC_URI="http://search.cpan.org/CPAN/authors/id/J/JT/JTPALMER/SDL-$V.tar.gz"

RDEPEND="mesa perl sdl-ttf sdl-mixer sdl-pango perl-alien-sdl perl-tie-simple sdl-gfx sdl-image sdl-net smpeg"
BDEPEND="perl-yaml perl-test-most"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    # Perl selects the proper CFLAGS set for binary modules
    unset CFLAGS
    # install module in vendor directories
    perl Build.PL installdirs=vendor
}    

pbs_build() {
    perl Build
}

pbs_install() {
    perl Build install destdir="$PKGDIR"
    perl_cleanup
}
