#
# YLmf_OS package build script
#

DESCRIPTION="Boost Libraries for C++"
HOMEPAGE="http://www.boost.org/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI=" http://nchc.dl.sourceforge.net/project/"$N"/"$N"/"$V$R"/"${N}"_1_42_0.tar.bz2 "

RDEPEND="gcc glibc zlib"
BDEPEND="gcc-dev glibc-dev zlib-dev"
RECOMMENDED=""

NOTES="Apply Hotfixes from:
http://svn.boost.org/trac/boost/wiki/ReleasePractices/HotFixes"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	# This is the python we build against:
	PYTHON_VERSION=$(python -c 'import sys; print sys.version[:3]')
	PYTHON_FLAGS="-sPYTHON_ROOT=/usr -sPYTHON_VERSION=$PYTHON_VERSION"
	# First build bjam, the boost build system:
	cd tools/jam/src
	CFLAGS="$CFLAGS -fno-strict-aliasing" CC=gcc ./build.sh cc
	cd -
	BJAM=$(find tools/jam/src/ -name bjam -a -type f)
	# Create build subdirectory
	mkdir obj
	# Change the build options from 'minimal' to what we want, since adding
 	# "-sBUILD=<optimization>speed <inlining>full <threading>single/multi
	# <link>shared <runtime-link>shared" to $BJAM command no longer seems to work.
	FLAGS="<threading>multi <threading>single <optimization>speed <inlining>full"
	sed -i "s/    <threading>multi/    $FLAGS/" Jamroot
	# Disable static libraries ( the only software that *requires* the static libs,
	# is Microsoft's CW compiler (CW or Comega is an experimental language which
	# extends C# )
	sed -i "s/<link>shared <link>static/<link>shared/" Jamroot
}

pbs_build() {
	# Next, we build boost using bjam
	$BJAM \
	  release \
	  "-sNO_COMPRESSION=0" \
	  "-sZLIB_INCLUDE=/usr/include" \
	  "-sZLIB_LIBPATH=/usr/lib" \
	  "-sBZIP2_INCLUDE=/usr/include" \
	  "-sBZIP2_LIBPATH=/usr/lib" \
	  "-sEXPAT_INCLUDE=/usr/include" \
	  "-sEXPAT_LIBPATH=/usr/lib" \
	  --toolset=gcc \
	  --layout=system \
	  --builddir=obj \
	  --prefix=/usr \
	  --libdir=/usr/lib \
	  --build-type=minimal \
	  $PYTHON_FLAGS stage
}

pbs_install() {
	mkdir -p "$YPPATH_DEST"/usr/{lib,include}
	$BJAM \
	  release \
	  "-sEXPAT_INCLUDE=/usr/include" \
	  "-sEXPAT_LIBPATH=/usr/lib" \
	  --toolset=gcc \
	  --layout=system \
	  --builddir=obj \
	  --prefix="$YPPATH_DEST"/usr \
	  --libdir="$YPPATH_DEST"/usr/lib \
          --build-type=minimal \
	  $PYTHON_FLAGS install
	ypkg_docp $BJAM  "$YPPATH_DEST"/usr/bin
	# Do not copy 44MB of developer 'doc/html' into our package...
	ypkg_docp LICENSE* index.html "$YPPATH_DEST"/usr/share/doc/boost-"$V$R"
	find "$YPPATH_DEST"/usr/share/doc/boost-"$V$R" -type f -exec chmod 0644 {} \;
}
