#
# Ylmf OS package build script
#

DESCRIPTION="X.Org Xp library"
HOMEPAGE="http://xorg.freedesktop.org/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://xorg.freedesktop.org/releases/individual/lib/libXp-1.0.1.tar.bz2"

RDEPEND=""
BDEPEND="printproto"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}


