#
# YLmf_OS package build script
#

DESCRIPTION="X.Org Xp library"
HOMEPAGE="http://xorg.freedesktop.org/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://xorg.freedesktop.org/releases/individual/lib/libXp-1.0.1.tar.bz2"

RDEPEND=""
BDEPEND="printproto"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}


