#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="yinst - modified from WUBI for installing Ylmf OS under Windows."
HOMEPAGE="www.ylmf.net"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
YARCH="any"

SRC_URI="git://git.ylmf.com/yinst.git"

RDEPEND=""
BDEPEND=""

OPTIONS="nodev"

pbs_unpack() {
	dounpack
}

pbs_install() {
	dosrc *
}

