#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The libgweather package is a library to access weather information from online services for numerous locations."
HOMEPAGE="http://www.gnome.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
 
SRC_URI="ftp://ftp.gnome.org/pub/gnome/sources/libgweather/2.28/$N-$V.tar.bz2"
BDEPEND="gtk+ libsoup"
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/libgweather"

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	config+=" --prefix=$(pkg-config --variable=prefix ORBit-2.0)
	             --sysconfdir=/etc/gnome/2.28.2 "
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
