#
# Ylmf OS package build script
#

DESCRIPTION="Provides access to weather information from the net"
HOMEPAGE="http://www.gnome.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.32/2.32.1/sources/"$N-$V".tar.bz2"

RDEPEND="atk cairo dbus expat fontconfig freetype gcc-lib gconf gdk-pixbuf glib2 glibc gnutls gtk+ libgcrypt libgnome-keyring libgpg-error libpng libproxy libsoup libtasn1 libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libxml2 libXrandr libXrender orbit pango pixman sqlite zlib"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-schemas-install --enable-locations-compression"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

