#
# YLmf_OS package build script
#

DESCRIPTION="The libgweather package is a library to access weather information from online services for numerous locations."
HOMEPAGE="http://www.gnome.org/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.30/2.30.2/sources/"$N-$V$R".tar.bz2"

RDEPEND="atk cairo dbus dbus-glib eggdbus expat fontconfig freetype gcc gconf glib2 gdk-pixbuf glibc gnutls gtk+ libgcrypt libgnome-keyring libgpg-error libpng libproxy libsoup libtasn1 libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libxml2 libXrandr libXrender orbit pango pixman sqlite zlib"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=" --disable-schemas-install --enable-locations-compression"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

