#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The libgweather package is a library to access weather information from online services for numerous locations."
HOMEPAGE="http://www.gnome.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.30/2.30.2/sources/"$N-$V$R".tar.bz2"

RDEPEND="atk cairo dbus dbus-glib eggdbus expat fontconfig freetype gcc-lib gconf glib2 gdk-pixbuf glibc gnutls gtk+ libgcrypt libgnome-keyring libgpg-error libpng libproxy libsoup libtasn1 libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libxml2 libXrandr libXrender orbit pango pixman sqlite zlib"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=" --disable-schemas-install --enable-locations-compression"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

