#
# YLmf_OS package build script
#

DESCRIPTION="The libgweather package is a library to access weather information from online services for numerous locations."
HOMEPAGE="http://www.gnome.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="ftp://ftp.gnome.org/pub/gnome/sources/libgweather/2.28/$N-$V.tar.bz2"
BDEPEND="gtk+ libsoup"
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/libgweather"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	YPB_CONFIG+=" --prefix=$(pkg-config --variable=prefix ORBit-2.0)
	             --sysconfdir=/etc/gnome/2.28.2 "
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
