#
# YLmf_OS package build script
#

DESCRIPTION="Standard compliant menu library used by LXDE."
HOMEPAGE="www.lxde.org"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="git://lxde.git.sourceforge.net/gitroot/lxde/"$N""

RDEPEND="zlib"
BDEPEND=""

pbs_unpack() {
	ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--libexecdir=/usr/lib/menu-cache"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
