#
# Ylmf OS package build script
#

DESCRIPTION="Standard compliant menu library used by LXDE."
HOMEPAGE="www.lxde.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://nchc.dl.sourceforge.net/project/lxde/"$N"/"$N"%200.3.2/"$N-$V".tar.gz"

RDEPEND="glib2 glibc zlib"
BDEPEND=""

pbs_unpack() {
	dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

