#
# YLmf_OS package build script
#

DESCRIPTION="Standard compliant menu library used by LXDE."
HOMEPAGE="www.lxde.org"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://nchc.dl.sourceforge.net/project/lxde/menu-cache/menu-cache%200.3.2/"$N-$V$R".tar.gz"

RDEPEND="glib2 glibc zlib"
BDEPEND=""

pbs_unpack() {
	ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
