#!/bin/sh
#
# checking /etc/X11/xorg.conf for confilcted xorg modules of grahpic cards.
#

xorgfile="/etc/X11/xorg.conf"
xorgfile_restore="/etc/X11/xorg.conf-"

card=""
conflict=""
fglrx=""
_fglrx=""
nvidia=""
_nvidia=""
vesa=""
_vesa=""
driver=""
_driver=""

if [ -f $xorgfile ]; then
	fglrx="$(grep -w "Driver"  $xorgfile |grep -w "fglrx")"
	[ "x$fglrx" != "x" ] && driver="fglrx"
	
	nvidia="$(grep -w "Driver" $xorgfile |grep -w "nvidia")"
	[ "x$nvidia" != "x" ] && driver="nvidia"
	
	vesa="$(grep -w "Driver" $xorgfile |grep -w "vesa")"
	[ "x$vesa" != "x" ] && driver="vesa"
fi

if [ -f $xorgfile_restore ]; then
	_fglrx="$(grep -w "Driver"  $xorgfile_restore |grep -w "fglrx")"
	[ "x$_fglrx" != "x" ] && _driver="fglrx"
	
	_nvidia="$(grep -w "Driver" $xorgfile_restore |grep -w "nvidia")"
	[ "x$_nvidia" != "x" ] && _driver="nvidia"
	
	_vesa="$(grep -w "Driver" $xorgfile_restore |grep -w "vesa")"
	[ "x$_vesa" != "x" ] && _driver="vesa"
fi

#
# xforcevesa
#
if grep -wq xforcevesa /proc/cmdline; then
	# xorg.conf exits and driver is not vesa, backup
	if [ "$driver" != "vesa" ]; then
		mv $xorgfile $xorgfile_restore
	fi
	cat >$xorgfile <<EOF
# xforcevesa mode
Section "Device"
    Identifier     "Device0"
    Driver         "vesa"
    VendorName     "Videocard"
EndSection
EOF
	exit 0
else
	# xorg.conf exits and driver is vesa, delete
	if [ "$driver" = "vesa" ]; then
		rm $xorgfile
	fi
	
	# xorg.conf- exits and driver is not vesa, restore
	if [ "$driver" = "vesa" ] && [ "$_driver" != "vesa" ]; then
		cp $xorgfile_restore $xorgfile
	fi
	
	#
	# dual grahpic cards 
	#
	if [ $(lspci |grep VGA |wc -l) -ge 2 ]; then
		if [ "$driver" != "vesa" ]; then
			mv $xorgfile $xorgfile_restore
		else
			rm $xorgfile
		fi
		exit 0
	fi

	lspci |grep VGA |grep -q "Intel Corporation" && card="intel"
	lspci |grep VGA |grep -q "ATI Technologies"  && card="ati"
	lspci |grep VGA |grep -q "nVidia"            && card="nv"

	case $card in 
		intel)
			if [ "$driver" = "fglrx" ] || [ "$driver" = "nvidia" ]; then
				conflict="yes"
			fi ;;
		  ati)
			[ "$driver" = "nvidia" ] && conflict="yes"  ;;
		  nv)
			[ "$driver" = "fglrx" ] && conflict="yes" 
	esac

	[ "$conflict" = "yes" ] && mv $xorgfile $xorgfile_restore

	case $card in 
		ati) [ "$_driver" = "fglrx" ]  && mv $xorgfile_restore $xorgfile ;;
		 nv) [ "$_driver" = "nvidia" ] && mv $xorgfile_restore $xorgfile 
	esac

fi

exit 0 
