#
# YLmf_OS package build script
#

DESCRIPTION="Capture STDOUT and STDERR from Perl, XS or external programs  "
HOMEPAGE="http://search.cpan.org/~dagolden/Capture-Tiny-0.11/"
LICENSE="GPL PerlArtistic"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://mirrors.xmu.edu.cn/CPAN/authors/id/D/DA/DAGOLDEN/Capture-Tiny-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

