#
# YLmf_OS package build script
#

DESCRIPTION="MPlayer with Video Acceleration support"
HOMEPAGE="http://www.splitted-desktop.com/~gbeauchesne/mplayer-vaapi/"
REPO="testing"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.splitted-desktop.com/~gbeauchesne/"$N"/"$N"-latest-FULL.tar.bz2"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_build() {
	./checkout-patch-build.sh 
}

pbs_install() {
	:
}
