#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Fast, lightweight YAML loader and dumper"
HOMEPAGE="http://search.cpan.org/dist/YAML-Syck"
LICENSE="custom"
GROUP="perl"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://www.cpan.org/authors/id/T/TO/TODDR/YAML-Syck-$V.tar.gz"
CHECKSUM="e9f8d4f9cea7def4d0b132dbf66516b2"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1 PERL5LIB="" \
           PERL_AUTOINSTALL=--skipdeps \
           PERL_MM_OPT="INSTALLDIRS=vendor" \
           PERL_MB_OPT="--installdirs vendor" \
           MODULEBUILDRC=/dev/null
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
    dodoc COPYING
}
