#
# YLmf_OS package build script
#

DESCRIPTION="Version 2 of the library to manipulate XML files"
HOMEPAGE="http://www.xmlsoft.org/"
 
SRC_URI="ftp://xmlsoft.org/libxml2/$N-$V.tar.gz"

RDEPEND=""
BDEPEND="${RDEPEND}"

pbs_unpack()
{
        ypkg_unpack
}

pbs_config()
{
	
	YPB_CONFIG+=" --prefix=/usr "
	ypkg_config
}

pbs_build()
{
	ypkg_make
}

pbs_check()
{
	make check
}

pbs_install()
{
	ypkg_mkinstall
}
