#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="XML parsing library, version2"
HOMEPAGE="http://www.xmlsoft.org/"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>
          chenqixing@ivali.com"

SRC_URI="ftp://xmlsoft.org/"$N"/"$N-$V".tar.gz"

RDEPEND="zlib readline ncurses xz"
BDEPEND="python"
OPTIONAL="python: for bindings"

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--with-threads --with-history"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodoc COPYING
    doln /usr/include/libxml2/libxml "$PKGDIR"/usr/include/libxml
}

