#
# YLmf_OS package build script
#

DESCRIPTION="library of simple functions that are optimized for various CPUs"
HOMEPAGE="http://liboil.freedesktop.org/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://liboil.freedesktop.org/download/"$N-$V$R".tar.gz"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/liboil"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
