#
# YLmf_OS package build script
#

DESCRIPTION="X.Org fontenc library"
HOMEPAGE="http://www.x.org/wiki/"
 
SRCURL="http://www.x.org/releases/X11R7.5/src/lib"
SRC_URI="$SRCURL/libfontenc-1.0.5.tar.bz2"

RDEPEND="zlib"
BDEPEND="${RDEPEND} "

pbs_unpack()
{
        ypkg_unpack
}

pbs_config()
{
	
	YPB_CONFIG+=" --sysconfdir=/etc --mandir=/usr/share/man --localstatedir=/var "
	ypkg_config
}

pbs_build()
{
	ypkg_make
}

pbs_install()
{
	ypkg_mkinstall
}
