#
# Ylmf OS package build script
#

DESCRIPTION="X.Org fontenc library"
HOMEPAGE="http://www.x.org/wiki/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
 
SRC_URI="http://xorg.freedesktop.org/archive/individual/lib/"$N-$V".tar.bz2"
CHECKSUM="a2a861f142c3b4367f14fc14239fc1f7"

RDEPEND="zlib glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

