#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python bindings for the Qt framework"
HOMEPAGE="http://www.pyside.org/"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"

SRC_URI="http://qt-project.org/uploads/pyside/pyside-qt4.8+$V.tar.bz2"
CHECKSUM="59c8653734b020b0128b82adc98ee704"

RDEPEND="py-shiboken phonon qtwebkit libjpeg-turbo"
RECOMMENDED=""
BDEPEND="cmake"
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    doconfig -DCMAKE_BUILD_TYPE=Release
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
