#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="date conversion routines "
HOMEPAGE="http://search.cpan.org/~gaas/HTTP-Date-6.00/lib/HTTP/Date.pm"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="StartOS Developers"

SRC_URI="http://search.cpan.org/CPAN/authors/id/G/GA/GAAS/HTTP-Date-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
