#
# YLmf_OS package build script
#

DESCRIPTION="a productivity suite that is compatible with other major office suites"
HOMEPAGE="http://www.libreoffice.org"
REPO=""
LICENSE="LGPL3"
#PRIORITY="required"
PACKAGER="Zhongxin Huang, hzx@115.com"

pkgbase="libreoffice"
LOver=3.3.2.2
mirror="http://download.documentfoundation.org/libreoffice/src"
source=(${mirror}/${pkgbase}-build-${LOver}.tar.gz
	${mirror}/${pkgbase}-{artwork,base,bootstrap,calc,components,extensions,extras,filters,help,impress,l10n,libs-core,libs-extern,libs-extern-sys,libs-gui,postprocess,sdk,testing,ure,writer}-${LOver}.tar.bz2
	http://cairographics.org/releases//cairo-1.4.10.tar.gz
	http://hg.services.openoffice.org/binaries/63ddc5116488985e820075e65fbe6aa4-openssl-0.9.8o.tar.gz
	http://hg.services.openoffice.org/binaries/09357cc74975b01714e00c5899ea1881-pixman-0.12.0.tar.gz
	http://hg.services.openoffice.org/binaries/0b49ede71c21c0599b0cc19b353a6cb3-README_apache-commons.txt
	http://hg.services.openoffice.org/binaries/68dd2e8253d9a7930e9fd50e2d7220d0-hunspell-1.2.9.tar.gz
	http://hg.services.openoffice.org/binaries/128cfc86ed5953e57fe0f5ae98b62c2e-libtextcat-2.2.tar.gz
	http://hg.services.openoffice.org/binaries/17410483b5b5f267aa18b7e00b65e6e0-hsqldb_1_8_0.zip
	http://hg.services.openoffice.org/binaries/1756c4fa6c616ae15973c104cd8cb256-Adobe-Core35_AFMs-314.tar.gz
	http://hg.services.openoffice.org/binaries/18f577b374d60b3c760a3a3350407632-STLport-4.5.tar.gz
	http://hg.services.openoffice.org/binaries/1f24ab1d39f4a51faf22244c94a6203f-xmlsec1-1.2.14.tar.gz
	http://hg.services.openoffice.org/binaries/24be19595acad0a2cae931af77a0148a-LICENSE_source-9.0.0.7-bj.html
	http://hg.services.openoffice.org/binaries/26b3e95ddf3d9c077c480ea45874b3b8-lp_solve_5.5.tar.gz
	http://hg.services.openoffice.org/binaries/284e768eeda0e2898b0d5bf7e26a016e-raptor-1.4.18.tar.gz
	http://hg.services.openoffice.org/binaries/2a177023f9ea8ec8bd00837605c5df1b-jakarta-tomcat-5.0.30-src.tar.gz
	http://hg.services.openoffice.org/binaries/2ae988b339daec234019a7066f96733e-commons-lang-2.3-src.tar.gz
	http://hg.services.openoffice.org/binaries/2c9b0f83ed5890af02c0df1c1776f39b-commons-httpclient-3.1-src.tar.gz
	http://hg.services.openoffice.org/binaries/2f6ecca935948f7db92d925d88d0d078-icu4c-4_0_1-src.tgz
	http://hg.services.openoffice.org/binaries/ca4870d899fd7e943ffc310a5421ad4d-liberation-fonts-ttf-1.06.0.20100721.tar.gz
	http://hg.services.openoffice.org/binaries/35c94d2df8893241173de1d16b6034c0-swingExSrc.zip
	http://hg.services.openoffice.org/binaries/35efabc239af896dfb79be7ebdd6e6b9-gentiumbasic-fonts-1.10.zip
	http://hg.services.openoffice.org/binaries/377a60170e5185eb63d3ed2fae98e621-README_silgraphite-2.3.1.txt
	http://hg.services.openoffice.org/binaries/39bb3fcea1514f1369fcfc87542390fd-sacjava-1.3.zip
	http://hg.services.openoffice.org/binaries/3ade8cfe7e59ca8e65052644fed9fca4-epm-3.7.tar.gz
	http://hg.services.openoffice.org/binaries/3c219630e4302863a9a83d0efde889db-commons-logging-1.1.1-src.tar.gz
	http://hg.services.openoffice.org/binaries/48470d662650c3c074e1c3fabbc67bbd-README_source-9.0.0.7-bj.txt
	http://hg.services.openoffice.org/binaries/48d8169acc35f97e05d8dcdfd45be7f2-lucene-2.3.2.tar.gz
	http://hg.services.openoffice.org/binaries/4a660ce8466c9df01f19036435425c3a-glibc-2.1.3-stub.tar.gz
	http://hg.services.openoffice.org/binaries/4ea70ea87b47e92d318d4e7f5b940f47-cairo-1.8.0.tar.gz
	http://hg.services.openoffice.org/binaries/599dc4cc65a07ee868cf92a667a913d2-xpdf-3.02.tar.gz
	http://hg.services.openoffice.org/binaries/5aba06ede2daa9f2c11892fbd7bc3057-libserializer.zip
	http://hg.services.openoffice.org/binaries/67b42915c8432abf0a922438f00860a2-libxml.zip
	http://hg.services.openoffice.org/binaries/7740a8ec23878a2f50120e1faa2730f2-libxml2-2.7.6.tar.gz
	http://hg.services.openoffice.org/binaries/7376930b0d3f3d77a685d94c4a3acda8-STLport-4.5-0119.tar.gz
	http://hg.services.openoffice.org/binaries/79600e696a98ff95c2eba976f7a8dfbb-liblayout.zip
	http://hg.services.openoffice.org/binaries/798b2ffdc8bcfe7bca2cf92b62caf685-rhino1_5R5.zip
	http://hg.services.openoffice.org/binaries/ecb2e37e45c9933e2a963cabe03670ab-curl-7.19.7.tar.gz
	http://hg.services.openoffice.org/binaries/8294d6c42e3553229af9934c5c0ed997-stax-api-1.0-2-sources.jar
	http://hg.services.openoffice.org/binaries/8ea307d71d11140574bfb9fcc2487e33-libbase.zip
	http://hg.services.openoffice.org/binaries/bd30e9cf5523cdfc019b94f5e1d7fd19-cppunit-1.12.1.tar.gz
	http://hg.services.openoffice.org/binaries/a06a496d7a43cbdc35e69dbe678efadb-libloader.zip
	http://hg.services.openoffice.org/binaries/a169ab152209200a7bad29a275cb0333-seamonkey-1.1.14.source.tar.gz
	http://hg.services.openoffice.org/binaries/a4d9b30810a434a3ed39fc0003bbd637-LICENSE_stax-api-1.0-2-sources.html
	http://hg.services.openoffice.org/binaries/a7983f859eafb2677d7ff386a023bc40-xsltml_2.1.2.zip
	http://hg.services.openoffice.org/binaries/ada24d37d8d638b3d8a9985e80bc2978-source-9.0.0.7-bj.zip
	http://hg.services.openoffice.org/binaries/af3c3acf618de6108d65fcdc92b492e1-commons-codec-1.3-src.tar.gz
	http://hg.services.openoffice.org/binaries/ba1015b59c112d44d7797b62fe7bee51-neon-0.29.3.tar.gz
	http://hg.services.openoffice.org/binaries/bc702168a2af16869201dbe91e46ae48-LICENSE_Python-2.6.1
	http://hg.services.openoffice.org/binaries/c441926f3a552ed3e5b274b62e86af16-STLport-4.0.tar.gz
	http://hg.services.openoffice.org/binaries/ca66e26082cab8bb817185a116db809b-redland-1.0.8.tar.gz
	http://hg.services.openoffice.org/binaries/d0b5af6e408b8d2958f3d83b5244f5e8-hyphen-2.4.tar.gz
	http://hg.services.openoffice.org/binaries/d1a3205871c3c52e8a50c9f18510ae12-libformula.zip
	http://hg.services.openoffice.org/binaries/d35724900f6a4105550293686688bbb3-silgraphite-2.3.1.tar.gz
	http://hg.services.openoffice.org/binaries/d4c4d91ab3a8e52a2e69d48d34ef4df4-core.zip
	http://hg.services.openoffice.org/binaries/d70951c80dabecc2892c919ff5d07172-db-4.7.25.NC-custom.tar.gz
	http://hg.services.openoffice.org/binaries/dbb3757275dc5cc80820c0b4dd24ed95-librepository.zip
	http://hg.services.openoffice.org/binaries/dbd5f3b47ed13132f04c685d608a7547-jpeg-6b.tar.gz
	http://hg.services.openoffice.org/binaries/e0707ff896045731ff99e99799606441-README_db-4.7.25.NC-custom.txt
	http://hg.services.openoffice.org/binaries/e81c2f0953aa60f8062c05a4673f2be0-Python-2.6.1.tar.bz2
	http://hg.services.openoffice.org/binaries/e61d0364a30146aaa3001296f853b2b9-libxslt-1.1.26.tar.gz
	http://hg.services.openoffice.org/binaries/ea570af93c284aa9e5621cd563f54f4d-bsh-2.0b1-src.tar.gz
	http://hg.services.openoffice.org/binaries/ea91f2fb4212a21d708aced277e6e85a-vigra1.4.0.tar.gz
	http://hg.services.openoffice.org/binaries/ee8b492592568805593f81f8cdf2a04c-expat-2.0.1.tar.gz
	http://hg.services.openoffice.org/binaries/f3e2febd267c8e4b13df00dac211dd6d-flute.zip
	http://hg.services.openoffice.org/binaries/f7925ba8491fe570e5164d2c72791358-libfonts.zip
	http://hg.services.openoffice.org/binaries/fb7ba5c2182be4e73748859967455455-README_stax-api-1.0-2-sources.txt
	http://hg.services.openoffice.org/binaries/fca8706f2c4619e2fa3f8f42f8fc1e9d-rasqal-0.9.16.tar.gz
	http://hg.services.openoffice.org/binaries/fcc6df1160753d0b8c835d17fdeeb0a7-boost_1_39_0.tar.gz
	http://hg.services.openoffice.org/binaries/fdb27bfe2dbe2e7b57ae194d9bf36bab-SampleICC-1.3.2.tar.gz
	http://hg.services.openoffice.org/binaries/37282537d0ed1a087b1c8f050dc812d9-dejavu-fonts-ttf-2.32.zip
	http://hg.services.openoffice.org/binaries/831126a1ee5af269923cfab6050769fe-mysql-connector-cpp.zip
	http://hg.services.openoffice.org/binaries/067201ea8b126597670b5eff72e1f66c-mythes-1.2.0.tar.gz
	http://hg.services.openoffice.org/binaries/cf8a6967f7de535ae257fa411c98eb88-mdds_0.3.0.tar.bz2
	http://download.go-oo.org/src/47e1edaa44269bc537ae8cabebb0f638-JLanguageTool-1.0.0.tar.bz2
	http://download.go-oo.org/src/debc62758716a169df9f62e6ab2bc634-zlib-1.2.3.tar.gz
	http://download.go-oo.org/src/e3738abd0d3ce1870dc1fd1f22bba5b1-icu4c-4_2_1-src.tgz
	http://download.go-oo.org/src/0f63ee487fda8f21fafa767b3c447ac9-ixion-0.2.0.tar.gz
	http://download.go-oo.org/src/71474203939fafbe271e1263e61d083e-nss-3.12.8-with-nspr-4.8.6.tar.gz
	http://download.go-oo.org/src/5ba6a61a2f66dfd5fee8cdd4cd262a37-libwpg-0.2.0.tar.bz2
	http://download.go-oo.org/src/5ff846847dab351604ad859e2fd4ed3c-libwpd-0.9.1.tar.bz2
	http://download.go-oo.org/src/9e436bff44c60dc8b97cba0c7fc11a5c-libwps-0.2.0.tar.bz2
	http://download.go-oo.org/extern/185d60944ea767075d27247c3162b3bc-unowinreg.dll
	http://www.numbertext.org/linux/881af2b7dca9b8259abbca00bbbc004d-LinLibertineG-20110101.zip
	http://archive.apache.org/dist/ant/binaries/apache-ant-1.8.1-bin.tar.gz
	http://download.go-oo.org//SRC680/extras-3.1.tar.bz2
	http://download.go-oo.org//SRC680/biblio.tar.bz2
	http://ftp.fsf.hu/OpenOffice.org_hu/numbertext//numbertext-0.9.3.oxt
	http://ftp.fsf.hu/OpenOffice.org_hu/typo//typo-0.3.oxt
	http://download.go-oo.org/src//ConvertTextToNumber-1.3.2.oxt
	http://ftp.devall.hu/kami/go-oo//WatchWindow_1.2.0.0.oxt
	http://ftp.devall.hu/kami/go-oo//Diagram_1.1.0.0.oxt
	http://download.go-oo.org/src//90401bca927835b6fbae4a707ed187c8-nlpsolver-0.9.tar.bz2
	http://download.go-oo.org//SRC680/mdbtools-0.6pre1.tar.gz
	http://download.go-oo.org/src//oooblogger-0.1.oxt
	http://download.go-oo.org//DEV300/ooo-cli-prebuilt-3.3.tar.bz2
	http://ftp.fsf.hu/OpenOffice.org_hu/hunart//hunart-0.3.oxt)
SRC_URI="${source[@]}"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

NOTES="base on:
https://aur.archlinux.org/packages/libreoffice-git/PKGBUILD
http://gitorious.org/chakra-packages/apps/blobs/testing/libreoffice/PKGBUILD"

#DESKTOPFILE="glchess.desktop" or "/opt/test/test.desktop"
#ICONFILE="test.png"   or "/opt/test/test.png"

pbs_config() {
	unset J2REDIR; unset J2SDKDIR; unset JAVA_HOME; unset CLASSPATH
	[ -z "${JAVA_HOME}" ] && . /etc/profile.d/openjdk6.sh
	[ -z "${MOZ_PLUGIN_PATH}" ] && . /etc/profile.d/mozilla-common.sh
	[ -z "${ANT_HOME}" ] && . /etc/profile.d/apache-ant.sh
	mkdir -p "$N-$V$R"
	cd "$N-$V$R"
	tar xf  $YPPATH_SOURCE/${pkgbase}-build-${LOver}.tar.gz
	cd ${pkgbase}-build-${LOver}
	for ((i=0; i<${#source[@]}; i++)); do
		tmp=${source[$i]}
		cp $YPPATH_SOURCE/${tmp##*/} src/
	done
	# Ylmfos Tweaks
	#ypkg_patch ylmfos.patch
	#cp $FILES_PATH/files/ylmfos.conf            distro-configs/
	#cp $FILES_PATH/files/ylmfos.conf.in         distro-configs/
	#sed -i -e "s~ArchLinux~ylmfos~g"            configure.in configure
	# hotfixes not yet upstream
	#cp $FILES_PATH/files/buildfix_64bit_system_libjpeg.diff patches/hotfixes/
	# export C(XX)FLAGS
	# http://www.openoffice.org/issues/show_bug.cgi?id=103205
	unset CFLAGS
	unset CXXFLAGS
	#python2 fix
	#export PYTHON=python2
	#fix dekstop menu entries
	sed -i -e "s/Exec=oo/Exec=lo/g"       desktop/*.desktop.in.in
	sed -i -e "s/TryExec=oo/TryExec=lo/g" desktop/*.desktop.in.in
	#http://wiki.documentfoundation.org/Development/How_to_build/Configure_options
	if [ "$CARCH" = "x86_64" ]; then
		EXTRAOPTS="--without-stlport"
	else
		EXTRAOPTS="--with-stlport" # --without-system-boost"
		# # avoid problems with ixion for now
		sed -i '/fields-table-formula.diff/d' patches/dev300/apply
	fi

	#--with-distro=ylmfos \
	#--with-srcdir=${srcdir} \
	#--with-nlpsolver \
	#--with-build-version="${LOver} ylmfos GNU/Linux build" \
	#--with-ant-home="/usr/share/java/apache-ant"\
	#--with-lucene-core-jar=/usr/share/java/lucene-core.jar \
	#--with-lucene-analyzers-jar=/usr/share/java/lucene-analyzers.jar \
	extra_conf="
		--without-git \
		--with-max-jobs=${MAKEFLAGS/-j/} \
		--with-installed-ooo-dirname="${pkgbase}" \
		--with-lang="" \
		--with-binsuffix=no \
		--enable-cairo \
		--enable-crashdump \
		--enable-graphite \
		--disable-gio \
		--disable-kde \
		--disable-kde4 \
		--disable-gtk \
		--disable-gconf \
		--disable-mono \
		--disable-evolution2 \
		--enable-ldap \
		--enable-lockdown \
		--enable-opengl \
		--enable-odk \
		--enable-opengl\
		--enable-ogltrans \
		--enable-minimizer \
		--enable-pdfimport \
		--enable-presenter-console \
		--enable-presenter-extra-ui \
		--enable-report-builder \
		--enable-wiki-publisher \
		--with-ct2n \
		--with-hunart \
		--with-numbertext \
		--with-oooblogger \
		--with-typo \
		--with-watch-window \
		--with-diagram \
		--without-fonts\
		--without-afms\
		--without-ppds\
		--without-system-agg \
		--without-system-libwps \
		--without-system-mdds \
		--without-myspell-dicts \
		--with-system-dicts \
		--with-external-dict-dir=/usr/share/hunspell \ 
		--with-external-hyph-dir=/usr/share/hyphen \ 
		--with-external-thes-dir=/usr/share/mythes \
		--with-system-cppunit \
		--with-system-libwpg \
		--with-system-redland \
		--without-system-saxon \
		--with-openldap \
		--with-system-boost \
		--with-system-cairo \
		--with-system-libs \
		--with-system-mythes\
		--with-system-unixodbc-headers \
		--with-system-xrender-headers \
		--with-system-headers \
		--with-alloc=system \
		--with-system-lucene \
		$EXTRAOPTS "

		./autogen.sh --prefix=/usr \
		             --exec-prefix=/usr  \
			     --sysconfdir=/etc \
			     --with-docdir=/usr/share/doc/"${pkgbase}" \
	                     --mandir=/usr/share/man \
			     --without-java  \
			     --disable-kde   \
			     --disable-kde4   
			     #$extra_conf

		unset MAKEFLAGS
		./download
}

pbs_build() {
	#make "$MAKEOPTS"
	LD_PRELOAD="" ypkg_make
}

pbs_install() {
	#ypkg_mkinstall
	bin/ooinstall -l "$YPPATH_DEST"
	cd ${YPPATH_DEST}
        mkdir -p usr/lib/libreoffice
 	ypkg_domv basis3.3 CREDITS.odt LICENSE LICENSE.odt program readmes share ure usr/lib/libreoffice
	rm -rfv basis-link
	# move sysui desktop files into place we want to use - javafilter and qstarter, but not unneeded printeradmin
	ypkg_docp usr/lib/libreoffice/share/xdg/javafilter.desktop \
		  usr/lib/libreoffice/share/xdg/qstart.desktop usr/share/applications/
	# remove version in menu entry and make it visible
	sed -i -e "s/3.3 Quickstarter/Quickstarter/g" usr/share/applications/qstart.desktop
	sed -i -e "/NoDisplay=true/d" 		      usr/share/applications/qstart.desktop
	# remove unneeded .desktop files from vanilla sysui
	rm -rf usr/lib/libreoffice/share/xdg
	# put configuration files into place
	install -dm755 etc/libreoffice
	install -m644  usr/lib/libreoffice/program/{bootstraprc,sofficerc}      etc/libreoffice/
	install -m644  usr/lib/libreoffice/basis3.3/share/psprint/psprint.conf  etc/libreoffice/
	# install dummy links to make them found by LibO
	cd ${YPPATH_DEST}/usr/lib/libreoffice/program/
	ln -vsf /etc/libreoffice/{bootstraprc,sofficerc} .
	cd ${YPPATH_DEST}/usr/lib/libreoffice/basis3.3/share/psprint/
	ln -vsf /etc/libreoffice/psprint.conf .
	#fix http://bugs.archlinux.org/task/17656
	find ${YPPATH_DEST} -perm 444 -exec ls -lh {} \; 
	find ${YPPATH_DEST} -perm 444 -exec chmod 644 {} \;
	find ${YPPATH_DEST} -perm 555 -exec ls -lh {} \;
	find ${YPPATH_DEST} -perm 555 -exec chmod 755 {} \;
	mkdir -p ${YPPATH_DEST}/usr/lib
	cd ${YPPATH_DEST}/usr/lib/
	ln -vsf ${YPPATH_DEST}/usr/lib/libreoffice/ure/lib/libuno_sal.so.3 .
	ln -vsf ${YPPATH_DEST}/usr/lib/libreoffice/basis3.3/program/libsofficeapp.so .
	cd ${YPPATH_DEST}/usr/lib/libreoffice/
	ln -vsf ${YPPATH_DEST}/usr/lib/libreoffice/basis3.3 ./basis-link
	mkdir -p ${YPPATH_DEST}/usr/bin
	cd ${YPPATH_DEST}/usr/bin
	ln -vsf ${pkdir}/usr/lib/libreoffice/program/soffice .
}

