#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="X.Org xtrans library"
HOMEPAGE="http://www.x.org/wiki/"
GROUP="x11-lib"
 
SRC_URI="http://www.x.org/releases/X11R7.6/src/lib/"$N-$V$R".tar.bz2"

RDEPEND="glib2 gdk-pixbuf2"
BDEPEND=""


pbs_unpack() {
        dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

