. /usr/lib/ybs/funcs

post_install() {
	gnome2_install_schema "/etc/gconf/schemas/bug-buddy.schemas"
	gnome2_install_defaut_gconf "bool" "/apps/gnome_settings_daemon/gtk-modules/gnomebreakpad" "true"
	gnome2_rarian_sk_update
	gnome2_desktop_database_update
	gnome2_icon_cache_update
	gnome2_gconfd_reload
}

post_remove() {
	gnome2_install_defaut_gconf "bool" "/apps/gnome_settings_daemon/gtk-modules/gnomebreakpad" "false"
}
