#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Pure Perl YAML Implementation  "
HOMEPAGE="http://search.cpan.org/"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://www.cpan.org/authors/id/A/AD/ADAMK/YAML-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

