#
# YLmf_OS package build script
#

DESCRIPTION="Meta build which provides python interfacing modules for some GNOME desktop libraries"
HOMEPAGE="http://pygtk.org/"
REPO=""
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.30/2.30.2/sources/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND="${RDEPEND} gnome-python gtksourceview libgnome libgnomeprintui gnome-keyring gnome-desktop bug-buddy totem-pl-parser gnome-media evince"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

pbs_postinst() {
	gnome2_desktop_database_update
}
