#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Meta build which provides python interfacing modules for some GNOME desktop libraries"
HOMEPAGE="http://pygtk.org/"
REPO=""
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.30/2.30.2/sources/"$N-$V$R".tar.bz2"

RDEPEND="alsa-lib atk audiofile avahi cairo dbus dbus-glib e2fsprogs eggdbus evince evolution-data-server expat fontconfig freetype gail gcc-lib gconf glib2 gdk-pixbuf glibc gmime gnome-desktop gnome-media gnome-panel gnome-vfs gnutls gst-plugins-base gstreamer gtk+ keyutils krb5 libart_lgpl libbonobo libbonoboui libcanberra libcroco libgcrypt libgnome libgnomecanvas libgnome-keyring libgnomeprint libgnomeprintui libgnomeui libgpg-error libgsf libgtop libical libICE libogg libpng librsvg libSM libsoup libtasn1 libtool libvorbis libwnck libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libxml2 libXrandr libXrender libXres nspr nss openssl orbit pango pixman popt python sqlite startup-notification totem-pl-parser util-linux-ng zlib"
BDEPEND=""
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
