#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Meta build which provides python interfacing modules for some GNOME desktop libraries"
HOMEPAGE="http://pygtk.org/"
LICENSE="GPLv2"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.32/2.32.1/sources/"$N-$V".tar.bz2"

RDEPEND="brasero evince gnome-media gnome-panel libgnomeprintui libgnomeui libgtop python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config="${config/--enable-shared/}"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

