#
# Ylmf OS package build script
#

DESCRIPTION="qiyi client (AIR)"
HOMEPAGE="www.qiyi.com"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://static.qiyi.com/ext/common/xplayerForAir.air"

RDEPEND="adobe-air-sdk"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_install() {
	docp_rename "$YPPATH_SOURCE"/xplayerForAir.air "$destdir"/usr/lib/"$N"/qiyi.air
	dodesktop   "$N.desktop"      "$N.png"
}

