#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="qiyi client (AIR)"
HOMEPAGE="www.qiyi.com"
LICENSE="custom"
PACKAGER="StartOS Developers"

SRC_URI="http://static.qiyi.com/ext/common/xplayerForAir.air"

RDEPEND="adobe-air-sdk"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_install() {
	docp_rename "$YBS_SOURCE"/xplayerForAir.air "$destdir"/usr/lib/"$N"/qiyi.air
	dodesktop   "$N.desktop"      "$N.png"
}

