#
# YLmf_OS package build script
#

DESCRIPTION="Python interface to the OpenSSL library"
HOMEPAGE="http://pyopenssl.sourceforge.net/ http://pypi.python.org/pypi/pyOpenSSL"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://pypi.python.org/packages/source/p/pyOpenSSL/pyOpenSSL-"$V$R".tar.gz"

RDEPEND="glibc openssl python"
BDEPEND="  "
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
