#
# Ylmf OS package build script
#

DESCRIPTION="An advanced interactive shell for Python."
HOMEPAGE="http://ipython.scipy.org/ http://pypi.python.org/pypi/ipython"
LICENSE="BSD"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
YARCH="any"

SRC_URI="http://ipython.scipy.org/dist/"$V"/"$N-$V".tar.gz"

RDEPEND="python"
BDEPEND="cups-dev"
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

