#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An advanced interactive shell for Python."
HOMEPAGE="http://ipython.org"
LICENSE="BSD"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://archive.ipython.org/release/"$V"/"$N-$V".tar.gz"
CHECKSUM="ca7e75f7c802afc6aaa0a1ea59846420"

RDEPEND="python distribute"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall --optimize=0
    find "$destdir/" -name '*.pyc' -delete
}

