#
# YLmf_OS package build script
#

DESCRIPTION="The gir-repository is a repository of GIR interface description files."
HOMEPAGE="http://www.gnome.org"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"
SRC_URI=" http://ftp.gnome.org/pub/gnome/sources/$N/0.6/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" gobject-introspection babl"
RECOMMENDED="gtk+"

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/gir-repository"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	patch -Np1 -i $FILES_PATH/files/"$N-$V$R"-dbus-glib-2.patch 
	#fix me!
	sed -i 's/babl-0.0/babl-0.1/g' gir/Makefile.in
	YPB_CONFIG+=" --prefix=/usr "
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
