#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION=" libdbi implements a database-independent abstraction layer in C, similar to the DBI/DBD layer in Perl."
HOMEPAGE="http://libdbi.sourceforge.net/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://sourceforge.net/projects/libdbi/files/"$N"/"$N-$V"/"$N-$V".tar.gz"

RDEPEND="glibc"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

