#
# Ylmf OS package build script
#

DESCRIPTION="Uncompress rar files"
HOMEPAGE="http://www.rarlab.com/rar_add.htm"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.rarlab.com/rar/unrarsrc-"$V".tar.gz"

RDEPEND="gcc glibc"
BDEPEND=""

pbs_unpack() {
	dounpack
}

pbs_build() {
	make -f makefile.unix CXXFLAGS="${CPPFLAGS}"
}

pbs_install() {
	mkdir -p "$destdir"/usr/bin
	make -f makefile.unix DESTDIR="$destdir"/usr install
}

