#
# YLmf_OS package build script
#

DESCRIPTION="Layout and render international text "
HOMEPAGE="http://search.cpan.org/~tsch/Pango-1.221/lib/Pango.pm"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YVERSION="1"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/Pango-"$V".tar.gz"

RDEPEND="perl pango cairo-perl glib-perl"
BDEPEND="extutils-depends extutils-pkgconfig"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

