#
# Ylmf OS package build script
#

DESCRIPTION="Layout and render international text "
HOMEPAGE="http://search.cpan.org/~tsch/Pango-1.221/lib/Pango.pm"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
LICENSE="GPL PerlArtistic"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/Pango-"$V".tar.gz"

RDEPEND="perl pango cairo-perl glib-perl"
BDEPEND="extutils-depends extutils-pkgconfig"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

