#
# YLmf_OS package build script
#

DESCRIPTION="The Theora Video Compression Codec"
HOMEPAGE="http://www.theora.org"
REPO=""
LICENSE=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://downloads.xiph.org/releases/theora/"$N-$V$R".tar.bz2"

RDEPEND="libvorbis libogg libsdl"
BDEPEND="${RDEPEND} "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS COPYING README
}
