#
# Ylmf OS package build script
#

DESCRIPTION="The Theora Video Compression Codec"
HOMEPAGE="http://www.theora.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://downloads.xiph.org/releases/theora/"$N-$V".tar.bz2"

RDEPEND="glibc libogg"
BDEPEND="libvorbis-dev libsdl-dev"
RECOMMENDED="libvorbis libsdl"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	make DESTDIR="$destdir" install
}


