#
# YLmf_OS package build script
#

DESCRIPTION="Perl interface to the Window Navigator Construction Kit "
HOMEPAGE="http://search.cpan.org/~tsch/Gnome2-Wnck-0.16/Wnck.pm"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/Gnome2-Wnck-"$V".tar.gz"

RDEPEND="perl gnome2-perl libwnck"
BDEPEND="extutils-depends extutils-pkgconfig"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

