#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl interface to the Window Navigator Construction Kit "
HOMEPAGE="http://search.cpan.org/~tsch/Gnome2-Wnck-0.16/Wnck.pm"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="GPL,PerlArtistic"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/Gnome2-Wnck-"$V".tar.gz"

RDEPEND="perl gnome2-perl libwnck"
BDEPEND="extutils-depends extutils-pkgconfig"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
        perl_cleanup
}

