#
# YLmf_OS package build script
#

DESCRIPTION="Taglib# 2.0 - Managed tag reader/writer"
HOMEPAGE="http://developer.novell.com/wiki/index.php/TagLib_Sharp"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://github.com/mono/"$N".git"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	#make DESTDIR="$destdir" install
	domkinstall
	rm -rf "$destdir"/tmp  || return 0
}
