#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Taglib# 2.0 - Managed tag reader/writer"
HOMEPAGE="http://developer.novell.com/wiki/index.php/TagLib_Sharp"
LICENSE="LGPL"
PACKAGER="StartOS Developers"

SRC_URI="git://github.com/mono/"$N".git"

RDEPEND="mono"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	rm -rf "$destdir"/tmp  || return 0
}

