#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A full-featured and high-performance event loop"
HOMEPAGE="http://software.schmorp.de/pkg/libev.html"
LICENSE="BSD"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://dist.schmorp.de/"$N"/"$N-$V".tar.gz"
CHECKSUM="e7752a518742c0f8086a8005aa7efcc4dcf02ed9"

RDEPEND="glibc"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc LICENSE

	# Conflict with libevent
	rm "$destdir"/usr/include/event.h
}

