#
# YLmf_OS package build script
#

DESCRIPTION="Telepathy Python base classes for use in connection managers, and proxy classes for use in clients."
HOMEPAGE="http://telepathy.freedesktop.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://telepathy.freedesktop.org/releases/"$N"/"$N-$V".tar.gz"

RDEPEND=""
BDEPEND="python-dev telepathy-glib-dev"
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG=${YPB_CONFIG/--enable-shared/}
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

