#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Tk Widget Set"
HOMEPAGE="http://www.tcl.tk/"

SRC_URI="http://downloads.sourceforge.net/tcl/tk"$V$R"-src.tar.gz"

RDEPEND="tcl libX11 libXScrnSaver libXext libXft freetype fontconfig libXrender 
	 libxcb libXau libXdmcp zlib expat"
BDEPEND=" "

pbs_unpack(){
        dounpack
}

pbs_config(){
	cd unix
	config+="--enable-threads"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	sed -i 	-e "s@^\(TK_SRC_DIR='\).*@\1/usr/include'@" \
		-e "/TK_B/s@='\(-L\)\?.*unix@='\1/usr/lib@" \
		tkConfig.sh
	domkinstall 
	make DESTDIR="$destdir" install-private-headers
	doln wish8.5 "$destdir"/usr/bin/wish 
}
