#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A windowing toolkit for use with tcl"
HOMEPAGE="http://tcl.sourceforge.net/"
LICENSE="custom"
PACKAGER="StartOS Developers"

SRC_URI="http://sourceforge.net/projects/tcl/files/Tcl/"$N"/"$N$V"-src.tar.gz"
CHECKSUM="1fc7dbb7495160756dbc805224afa360"

RDEPEND="libXft libXScrnSaver tcl"
BDEPEND=""

pbs_unpack(){
        dounpack
}

pbs_config(){
	cd unix
	case "$ARCH" in
	  x86_64) config+="--enable-threads --enable-64bit" ;;
	    i?86) config+="--enable-threads --disable-64bit"
	esac
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	make INSTALL_ROOT="$destdir" install install-private-headers
	doln /usr/bin/wish8.5 "$destdir"/usr/bin/wish 

	# Install private headers
	cd ../
	for dir in compat generic generic/ttk unix; do
		install -dm755 "$destdir"/usr/include/tk-private/"$dir"
	        install -m644 -t "$destdir"/usr/include/tk-private/"$dir" "$dir"/*.h
	done

        # Install license
	dodoc license.terms

        # Remove buildroot traces
        sed -i \
            -e "s,^TK_BUILD_LIB_SPEC='-L.*/unix,TK_BUILD_LIB_SPEC='-L/usr/lib"$LIBDIRSUFFIX"," \
            -e "s,^TK_SRC_DIR='.*',TK_SRC_DIR='/usr/include'," \
            -e "s,^TK_BUILD_STUB_LIB_SPEC='-L.*/unix,TK_BUILD_STUB_LIB_SPEC='-L/usr/lib"$LIBDIRSUFFIX"," \
            -e "s,^TK_BUILD_STUB_LIB_PATH='.*/unix,TK_BUILD_STUB_LIB_PATH='/usr/lib"$LIBDIRSUFFIX"," \
		      "$destdir"/usr/lib"$LIBDIRSUFFIX"/tkConfig.sh
}

