#
# YLmf_OS package build script
#

DESCRIPTION="A windowing toolkit for use with tcl"
HOMEPAGE="http://tcl.sourceforge.net/"

SRC_URI="http://downloads.sourceforge.net/sourceforge/tcl/tk"$V$R"-src.tar.gz"

RDEPEND="tcl libX11 libXScrnSaver libXext libXft freetype fontconfig libXrender libxcb libXau libXdmcp zlib expat"
BDEPEND=""

pbs_unpack(){
        ypkg_unpack
}

pbs_config(){
	cd unix
	YPB_CONFIG+="--enable-threads --disable-64bit"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	make INSTALL_ROOT="$YPPATH_DEST" install install-private-headers
	ypkg_doln /usr/bin/wish8.5 "$YPPATH_DEST"/usr/bin/wish 

	# install private headers
	cd ../
	for dir in compat generic generic/ttk unix; do
		install -dm755 "$YPPATH_DEST"/usr/include/tk-private/"$dir"
	        install -m644 -t "$YPPATH_DEST"/usr/include/tk-private/"$dir" "$dir"/*.h
	done

        # install license
	ypkg_dodoc license.terms

        # remove buildroot traces
        sed -i \
            -e "s,^TK_BUILD_LIB_SPEC='-L.*/unix,TK_BUILD_LIB_SPEC='-L/usr/lib," \
            -e "s,^TK_SRC_DIR='.*',TK_SRC_DIR='/usr/include'," \
            -e "s,^TK_BUILD_STUB_LIB_SPEC='-L.*/unix,TK_BUILD_STUB_LIB_SPEC='-L/usr/lib," \
            -e "s,^TK_BUILD_STUB_LIB_PATH='.*/unix,TK_BUILD_STUB_LIB_PATH='/usr/lib," \
		      "$YPPATH_DEST"/usr/lib/tkConfig.sh
}

