#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A windowing toolkit for use with tcl"
HOMEPAGE="http://tcl.sourceforge.net/"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://downloads.sourceforge.net/sourceforge/tcl/$N$V-src.tar.gz"
CHECKSUM="b883a1a3c489c17413fb602a94bf54e8"

RDEPEND="libXft libXScrnSaver tcl(=8.6.0)"
BDEPEND=""

pbs_unpack(){
    dounpack
}

pbs_config(){
    cd unix
    config+="--enable-threads "
    case "$ARCH" in
      x86_64) config+="--enable-64bit" ;;
        i?86) config+="--disable-64bit"
    esac
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    make INSTALL_ROOT="$PKGDIR" install install-private-headers
    dodoc ../license.terms
    cd "$PKGDIR"
    doln /usr/bin/wish${V%.*} usr/bin/wish 
    # remove buildroot traces
    sed -i "s#$SRCDIR#/usr/src/$N$V#" usr/lib"$LIBDIRSUFFIX"/tkConfig.sh
}

