#
# Ylmf OS package build script
#

DESCRIPTION="A windowing toolkit for use with tcl"
HOMEPAGE="http://tcl.sourceforge.net/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://downloads.sourceforge.net/sourceforge/tcl/"$N$V"-src.tar.gz"

RDEPEND="expat fontconfig freetype glibc libX11 libXau libxcb libXdmcp libXext libXft libXrender libXScrnSaver tcl zlib"
BDEPEND=""

pbs_unpack(){
        dounpack
}

pbs_config(){
	cd unix
	config+="--enable-threads --disable-64bit"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	make INSTALL_ROOT="$destdir" install install-private-headers
	doln /usr/bin/wish8.5 "$destdir"/usr/bin/wish 

	# Install private headers
	cd ../
	for dir in compat generic generic/ttk unix; do
		install -dm755 "$destdir"/usr/include/tk-private/"$dir"
	        install -m644 -t "$destdir"/usr/include/tk-private/"$dir" "$dir"/*.h
	done

        # Install license
	dodoc license.terms

        # Remove buildroot traces
        sed -i \
            -e "s,^TK_BUILD_LIB_SPEC='-L.*/unix,TK_BUILD_LIB_SPEC='-L/usr/lib," \
            -e "s,^TK_SRC_DIR='.*',TK_SRC_DIR='/usr/include'," \
            -e "s,^TK_BUILD_STUB_LIB_SPEC='-L.*/unix,TK_BUILD_STUB_LIB_SPEC='-L/usr/lib," \
            -e "s,^TK_BUILD_STUB_LIB_PATH='.*/unix,TK_BUILD_STUB_LIB_PATH='/usr/lib," \
		      "$destdir"/usr/lib/tkConfig.sh
}

