#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A Python module to deal with freedesktop.org specifications"
HOMEPAGE="http://pyxdg.freedesktop.org/ http://people.freedesktop.org/~lanius/"
LICENSE="GPL"
PACKAGER="StartOS Developers"
YARCH="any"

SRC_URI="http://www.freedesktop.org/~lanius/"$N-$V".tar.gz "

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_patch() {
	dopatch startos-skip-parse-kdelegacydirs.patch
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

