#
# Ylmf OS package build script
#

DESCRIPTION="A Python module to deal with freedesktop.org specifications"
HOMEPAGE="http://pyxdg.freedesktop.org/ http://people.freedesktop.org/~lanius/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://www.freedesktop.org/~lanius/"$N-$V".tar.gz "

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	dopatch ylmfos-skip-parse-kdelegacydirs.patch
	domake
}

pbs_install() {
	domkinstall
	dodoc AUTHORS ChangeLog COPYING INSTALL PKG-INFO README TODO
}

