#
# YLmf_OS package build script
#

DESCRIPTION=" C++ interface for pango"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/sources/pangomm/2.26/$N-$V.tar.bz2"

RDEPEND=""
BDEPEND=" cairomm glibmm pango"
RECOMMENDED=""

NOTES=" http://wiki.linuxfromscratch.org/blfs/wiki/pangomm"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	YPB_CONFIG+=" --prefix=/usr "
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
