#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="C++ interface for pango"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="GPL"
PACKAGER="StartOS Developers"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/sources/"$N"/2.26/"$N-$V".tar.bz2"

BDEPEND="cairomm glibmm pango"
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="" 
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

