#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION=" C++ interface for pango"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="GPL-2"
PACKAGER="StartOS Developers"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/sources/pangomm/2.26/$N-$V.tar.bz2"

RDEPEND=""
BDEPEND=" cairomm glibmm pango"
RECOMMENDED=""

NOTES=" http://wiki.linuxfromscratch.org/blfs/wiki/pangomm"

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	config+=" --prefix=/usr "
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
