#
# YLmf_OS package build script
#

DESCRIPTION=" C++ interface for pango"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"
 
SRC_URI=" http://ftp.gnome.org/pub/gnome/sources/"$N"/2.26/"$N-$V$R".tar.bz2"

RDEPEND="glibmm cairomm libsigc++ pango cairo pixman fontconfig libxml2 freetype directfb libpng
libxcb libXrender libX11 libxcb libXau libXdmcp zlib expat"
BDEPEND="${RDEPEND} cairomm glibmm pango"
RECOMMENDED=""

NOTES=" http://wiki.linuxfromscratch.org/blfs/wiki/pangomm"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-documentation" 
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
