#
# Ylmf OS package build script
#

DESCRIPTION="Package management system of Ylmf OS Linux"
HOMEPAGE="www.ylmf.net"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
PRIORITY="required"

INSTALL="$N.install"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="gawk cpio xz-utils sed coreutils git findutils procps psmisc bash bc glibc"
BDEPEND=""
RECOMMENDED="ypkg2 upx"

pbs_unpack() {
	dounpack
}

pbs_build() {
	git checkout develop 
	make
}

pbs_install() {
	domkinstall
}

