#
# YLmf_OS package build script
#

DESCRIPTION="Package management system for Ylmf_OS Linux"
HOMEPAGE="www.ylmf.net"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
PRIORITY="required"

INSTALL="$N.install"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="gawk cpio xz-utils sed coreutils git findutils procps psmisc bash bc glibc upx"
BDEPEND=""
RECOMMENDED="ypkg2"

pbs_unpack() {
	ypkg_unpack
}

pbs_build() {
	git checkout develop
	make
}

pbs_install() {
	ypkg_mkinstall
}

