#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An open-source JPEG 2000 codec written in C"
HOMEPAGE="http://www.openjpeg.org/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://openjpeg.googlecode.com/files/"${N}"_v1_3.tar.gz"

RDEPEND="gcc-lib"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install(){
	domkinstall
}

