#
# YLmf_OS package build script
#

DESCRIPTION="X.Org driver for tga cards"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://www.x.org/releases/X11R7.6/src/driver/"$N-$V$R".tar.bz2"

RDEPEND="glibc"
BDEPEND="glibc-dev xorg-server-dev"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
