#
# YLmf_OS package build script
#

DESCRIPTION="Perl interpreter-based threads"
HOMEPAGE="http://search.cpan.org/dist/threads/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://cpan.communilink.net/authors/id/J/JD/JDHEDDEN/threads-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
