#
# YLmf_OS package build script
#

DESCRIPTION="The OpenAL Utility Toolkit"
HOMEPAGE="http://www.openal.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://connect.creativelabs.com/openal/Downloads/ALUT/"$N-$V".tar.gz"

RDEPEND="glibc openal"
BDEPEND=" "

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

