#
# Ylmf OS package build script
#

DESCRIPTION="The OpenAL Utility Toolkit"
HOMEPAGE="http://www.openal.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://connect.creativelabs.com/openal/Downloads/ALUT/"$N-$V".tar.gz"

RDEPEND="glibc openal"
BDEPEND=" "

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

