#
# YLmf_OS package build script
#

DESCRIPTION="A commandline client for Music Player Daemon (media-sound/mpd)"
HOMEPAGE="http://www.multiprecision.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.multiprecision.org/"$N"/download/"$N-$V".tar.gz"

RDEPEND="glibc gmp mpfr"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	export EGREP="grep -E"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

