. /usr/lib/ybs/funcs

post_install() {
        gnome2_install_defaut_gconf "string" "/desktop/gnome/interface/gtk_theme"     "ylmfos"
	gnome2_install_defaut_gconf "string" "/apps/metacity/general/theme"           "ylmfos"
	gnome2_install_defaut_gconf "string" "/desktop/gnome/interface/toolbar_style" "icons"
	gnome2_install_defaut_gconf "float"  "/apps/compiz/plugins/decoration/allscreens/options/shadow_opacity" "1.0"
	gnome2_install_defaut_gconf "int"    "/apps/compiz/plugins/decoration/allscreens/options/shadow_radius"  "50"
	gnome2_install_defaut_gconf "int"    "/apps/compiz/plugins/decoration/allscreens/options/shadow_x_offset" "0"
	gnome2_install_defaut_gconf "int"    "/apps/compiz/plugins/decoration/allscreens/options/shadow_y_offset" "0"
}

post_upgrade() {
	post_install
}

