#
# YLmf_OS package build script
#

DESCRIPTION="Interfaces for Python"
HOMEPAGE="http://pypi.python.org/pypi/zope.interface"
REPO=""
LICENSE="ZPL 2.1"
PRIORITY=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://pypi.python.org/packages/source/z/zope.interface/"zope.interface-$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
