#
# YLmf_OS package build script
#

DESCRIPTION="A library to encapsulate CD-ROM reading and control"
HOMEPAGE="http://www.gnu.org/software/libcdio/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"
 
SRC_URI="http://ftp.gnu.org/gnu/"$N"/"$N-$V$R".tar.gz"

RDEPEND="gcc glibc libcddb ncurses"
BDEPEND="   "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README
}

pbs_postinst() {
	[ -x /usr/bin/install-info ] || return 0
	infodir=/usr/share/info
	install-info $infodir/libcdio.info.gz $infodir/dir 2>/dev/null
}

pbs_postrm() {
	[ -x /usr/bin/install-info ] || return 0
	infodir=/usr/share/info
	install-info --delete $infodir/libcdio.info.gz $infodir/dir 2>/dev/null
}
