#
# YLmf_OS package build script
#

DESCRIPTION="A library to encapsulate CD-ROM reading and control"
HOMEPAGE="http://www.gnu.org/software/libcdio/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"
 
SRC_URI="http://ftp.gnu.org/gnu/"$N"/"$N-$V$R".tar.gz"

RDEPEND="libcddb ncurses glibc"
BDEPEND="${RDEPEND} media-libs/libcddb"
RECOMMENDED="media-libs/libcddb"

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README
}
