#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A library to encapsulate CD-ROM reading and control"
HOMEPAGE="http://www.gnu.org/software/libcdio/"
LICENSE="GPLv3"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
 
SRC_URI="http://ftp.gnu.org/gnu/"$N"/"$N-$V".tar.gz"

RDEPEND="libcddb ncurses gcc-libs"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
    dounpack
}

pbs_patch() {
    dopatch libcdio-0.83-linking.patch
}

pbs_config() {
    config+="--disable-vcd-info --enable-cpp-progs"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    sed -i "/LIBCDIO_SOURCE_PATH/s|.*|/* #undef LIBCDIO_SOURCE_PATH */|" \
        "$PKGDIR"/usr/include/cdio/cdio_config.h
}
