#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The open source version of IntelliJ IDEA, a premier IDE for Java, Groovy and other programming languages."
HOMEPAGE="http://www.jetbrains.org/"
LICENSE="APACHE"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://download-ln.jetbrains.com/idea/ideaIC-"$V".tar.gz"
CHECKSUM="09f814cc26b6c98d6e5f0fdf2aaa293c"

RDEPEND="jdk jre"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
    dounpack
}

pbs_install() {
    docp * "$PKGDIR"/usr/share/"$N"/
    dodesktop "$N".desktop bin/idea.png
    doln /usr/share/idea-ic/bin/idea.sh "$PKGDIR"/usr/bin/"$N"
}

