#
# YLmf_OS package build script
#

DESCRIPTION="intel gpu userland tools"
HOMEPAGE="http://xorg.freedesktop.org/"
 
SRC_URI="http://xorg.freedesktop.org/releases/individual/app/$N-$V$R.tar.bz2"

RDEPEND=""
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	install -m755 -d "$YPPATH_DEST"/usr/share/doc/"$N-$V$R"
	cp -a README   "$YPPATH_DEST"/usr/share/doc/"$N-$V$R"
}
