#
# Ylmf OS package build script
#

DESCRIPTION="intel gpu userland tools"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://xorg.freedesktop.org/archive/individual/app/"$N-$V".tar.bz2"
CHECKSUM="08c860aa4d067c4ee10c5a672092f2d8"

RDEPEND="glibc libdrm libpciaccess"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}
