#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Contribution database for the m17n library"
HOMEPAGE="http://www.m17n.org/m17n-lib/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://www.m17n.org/m17n-lib-download/"$N-$V".tar.gz"
CHECKSUM="b4cae1ca81ec83d3d9c3f9dc45b0c12f"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

