#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl-compatible regular expression library"
HOMEPAGE="http://www.pcre.org/"
LICENSE="BSD"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="ftp://ftp.csx.cam.ac.uk/pub/software/programming/$N/$N-$V.tar.bz2"
CHECKSUM="62f02a76bb57a40bc66681760ed511d5"

RDEPEND="gcc-libs"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_config() {
	config+="--enable-pcre16 
             --enable-pcre32 
             --enable-jit 
             --enable-utf 
             --enable-unicode-properties"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc LICENCE
}

