#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GNU awk pattern-matching language"
HOMEPAGE="http://www.gnu.org/software/gawk/gawk.html"
 
SRC_URI="http://mirror.anl.gov/pub/gnu/"$N"/"$N-$V$R".tar.gz"

RDEPEND="glibc"
BDEPEND=""

PRIORITY="required"

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

