#
# YLmf_OS package build script
#

DESCRIPTION="GNU awk pattern-matching language"
HOMEPAGE="http://www.gnu.org/software/gawk/gawk.html"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
PRIORITY="required"

SRC_URI="http://mirror.anl.gov/pub/gnu/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""


INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

