#
# Ylmf OS package build script
#

DESCRIPTION="manager service for ylmfos"
HOMEPAGE="www.ylmf.net"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="dbus"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

