#
# Ylmf OS package build script
#

DESCRIPTION="Compizconfig Gconf Backend"
HOMEPAGE="http://www.compiz.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
REPO="testing"

SRC_URI="http://releases.compiz-fusion.org/0.8.4/"$N-$V$R".tar.bz2"

RDEPEND="gconf libcompizconfig"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc AUTHORS COPYING NEWS README
}
