#
# YLmf_OS package build script
#

DESCRIPTION="Compizconfig Gconf Backend"
HOMEPAGE="http://www.compiz.org/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"
REPO="testing"

SRC_URI="http://releases.compiz.org/"$V$R"/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" gconf libcompizconfig"
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

pbs_postinst() {
	gnome2_gconfd_reload
}
