#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl Module: Keyed-Hashing for Message Authentication."
HOMEPAGE="http://search.cpan.org/dist/$N"
LICENSE="GPL,PerlArtistic"
GROUP="perl"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://www.cpan.org/authors/id/G/GA/GAAS/Digest-HMAC-$V.tar.gz"
CHECKSUM="e6a5d6f552da16eacb5157ea4369ff9d"

RDEPEND="perl perl-digest-sha1"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}
