#
# Ylmf OS package build script
#

DESCRIPTION="Software for generating and retrieving SNMP data"
HOMEPAGE="http://net-snmp.sourceforge.net/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://downloads.sourceforge.net/project/$N/$N/$V/"$N-$V$R".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config="--prefix=/usr"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc *.txt
	doman *.1
}

