#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl wrappers for the eggdbus cup Gtk2::TrayIcon utilities."
HOMEPAGE="http://gtk2-perl.sf.net/"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="GPL,PerlArtistic"

SRC_URI="http://nchc.dl.sourceforge.net/project/gtk2-perl/Gtk2_TrayIcon/0.06/Gtk2-TrayIcon-"$V".tar.gz"

RDEPEND="gtk2-perl"
BDEPEND="extutils-depends extutils-pkgconfig"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

