#
# YLmf_OS package build script
#

DESCRIPTION="Perl wrappers for the eggdbus cup Gtk2::TrayIcon utilities."
HOMEPAGE="http://gtk2-perl.sf.net/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://nchc.dl.sourceforge.net/project/gtk2-perl/Gtk2_TrayIcon/0.06/Gtk2-TrayIcon-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}
