#
# YLmf_OS package build script
#

DESCRIPTION="C++ port of the famous JUnit framework for unit testing"
HOMEPAGE="http://cppunit.sourceforge.net/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://nchc.dl.sourceforge.net/project/cppunit/cppunit/1.12.1/cppunit-1.12.1.tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}


