#
# YLmf_OS package build script
#

DESCRIPTION="Mozilla's Network Security Services library that implements PKI support"
HOMEPAGE="http://www.mozilla.org/projects/security/pki/nss/"
LICENSE="GPL-2"

SRC_URI="http://ftp.mozilla.org/pub/mozilla.org/security/"$N"/releases/NSS_3_12_6_RTM/src/"$N-$V".tar.gz"

RDEPEND="glibc nspr sqlite zlib"
BDEPEND="   "

pbs_unpack() {
        ypkg_unpack
}

pbs_build() {
	export BUILD_OPT=1 
	export NSS_USE_SYSTEM_SQLITE=1 
	export NSPR_INCLUDE_DIR=/usr/include/nspr 
	export USE_SYSTEM_ZLIB=1 
	export ZLIB_LIBS=-lz 
	ypkg_patch "$N-$V"-standalone-1.patch 
	make -C mozilla/security/nss nss_build_all
}

pbs_install() {
	NSS_LINUXDIR="Linux2.6_x86_glibc_PTH_OPT.OBJ"
	cd mozilla/dist 
	for i in $(ls "$NSS_LINUXDIR"/lib/*.so); do
		ypkg_docp $(readlink -f "$i") "$YPPATH_DEST"/usr/lib 
	done
	for i in $(ls "$NSS_LINUXDIR"/lib/{*.chk,libcrmf.a}); do
		ypkg_docp $(readlink -f "$i") "$YPPATH_DEST"/usr/lib 
	done
	for i in $(ls "$NSS_LINUXDIR"/bin/{certutil,nss-config,pk12util}); do
		ypkg_docp $(readlink -f "$i") "$YPPATH_DEST"/usr/bin 
	done
	for i in $(ls {public,private}/nss/*); do
		ypkg_docp $(readlink -f "$i") "$YPPATH_DEST"/usr/include/nss
	done
	ypkg_docp "$(readlink -f "$NSS_LINUXDIR"/lib/pkgconfig/nss.pc)" "$YPPATH_DEST"/usr/lib/pkgconfig 	#
	cd "$YPPATH_DEST"/
	ypkg_doln /usr/lib/libnss3.so      usr/lib/libnss3.so.1d
	ypkg_doln /usr/lib/libnssutil3.so  usr/lib/libnssutil3.so.1d
	ypkg_doln /usr/lib/libsmime3.so    usr/lib/libsmime3.so.1d
}
