#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Mozilla's Network Security Services library that implements PKI support"
HOMEPAGE="http://www.mozilla.org/projects/security/pki/nss/"
LICENSE="GPL,MPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="ftp://ftp.mozilla.org/pub/security/nss/releases/NSS_${V//./_}_RTM/src/"$N-$V".tar.gz"
CHECKSUM="b326c2be8df277f62fb9c65fb3428148"

RDEPEND="nspr(>=4.9.4) glibc zlib sqlite"
BDEPEND=""

pbs_unpack() {
    dounpack
}

pbs_patch() {
    # Add CAcert and spi-inc.org CA certificates.
    # See http://wiki.cacert.org/NSSLib for how to generate
    dopatch add_spi+cacert_ca_certs.patch
    # Adds transitional SSL renegotiate support - patch from Debian
    dopatch ssl-renegotiate-transitional.patch
    # Respect LDFLAGS
    sed -e 's/\$(MKSHLIB) -o/\$(MKSHLIB) \$(LDFLAGS) -o/g' \
        -i mozilla/security/coreconf/rules.mk
}

pbs_build() {
    # Generate certdata.c from certdata.txt
    cd mozilla/security/nss/lib/ckfw/builtins
    make generate
    
    cd "$SRCDIR"
    export BUILD_OPT=1
    export PKG_CONFIG_ALLOW_SYSTEM_LIBS=1
    export PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1
    export NSS_USE_SYSTEM_SQLITE=1
    export NSS_ENABLE_ECC=1
    export NSPR_INCLUDE_DIR=`pkg-config --cflags-only-I nspr | sed 's/-I//'`
    export NSPR_LIB_DIR=`pkg-config --libs-only-L nspr | sed 's/-L.//'`
    export XCFLAGS="${CFLAGS}"

    [ "$ARCH" = "x86_64" ] && export USE_64=1

    make -j 1 -C mozilla/security/coreconf
    make -j 1 -C mozilla/security/dbm
    make -j 1 -C mozilla/security/nss
}

pbs_install() {
    install -m755 -d "$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/pkgconfig
    install -m755 -d "$PKGDIR"/usr/bin
    install -m755 -d "$PKGDIR"/usr/include/nss
    
    NSS_VMAJOR=`grep "#define.*NSS_VMAJOR" mozilla/security/nss/lib/nss/nss.h | awk '{print $3}'`
        NSS_VMINOR=`grep "#define.*NSS_VMINOR" mozilla/security/nss/lib/nss/nss.h | awk '{print $3}'`
    NSS_VPATCH=`grep "#define.*NSS_VPATCH" mozilla/security/nss/lib/nss/nss.h | awk '{print $3}'`

    sed "$FILESDIR"/nss.pc.in \
              -e "s,%libdir%,/usr/lib"$LIBDIRSUFFIX",g" \
                  -e "s,%prefix%,/usr,g" \
              -e "s,%exec_prefix%,/usr/bin,g" \
              -e "s,%includedir%,/usr/include/nss,g" \
              -e "s,%NSPR_VERSION%,${V},g" \
              -e "s,%NSS_VERSION%,${V},g" \
               > "$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/pkgconfig/nss.pc
    doln nss.pc "$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/pkgconfig/mozilla-nss.pc
    chmod 644 "$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/pkgconfig/*.pc

    sed "$FILESDIR"/nss-config.in \
                      -e "s,@libdir@,/usr/lib"$LIBDIRSUFFIX",g" \
                         -e "s,@prefix@,/usr/bin,g" \
              -e "s,@exec_prefix@,/usr/bin,g" \
              -e "s,@includedir@,/usr/include/nss,g" \
              -e "s,@MOD_MAJOR_VERSION@,${NSS_VMAJOR},g" \
              -e "s,@MOD_MINOR_VERSION@,${NSS_VMINOR},g" \
              -e "s,@MOD_PATCH_VERSION@,${NSS_VPATCH},g" \
               > "$PKGDIR"/usr/bin/nss-config
    chmod 755 "$PKGDIR"/usr/bin/nss-config
    
    for file in libsoftokn3.so libfreebl3.so libnss3.so libnssutil3.so \
        libssl3.so libsmime3.so libnssckbi.so libnssdbm3.so; do
        install -m755 mozilla/dist/*.OBJ/lib/"${file}" "$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/
    done

    install -m644 mozilla/dist/*.OBJ/lib/libcrmf.a "$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/
    install -m644 mozilla/dist/*.OBJ/lib/*.chk "$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/

    for file in certutil cmsutil crlutil modutil pk12util shlibsign signtool signver ssltap; do
        install -m755 mozilla/dist/*.OBJ/bin/${file} "$PKGDIR"/usr/bin/
    done

    install -m644 mozilla/dist/public/nss/*.h "$PKGDIR"/usr/include/nss/
}

