#!/bin/bash
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/distccd
NAME=distccd
DAEMON_ARGS="--pid-file=/run/$NAME.pid --daemon --user nobody"

# please change those variables by overriding them in /etc/defaults/distcc
ALLOWEDNETS=""
LISTENER=""
NICE=""
ZEROCONF=""

# Reads config file (will override defaults above)
[ -r /etc/default/distcc ] && . /etc/default/distcc

test -x $DAEMON || exit 0

# construct access list
ALLOW=""
for net in $ALLOWEDNETS
do
	ALLOW="$ALLOW --allow $net"
done

if test -n "$ALLOW"; then
        DAEMON_ARGS="$DAEMON_ARGS $ALLOW"
fi

if test -n "$LISTENER"; then
        DAEMON_ARGS="$DAEMON_ARGS --listen $LISTENER"
fi

if test -n "$NICE"; then
        if [ "$NICE" -gt 0 ] && [ "$NICE" -le 20 ]; then
	                DAEMON_ARGS="$DAEMON_ARGS --nice $NICE"
	fi
fi

if test -n "$JOBS"; then
	DAEMON_ARGS="$DAEMON_ARGS --jobs $JOBS"
fi

if [ "$ZEROCONF" = "true" ] || [ "$ZEROCONF" = "YES" ]; then
	DAEMON_ARGS="$DAEMON_ARGS --zeroconf"
fi

$DAEMON $DAEMON_ARGS 
