#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GtkSharp's gnome-desktop module of the gnome-desktop-sharp tarball"
HOMEPAGE="http://www.mono-project.com/GtkSharp"
LICENSE="LGPL"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.32/2.32.1/sources/"$N-$V".tar.bz2"

RDEPEND="gnome-sharp gnome-panel gtkhtml gtksourceview vte"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

