#
# YLmf_OS package build script
#

DESCRIPTION="GtkSharp's gnome-desktop module of the gnome-desktop-sharp tarball"
HOMEPAGE="http://www.mono-project.com/GtkSharp"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.32/2.32.1/sources/"$N-$V".tar.bz2"

RDEPEND=""
BDEPEND="gnome-sharp"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

