#
# Ylmf OS package build script
#

DESCRIPTION="X.Org Xv library"
HOMEPAGE="http://www.x.org/wiki/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://xorg.freedesktop.org/archive/individual/lib/"$N-$V".tar.bz2"
CHECKSUM="e292445a64b63e918bbc8b6aae6391dd"

RDEPEND="glibc libX11 libXau libxcb libXdmcp libXext"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

