#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Professional IDE (Integrated Development Environment) for Web and PHP developers."
HOMEPAGE="http://www.jetbrains.com/products.html"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
YARCH="any"

SRC_URI="http://download-ln.jetbrains.com/webide/PhpStorm-"$V".tar.gz"
CHECKSUM="d7913aa7ee7dafb7ef7c232a0eb5ddd3"

RDEPEND="jdk jre"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_install() {
	docp * "$destdir"/usr/share/"$N"/
	dodesktop "$N".desktop bin/webide.png
	doln /usr/share/phpstorm/bin/phpstorm.sh "$destdir"/usr/bin/"$N"
}

