#
# YLmf_OS package build script
#

DESCRIPTION="X C-language Bindings sample implementations"
HOMEPAGE="http://xcb.freedesktop.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://xcb.freedesktop.org/dist/"$N-$V".tar.bz2"

RDEPEND="glibc libXau libxcb libXdmcp"
BDEPEND="gperf"
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

