#
# YLmf_OS package build script
#

DESCRIPTION="X C-language Bindings sample implementations"
HOMEPAGE="http://xcb.freedesktop.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://xcb.freedesktop.org/dist/"$N-$V".tar.bz2"

RDEPEND="glibc libXau libxcb libXdmcp"
BDEPEND="gperf"
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

