#
# YLmf_OS package build script
#

DESCRIPTION="gio sharp tarball"
HOMEPAGE="http://banshee.fm/download/development/"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://github.com/mono/gio-sharp.git"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	./autogen-2.22.sh
	config+=""
	doconfig
}

pbs_build() {
	make
}

pbs_install() {
	domkinstall
}
