#
# YLmf_OS package build script
#

DESCRIPTION="X.Org cursor themes: whiteglass, redglass and handhelds"
HOMEPAGE="http://xorg.freedesktop.org/"
 
SRC_URI="http://xorg.freedesktop.org/releases/individual/data/$N-$V$R.tar.bz2"

RDEPEND=""
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	YPB_CONFIG+=" --prefix=/usr --sysconfdir=/etc --mandir=/usr/share/man --localstatedir=/var "
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	install -m755 -d "$YPPATH_DEST"/usr/share/doc/"$N-$V$R"
	cp -a ChangeLog COPYING README   "$YPPATH_DEST"/usr/share/doc/"$N-$V$R"
}
