#
# Ylmf OS package build script
#

DESCRIPTION="X.Org cursor themes: whiteglass, redglass and handhelds"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"
OPINION="nodev"

SRC_URI="http://www.x.org/releases/X11R7.6/src/data/"$N-$V".tar.bz2"

RDEPEND=""
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

