#
# YLmf_OS package build script
#

DESCRIPTION="X.Org cursor themes: whiteglass, redglass and handhelds"
HOMEPAGE="http://xorg.freedesktop.org/"
 
SRC_URI="http://www.x.org/releases/X11R7.6/src/data/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

pbs_postinst() {
	gnome2_icon_cache_update "whiteglass" "redglass" "handhelds"
}
