#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Mercurial is a free, distributed source control management tool"
HOMEPAGE="http://mercurial.selenic.com/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://mercurial.selenic.com/release/"$N-$V".tar.gz"
CHECKSUM="e0a8cfca69aa4003ea3187aed609d5e0"

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

