#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Mercurial is a free, distributed source control management tool"
HOMEPAGE="http://mercurial.selenic.com/"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="StartOS Developers"

SRC_URI="http://mercurial.selenic.com/release/mercurial-1.8.1.tar.gz"

RDEPEND="python"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
