#
# Ylmf OS package build script
#

DESCRIPTION="Port of CLooG (Chunky LOOp Generator) to PPL (Parma Polyhedra Library)"
HOMEPAGE="http://repo.or.cz/w/cloog-ppl.git"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://mirrors-us.seosue.com/gcc/infrastructure/"$N-$V$R".tar.gz"

RDEPEND="ppl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--with-gmp --with-ppl"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

