#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python Bindings for Alsa lib"
HOMEPAGE="http://alsa-project.org/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="ftp://ftp.alsa-project.org/pub/"$N"/"$N-$V".tar.bz2"
CHECKSUM=""

RDEPEND="alsa-lib glibc python"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

