#
# YLmf_OS package build script
#

DESCRIPTION="Python bindings for libsexy."
HOMEPAGE="http://www.chipx86.com/wiki/Libsexy"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://releases.chipx86.com/libsexy/"$N"/"$N-$V$R".tar.gz"

RDEPEND="atk cairo expat fontconfig freetype gcc glib2 glibc gtk+ libpng libsexy libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libxml2 libXrandr libXrender pango pixman zlib"
BDEPEND="pygtk-dev atk-dev cairo-dev expat-dev fontconfig-dev freetype-dev gcc-dev glib2-dev glibc-dev gtk+-dev libpng-dev libsexy-dev libX11-dev libXau-dev libxcb-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXi-dev libxml2-dev libXrandr-dev libXrender-dev pango-dev pixman-dev zlib-dev"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-static --enable-shared "
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README
}
