#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Serial Communication Program"
HOMEPAGE="http://alioth.debian.org/projects/minicom"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://alioth.debian.org/frs/download.php/3487/"$N-$V".tar.gz"

RDEPEND="ncurses"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

