#
# YLmf_OS package build script
#

DESCRIPTION="XSel is a command-line program for getting and setting the contents of the X selection."
HOMEPAGE="http://www.vergenet.net/~conrad/software/xsel"
 
SRC_URI="http://www.vergenet.net/~conrad/software/"$N"/download/"$N-$V$R".tar.gz"

RDEPEND=""
BDEPEND="${RDEPEND}"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build()  {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
