#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A Python library to provide easy scripting with Jabber"
HOMEPAGE="http://xmpppy.sourceforge.net/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://downloads.sourceforge.net/project/$N/$N/$V$R/"$N-$V"rc1.tar.gz"
CHECKSUM="e0d2b3f9e4a278c163431e64adb0c861"

RDEPEND="python"
BDEPEND="distribute"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

