#
# YLmf_OS package build script
#

DESCRIPTION="Musepack decoding library"
HOMEPAGE="http://musepack.net/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://files.musepack.net/source/"$N-$V$R".tar.bz2"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc COPYING
}

