#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="C++ interface for GTK+2"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/sources/"$N"/${V%.*}/"$N-$V".tar.xz"
CHECKSUM="c90c7a29c20dd6d795925bd66ad1ff40be07cea0e4c03f4d6105a8c07448953d"

RDEPEND="atkmm gtk2 pangomm"
BDEPEND="gtk2 pangomm atkmm" 
RECOMMENDED=""
ALIAS="gtkmm2"

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

