#
# YLmf_OS package build script
#

DESCRIPTION="C++ interface for GTK+2"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/sources/"$N"/2.20/"$N-$V".tar.bz2 "

RDEPEND="atk atkmm cairo cairomm expat fontconfig freetype gcc gdk-pixbuf glib2 glibc glibmm gtk+ libpng libsigc++ libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender pango pangomm pixman zlib"
BDEPEND="" 
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-documentation"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc NEWS README ChangeLog COPYING INSTALL
}

