#
# Ylmf OS package build script
#

DESCRIPTION="C++ interface for GTK+2"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/sources/gtkmm/2.18/$N-$V.tar.bz2"

RDEPEND=""
BDEPEND=" gtk+ pangomm"
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/gtkmm"

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	config+=" --prefix=/usr "
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
