#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl/CPAN Error module - Error/exception handling in an OO-ish way"
HOMEPAGE="http://search.cpan.org/dist/Error/"
LICENSE="GPL,PerlArtistic"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://mirrors.sohu.com/CPAN/authors/id/S/SH/SHLOMIF/Error-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
        perl_cleanup
}

