#
# Ylmf OS package build script
#

DESCRIPTION="Streaming media framework"
HOMEPAGE="http://gstreamer.sourceforge.net"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/gstreamer/0.10/"$N-$V".tar.xz"

RDEPEND="glib2 glibc libxml2 zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-docbook --disable-tests"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

