#
# YLmf_OS package build script
#

DESCRIPTION="Streaming media framework"
HOMEPAGE="http://gstreamer.sourceforge.net"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://gstreamer.freedesktop.org/src/"$N"/"$N-$V$R".tar.bz2"

RDEPEND="glib2 glibc libxml2 zlib"
BDEPEND="   "
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=" --disable-docbook --disable-tests"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
