#
# Ylmf OS package build script
#

DESCRIPTION="Introspection infrastructure for gobject library bindings"
HOMEPAGE="http://live.gnome.org/GObjectIntrospection/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
 
SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/gobject-introspection/0.6/$N-$V.tar.bz2"

RDEPEND="glib2 libffi python"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	config+=" --prefix=/usr   "
	doconfig
}

pbs_build() {
	make
}

pbs_check() {
	make check
}

pbs_install() {
	domkinstall
}
