#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Introspection infrastructure for gobject library bindings"
HOMEPAGE="http://live.gnome.org/GObjectIntrospection/"
LICENSE="GPL"
PACKAGER="StartOS Developers"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/sources/"$N"/0.10/"$N-$V".tar.bz2"

RDEPEND="glib2"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build(){
	make
}

pbs_install() {
	domkinstall
}

