#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Introspection infrastructure for gobject library bindings"
HOMEPAGE="http://live.gnome.org/GObjectIntrospection/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
 
SRC_URI=" http://download.gnome.org/sources/gobject-introspection/0.6/$N-$V.tar.bz2 "

RDEPEND="glib2 gdk-pixbuf libffi python"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	config+=" --prefix=/usr  --disable-static --disable-tests"
	doconfig
}

pbs_build(){
	make
}

pbs_install() {
	domkinstall
}
