#
# YLmf_OS package build script
#

DESCRIPTION="Introspection infrastructure for gobject library bindings"
HOMEPAGE="http://live.gnome.org/GObjectIntrospection/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"
 
SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/gobject-introspection/0.6/$N-$V.tar.bz2"

RDEPEND=""
BDEPEND="${RDEPEND} glib2 libffi python"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	YPB_CONFIG+=" --prefix=/usr  "
	ypkg_config
}

pbs_build() {
	make
}

pbs_check() {
	make check
}

pbs_install() {
	ypkg_mkinstall
}
