#
# Ylmf OS package build script
#

DESCRIPTION="A strong and fast cryptography toolki"
HOMEPAGE="http://sourceforge.net/projects/beecrypt/"
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://downloads.sourceforge.net/sourceforge/"$N"/"$N-$V".tar.gz"
CHECKSUM="8441c014170823f2dff97e33df55af1e"

RDEPEND="gcc-lib glibc icu"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}


