#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="D-Bus bindings for glib"
HOMEPAGE="http://dbus.freedesktop.org/"
 
SRC_URI="http://dbus.freedesktop.org/releases/"$N"/"$N-$V$R".tar.gz"

RDEPEND=""

RDEPEND="dbus expat glib2 gdk-pixbuf glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--libexecdir=/usr/lib/dbus-1.0/dbus-1"
	doconfig
}

pbs_install() {
	domkinstall
	doln /usr/include/dbus-1.0/dbus "$destdir"/usr/include/dbus
}
