#
# YLmf_OS package build script
#

DESCRIPTION="Point-to-Point Protocol (PPP)"
HOMEPAGE="http://www.samba.org/ppp"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://samba.org/ftp/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc libpcap"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	make DESTDIR="$YPPATH_DEST"/usr install
	make DESTDIR="$YPPATH_DEST"/usr install-etcppp
}

