#
# Ylmf OS package build script
#

DESCRIPTION="Point-to-Point Protocol (PPP)"
HOMEPAGE="http://www.samba.org/ppp"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://samba.org/ftp/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc libpcap"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	make DESTDIR="$destdir"/usr install
	make DESTDIR="$destdir"/usr install-etcppp
}

