#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A tool that makes it easy to create Python bindings for C and C++ libraries"
HOMEPAGE="http://www.riverbankcomputing.com/software/sip/"
LICENSE="custom,sip"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://downloads.sourceforge.net/pyqt/$N-$V.tar.gz"

RDEPEND="python"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    python configure.py CFLAGS="${CFLAGS}" LFLAGS="${LDFLAGS}"
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodoc LICENSE
}

