#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="SIP is an extension module generator similar to SWIG but is specifically designed for creating Python modules"
HOMEPAGE="http://pypi.python.org/pypi/SIP"
REPO=""
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://www.riverbankcomputing.com/static/Downloads/sip4/sip-4.12.3.tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    python configure.py CFLAGS="${CFLAGS}" LFLAGS="${LDFLAGS}"
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodoc LICENSE
}
