#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="C# bindings for gtkmozembed"
HOMEPAGE="http://www.mono-project.com/"
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://go-mono.com/sources/"$N"/"$N-$V".tar.bz2"

RDEPEND="xulrunner gtk-sharp"
RECOMMENDED=""
BDEPEND="mono"
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

