#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A Post-Processor for SGMLS and NSGMLS"
HOMEPAGE="http://search.cpan.org/dist/SGMLSpm"
LICENSE="GPL,PerlArtistic"
GROUP="perl"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://www.cpan.org/authors/id/D/DM/DMEGG/SGMLSpm-"$V"ii.tar.gz"
CHECKSUM="5bcb197fd42e67d51c739b1414d514a7"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_patch() {
    mkdir -p "$PKGDIR"/usr/bin \
             "$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/perl5/vendor_perl \
             "$PKGDIR"/usr/share/doc/perl-sgmls
}

pbs_install() {
    make install \
         BINDIR="$PKGDIR"/usr/bin \
         PERL5DIR="$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/perl5/vendor_perl \
         HTMLDIR="$PKGDIR"/usr/share/doc/perl-sgmls
    perl_cleanup
}
