#
# Ylmf OS package build script
#

DESCRIPTION=="X.Org Xfont library"
HOMEPAGE="http://www.x.org/wiki/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://xorg.freedesktop.org/archive/individual/lib/"$N-$V".tar.bz2"
CHECKSUM="6851da5dae0a6cf5f7c9b9e2b05dd3b4"

RDEPEND="freetype glibc libfontenc zlib"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

