#
# Ylmf OS package build script
#

DESCRIPTION="Easily build XS extensions that depend on XS extensions"
HOMEPAGE="http://search.cpan.org/~flora/ExtUtils-Depends-0.304/lib/ExtUtils/Depends.pm"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/F/FL/FLORA/ExtUtils-Depends-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
