#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="a strictly RFC 3986 compliant URI parsing library written in C"
HOMEPAGE="http://uriparser.sourceforge.net/"
LICENSE="custom"
PACKAGER="StartOS Developers"
 
SRC_URI="http://downloads.sourceforge.net/project/"$N"/Sources/"$V"/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND="cpptest"

pbs_unpack() {
        dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    ln -sf "$PWD"/doc/Doxyfile.in doc/Doxyfile
    domake
}

pbs_install() {
    domkinstall
}

