#
# Ylmf OS package build script
#

DESCRIPTION="a strictly RFC 3986 compliant URI parsing library written in C"
HOMEPAGE="http://uriparser.sourceforge.net/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="http://downloads.sourceforge.net/project/"$N"/Sources/"$V"/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND="cpptest"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	ln -sf "$PWD"/doc/Doxyfile.in doc/Doxyfile
	domake
}

pbs_install() {
	domkinstall
}

