#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Interface to Bzip2 compression library"
HOMEPAGE="http://search.cpan.org/dist/Compress-Bzip2"
LICENSE="GPL,PerlArtistic"
GROUP="perl"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/A/AR/ARJAY/Compress-Bzip2-$V.tar.gz"

RDEPEND="perl bzip2"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}
