#
# Ylmf OS package build script
#

DESCRIPTION="Analyzes Python code looking for bugs and signs of poor quality"
HOMEPAGE="http://www.logilab.org/project/pylint"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.logilab.org/pub/"$N"/"$N-$V$R".tar.gz"

RDEPEND="python"
BDEPEND="distribute"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

