. /usr/lib/ybs/funcs

files="/etc/gconf/schemas/brasero.schemas"

post_install() {
	gnome2_install_schema $files
	gnome2_desktop_database_update
	gnome2_icon_cache_update
	gnome2_gconfd_reload
}

pre_remove() {
	gnome2_uninstall_schema $files
}

post_remove() {
	gnome2_desktop_database_update
	gnome2_icon_cache_update
	gnome2_gconfd_reload
}

post_upgrade() {
	post_remove
}

post_downgrade() {
	post_remove
}

