#!/bin/bash
#

file=/etc/lsb-release

source $file

usage()
{
cat <<__end
Usage: lsb_release [options]

Options:
  -h, --help         show this help message and exit
  -v, --version      show LSB modules this system supports
  -i, --id           show distributor ID
  -d, --description  show description of this distribution
  -r, --release      show release number of this distribution
  -c, --codename     show code name of this distribution
  -a, --all          show all of the above information
  -s, --short        show requested information in short format
__end
exit 0
}

while test -n "$1"
do
case "$1" in
-h|--help)
usage
;;

-v|--release)
ver='yes'
;;

-i|--id)
id='yes'
;;

-d|--description)
desc='yes'
;;

-r|--release)
rel='yes'
;;

-c|--code)
cd='yes'
;;

-a|--all)
ver="yes"
id="yes"
desc="yes"
rel="yes"
cd="yes"
;;

-s|--short)
short='yes'
;;

*)
echo "unknown option $1"
exit 1;;

esac
shift
done

if test x$id == xyes;then
	if !(test x$short == xyes);then
		rs=${rs}"Distributor ID:\t"
	fi
	rs=${rs}"$DISTRIB_ID\n"
fi

if test x$desc == xyes;then
	if !(test x$short == xyes);then
		rs=${rs}"Description:\t"
	fi
	rs=${rs}"${DISTRIB_DESCRIPTION}\n"
fi

if test x$rel == xyes;then
	if !(test x$short == xyes);then
		rs=${rs}"Release:\t"
	fi
	rs=${rs}"$DISTRIB_RELEASE\n"
fi

if test x$cd == xyes;then
	if !(test x$short == xyes);then
		rs=${rs}"Codename:\t"
	fi
	rs=${rs}"$DISTRIB_CODENAME\n"
fi

test "x$rs" == x && ver='yes'

if test x$ver == xyes;then
	rs="No LSB modules are available.\n"${rs}
fi

echo -e -n $rs
exit 0
