#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Provides simple control over terminal driver modes"
HOMEPAGE="http://search.cpan.org/~stsi/TermReadKey/"
LICENSE="GPL PerlArtistic"
PACKAGER="StartOS Developers"
YARCH="any"

SRC_URI="http://cpan.wenzk.com/authors/id/S/ST/STSI/TermReadKey-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

