#
# Ylmf OS package build script
#

DESCRIPTION="GLib-based library for accessing online service APIs using the GData protocol"
HOMEPAGE="http://live.gnome.org/libgdata"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/libgdata/0.6/"$N-$V".tar.bz2"

RDEPEND="dbus gconf glib2 glibc gnutls libgcrypt libgnome-keyring libgpg-error libproxy libsoup libtasn1 libxml2 orbit sqlite zlib"
RECOMMENDED=""
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

