#
# YLmf_OS package build script
#

DESCRIPTION="Hardware Monitoring user-space utilities"
HOMEPAGE="http://www.lm-sensors.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://dl.lm-sensors.org/"$N"/releases/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" sysfsutils"
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall PREFIX=/usr MANDIR=/usr/share/man LIBDIR=/usr/lib 
	ypkg_dodoc COPYING INSTALL README
}
