#
# Ylmf OS package build script
#

DESCRIPTION="Hardware Monitoring user-space utilities"
HOMEPAGE="http://www.lm-sensors.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://dl.lm-sensors.org/"$N"/releases/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" sysfsutils"
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall PREFIX=/usr MANDIR=/usr/share/man LIBDIR=/usr/lib 
	dodoc COPYING INSTALL README
}
