#
# YLmf_OS package build script
#

DESCRIPTION="XML::Simple - Easy API to read/write XML (esp config files)"
HOMEPAGE="http://search.cpan.org/dist/XML-Simple/"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://search.cpan.org/CPAN/authors/id/G/GR/GRANTM/XML-Simple-"$V".tar.gz"

RDEPEND="perl xml-parser"
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}
