#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="XML::Simple - Easy API to read/write XML (esp config files)"
HOMEPAGE="http://search.cpan.org/dist/XML-Simple/"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>
          chenqixing@ivali.com"
LICENSE="PerlArtistic"
YARCH="any"

SRC_URI="http://search.cpan.org/CPAN/authors/id/G/GR/GRANTM/XML-Simple-"$V".tar.gz"

RDEPEND="perl xml-parser"
BDEPEND=""
OPTIONAL="gawk: to use Simple.pm"

pbs_unpack() {
    dounpack
}

pbs_config() {
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}
