#
# YLmf_OS package build script
#

DESCRIPTION="X.Org DRI2 protocol headers"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
REPO=""

SRC_URI="http://www.x.org/releases/individual/proto/dri2proto-2.6.tar.bz2"

RDEPEND=""
BDEPEND=""
OPINION="nodev"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {	
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
