#
# Ylmf OS package build script
#

DESCRIPTION="Network Audio System"
HOMEPAGE="http://radscan.com/nas.html"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://downloads.sourceforge.net/project/"$N"/"$N"/nas%201.9.2/"$N-$V$R".src.tar.gz"

RDEPEND=""
BDEPEND="imake"
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

