#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A C library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result."
HOMEPAGE="http://www.multiprecision.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://www.multiprecision.org/mpc/download/mpc-"$V".tar.gz"
CHECKSUM="0d6acab8d214bd7d1fbbc593e83dd00d"

RDEPEND="glibc gmp mpfr"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	export EGREP="grep -E"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

