#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A C library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result."
HOMEPAGE="http://www.multiprecision.org/"
LICENSE="LGPL"
PACKAGER="StartOS Developers"

SRC_URI="http://www.multiprecision.org/mpc/download/mpc-"$V".tar.gz"
CHECKSUM="b32a2e1a3daa392372fbd586d1ed3679"

RDEPEND="mpfr(>=3.0.0)"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

