#
# Ylmf OS package build script
#

DESCRIPTION="The Cyrus SASL (Simple Authentication and Security Layer)."
HOMEPAGE="http://asg.web.cmu.edu/sasl/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="ftp://ftp.andrew.cmu.edu/pub/cyrus-mail/"$N-$V".tar.gz"

RDEPEND="berkeley-db e2fsprogs glibc keyutils krb5 openssl pam zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	sed -i "/elif/s/WITH_DES/defined &/" plugins/digestmd5.c
	config+="--with-dbpath=/var/lib/sasl/sasldb2 --with-saslauthd=/var/run"
	doconfig
}

pbs_build() {
	domake 
}

pbs_install() {
	domkinstall
	install -m700 -d "$destdir"/var/lib/sasl
}

