#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The Cyrus SASL (Simple Authentication and Security Layer)."
HOMEPAGE="http://asg.web.cmu.edu/sasl/"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>
          chenqixing@ivali.com"
 
SRC_URI="ftp://ftp.andrew.cmu.edu/pub/cyrus-mail/"$N-$V".tar.gz"
CHECKSUM="341cffe829a4d71f2a6503d669d5a946"

RDEPEND="pam krb5"
BDEPEND="postgresql-libs libmysqlclient openldap krb5 openssl"
RECOMMENDED=""

OPTIONS="nolibtool"

pbs_unpack() {
    dounpack
}

pbs_patch() {
    dopatch 0027_db5_support.patch
}

pbs_config() {
    config+="--with-plugindir=/usr/lib$LIBDIRSUFFIX/sasl2
             --with-pam
             --disable-static
             --with-saslauthd=/run/saslauthd
             --with-devrandom=/dev/urandom"
    doconfig
}

pbs_build() {
    make 
}

pbs_install() {
    domkinstall sasldir=/usr/lib"$LIBDIRSUFFIX"/sasl2
    cd "$destdir"    
    dounit saslauthd.service
    docp "$filesdir"/saslauthd etc/default/
    docp "$filesdir"/saslauthd.conf usr/lib/tmpfiles.d/
}

