#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The Cyrus SASL (Simple Authentication and Security Layer)."
HOMEPAGE="http://asg.web.cmu.edu/sasl/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
 
SRC_URI="ftp://ftp.andrew.cmu.edu/pub/cyrus-mail/"$N-$V".tar.gz"

RDEPEND="berkeley-db e2fsprogs glibc keyutils krb5 openssl pam zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_patch() {
	dopatch 0027_db5_support.patch
}

pbs_config() {
	config+="--with-dbpath=/var/lib/sasl/sasldb2 
	         --with-saslauthd=/var/run"
	doconfig
}

pbs_build() {
	make 
}

pbs_install() {
	domkinstall
	install -m700 -d "$destdir"/var/lib/sasl
}

