#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The Cyrus SASL (Simple Authentication and Security Layer)."
HOMEPAGE="http://asg.web.cmu.edu/sasl/"
LICENSE="GPL-2"
PACKAGER="StartOS Developers"
 
SRC_URI="ftp://ftp.andrew.cmu.edu/pub/cyrus-mail/"$N-$V$R".tar.gz"

RDEPEND="berkeley-db glibc keyutils krb5 openssl pam"
BDEPEND="     "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	sed -i "/elif/s/WITH_DES/defined &/" plugins/digestmd5.c
	config+="--with-dbpath=/var/lib/sasl/sasldb2 --with-saslauthd=/var/run"
	doconfig
}

pbs_build() {
	domake 
}

pbs_install() {
	domkinstall
	dodoc doc/{*.{html,txt,fig},ONEWS,TODO} saslauthd/LDAP_SASLAUTHD
	doinit $filesdir/"$N"
	install -m700 -d "$destdir"/var/lib/sasl
}
