#
# YLmf_OS package build script
#

DESCRIPTION="The Cyrus SASL (Simple Authentication and Security Layer)."
HOMEPAGE="http://asg.web.cmu.edu/sasl/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="ftp://ftp.andrew.cmu.edu/pub/cyrus-mail/"$N-$V".tar.gz"

RDEPEND="berkeley-db e2fsprogs glibc keyutils krb5 openssl pam zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	sed -i "/elif/s/WITH_DES/defined &/" plugins/digestmd5.c
	YPB_CONFIG+="--with-dbpath=/var/lib/sasl/sasldb2 --with-saslauthd=/var/run"
	ypkg_config
}

pbs_build() {
	ypkg_make 
}

pbs_install() {
	ypkg_mkinstall
	install -m700 -d "$YPPATH_DEST"/var/lib/sasl
}

