#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="anjuta extras" 
HOMEPAGE="http://www.anjuta.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/"$N"/2.32/"$N-$V".tar.bz2"

RDEPEND="anjuta"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-schemas-install"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}


