#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An asynchronous networking framework written in Python"
HOMEPAGE="http://pypi.python.org/pypi/Twisted"
LICENSE="MIT"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"

SRC_URI="http://pypi.python.org/packages/source/T/Twisted/Twisted-"$V".tar.bz2"
CHECKSUM="c51834c1270e7a4bb0de9190056e4317413920f9"

RDEPEND="python glibc py-crypto py-zope-interface"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""
OPTIONAL="py-openssl:
          py-soappy: for twisted.web.soap
          pyasn1: for using conch
          pygtk: for using manhole
          tk: for using tkconch"

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall --optimize=1
    dodoc LICENSE
}
