#
# YLmf_OS package build script
#

DESCRIPTION="sunpinyin ibus wrapper"
HOMEPAGE="http://code.google.com/p/sunpinyin/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://github.com/sunpinyin/sunpinyin.git"

RDEPEND="sunpinyin"
BDEPEND=" "
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	cd wrapper/ibus
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
