#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="High-level Python web framework"
COMMENTS="A high-level Python Web framework that encourages rapid development and clean, pragmatic design."
HOMEPAGE="http://pypi.python.org/pypi/Django"
LICENSE="BSD"
PACKAGER="StartOS Developers"
YARCH="any"

SRC_URI="http://media.djangoproject.com/releases/1.3/Django-"$V".tar.gz"
CHECKSUM="62d8642fd06b9a0bf8544178f8500767"

RDEPEND="python"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    docp_rename extras/django_bash_completion "$PKGDIR"/etc/bash_completion.d/django
    dodoc LICENSE
    cd "$PKGDIR"
    doln /usr/bin/django-admin.py usr/bin/django-admin
}

