#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="This is Python module for Rar archive reading."
HOMEPAGE="http://pypi.python.org/pypi/rarfile/2.0"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://download.berlios.de/"$N"/"$N-$V".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

