#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Multilingual Library for Unix/Linux"
HOMEPAGE="http://www.m17n.org/m17n-lib/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://download.savannah.gnu.org/releases/m17n/$N-$V.tar.gz"
CHECKSUM="83f2fc4facfd70a580bb95d9381eac7472d85171"

RDEPEND="m17n-db libXaw libxml2 fribidi gd libXft anthy"
RECOMMENDED=""
BDEPEND=""
OPTIONAL="anthy: to use the anthy input method"
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--enable-static=no"
    doconfig
}

pbs_build() {
    make
}

pbs_install() {
    domkinstall
}
