#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Multilingual Library for Unix/Linux"
HOMEPAGE="http://www.m17n.org/m17n-lib/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://www.m17n.org/m17n-lib-download/"$N-$V".tar.gz"
CHECKSUM="24c8f0a2fb167e1a0e25815c8421a2a4"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--enable-static=no"
	doconfig
}

pbs_build() {
	make
}

pbs_install() {
	domkinstall
}

