#
# YLmf_OS package build script
#

DESCRIPTION="X11 Apps"
HOMEPAGE="http://www.x.org/wiki/"
 
SRC_URI="http://www.x.org/releases/X11R7.6/src/app/"$N-$V$R".tar.bz2"

RDEPEND="libXmu libXt libX11 libSM libICE libXext libxcb util-linux-ng libXau libXdmcp"
BDEPEND="${RDEPEND}"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
