#
# Ylmf OS package build script
#

DESCRIPTION="X11 Apps"
HOMEPAGE="http://www.x.org/wiki/"
 
SRCURL="http://www.x.org/releases/X11R7.5/src/app"
SRC_URI="$SRCURL/smproxy-1.0.3.tar.bz2"

RDEPEND="libXmu libXt libX11 libSM libICE libXext libxcb util-linux-ng libXau libXdmcp"
BDEPEND=""

pbs_unpack()
{
        dounpack
}

pbs_config()
{
	
	doconfig
}

pbs_build()
{
	domake
}

pbs_install()
{
	domkinstall
}
