#
# YLmf_OS package build script
#

DESCRIPTION="A set of programs for extracting and converting images in Microsoft Windows icon and cursor files (.ico, .cur)."
HOMEPAGE="http://www.nongnu.org/icoutils/"
 
SRC_URI="http://savannah.nongnu.org/download/"$N"/"$N-$V$R".tar.bz2"

RDEPEND="libpng zlib glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
