#
# YLmf_OS package build script
#

DESCRIPTION="Redhat's Newt windowing toolkit development files"
HOMEPAGE="https://fedorahosted.org/newt/"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="https://fedorahosted.org/releases/n/e/"$N"/"$N-$V$R".tar.gz"

RDEPEND=""
BDEPEND="slang"
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--without-tcl"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	#make DESTDIR="$destdir" install
	domkinstall instroot="$destdir" install
}
