#
# Ylmf OS package build script
#

DESCRIPTION="Library for manipulating Unicode strings and C strings according to the Unicode standard"
HOMEPAGE="http://www.gnu.org/software/libunistring/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnu.org/gnu/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

