#
# YLmf_OS package build script
#

DESCRIPTION="Chinese Lunar Library"
HOMEPAGE="http://code.google.com/p/liblunar/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://liblunar.googlecode.com/files/"$N-$V".tar.gz"

RDEPEND="glib2 glibc"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--enable-introspection=no"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	#ypkg_docp "$FILES_PATH"/files/holiday.zh_CN  "$YPPATH_DEST"/usr/share/liblunar/
}

