#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A tool for creating Python bindings for C++ libraries"
HOMEPAGE="http://www.pyside.org/"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"

SRC_URI="http://qt-project.org/uploads/pyside/shiboken-$V.tar.bz2"
CHECKSUM="0a37b5011b3a7276bf4584317412a4b6"

RDEPEND="qt libxslt python"
RECOMMENDED=""
BDEPEND="cmake"
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    doconfig -DCMAKE_BUILD_TYPE=Release
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
