#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python Imaging Library (PIL)"
HOMEPAGE="http://www.pythonware.com/products/pil/index.htm"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://effbot.org/media/downloads/Imaging-"$V".tar.gz"

RDEPEND="expat fontconfig freetype glibc lcms libjpeg-turbo libX11 libXau libxcb libXdmcp libXext libXft libXrender libXScrnSaver python tcl tk zlib"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
