#
# Ylmf OS package build script
#

DESCRIPTION="Low-level pixel manipulation routines"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://cairographics.org/releases/"$N-$V".tar.gz"
CHECKSUM="efaa09789128ebc42d17a11d2e350b7217a7cd05"

RDEPEND="glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

