#
# YLmf_OS package build script
#

DESCRIPTION="Low-level pixel manipulation routines"
HOMEPAGE="http://xorg.freedesktop.org/"
 
SRC_URI="http://cairographics.org/releases/$N-$V.tar.gz"

RDEPEND=""
BDEPEND=""

pbs_unpack()
{
        ypkg_unpack
}

pbs_config()
{
	
	YPB_CONFIG+=" --prefix=/usr " #opt/gnome-2.30 --libdir=/opt/gnome-2.30/lib "
	ypkg_config
}

pbs_build()
{
	ypkg_make
}

pbs_install()
{
	ypkg_mkinstall
}
