#
# Ylmf OS package build script
#

DESCRIPTION="Nearly transparent SSL encapsulation for IO::Socket::INET.  "
HOMEPAGE="http://search.cpan.org/"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://cpan.communilink.net/authors/id/S/SU/SULLR/IO-Socket-SSL-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

