#
# YLmf_OS package build script
#

DESCRIPTION="A Client that groks URLs"
HOMEPAGE="http://curl.haxx.se/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://curl.haxx.se/download/"$N-$V".tar.bz2"

RDEPEND="cyrus-sasl glibc openldap openssl zlib"
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

