#
# YLmf_OS package build script
#

DESCRIPTION="Gudev mono bindings"
HOMEPAGE="http://github.com/mono/gudev-sharp"
REPO=""
LICENSE="LGPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://github.com/mono/gudev-sharp.git"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	make
}

pbs_install() {
	domkinstall
}
