#
# Ylmf OS package build script
#

DESCRIPTION="Gudev mono bindings"
HOMEPAGE="http://github.com/mono/gudev-sharp"
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
YARCH="any"

SRC_URI="git://github.com/mono/gudev-sharp.git"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	make
}

pbs_install() {
	domkinstall
}

