#
# YLmf_OS package build script
#

DESCRIPTION="Utilities for creating and parsing messages using MIME"
HOMEPAGE="http://spruce.sourceforge.net/gmime/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/"$N"/2.4/"$N-$V$R".tar.bz2"

RDEPEND="glib2 gdk-pixbuf glibc zlib"
BDEPEND="  "
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/gmime"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc README docs/tutorial/gmime*
}
