#
# YLmf_OS package build script
#

DESCRIPTION="A Pythonic binding for the libxml2 and libxslt libraries"
HOMEPAGE="http://codespeak.net/lxml/ http://pypi.python.org/pypi/lxml"
LICENSE="BSD GPL custom"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://lxml.de/files/"$N-$V".tgz"

RDEPEND="glibc libgcrypt libgpg-error libxml2 libxslt python zlib"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

