. /usr/lib/ybs/funcs

post_install() {
	gnome2_icon_cache_update "hicolor"
	gnome2_desktop_database_update
	gnome2_install_defaut_gconf "string" "/desktop/gnome/url-handlers/vnc/command" "remmina %s"
	gnome2_install_defaut_gconf "bool"  "/desktop/gnome/url-handlers/vnc/enabled"  "True"
}

post_remove() {
	gnome2_desktop_database_update
}

post_upgrade() {
	gnome2_desktop_database_update
}

post_downgrade() {	
	gnome2_desktop_database_update
}
