#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The PHP language runtime engine: CLI, CGI, FPM/FastCGI, Apache2 and embed SAPIs."
HOMEPAGE="http://www.php.net"
LICENSE="PHP"
PACKAGER="StartOS Developers"

SRC_URI="http://www.php.net/distributions/"$N-$V".tar.bz2"
CHECKSUM="816259e5ca7d0a7e943e56a3bb32b17f"

RDEPEND="aspell berkeley-db bzip2 curl cyrus-sasl enchant freetds freetype gcc-lib gdbm glib2 glibc gmp gnutls icu libgcrypt libgpg-error libidn libjpeg-turbo libmcrypt libpcre libpng libssh2 libtasn1 libtool libxml2 libxslt net-snmp openldap openssl pam postgresql-libs rtmpdump sqlite tidyhtml unixodbc zlib"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	phpconfig=" --srcdir=../$N-$V$R
	  	    --prefix=/usr
		    --sysconfdir=/etc/php
		    --localstatedir=/var 
		    --with-layout=GNU 
		    --with-config-file-path=/etc/php 
		    --with-config-file-scan-dir=/etc/php/conf.d 
		    --enable-inline-optimization 
		    --disable-debug 
		    --disable-rpath 
		    --disable-static 
		    --enable-shared 
		    --mandir=/usr/share/man 
		    --without-pear" 
	
	phpextensions=" --enable-bcmath=shared 
			--enable-calendar=shared 
			--enable-dba=shared 
			--enable-exif=shared 
			--enable-ftp=shared 
			--enable-gd-native-ttf 
			--enable-intl=shared 
			--enable-json=shared 
			--enable-mbregex 
			--enable-mbstring 
			--enable-pdo 
			--enable-phar=shared 
			--enable-posix=shared 
			--enable-session 
			--enable-shmop=shared 
			--enable-soap=shared 
			--enable-sockets=shared 
			--enable-sqlite-utf8 
			--enable-sysvmsg=shared 
			--enable-sysvsem=shared 
			--enable-sysvshm=shared
			--enable-xml 
			--enable-zip=shared 
			--with-bz2=shared 
			--with-curl=shared 
			--with-db4=/usr 
			--with-enchant=shared,/usr 
			--with-freetype-dir=shared,/usr 
			--with-gd=shared 
			--with-gdbm=shared 
			--with-gettext=shared 
			--with-gmp=shared 
			--with-iconv=shared 
			--with-icu-dir=/usr 
			--with-imap-ssl=shared 
			--with-imap=shared 
			--with-jpeg-dir=shared,/usr 
			--with-ldap=shared 
			--with-ldap-sasl 
			--with-mcrypt=shared 
			--with-mhash 
			--with-mssql=shared 
			--with-mysql-sock=/var/run/mysqld/mysqld.sock 
			--with-mysql=shared,mysqlnd 
			--with-mysqli=shared,mysqlnd 
			--with-openssl=shared 
			--with-pcre-regex=/usr 
			--with-pdo-mysql=shared,mysqlnd 
			--with-pdo-odbc=shared,unixODBC,/usr 
			--with-pdo-pgsql=shared 
			--with-pdo-sqlite=shared,/usr 
			--with-pgsql=shared 
			--with-png-dir=shared,/usr 
			--with-pspell=shared 
			--with-regex=php
			--with-snmp=shared 
			--with-sqlite3=shared,/usr 
			--with-sqlite=shared 
			--with-tidy=shared 
			--with-unixODBC=shared,/usr 
			--with-xmlrpc=shared 
			--with-xsl=shared 
			--with-zlib 
			--without-db2 
			--without-db3 "
	
	EXTENSION_DIR=/usr/lib/php/modules
	export EXTENSION_DIR
	PEAR_INSTALLDIR=/usr/share/pear
	export PEAR_INSTALLDIR

	config="${phpconfig} ${phpextensions}"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	make -j1 INSTALL_ROOT="${destdir}" install
}

