#!/bin/bash

INPUTFILE="$1"
OUTPUTFILE="$2"
BG=/usr/share/pixmaps/ypk-package-installer/template.png
DEFAULT_ICON=/usr/share/pixmaps/ypk-package-installer/default.png
TEMPFILE1=$(mktemp)
TEMPFILE2=$(mktemp)
TEMPTHUMB=$(mktemp)

tar -xf $1  'pkginfo' --to-command='cat' >$TEMPFILE1

ICON_NAME=`tar -tf $TEMPFILE1 2>/dev/null | grep -E '.png|.svg|.jpg|.xpm' | head -1`

if [ "$ICON_NAME" != "" ]
then
    tar -xf $TEMPFILE1 --to-command='cat' $ICON_NAME >$TEMPFILE2
    composite -geometry 32x32+16+16 $TEMPFILE2 $BG $TEMPTHUMB
else
    #composite -geometry 32x32+16+16 $DEFAULT_ICON $BG $TEMPTHUMB
    cat $DEFAULT_ICON >$TEMPTHUMB
fi

cp $TEMPTHUMB $OUTPUTFILE

rm $TEMPFILE1
rm $TEMPFILE2
rm $TEMPTHUMB
