#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A library for manipulating integer points bounded by affine constraints."
HOMEPAGE="http://www.kotnet.org/~skimo/isl/"
LICENSE="LGPL2.1"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://www.kotnet.org/~skimo/isl/"$N-$V".tar.bz2"
CHECKSUM="6873f0b3c9f4d1fb8efae4aea53f2ab2"

RDEPEND="glibc gmp"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	cd "$destdir"
	domv usr/lib/libisl.so.9.0.0-gdb.py usr/share/gdb/auto-load/
}

