#
# Ylmf OS package build script
#

DESCRIPTION=" GStreamer plugin for muxing of MPEG2 TS streams"
HOMEPAGE="http://core.fluendo.com/gstreamer/src/gst-fluendo-mpegmux/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://core.fluendo.com/gstreamer/src/"$N"/"$N-$V".tar.bz2"

RDEPEND="gstreamer libtsmux"
BDEPEND=" "
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

