#!/bin/sh

OPTION=FRAMEBUFFER
PREREQ="udev"
[ -f /scripts/functions ] && . /scripts/functions

prereqs()
{
        echo "$PREREQ"
}

case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

if [ -f ${rootmnt}/run/plymouth.pid ]; then
	/usr/bin/plymouth update-root-fs --new-root-dir=${rootmnt}
fi
