#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Urwid is a curses-based user interface library."
HOMEPAGE="http://excess.org/urwid"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://excess.org/urwid/urwid-$V.tar.gz"
CHECKSUM="eca2e0413cf7216b01c84b99e0f2576d"

RDEPEND="python glibc"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall --optimize=1
}
