#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="This module provides bindings for the cURL library."
HOMEPAGE="http://pycurl.sourceforge.net"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"

SRC_URI="http://pycurl.sourceforge.net/download/pycurl-$V.tar.gz"

RDEPEND="curl python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
