#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Sun's Java Development Kit"
HOMEPAGE="http://java.sun.com"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://download.oracle.com/auth/otn-pub/java/jdk/6u25-b06/jdk-6u25-linux-i586.bin"

RDEPEND="glibc jre"
BDEPEND=""
RECOMMENDED=""
CONFLICT="sun-jdk"

INSTALL="$N.install"

pbs_unpack() {
    mkdir -p "$N-$V$R"
    cd "$N-$V$R"
    mkdir -p unbundle-jdk
    cd unbundle-jdk
    sh "$YBS_SOURCE"/jdk-6u25-linux-i586.bin --accept-license
    cd ../
    sh $FILESDIR/construct.sh unbundle-jdk linux-jdk linux-jre
}

pbs_install() {
    # Make DESTDIR="$PKGDIR" install
    # Copy icon
    docp_rename linux-jdk/jre/lib/desktop/icons/hicolor/48x48/apps/sun-java.png "$PKGDIR"/usr/share/pixmaps/java.png
    rm -rf linux-jdk/jre
    docp linux-jdk/* "$PKGDIR"/opt/java/
    docp_rename $FILESDIR/jdk.profile    "$PKGDIR"/etc/profile.d/jdk.sh
    docp_rename $FILESDIR/jdk.profile.csh "$PKGDIR"/etc/profile.d/jdk.csh
    
    cd "$PKGDIR"
    docp opt/java/{COPYRIGHT,LICENSE,THIRDPARTYLICENSEREADME.txt} usr/share/licenses/jdk/
    # Desktop entries
    dodesktop java-control-panel.desktop java-monitoring-and-management-console.desktop java-policy-settings.desktop java-visualvm.desktop java-web-start.desktop
}

