#
# Ylmf OS package build script
#

DESCRIPTION="orbit bindings for Python"
HOMEPAGE="http://www.pygtk.org/"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.acc.umu.se/pub/gnome/bindings/2.32/2.32.1/sources/python/"$N-$V".tar.bz2"

RDEPEND="glib2 glibc libIDL orbit python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-static"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

