#
# YLmf_OS package build script
#

DESCRIPTION="orbit bindings for Python"
HOMEPAGE="http://www.pygtk.org/"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.acc.umu.se/pub/gnome/bindings/2.32/2.32.1/sources/python/"$N-$V".tar.bz2"

RDEPEND="glib2 gdk-pixbuf glibc libIDL orbit python"
BDEPEND="    "
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-static"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

