#
# YLmf_OS package build script
#

DESCRIPTION="orbit bindings for Python"
HOMEPAGE="http://www.pygtk.org/"
REPO=""
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/"$N"/2.24/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND="${RDEPEND} orbit"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-static"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc AUTHORS COPYING ChangeLog* INSTALL NEWS README
}
