#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python bindings for the D-Bus messagebus."
HOMEPAGE="http://www.freedesktop.org/wiki/Software/DBusBindings"
LICENSE="LGPL"
PACKAGER="StartOS Developers"

SRC_URI="http://dbus.freedesktop.org/releases/"$N"/"$N-$V".tar.gz"
CHECKSUM="742c7432ad0f7c3f98291d58fa2e35dc"

RDEPEND="dbus-glib"
BDEPEND=""
RECOMMENDED=""

NOTES="dodocutils epydodoc is required to Build Documentation"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

