#
# Ylmf OS package build script
#

DESCRIPTION="Python bindings for the D-Bus messagebus."
HOMEPAGE="http://www.freedesktop.org/wiki/Software/DBusBindings http://dbus.freedesktop.org/doc/dbus-python/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://dbus.freedesktop.org/releases/"$N"/"$N-$V".tar.gz"
CHECKSUM="fe69a2613e824463e74f10913708c88a"

RDEPEND="dbus dbus-glib glib2 glibc"
BDEPEND=""
RECOMMENDED=""

NOTES="dodocutils epydodoc is required to Build Documentation"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

