#
# YLmf_OS package build script
#

DESCRIPTION=" Python bindings for the D-Bus messagebus."
HOMEPAGE="http://www.freedesktop.org/wiki/Software/DBusBindings http://dbus.freedesktop.org/doc/dbus-python/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://dbus.freedesktop.org/releases/"$N"/"$N-$V$R".tar.gz"

RDEPEND="dbus dbus-glib glib2 gdk-pixbuf glibc"
BDEPEND="    python-dev"
RECOMMENDED=""

NOTES="docutils epydoc is required to Build Documentation"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
