#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Use single instance applications"
HOMEPAGE="http://search.cpan.org/~potyl/Gtk2-Unique"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="GPL,PerlArtistic"
GROUP="perl"

SRC_URI="http://search.cpan.org/CPAN/authors/id/P/PO/POTYL/Gtk2-Unique-"$V".tar.gz"

RDEPEND="perl libunique gdk-pixbuf2"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}
