#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The pkg_resources module provides an API for Python libraries to access their resource files"
HOMEPAGE="http://packages.python.org/distribute"
LICENSE="PSF/ZPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://pypi.python.org/packages/source/d/"$N"/"$N-$V".tar.gz"

RDEPEND="python(>=2.7.2)"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

