#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The pkg_resources module provides an API for Python libraries to access their resource files"
HOMEPAGE="http://packages.python.org/distribute"
REPO=""
LICENSE="PSF or ZPL"
PRIORITY=""
PACKAGER="StartOS Developers"

SRC_URI="http://pypi.python.org/packages/source/d/"$N"/"$N-$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
