#
# YLmf_OS package build script
#

DESCRIPTION="The GNU info program and utilities"
HOMEPAGE="http://www.gnu.org/software/texinfo/"
LICENSE="GPLv3"

SRC_URI="http://ftp.gnu.org/gnu/"$N"/"$N-$V"a.tar.gz"

RDEPEND="glibc ncurses"
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	# Support for new compressors like XZ Utils
	ypkg_patch texinfo-4.13a-new_compressors-1.patch
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

