#
# YLmf_OS package build script
#

DESCRIPTION="an advanced CDDA reader with error correction"
HOMEPAGE="http://www.xiph.org/paranoia"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://downloads.xiph.org/releases/"$N"/"$N"-III-10.2.src.tgz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	YPB_CONFIG+=" --prefix=/usr "
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
