#
# YLmf_OS package build script
#

DESCRIPTION=" Client library to access metadata of mp3/vorbis/CD media"
HOMEPAGE="http://musicbrainz.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.musicbrainz.org/pub/musicbrainz/"$N-$V".tar.gz "

RDEPEND="e2fsprogs expat gcc glibc keyutils krb5 libproxy neon openssl zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

