#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Provide a simple protocol for reading and writing data on the web."
HOMEPAGE="http://code.google.com/p/google-gdata/"
LICENSE="apache"
PACKAGER="StartOS Developers"
YARCH="any"

SRC_URI="http://google-gdata.googlecode.com/files/libgoogle-data-mono-"$V".tar.gz"

RDEPEND="mono"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_build() {
    sed -i '/PREFIX=/ s|/usr/local|/usr|' ./Makefile
    domake
}

pbs_install() {
    domkinstall
}

