#
# YLmf_OS package build script
#

DESCRIPTION="install build-essential packages"
HOMEPAGE="www.ylmf.com"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

RDEPEND="ypkg"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

pbs_install() {
	mkdir -p "$YPPATH_DEST"/usr/share/doc/"$N"/
	cat >>"$YPPATH_DEST"/usr/share/doc/"$N"/README << "EOF"
install build-essential packages
EOF
}
