#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python Cryptography Toolkit"
HOMEPAGE="http://www.dlitz.net/software/pycrypto"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"

SRC_URI="http://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-$V.tar.gz"
CHECKSUM=""

RDEPEND="python glibc gmp"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall --optimize=1
    dodoc COPYRIGHT
}
