#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl module Test-Script"
HOMEPAGE="http://search.cpan.org/~adamk/Test-Script-1.07/"
REPO=""
LICENSE="GPL-2"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/A/AD/ADAMK/Test-Script-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" ipc-run3 probe-perl"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
