#
# YLmf_OS package build script
#

DESCRIPTION="Concurrent Versions System - source code revision control tools"
HOMEPAGE="http://www.nongnu.org/cvs/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="ftp://ftp.gnu.org/non-gnu/"$N"/source/stable/"$V$R"/"$N-$V$R".tar.bz2 "

RDEPEND="zlib glibc"
BDEPEND=" "
RECOMMENDED=""

INSTALL="$N.install"

NOTES="
If you want any CVS server functionality, you MUST parse server to congfigure.
"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc FAQ README doc/*.pdf
}

