#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="JavaScript interpreter and libraries"
HOMEPAGE="https://developer.mozilla.org/En/SpiderMonkey/1.8.5"
LICENSE="GPL2"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://ftp.mozilla.org/pub/mozilla.org/$N/"$N"185-1.0.0.tar.gz"
CHECKSUM="a4574365938222adca0a6bd33329cb32"

RDEPEND="nspr gcc-libs"
RECOMMENDED=""
BDEPEND="python zip"
OPTIONAL=""
CONFLICT=""
REPLACE="spidermonkey"

pbs_unpack() {
    dounpack
}

pbs_patch() {
    cd js/src
    dopatch js185-destdir.patch
}

pbs_config() {
    config+="--with-system-nspr --enable-threadsafe"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    install -m 0755 shell/js "$PKGDIR"/usr/bin
    # Cleanup
    rm -f "$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/libmozjs185-1.0.a
}

