#
# YLmf_OS package build script
#

DESCRIPTION="The VP8 Codec SDK"
HOMEPAGE="http://www.webmproject.org/"
REPO=""
LICENSE="GPL"
#PRIORITY="required"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://review.webmproject.org/libvpx.git"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG="--prefix=/usr"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
