#
# Ylmf OS package build script
#

DESCRIPTION="The VP8 Codec SDK"
HOMEPAGE="http://www.webmproject.org/"
REPO=""
LICENSE="GPL"
#PRIORITY="required"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://review.webmproject.org/libvpx.git"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config="--prefix=/usr"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
