#
# Ylmf OS package build script
#

DESCRIPTION="The VP8 Codec SDK"
HOMEPAGE="http://www.webmproject.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://webm.googlecode.com/files/"$N"-v"$V"-p1.tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config="--prefix=/usr"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

