#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Lisp system for Sawfish"
HOMEPAGE="http://sawfish.wikia.com/wiki/Librep"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://download.tuxfamily.org/"$N"/"$N-$V".tar.xz"
CHECKSUM="45903b169d59d00f75a4b619b2b23f442e9146be"

RDEPEND="gdbm glibc gmp libffi ncurses readline"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""
REPLACE=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-static --with-readline"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

