#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Library for accessing Sybase and MS SQL Server databases"
HOMEPAGE="http://www.freetds.org"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="ftp://ftp.ibiblio.org/pub/Linux/ALPHA/"$N"/stable/"$N-$V".tar.gz"
CHECKSUM="b14db5823980a32f0643d1a84d3ec3ad"

RDEPEND="readline"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--enable-msdblib 
             --with-tdsver=7.0"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
