#
# Ylmf OS package build script
#

DESCRIPTION="Prints out location of specified executables"
HOMEPAGE="http://www.xs4all.nl/~carlo17/which/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnu.org/gnu/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

