#
# YLmf_OS package build script
#

DESCRIPTION="C++ bindings for libgnomecanvas"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/gnome/bindings/2.32/2.32.1/sources/c++/"$N-$V".tar.bz2"

RDEPEND="atk atkmm cairo cairomm expat fontconfig freetype gail gcc gdk-pixbuf glib2 glibc glibmm gtk+ gtkmm libart_lgpl libgnomecanvas libpng libsigc++ libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender pango pangomm pixman zlib"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
