#
# YLmf_OS package build script
#

DESCRIPTION="C++ bindings for GConf"
HOMEPAGE="http://www.gtkmm.org"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.acc.umu.se/pub/GNOME/sources/"$N"/2.28/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
