#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="C++ bindings for GConf"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gnome.org/pub/gnome/bindings/2.32/2.32.1/sources/c++/"$N-$V".tar.bz2"

RDEPEND="gconf glibmm"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
