#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="the python bindings for GooCanvas which is a canvas widget for GTK+ that uses the cairo 2D library for drawing."
HOMEPAGE="http://live.gnome.org/PyGoocanvas"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/"$N"/0.14/"$N-$V$R".tar.bz2"

RDEPEND="goocanvas"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
