#
# YLmf_OS package build script
#

DESCRIPTION="GStreamer plugin for demuxing of MPEG2 streams"
HOMEPAGE="http://core.fluendo.com/gstreamer/src/gst-fluendo-mpegdemux/"
REPO=""
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://core.fluendo.com/gstreamer/src/"$N"/"$N-$V$R".tar.bz2"

RDEPEND="gstreamer"
BDEPEND=" "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
