#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Yet Another JSON Library"
HOMEPAGE="http://lloyd.github.com/yajl/"
LICENSE="ISC"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="https://github.com/lloyd/"$N"/tarball/"$V"/"$N-$V".tar.gz"
CHECKSUM="ee6208e697c43dcccf798ce80d370379"

RDEPEND="glibc"
RECOMMENDED=""
BDEPEND="cmake"
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodoc ../COPYING
}

