#
# Ylmf OS package build script
#

DESCRIPTION="Small event-driven (SAX-style) JSON parser"
HOMEPAGE="http://lloyd.github.com/yajl/"
LICENSE="ISC"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="https://github.com/lloyd/"$N"/tarball/"$V"/"$N-$V".tar.gz"
CHECKSUM=""

RDEPEND="glibc"
RECOMMENDED=""
BDEPEND="cmake"
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	cmake -DCMAKE_INSTALL_PREFIX=/usr .
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

