#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Fast and lightweight IDE"
HOMEPAGE="http://www.geany.org"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://download.geany.org/"$N-$V".tar.bz2"
CHECKSUM="901a35a7395ef10a80fb10b3ab63bae3871693a4e82d56388e9521a27877577e"

RDEPEND="gtk2 desktop-file-utils"
BDEPEND="intltool"
RECOMMENDED="geany-plugins"
OPTIONAL="vte: for terminal support"

INSTALL="$N.install"

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

