#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GTK+ based fast and lightweight IDE"
HOMEPAGE="http://geany.uvena.de"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://download.geany.org/"$N-$V".tar.bz2"

RDEPEND="gtk+"
BDEPEND=""
RECOMMENDED="geany-plugins"

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

