#
# YLmf_OS package build script
#

DESCRIPTION="C++ bindings for the Cairo vector graphics library"
HOMEPAGE="http://cairographics.org/cairomm"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="http://cairographics.org/releases/$N-$V.tar.gz"

RDEPEND=""
BDEPEND=" cairo"
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/cairomm"

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	config+=" --prefix=/usr "
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
