#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="add remove user and group"
HOMEPAGE="http://www.startos.org"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="shadow perl"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_install() {
    docp etc usr "$destdir"
}

