#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="add remove user and group"
HOMEPAGE="http://www.ylmf.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="shadow perl"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_install() {
	docp etc usr "$destdir"
}

