#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GTK+2 bindings for Python"
HOMEPAGE="http://www.pygtk.org/"
LICENSE="GPLv2"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gnome.org/pub/gnome/bindings/2.32/2.32.1/sources/python/"$N-$V".tar.bz2 "

RDEPEND="atk cairo expat fontconfig freetype gcc-lib gdk-pixbuf glib2 glibc gtk+ libglade libpng libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libxml2 libXrandr libXrender pango pixman zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-static"
	doconfig
}

pbs_build() {
	make "$MAKEOPTS"
}

pbs_install() {
	make DESTDIR="$destdir" install
}

