#
# YLmf_OS package build script
#

DESCRIPTION="GTK+2 bindings for Python"
HOMEPAGE="http://www.pygtk.org/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"
SRC_URI="ftp://ftp.gnome.org/pub/gnome/sources/pygtk/2.16/$N-$V.tar.bz2"

RDEPEND=""
BDEPEND="${RDEPEND} pygobject atk pango pycairo gtk+ libglade"
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/pygtk"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=" --prefix=/usr "
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
