#
# Ylmf OS package build script
#

DESCRIPTION="GTK+2 bindings for Python"
HOMEPAGE="http://www.pygtk.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI=" http://ftp.gnome.org/pub/gnome/bindings/2.30/2.30.2/sources/python/"$N-$V".tar.bz2 "

RDEPEND="atk cairo expat fontconfig freetype gcc glib2 gdk-pixbuf glibc gtk+ libglade libpng libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libxml2 libXrandr libXrender pango pixman zlib"
BDEPEND="                          "
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/pygtk"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-static"
	doconfig
}

pbs_build() {
	domake make
}

pbs_install() {
	domkinstall make
}
