#
# YLmf_OS package build script
#

DESCRIPTION="SCM is a Scheme implementation conforming to Revised5 Report on the Algorithmic Language Scheme and the IEEE P1178 specification*. "
HOMEPAGE="http://people.csail.mit.edu/jaffer/SCM"
REPO=""
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://groups.csail.mit.edu/mac/ftpdir/scm/scm-5e7.zip"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	#dopatch $filesdir/patches/*.patch 
	#XX.patch should be found under $filesdir or $filesdir/patches/
	#second, add package specified config params to config
	#default is :
	config=" --prefix=/usr
	             --exec-prefix=/usr
		     --sysconfdir=/etc
		     --localstatedir=/var
	             --infodir=/usr/share/info
		     --mandir=/usr/share/man"
	#Third, call configure with $config
	#./configure $config
	doconfig
}

pbs_build() {
	echo "Making scmlit"
	make -j1 scmlit clean
	echo "Building scm"
	./build -h system -o scm
	echo "Building DLLs"
	./build -h system -F edit-line -t dll 
}

pbs_install() {
	#install everything to $destdir
	#make DESTDIR="$destdir" install
	domkinstall
	#doinit "$N"
	#doinit "N".service
	#dodesktop "*.desktop" "*.png"
	#dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README 
	#docp "$filesdir/XXXX" "dirname"
	#domv "$filesdir/XXXX" "dirname"
	#docp_rename "$1" "$2"
	#domv_rename "$1" "$2"
	#doln "$1 "$2"
	#*****************
	#when SRC_URI is deb or rpm package
	#docp data/*  "$destdir"
}
