#
# YLmf_OS package build script
#

DESCRIPTION="SCM is a Scheme implementation conforming to Revised5 Report on the Algorithmic Language Scheme and the IEEE P1178 specification*. "
HOMEPAGE="http://people.csail.mit.edu/jaffer/SCM"
REPO=""
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://groups.csail.mit.edu/mac/ftpdir/scm/scm-5e7.zip"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	#ypkg_patch $FILES_PATH/files/patches/*.patch 
	#XX.patch should be found under $FILES_PATH/files or $FILES_PATH/files/patches/
	#second, add package specified config params to YPB_CONFIG
	#default is :
	YPB_CONFIG=" --prefix=/usr
	             --exec-prefix=/usr
		     --sysconfdir=/etc
		     --localstatedir=/var
	             --infodir=/usr/share/info
		     --mandir=/usr/share/man"
	#Third, call configure with $YPB_CONFIG
	#./configure $YPB_CONFIG
	ypkg_config
}

pbs_build() {
	echo "Making scmlit"
	make -j1 scmlit clean
	echo "Building scm"
	./build -h system -o scm
	echo "Building DLLs"
	./build -h system -F edit-line -t dll 
}

pbs_install() {
	#install everything to $YPPATH_DEST
	#make DESTDIR="$YPPATH_DEST" install
	ypkg_mkinstall
	#ypkg_doinit "$N"
	#ypkg_doinit "N".service
	#ypkg_dodesktop "*.desktop" "*.png"
	#ypkg_dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README 
	#ypkg_docp "$FILES_PATH/files/XXXX" "dirname"
	#ypkg_domv "$FILES_PATH/files/XXXX" "dirname"
	#ypkg_docp_rename "$1" "$2"
	#ypkg_domv_rename "$1" "$2"
	#ypkg_doln "$1 "$2"
	#*****************
	#when SRC_URI is deb or rpm package
	#ypkg_docp data/*  "$YPPATH_DEST"
}
