#
# YLmf_OS package build script
#

DESCRIPTION="X.Org xeyes application"
HOMEPAGE="http://xorg.freedesktop.org/"
REPO=""
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://xorg.freedesktop.org/releases/individual/app/$N-$V$R.tar.bz2"

RDEPEND=""
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc ChangeLog COPYING INSTALL README 
}
