#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="easily lookup countries by IP addresses, even when Reverse DNS entries don't exist"
HOMEPAGE="http://www.maxmind.com/geoip/api/c.shtml"
LICENSE="GPLv2+"
PACKAGER="StartOS Developers"

SRC_URI="http://geolite.maxmind.com/download/"$N"/api/c/GeoIP-"$V".tar.gz"

RDEPEND="zlib"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    sed -e "s:usr local share GeoIP:usr share GeoIP:" -e "s:usr local etc:etc:" -i apps/geoipupdate-pureperl.pl
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

