#
# YLmf_OS package build script
#

DESCRIPTION="Facility for creating read-only scalars, arrays, hashes."
HOMEPAGE="http://search.cpan.org/~roode/Readonly-1.03/"
LICENSE="GPL PerlArtistic"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://cpan.communilink.net/authors/id/R/RO/ROODE/Readonly-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

