
post_install() {
    doinstall_catalog /etc/sgml/sgml-ent.cat /usr/share/sgml/sgml-iso-entities-8879.1986/catalog
    doinstall_catalog /etc/sgml/sgml-docbook.cat /etc/sgml/sgml-ent.cat ||true
}

pre_remove() {
    doremove_catalog /etc/sgml/sgml-ent.cat /usr/share/sgml/sgml-iso-entities-8879.1986/catalog
    doremove_catalog /etc/sgml/sgml-docbook.cat /etc/sgml/sgml-ent.cat ||true
}

post_upgrade() {
    post_install
}
