#
# YLmf_OS package build script
#

DESCRIPTION="1g1g online music (AIR)"
HOMEPAGE="http://www.ruochi.com/main/1g1g-air/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://1g1g.ruochi.com/updates/1g1g."$V".air"

RDEPEND="adobe-air-sdk"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

pbs_install() {
	ypkg_docp_rename "$YPPATH_SOURCE"/1g1g."$V".air "$YPPATH_DEST"/usr/lib/1g1g-air/1g1g.air
	ypkg_dodesktop "1g1g-air.desktop" "1g1g-air.png"
}

