#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An advanced molecular editor based on Qt"
HOMEPAGE="http://avogadro.openmolecules.net/wiki/Main_Page"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://downloads.sourceforge.net/"$N"/"$N-$V".tar.bz2"
CHECKSUM="92c2702c1980f70fb6d87a1a58147911"

RDEPEND="numpy"
RECOMMENDED=""
BDEPEND="cmake"
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_patch() {
	dopatch replace-qt4_automoc-with-qt4_wrap_cpp.patch \
		fix-boost.patch \
		fix-opengl-headers.patch
}

pbs_config() {
	doconfig -DCMAKE_BUILD_TYPE=Release \
	         -DQT_MKSPECS_RELATIVE=share/qt/mkspecs
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

