#
# Ylmf OS package build script
#

DESCRIPTION="Offline Windows NT Password & Registry Editor"
HOMEPAGE="http://pogostick.net/~pnh/ntpasswd/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://pogostick.net/~pnh/ntpasswd/"$N"-source-"$V".zip"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	docp chntpw chntpw.static cpnt reged reged.static "$destdir"/usr/bin/
}

