#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A cross-platform GUI front-end for the Subversion revision system written in C++ using the wxgtk framework."
HOMEPAGE="http://rapidsvn.tigris.org"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://www.rapidsvn.org/download/release/"$V"/"$N-$V".tar.gz"
CHECKSUM="8de3ca6da3ef6a27d59f959d1bbcd96b"

RDEPEND="subversion wxgtk"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
        dounpack
}

pbs_patch() {
    dopatch use-xdg-open-instead-of-firefox.patch
}

pbs_config() {
    ./autogen.sh
    sed -i 's#src/tests/svncpp/Makefile##' configure
    ./configure --prefix=/usr \
                --with-apu-config="`which apu-1-config`" \
            --with-apr-config="`which apr-1-config`"
}

pbs_build() {
    domake -k
}

pbs_install() {
    domkinstall
    dodesktop "$FILESDIR"/"$N".desktop src/res/bitmaps/rapidsvn_32x32.xpm
}

