#
# YLmf_OS package build script
#

DESCRIPTION="Compizconfig Python Bindings"
HOMEPAGE="http://www.compiz.org/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://releases.compiz.org/components/compizconfig-python/compizconfig-python-0.8.4.tar.bz2"

RDEPEND="python pygtk pyrex compiz compiz-bcop libcompizconfig"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

