#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Netscape Portable Runtime"
HOMEPAGE="http://www.mozilla.org/projects/nspr/"
LICENSE="GPL-2"

SRC_URI="http://ftp.mozilla.org/pub/mozilla.org/"$N"/releases/v"$V"/src/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	dopatch nspr-4.8.3-pkgconfig-1.patch
 	cd mozilla/nsprpub
	config+="--with-mozilla --with-pthreads"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	docp pr/include/* "$destdir"/usr/include/nspr
	cd "$destdir"
	doln /usr/lib/libplc4.so  usr/lib/libplc4.so.0d
	doln /usr/lib/libnspr4.so usr/lib/libnspr4.so.0d
}
