#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Netscape Portable Runtime"
HOMEPAGE="http://www.mozilla.org/projects/nspr/"
LICENSE="GPL-2"

SRC_URI="http://ftp.mozilla.org/pub/mozilla.org/"$N"/releases/v"$V"/src/"$N-$V$R".tar.gz"

RDEPEND=""
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	dopatch "$N-$V$R"-pkgconfig-1.patch
 	cd mozilla/nsprpub
	config+="--with-mozilla --with-pthreads"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	docp -LR dist/include/nspr "$destdir"/usr/include
}
