#
# YLmf_OS package build script
#

DESCRIPTION="Netscape Portable Runtime"
HOMEPAGE="http://www.mozilla.org/projects/nspr/"
LICENSE="GPL-2"
YVERSION="1"

SRC_URI="http://ftp.mozilla.org/pub/mozilla.org/"$N"/releases/v"$V"/src/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_patch nspr-4.8.3-pkgconfig-1.patch
 	cd mozilla/nsprpub
	YPB_CONFIG+="--with-mozilla --with-pthreads"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall

	ypkg_docp pr/include/*.h     "$YPPATH_DEST"/usr/include/
	for i in md private obsolete; do
		ypkg_docp pr/include/"$i"/*.h  "$YPPATH_DEST"/usr/include/"$i"
	done

	cd "$YPPATH_DEST"
	ypkg_doln /usr/lib/libplc4.so  usr/lib/libplc4.so.0d
	ypkg_doln /usr/lib/libnspr4.so usr/lib/libnspr4.so.0d
}
