#
# YLmf_OS package build script
#

DESCRIPTION="Netscape Portable Runtime"
HOMEPAGE="http://www.mozilla.org/projects/nspr/"
LICENSE="GPL-2"

SRC_URI="http://ftp.mozilla.org/pub/mozilla.org/"$N"/releases/v"$V"/src/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	dopatch nspr-4.8.3-pkgconfig-1.patch
 	cd mozilla/nsprpub
	config+="--with-mozilla --with-pthreads"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall

	docp pr/include/*.h     "$destdir"/usr/include/
	for i in md private obsolete; do
		docp pr/include/"$i"/*.h  "$destdir"/usr/include/"$i"
	done

	cd "$destdir"
	doln /usr/lib/libplc4.so  usr/lib/libplc4.so.0d
	doln /usr/lib/libnspr4.so usr/lib/libnspr4.so.0d
}
