#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Netscape Portable Runtime"
HOMEPAGE="http://www.mozilla.org/projects/nspr/"
LICENSE="MPL,GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://ftp.mozilla.org/pub/mozilla.org/"$N"/releases/v"$V"/src/"$N-$V".tar.gz"
CHECKSUM="8a21b3b6766bde3b5ed2a6a7b725e4aa"

RDEPEND="glibc"
BDEPEND=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    case "$ARCH" in
     x86_64) confflags="--enable-64bit" ;;
          *) confflags=""
    esac

    sed -e 's/\$(MKSHLIB) \$(OBJS)/\$(MKSHLIB) \$(LDFLAGS) \$(OBJS)/g' \
        -i mozilla/nsprpub/config/rules.mk

    ./mozilla/nsprpub/configure \
            --prefix=/usr \
            --libdir=/usr/lib"$LIBDIRSUFFIX" \
            --includedir=/usr/include/nspr \
            --enable-optimize \
            --disable-debug "$confflags"
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall 

    NSPR_LIBS=`./config/nspr-config --libs`
    NSPR_CFLAGS=`./config/nspr-config --cflags`
    NSPR_VERSION=`./config/nspr-config --version`

    install -m755 -d "$PKGDIR/usr/lib"$LIBDIRSUFFIX"/pkgconfig"
    sed "$FILESDIR"/nspr.pc.in -e "s,%libdir%,/usr/lib"$LIBDIRSUFFIX"," \
               -e "s,%prefix%,/usr," \
             -e "s,%exec_prefix%,/usr/bin," \
             -e "s,%includedir%,/usr/include/nspr," \
             -e "s,%NSPR_VERSION%,${NSPR_VERSION}," \
             -e "s,%FULL_NSPR_LIBS%,${NSPR_LIBS}," \
             -e "s,%FULL_NSPR_CFLAGS%,${NSPR_CFLAGS},"  \
             >"$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/pkgconfig/nspr.pc

    cd "$PKGDIR"
    chmod 644 usr/lib"$LIBDIRSUFFIX"/{*.a,pkgconfig/nspr.pc}
    doln /usr/lib"$LIBDIRSUFFIX"/pkgconfig/nspr.pc usr/lib"$LIBDIRSUFFIX"/pkgconfig/mozilla-nspr.pc
    rm -rf usr/bin/{compile-et.pl,prerr.properties} usr/share/aclocal/nspr.m4 usr/include/nspr/md
}

