#
# YLmf_OS package build script
#

DESCRIPTION="Get information about a class and its structure  "
HOMEPAGE="http://search.cpan.org/~adamk/Class-Inspector-1.25/"
LICENSE="GPL PerlArtistic"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://mirrors.163.com/cpan/authors/id/A/AD/ADAMK/Class-Inspector-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

