#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Plotting package which outputs to X11, PostScript, PNG, GIF, and others"
HOMEPAGE="http://www.gnuplot.info"
LICENSE="custom"
PACKAGER="StartOS Developers"

SRC_URI="http://downloads.sourceforge.net/sourceforge/"$N"/"$N-$V".tar.gz"
CHECKSUM="9a43ae13546d97d4b174533ddac31a14e0edc9b2"

RDEPEND="gd lua wxgtk"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""
REPLACE=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=" --libexecdir=/usr/bin 
                  --with-gihdir=/usr/share/gnuplot 
		  --datadir=/usr/share 
		  --with-readline=gnu 
		  --with-texdir="$destdir"/usr/share/texmf/tex/latex/gnuplot "
	doconfig
}

pbs_build() {
	domake pkglibexecdir=/usr/bin
}

pbs_install() {
	make prefix="$destdir"/usr libexecdir="$destdir"/usr/bin \
	     mandir="$destdir"/usr/share/man \
	     infodir="$destdir"/usr/share/info \
	     pkglibexecdir="$destdir"/usr/bin \
	     GIHDIR="$destdir"/usr/share/gnuplot \
	     datadir="$destdir"/usr/share install

	dodoc Copyright
	install -Dm644 lisp/dotemacs "$destdir"/usr/share/emacs/site-lisp/dotemacs

	rm -f "$destdir"/usr/share/texmf-dist/ls-R
}

