#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl extension for using OpenSSL"
HOMEPAGE="http://search.cpan.org/dist/$N"
LICENSE="custom:BSD"
GROUP="perl"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://www.cpan.org/authors/id/M/MI/MIKEM/$N-$V.tar.gz"
CHECKSUM="8dfa6adc39623905267a4d3232158e01"

RDEPEND="openssl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodoc README
    perl_cleanup
}

