#
# YLmf_OS package build script
#

DESCRIPTION="Free implementation of the .NET platform including runtime and compiler"
HOMEPAGE="http://www.go-mono.com http://ftp.novell.com/pub/mono/sources-stable/"
LICENSE="LGPLv2, MIT X11"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

# another download url: http://download.mono-project.com/sources/
SRC_URI="http://ftp.novell.com/pub/mono/sources/"$N"/"$N-$V".tar.bz2"

RDEPEND="zlib libgdiplus"
BDEPEND="bison pkgconfig"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	autoreconf -f -i -s

	YPB_CONFIG+="--with-jit=yes
	             --with-ikvm-native=no
		     --with-preview=yes
		     --with-libgdiplus=installed
		     --with-x=yes
		     --with-profile4=no
		     --with-moonlight=no
		     --enable-quiet-build=no							 
		     --disable-shared-handles"
	ypkg_config
}

pbs_build() {
	ypkg_make
	
	# Build jay
	#cd mcs/jay
	#ypkg_make
	#cd -
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc mcs/MIT.X11
	
	# Install jay
	#cd mcs/jay
	#ypkg_mkinstall prefix=/usr install=../../install-sh install

	# Fix .pc file to be able to request mono on what it depends, fixes #go-oo build
	sed -i -e "s:#Requires:Requires:" "$YPPATH_DEST"/usr/lib/pkgconfig/mono.pc
}

