#
# YLmf_OS package build script
#

DESCRIPTION="Perl module implementing 'which' internally"
HOMEPAGE="http://search.cpan.org/~adamk/File-Which-1.09/"
LICENSE="GPL PerlArtistic"
YARCH="any"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/A/AD/ADAMK/File-Which-"$V".tar.gz"

RDEPEND=""
BDEPEND="test-script"

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}
