#
# Ylmf OS package build script
#

DESCRIPTION="nvidia opensource X driver - firmware needed for NV40 and above"
HOMEPAGE="http://nouveau.freedesktop.org/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://people.freedesktop.org/~pq/nouveau-drm/"$N-$V".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_install() {
	docp *  "$destdir"/lib/firmware/nouveau/
}

