#
# YLmf_OS package build script
#

DESCRIPTION="driver manager for ylmfos, gtk frontend"
HOMEPAGE="www.ylmf.net"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="ylmfos-driver-manager"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

