#
# Ylmf OS package build script
#
DESCRIPTION="Ghostscript Standard Fonts"
HOMEPAGE="http://www.cups.org/"
LICENSE="GPL"
YARCH="any"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://mirror.cs.wisc.edu/pub/mirrors/ghost/fonts/ghostscript-fonts-std-"$V".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_install() {
	docp * "$destdir"/usr/share/fonts/ghostscript
}

