#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Patches text with given patch "
HOMEPAGE="http://search.cpan.org/~cade/Text-Patch-1.8/"
LICENSE="GPL PerlArtistic"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
YARCH="any"

SRC_URI="http://mirrors.xmu.edu.cn/CPAN/authors/id/C/CA/CADE/Text-Patch-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

