#
# Ylmf OS package build script
#

DESCRIPTION="C++ interface for the ATK library"
HOMEPAGE="http://www.gtkmm.org"
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/"$N"/2.22/"$N-$V".tar.xz"
CHECKSUM="30f8e34c92b14f17ba3029937b2f218a"

RDEPEND="atk gcc-lib glib2 glibc glibmm libsigc++"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

