#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Exuberant Ctags creates tags files for code browsing in editors"
HOMEPAGE="http://ctags.sourceforge.net"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://prdownloads.sourceforge.net/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--with-posix-regex 
	             --without-readlib 
		     --disable-etags 
		     --enable-tmpdir=/tmp"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	make prefix="$destdir"/usr install
}

