#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Exuberant Ctags creates tags files for code browsing in editors"
HOMEPAGE="http://ctags.sourceforge.net"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://downloads.sourceforge.net/sourceforge/$N/$N-$V.tar.gz"
CHECKSUM="c00f82ecdcc357434731913e5b48630d"

RDEPEND="glibc"
BDEPEND=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--disable-external-sort"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    make prefix="$PKGDIR"/usr install
}

