#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A library to execute a function when a specific event occurs on a file descriptor"
HOMEPAGE="http://monkey.org/~provos/libevent/"
LICENSE="BSD"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="https://github.com/downloads/${N}/${N}/${N}-$V-stable.tar.gz"
CHECKSUM="b2405cc9ebf264aa47ff615d9de527a2"

RDEPEND="openssl"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

