#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="MariaDB client tools"
HOMEPAGE="http://mariadb.org/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://mirrors.supportex.net/mariadb/mariadb-$V/kvm-tarbake-jaunty-x86/mariadb-$V.tar.gz"
CHECKSUM="64dba5f1819f1d4ebf7ed31d74e4106c981a24b88259995deba3734fb7c4635f"

RDEPEND="libmariadbclient openssl gcc-libs ncurses"
BDEPEND="cmake openssl zlib"
REPLACE="mysql-clients"

pbs_unpack() {
    dounpack
}

pbs_config() {
    mkdir build
    cd build
    # CFLAGS/CXXFLAGS as suggested upstream
    cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DSYSCONFDIR=/etc/mysql \
          -DMYSQL_DATADIR=/var/lib/mysql \
          -DMYSQL_UNIX_ADDR=/run/mysqld/mysqld.sock \
          -DDEFAULT_CHARSET=utf8 \
          -DDEFAULT_COLLATION=utf8_general_ci \
          -DENABLED_LOCAL_INFILE=ON \
          -DINSTALL_INFODIR=share/mysql/docs \
          -DINSTALL_MANDIR=share/man \
          -DINSTALL_LIBDIR=lib"$LIBDIRSUFFIX" \
          -DINSTALL_PLUGINDIR=lib"$LIBDIRSUFFIX"/mysql/plugin \
          -DINSTALL_SCRIPTDIR=bin \
          -DINSTALL_INCLUDEDIR=include/mysql \
          -DINSTALL_DOCREADMEDIR=share/mysql \
          -DINSTALL_SUPPORTFILESDIR=share/mysql \
          -DINSTALL_MYSQLSHAREDIR=share/mysql \
          -DINSTALL_DOCDIR=share/mysql/docs \
          -DINSTALL_SHAREDIR=share/mysql \
          -DWITH_READLINE=ON \
          -DWITH_ZLIB=system \
          -DWITH_SSL=system \
          -DWITH_LIBWRAP=OFF \
          -DWITH_EXTRA_CHARSETS=complex \
          -DWITH_EMBEDDED_SERVER=ON \
          -DWITH_INNOBASE_STORAGE_ENGINE=1 \
          -DWITH_PARTITION_STORAGE_ENGINE=1 \
          -DWITHOUT_EXAMPLE_STORAGE_ENGINE=1 \
          -DWITHOUT_ARCHIVE_STORAGE_ENGINE=1 \
          -DWITHOUT_BLACKHOLE_STORAGE_ENGINE=1 \
          -DWITHOUT_FEDERATED_STORAGE_ENGINE=1 \
          -DCMAKE_C_FLAGS="-fPIC ${CFLAGS} -fno-strict-aliasing -DBIG_JOINS=1 -fomit-frame-pointer" \
          -DCMAKE_CXX_FLAGS="-fPIC ${CXXFLAGS} -fno-strict-aliasing -DBIG_JOINS=1 -felide-constructors -fno-rtti"
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall -C client
    # install man pages
    for x in mysql mysqladmin mysqlcheck mysqldump mysqlimport mysqlshow mysqlslap; do
        doman "$SRCDIR"/man/"$x".1
    done  
    # provided by mariadb
    rm "$PKGDIR"/usr/bin/{mysql_{plugin,upgrade},mysqlbinlog,mysqltest}
}
