#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python bindings for libnotify"
HOMEPAGE="http://www.galago-project.org"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://www.galago-project.org/files/releases/source/"$N"/"$N-$V".tar.gz"
CHECKSUM="8f0ef0939cc8edd2efd896ce5ba80cf4"

RDEPEND="libnotify pygtk"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_patch() {
    dopatch libnotify07.patch notify-python-0.1.1-fix-GTK-symbols.patch
	# Remove the old pynotify.c to ensure it's properly regenerated #212128.
	rm -f src/pynotify.c
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

