#
# YLmf_OS package build script
#

DESCRIPTION="Python bindings for libnotify"
HOMEPAGE="http://www.galago-project.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.galago-project.org/files/releases/source/"$N"/"$N-$V".tar.gz"

RDEPEND="atk cairo dbus dbus-glib expat fontconfig freetype gcc gdk-pixbuf glib2 glibc gtk+ libnotify libpng libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender pango pixman zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	# Remove the old pynotify.c to ensure it's properly regenerated #212128.
	rm -f src/pynotify.c
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

