#
# YLmf_OS package build script
#

DESCRIPTION="Python bindings for libnotify"
HOMEPAGE="http://www.galago-project.org"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://www.galago-project.org/files/releases/source/"$N"/"$N-$V$R".tar.gz"

RDEPEND="atk cairo dbus dbus-glib expat fontconfig freetype gcc glib2 glibc gtk+ libnotify libpng libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender pango pixman zlib"
BDEPEND="atk-dev cairo-dev dbus-dev dbus-glib-dev expat-dev fontconfig-dev freetype-dev gcc-dev glib2-dev glibc-dev gtk+-dev libnotify-dev libpng-dev libX11-dev libXau-dev libxcb-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXi-dev libXrandr-dev libXrender-dev pango-dev pixman-dev zlib-dev"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	# Remove the old pynotify.c to ensure it's properly regenerated #212128.
	rm -f src/pynotify.c
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
