
post_install() {
	# For initramfs
	name="$1"
	version="$2"
	depmod -a "$version"
	update-initramfs -d -c -k "$version"

	# For grub
	update-grub
}       

post_remove() {
	name="$1"
	version="$2"
	rm /boot/initrd.img-"$version"         2>/dev/null
	rm /var/lib/initramfs-tools/"$version" 2>/dev/null

	# For grub
	update-grub
}

post_upgrade() {
	old_ver="$2"
	rm -rf /var/lib/initramfs-tools/"$old_ver" 2>/dev/null
	post_install $1 $2
}

post_downgrade() {
	post_upgrade
}

