#
# YLmf_OS package build script
#

DESCRIPTION="KDE Yet Another Weather Plasmoid"
HOMEPAGE="http://www.kde-look.org/content/show.php?content=94106"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://downloads.sourceforge.net/yawp/yawp-$V.tar.bz2"

RDEPEND=""
BDEPEND="kdelibs cmake automoc4"

INSTALL="$N.install"

pbs_unpack() {
       dounpack
}

pbs_config() {
       mkdir -p ../build && cd ../build
	cmake ../$N-$V -DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=/usr
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

