#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Simple but powerful unit testing framework for C++"
HOMEPAGE="http://cpptest.sourceforge.net/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://downloads.sourceforge.net/project/"$N"/"$N"/"$N-$V$R"/"$N-$V$R".tar.gz"

RDEPEND=""
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
