#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="a simple, small, C++ XML parser that can be easily integrating into other programs"
HOMEPAGE="http://www.grinninglizard.com/tinyxml/index.html"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://downloads.sourceforge.net/$N/${N}_${V//./_}.tar.gz"
CHECKSUM="c1b864c96804a10526540c664ade67f0"

RDEPEND="gcc-libs"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_patch() {
    # Fix entity encoding.
    dopatch entity.patch
    # Make TINYXML_USE_STL permanently defined in tinyxml.h
    dopatch tinyxml-2.5.3-stl.patch
    # Fix Makefile
    sed -i \
        -e '/^TINYXML_USE_STL/ s|=.*|=YES|' \
        -e "s|^RELEASE_CFLAGS.*|& ${CXXFLAGS} -fPIC|" Makefile
}

pbs_build() {
    make
    g++ -fPIC ${CXXFLAGS} -shared -o lib$"$N".so.0."$V" \
      -Wl,-soname,lib"$N".so.0 $(ls *.o | grep -v xmltest)
}

pbs_install() {
    docp lib"$N".so.0."$V" "$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/
    docp "$N".h tinystr.h  "$PKGDIR"/usr/include

    cd "$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/
    doln lib"$N".so.0."$V" lib"$N".so.0
    doln lib"$N".so.0."$V" lib"$N".so
}
