#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Interactively examine a C program"
HOMEPAGE="http://cscope.sourceforge.net/"
REPO=""
LICENSE="BSD"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://nchc.dl.sourceforge.net/project/cscope/cscope/15.7a/cscope-15.7a.tar.bz2"

RDEPEND="glibc ncurses"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	sed -i 's|/usr/local/lib/cs|/usr/lib/cs|' contrib/ocs
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc AUTHORS COPYING README
	install -d "${destdir}/usr/lib/cs"
	cd contrib/xcscope
	docp xcscope.el ${destdir}/usr/share/emacs/site-lisp/
	install -m755 cscope-indexer $destdir/usr/bin
}

