#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="library that handles Resource Description Framework (RDF)"
HOMEPAGE="http://librdf.org/rasqal/"
LICENSE="GPL,LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://download.librdf.org/source/"$N-$V".tar.gz"
CHECKSUM="49e4b75a0c67465edf55dd20606715fa"

RDEPEND="mpfr raptor2 mhash"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--disable-static --enable-release"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

