#
# YLmf_OS package build script
#

DESCRIPTION="an open-source library for reading, mastering and writing optical discs."
HOMEPAGE="http://icculus.org/burn/"
LICENSE="GNU General Public License"
PACKAGER="<ylmfos@115.com>"
 
SRC_URI="http://icculus.org/burn/releases/"$N-$V$R".tar.gz"

RDEPEND="acl attr glibc"
BDEPEND="  "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
