#
# YLmf_OS package build script
#

DESCRIPTION="an open-source library for reading, mastering and writing optical discs."
HOMEPAGE="http://icculus.org/burn/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="http://icculus.org/burn/releases/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

