#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="an open-source library for reading, mastering and writing optical discs."
HOMEPAGE="http://libburnia-project.org/"
LICENSE="GPL"
PACKAGER="StartOS Developers"
 
SRC_URI="http://files.libburnia-project.org/releases/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--disable-static"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

