#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An object-oriented language for quick and easy programming"
HOMEPAGE="http://www.ruby-lang.org/en/"
REPO=""
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="ftp://ftp.ruby-lang.org/pub/ruby/1.9/ruby-"$V$R"-p180.tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
	dounpack
}

pbs_config() {
	config+="--enable-pthread --disable-rpath"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall 
	dodoc COPYING
}

