#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An object-oriented language for quick and easy programming"
HOMEPAGE="http://www.ruby-lang.org/en/"
LICENSE="custom,BSD"
PACKAGER="StartOS Developers"

SRC_URI="ftp://ftp.ruby-lang.org/pub/"$N"/1.9/"$N-$V"-p194.tar.bz2"
CHECKSUM="2278eff4cfed3cbc0653bc73085caa34"

RDEPEND="berkeley-db expat fontconfig freetype gdbm glibc libffi libX11 libXau libxcb libXdmcp libXext libXft libXrender libXScrnSaver ncurses openssl readline tcl tk zlib"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
	dounpack
}

pbs_config() {
	config+=" --enable-shared
	          --enable-pthread 
	          --disable-rpath 
		  --disable-install-doc "
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	make DESTDIR="${destdir}" install-nodoc
	docp "${filesdir}"/gemrc "${destdir}"/etc/
	dodoc COPYING BSDL
}

