#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python bindings for sys-apps/parted"
HOMEPAGE="https://fedorahosted.org/pyparted/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="https://fedorahosted.org/releases/p/y/"$N"/"$N-$V".tar.gz"
CHECKSUM="e9cd0c94c71ac17755f71a8e1561eac2"

RDEPEND="parted(>=3.1) python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

