#
# YLmf_OS package build script
#

DESCRIPTION="Python bindings for sys-apps/parted"
HOMEPAGE="https://fedorahosted.org/pyparted/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="https://fedorahosted.org/releases/p/y/"$N"/"$N-$V".tar.gz"

RDEPEND="device-mapper glibc parted python udev util-linux-ng"
BDEPEND="decorator"
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	sed -i -e 's/-avoid-version/& -shared /' src/Makefile.am 
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc ChangeLog NEWS README TODO
}
