#
# YLmf_OS package build script
#

DESCRIPTION="ruijie client"
HOMEPAGE="http://code.google.com/p/mentohust/"
REPO=""
LICENSE="GPLv3"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://mentohust.googlecode.com/files/"$N-$V$R".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
