#!/bin/sh

device_ids() {
	local filename="$1"
	grep "0x" "$filename" | \
	  sed -n 's/FGL_ASIC_ID(0x\([0-9A-F]\{4\}\)),$/alias pci:v00001002d0000\1sv*sd*bc03sc*i*/p' | \
	  sort | uniq | sed -e 's/^[ \t]*//'
}

echo "package ati-graphic-legacy-driver"
echo "module fglrx.ko"
echo "description AMD Catalyst™ Legacy Driver for AMD Radeon™ HD 4000, HD 3000 and HD 2000 Series"
device_ids fglrxko_pci_ids.h

