#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="X11 Apps"
HOMEPAGE="http://www.x.org/wiki/"
 
SRCURL="http://www.x.org/releases/X11R7.5/src/app"
SRC_URI="$SRCURL/xsetroot-1.0.3.tar.bz2"

RDEPEND="libXmu libX11 libxcb libXau libXdmcp"
BDEPEND=""

pbs_unpack()
{
        dounpack
}

pbs_config()
{
	
	doconfig
}

pbs_build()
{
	domake
}

pbs_install()
{
	domkinstall
}
