#
# YLmf_OS package build script
#

DESCRIPTION="Print out X-Video extension adaptor information"
HOMEPAGE="http://xorg.freedesktop.org/"
 
SRC_URI="http://www.x.org/releases/X11R7.6/src/app/"$N-$V$R".tar.bz2"

RDEPEND="libXv libX11 libXext libxcb libXau libXdmcp"
BDEPEND="${RDEPEND}"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
