#
# YLmf_OS package build script
#

DESCRIPTION="A spell checker replacement for ispell"
HOMEPAGE="http://aspell.net/"
LICENSE="LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="ftp://ftp.gnu.org/gnu/"$N"/"$N-$V".tar.gz"

RDEPEND="gcc glibc ncurses"
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

