#
# YLmf_OS package build script
#

DESCRIPTION=" A Perl extension interface to James Clark's XML parser, expat"
HOMEPAGE="http://search.cpan.org/~msergeant/"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"

SRC_URI="http://mirror.osqdu.org/CPAN/authors/id/T/TO/TODDR/XML-Parser-"$V".tar.gz"

RDEPEND="perl expat glibc"
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

