#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Collection of data files to add support for various chemical MIME types"
HOMEPAGE="http://chemical-mime.sourceforge.net"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://downloads.sourceforge.net/chemical-mime/$N-$V.tar.gz"
CHECKSUM="ca54b5fbd7f43ee5380e394bfd273b95"

RDEPEND="xdg-utils gnome-mime-data"
RECOMMENDED=""
BDEPEND="intltool libxslt imagemagick librsvg"
OPTIONAL=""
CONFLICT=""
REPLACE=""

INSTALL="$N.install"

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--disable-update-database"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
