#
# YLmf_OS package build script
#

DESCRIPTION="The libdbi-drivers project maintains drivers for libdbi."
HOMEPAGE="http://libdbi-drivers.sourceforge.net/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://sourceforge.net/projects/"$N"/files/"$N"/"$N-$V"/"$N-$V".tar.gz"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-docs
	  	     --with-libdbi" 
		     #--with-sqlite
		     #--with-sqlite3
		     #--with-pgsql
		     #--with-mysql
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	#make DESTDIR="$YPPATH_DEST" install
	ypkg_mkinstall
	#ypkg_doinit "$N"
	#ypkg_dounit "N".service
	#ypkg_dodesktop "*.desktop" "*.png"
	#ypkg_dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README 
	#ypkg_docp "$FILES_PATH/files/XXXX" "dirname"
	#ypkg_domv "$FILES_PATH/files/XXXX" "dirname"
	#ypkg_docp_rename "$1" "$2"
	#ypkg_domv_rename "$1" "$2"
	#ypkg_doln "$1 "$2"
	#ypkg_doman a.1 b.2 c.3
	#*****************
	#when SRC_URI is deb or rpm package
	#ypkg_docp data/*  "$YPPATH_DEST"
}

#split package
foo_install () {
	:
}


