. /usr/lib/ybs/funcs

post_install() {
	gnome2_install_schema "/etc/gconf/schemas/gnome-terminal.schemas"
	gnome2_install_defaut_gconf "string" "/apps/gnome-terminal/profiles/Default/background_color"    "#000000000000"
	gnome2_install_defaut_gconf "float"  "/apps/gnome-terminal/profiles/Default/background_darkness" "0.5"
	gnome2_install_defaut_gconf "string" "/apps/gnome-terminal/profiles/Default/bold_color"          "#000000000000"
	gnome2_install_defaut_gconf "string" "/apps/gnome-terminal/profiles/Default/foreground_color"    "#AAAAAAAAAAAA"
	gnome2_install_defaut_gconf "string" "/apps/gnome-terminal/profiles/Default/cursor_shape"        "ibeam"
	gnome2_install_defaut_gconf "string" "/apps/gnome-terminal/profiles/Default/font"                "Bitstream Vera Sans Mono 11"
	gnome2_install_defaut_gconf "bool"   "/apps/gnome-terminal/profiles/Default/use_system_font"     "false"
	gnome2_install_defaut_gconf "bool"   "/apps/gnome-terminal/profiles/Default/use_theme_colors"    "false"
	gnome2_rarian_sk_update
	gnome2_desktop_database_update
	gnome2_gconfd_reload
}

