#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Pthread functions stubs for platforms missing them"
HOMEPAGE="http://xorg.freedesktop.org/"
 
SRC_URI="http://xcb.freedesktop.org/dist/$N-$V.tar.bz2"

RDEPEND=""
BDEPEND=""

pbs_unpack()
{
        dounpack
}

pbs_config()
{
	
	doconfig
}

pbs_build()
{
	domake
}

pbs_install()
{
	domkinstall
}
