#
# Ylmf OS package build script
#

DESCRIPTION="An OCR (Optical Character Recognition) reader"
HOMEPAGE="http://jocr.sourceforge.net"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www-e.uni-magdeburg.de/jschulen/ocr/"$N-$V".tar.gz"

RDEPEND="glibc"
RECOMMENDED=""
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	make -j1 all libs
}

pbs_install() {
	domkinstall
}

