#
# YLmf_OS package build script
#

DESCRIPTION="Compatibility library for accessing secrets"
HOMEPAGE="http://live.gnome.org/GnomeKeyring"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/$N/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	
	YPB_CONFIG+=" --prefix=/usr "
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
