#
# YLmf_OS package build script
#

DESCRIPTION="Extract translatable strings from source  "
HOMEPAGE="http://search.cpan.org/~drtech/Locale-Maketext-Lexicon-0.91/"
LICENSE="GPL PerlArtistic"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://mirrors.sohu.com/CPAN/authors/id/D/DR/DRTECH/Locale-Maketext-Lexicon-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

