#
# Ylmf OS package build script
#

DESCRIPTION="Convert a .rpm file to a .tar.gz archive"
HOMEPAGE="http://www.slackware.com/config/packages.php"
REPO=""
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://gentoo.osuosl.org/distfiles/"$N-$V$R".tar.lzma"

RDEPEND="cpio"
BDEPEND=" xz-utils"

pbs_unpack() {
        dounpack
}

pbs_build() { 	
	domake
}

pbs_install() {
	domkinstall
}
