#
# YLmf_OS package build script
#

DESCRIPTION="Convert a .rpm file to a .tar.gz archive"
HOMEPAGE="http://www.slackware.com/config/packages.php"
REPO=""
LICENSE=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://gentoo.osuosl.org/distfiles/"$N-$V$R".tar.lzma"

RDEPEND="cpio"
BDEPEND=" xz-utils"

pbs_unpack() {
        ypkg_unpack
}

pbs_build() { 	
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
