#
# YLmf_OS package build script
#

DESCRIPTION="simplistic interface to pkg-config "
HOMEPAGE="http://search.cpan.org/~tsch/ExtUtils-PkgConfig-1.12/lib/ExtUtils/PkgConfig.pm"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/ExtUtils-PkgConfig-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
