#
# YLmf_OS package build script
#

DESCRIPTION="broadcom firmware for b43 legacy"
HOMEPAGE="http://wireless.kernel.org/en/users/Drivers/b43#List_of_firmwares"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://downloads.openwrt.org/sources/wl_apsta-"$V".o"

RDEPEND=""
BDEPEND="b43-fwcutter"
RECOMMENDED=""
CONFLICT=""

pbs_build() {
	b43-fwcutter "$YPPATH_SOURCE"/wl_apsta-3.130.20.0.o
}

pbs_install() {
	ypkg_docp b43legacy "$YPPATH_DEST"/lib/firmware
}

