#
# Ylmf OS package build script
#

DESCRIPTION="SPICE server and client."
HOMEPAGE="http://spice-space.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://spice-space.org/download/releases/"$N-$V".tar.bz2"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

OPINION="nodev"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

