#
# YLmf_OS package build script
#

DESCRIPTION="English (US, British, Canadian) language dictionary for aspell"
HOMEPAGE="http://aspell.net"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="ftp://ftp.gnu.org/gnu/aspell/dict/en/aspell6-en-"$V$R".tar.bz2"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

