#
# Ylmf OS package build script
#

DESCRIPTION="English (US, British, Canadian) language dictionary for aspell"
HOMEPAGE="http://aspell.net"
LICENSE="GPLv2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="ftp://ftp.gnu.org/gnu/aspell/dict/en/aspell6-en-"$V$R".tar.bz2"

RDEPEND=""
RECOMMENDED=""
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

