#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="This module provides bindings for the cURL library."
HOMEPAGE="http://ipython.scipy.org/ http://pypi.python.org/pypi/ipython"
LICENSE="Dual licensed under the LGPL and an MIT/X derivative."
PACKAGER="StartOS Developers"

SRC_URI="http://pycurl.sourceforge.net/download/"$N-$V".tar.gz"

RDEPEND="curl python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

