#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="This module provides bindings for the cURL library."
HOMEPAGE="http://ipython.scipy.org/ http://pypi.python.org/pypi/ipython"
LICENSE="Dual licensed under the LGPL and an MIT/X derivative."
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://pycurl.sourceforge.net/download/pycurl-7.19.0.tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

