#
# Ylmf OS package build script
#

DESCRIPTION="GObject-based wrapper around the Exiv2 library"
HOMEPAGE="http://trac.yorba.org/wiki/gexiv2"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://yorba.org/download/gexiv2/0.2/"$N-$V".tar.bz2"

RDEPEND="exiv2 gcc glib2 glibc zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	dopatch gexiv2-0.2.1-new-exiv2.patch
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

