#
# YLmf_OS package build script
#

DESCRIPTION="D-Bus bindings for GObject"
HOMEPAGE="http://cgit.freedesktop.org/~david/eggdbus"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://hal.freedesktop.org/releases/"$N-$V".tar.gz"

RDEPEND="dbus dbus-glib glib2 glibc zlib"
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	make 
}

pbs_install() {
	ypkg_mkinstall
}

