#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Crypto++ is a C++ class library of cryptographic schemes"
HOMEPAGE="http://cryptopp.com"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://cryptopp.com/cryptopp560.zip"

RDEPEND="gcc-lib glibc"
BDEPEND="unzip"

pbs_unpack() {
	dounpack
}

pbs_build() {
	dopatch "$N-$V"-fix_build_system.patch
	domake 
}

pbs_install() {
	domkinstall
	docp $filesdir/libcrypto++.pc "$destdir"/usr/lib/pkgconfig/
}

