#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Crypto++ is a C++ class library of cryptographic schemes"
HOMEPAGE="http://cryptopp.com"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://cryptopp.com/cryptopp560.zip"

RDEPEND="gcc-libs"
BDEPEND="unzip"

pbs_unpack() {
    dounpack
}

pbs_build() {
    dopatch "$N-$V"-fix_build_system.patch
    domake 
}

pbs_install() {
    domkinstall
    docp $FILESDIR/libcrypto++.pc "$PKGDIR"/usr/lib/pkgconfig/
}

