#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A computer display server protocol"
HOMEPAGE="http://wayland.freedesktop.org"
LICENSE="MIT"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://wayland.freedesktop.org/releases/$N-$V.tar.xz"
CHECKSUM="e2e9ebfbaf9b013471c620b99938d764"

RDEPEND="expat glibc libffi"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--disable-static"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodoc COPYING
}
