#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="DNSSEC trust anchors for the root zone"
HOMEPAGE="http://data.iana.org/root-anchors"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI=""

RDEPEND=""
RECOMMENDED=""
BDEPEND=""
CONFLICT=""
REPLACE=""

pbs_install() {
    docp "$filesdir"/trusted-key.key "$destdir"/etc/
}

