#
# YLmf_OS package build script
#

DESCRIPTION="Tool Command Language"
HOMEPAGE="http://www.tcl.tk/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI="http://downloads.sourceforge.net/"$N"/"$N$V"-src.tar.gz"

RDEPEND="glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	cd unix
	config+="--enable-threads --disable-64bit"  
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	make INSTALL_ROOT="$destdir" install install-private-headers
	dodoc ../license.terms
	cd "$destdir"
	doln /usr/bin/tclsh8.5 usr/bin/tclsh 
	# Remove buildroot traces
	sed -i \
	    -e "s,^TCL_BUILD_LIB_SPEC='-L.*/unix,TCL_BUILD_LIB_SPEC='-L/usr/lib," \
	    -e "s,^TCL_SRC_DIR='.*',TCL_SRC_DIR='/usr/include'," \
	    -e "s,^TCL_BUILD_STUB_LIB_SPEC='-L.*/unix,TCL_BUILD_STUB_LIB_SPEC='-L/usr/lib," \
	    -e "s,^TCL_BUILD_STUB_LIB_PATH='.*/unix,TCL_BUILD_STUB_LIB_PATH='/usr/lib," \
	    -e "s,^TCL_LIB_FILE='libtcl8.5..TCL_DBGX..so',TCL_LIB_FILE=\"libtcl8.5\$\{TCL_DBGX\}.so\"," \
	    -e "s,^TCL_CC_SEARCH_FLAGS='\(.*\)',TCL_CC_SEARCH_FLAGS='\1:/usr/lib'," \
	    -e "s,^TCL_LD_SEARCH_FLAGS='\(.*\)',TCL_LD_SEARCH_FLAGS='\1:/usr/lib'," \
			usr/lib/tclConfig.sh
}

