#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Tool Command Language"
HOMEPAGE="http://www.tcl.tk/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
 
SRC_URI="http://downloads.sourceforge.net/"tcl"/"$N$V$R"-src.tar.gz"

RDEPEND=""
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	cd unix
	config+="--enable-threads" 
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	sed -i -e "s@^\(TCL_SRC_DIR='\).*@\1/usr/include'@" \
	       -e "/TCL_B/s@='\(-L\)\?.*unix@='\1/usr/lib@" \
	       tclConfig.sh
	domkinstall 
	make DESTDIR="$destdir" install-private-headers
	cd "$destdir"
	doln tclsh8.5 usr/bin/tclsh 
}
