#
# Ylmf OS package build script
#

DESCRIPTION="Multi-dimensional data index algorithm"
HOMEPAGE="http://code.google.com/p/multidimalgorithm/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://multidimalgorithm.googlecode.com/files/mdds_0.5.3.tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

