#! /bin/sh
# Updates the gdk-pixbuf.loaders in /etc/gtk-2.0/

umask 022

FILE=/etc/gtk-2.0/gdk-pixbuf.loaders

if [ -x /usr/bin/gdk-pixbuf-query-loaders ]; then
     /usr/bin/gdk-pixbuf-query-loaders > $FILE
fi

