#
# Ylmf OS package build script
#

DESCRIPTION="Perl module"
HOMEPAGE="http://search.cpan.org/~jsiracusa/Rose-HTML-Objects/lib/Rose/HTML/Form.pm"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://search.cpan.org/CPAN/authors/id/J/JS/JSIRACUSA/Rose-HTML-Objects-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

