#
# YLmf_OS package build script
#

DESCRIPTION="Perl module"
HOMEPAGE="http://search.cpan.org/~jsiracusa/Rose-HTML-Objects/lib/Rose/HTML/Form.pm"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://search.cpan.org/CPAN/authors/id/J/JS/JSIRACUSA/Rose-HTML-Objects-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

