#
# YLmf_OS package build script
#

DESCRIPTION="Perl module"
HOMEPAGE="http://search.cpan.org/~jsiracusa/Rose-HTML-Objects/lib/Rose/HTML/Form.pm"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://search.cpan.org/CPAN/authors/id/J/JS/JSIRACUSA/Rose-HTML-Objects-"$V$R".tar.gz"

RDEPEND=""
BDEPEND="${RDEPEND} "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
