#
# YLmf_OS package build script
#

DESCRIPTION="LXDE terminal emulator"
HOMEPAGE="www.lxde.org"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://ncu.dl.sourceforge.net/project/lxde/LXTerminal%20%28terminal%20emulator%29/LXTerminal%200.1.11/"$N-$V$R".tar.gz"

RDEPEND="atk cairo expat fontconfig freetype gcc glib2 glibc gtk+ libpng libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender ncurses pango pixman vte zlib"
BDEPEND=""

pbs_unpack() {
	ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--enable-man"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
