#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="LXDE terminal emulator"
HOMEPAGE="www.lxde.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ncu.dl.sourceforge.net/project/lxde/LXTerminal%20%28terminal%20emulator%29/LXTerminal%200.1.11/"$N-$V".tar.gz"

RDEPEND="atk cairo expat fontconfig freetype gcc-lib gdk-pixbuf glib2 glibc gtk+ libpng libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender ncurses pango pixman vte zlib"
BDEPEND=""

pbs_unpack() {
	dounpack
}

pbs_config() {
	config+="--enable-man"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
