#
# YLmf_OS package build script
#

DESCRIPTION="LXDE terminal emulator"
HOMEPAGE="www.lxde.org"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="git://lxde.git.sourceforge.net/gitroot/lxde/"$N""

RDEPEND="atk cairo expat fontconfig freetype gcc glib2 glibc gtk+ libpng libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libXrandr libXrender ncurses pango pixman vte zlib"
BDEPEND="atk-dev cairo-dev expat-dev fontconfig-dev freetype-dev gcc-dev glib2-dev glibc-dev gtk+-dev libpng-dev libX11-dev libXau-dev libxcb-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXi-dev libXrandr-dev libXrender-dev ncurses-dev pango-dev pixman-dev vte-dev zlib-dev"

pbs_unpack() {
	ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--enable-man"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
