#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="LXDE terminal emulator"
HOMEPAGE="www.lxde.org"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://ncu.dl.sourceforge.net/project/lxde/LXTerminal%20%28terminal%20emulator%29/LXTerminal%200.1.11/"$N-$V".tar.gz"

RDEPEND="vte"
BDEPEND=""

pbs_unpack() {
	dounpack
}

pbs_config() {
	config+="--enable-man"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
