#
# YLmf_OS package build script
#

DESCRIPTION="Python bindings for the WebKit GTK+ port"
HOMEPAGE="http://code.google.com/p/pywebkitgtk/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://pywebkitgtk.googlecode.com/files/"$N-$V$R".tar.bz2"

RDEPEND="atk cairo enchant expat fontconfig freetype gail gcc glib2 glibc gnutls gst-plugins-base gstreamer gtk+ icu libgcrypt libgpg-error libICE libjpeg-turbo libpng libSM libsoup libtasn1 libX11 libXau libxcb libXcomposite libXcursor libXdamage libXdmcp libXext libXfixes libXi libxml2 libXrandr libXrender libxslt libXt pango pixman sqlite util-linux-ng webkit zlib"
BDEPEND="atk-dev cairo-dev enchant-dev expat-dev fontconfig-dev freetype-dev gail-dev gcc-dev glib2-dev glibc-dev gnutls-dev gst-plugins-base-dev gstreamer-dev gtk+-dev icu-dev libgcrypt-dev libgpg-error-dev libICE-dev libjpeg-turbo-dev libpng-dev libSM-dev libsoup-dev libtasn1-dev libX11-dev libXau-dev libxcb-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXi-dev libxml2-dev libXrandr-dev libXrender-dev libxslt-dev libXt-dev pango-dev pixman-dev sqlite-dev util-linux-ng-dev webkit-dev zlib-dev"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc ChangeLog COPYING NEWS README 
}
