#
# YLmf_OS package build script
#

DESCRIPTION="Python bindings for the WebKit GTK+ port"
HOMEPAGE="http://code.google.com/p/pywebkitgtk/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://pywebkitgtk.googlecode.com/files/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND="${RDEPEND}"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc ChangeLog COPYING NEWS README 
}
