#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Package config system that manages compile/link flags"
HOMEPAGE="http://pkgconfig.freedesktop.org/wiki/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://pkgconfig.freedesktop.org/releases/pkg-config-"$V".tar.gz"
CHECKSUM="5392b4e3372879c5bf856173b418d6a2"

RDEPEND="glib2"
BDEPEND=""
CONFLICT=""

OPTIONS="nodev"

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

