#
# Ylmf OS package build script
#

DESCRIPTION="Package config system that manages compile/link flags"
HOMEPAGE="http://pkgconfig.freedesktop.org/wiki/"
 
SRC_URI="http://pkgconfig.freedesktop.org/releases/pkg-config-"$V$R".tar.gz"

RDEPEND="glibc"
BDEPEND=""
CONFLICT=""

OPINION="nodev"

pbs_unpack() {
        dounpack
}

pbs_config() {
	export GLIB_CFLAGS="-I/usr/include/glib-2.0 -I/usr/lib"$LIBDIRSUFFIX"/glib-2.0/include"
	export GLIB_LIBS="-lglib-2.0"	
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

