#
# Ylmf OS package build script
#

DESCRIPTION="The Eazel Extentions Library"
HOMEPAGE="http://www.gnome.org/"
REPO="Testing"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/eel/2.26/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" gnome-desktop gnome-menus gail"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--prefix=/usr"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
