#
# Ylmf OS package build script
#

DESCRIPTION="A qt-based library that maps JSON data to QVariant objects"
HOMEPAGE="http://qjson.sourceforge.net"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://downloads.sourceforge.net/"$N"/"$N-$V".tar.bz2"
CHECKSUM="5a833ad606c164ed8aa69f0873366ace"

RDEPEND="gcc-lib glib2 glibc qt-core zlib"
RECOMMENDED=""
BDEPEND="cmake"
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	mkdir -p build && cd build
	cmake .. \
	      -DCMAKE_INSTALL_PREFIX=/usr \
	      -DCMAKE_BUILD_TYPE=Release
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

