#
# Ylmf OS package build script
#

DESCRIPTION="san guo sha (AIR)"
HOMEPAGE="http://www.sanguosha.com/web2/downloads.asp"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://web.sanguosha.com/2/air/SanGuoSha.air"

RDEPEND="adobe-air-sdk"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

pbs_install() {
	docp      "$YPPATH_SOURCE"/SanGuoSha.air  "$destdir"/usr/lib/"$N"
	dodesktop "$N.desktop" "$N.png"
}

