#
# YLmf_OS package build script
#

DESCRIPTION="Run commands simply, with detailed diagnostics"
HOMEPAGE="http://search.cpan.org/~pjf/IPC-System-Simple-1.21/"
LICENSE="GPL PerlArtistic"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://cpan.communilink.net/authors/id/P/PJ/PJF/IPC-System-Simple-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

