#
# YLmf_OS package build script
#

DESCRIPTION="X.Org autotools utility macros"
HOMEPAGE="http://xorg.freedesktop.org/"
REPO=""
LICENSE=""
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://www.x.org/releases/X11R7.6/src/util/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {	
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
