#
# YLmf_OS package build script
#

DESCRIPTION="Log4j implementation for Perl"
HOMEPAGE="http://search.cpan.org/~mschilli/Log-Log4perl-1.33/"
LICENSE="GPL PerlArtistic"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"
YVERSION="1"

SRC_URI="http://cpan.communilink.net/authors/id/M/MS/MSCHILLI/Log-Log4perl-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

