#
# Ylmf OS package build script
#

DESCRIPTION="Fallback theme for the freedesktop icon theme specification"
HOMEPAGE="http://icon-theme.freedesktop.org/wiki/HicolorTheme"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"
 
SRC_URI="http://icon-theme.freedesktop.org/releases/"$N-$V".tar.gz"

RDEPEND=""
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_install() {
	domkinstall
}
