#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="getaddrinfo/getnameinfo support module"
HOMEPAGE="http://search.cpan.org/dist/Socket6"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="GPL,PerlArtistic"
GROUP="perl"

SRC_URI="http://search.cpan.org/CPAN/authors/id/U/UM/UMEMOTO/Socket6-$V.tar.gz"
CHECKSUM="2c02adb13c449d48d232bb704ddbd492"

RDEPEND="perl glibc"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1 PERL5LIB="" \
           PERL_AUTOINSTALL=--skipdeps \
           PERL_MM_OPT="INSTALLDIRS=vendor" \
           PERL_MB_OPT="--installdirs vendor" \
           MODULEBUILDRC=/dev/null
    perl Makefile.PL
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}
