#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="minimal try/catch with proper localization of \$@"
HOMEPAGE="http://search.cpan.org/dist/$N"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="GPL,PerlArtistic"
YARCH="any"

SRC_URI="http://search.cpan.org/CPAN/authors/id/D/DO/DOY/"$N-$V".tar.gz"
CHECKSUM="4d2c8ff385ac3513edf4c042dd0eacbe"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1 PERL5LIB="" \
           PERL_AUTOINSTALL=--skipdeps  \
           PERL_MM_OPT="INSTALLDIRS=vendor DESTDIR='$destdir'" \
           PERL_MB_OPT="--installdirs vendor --destdir '$destdir'" \
           MODULEBUILDRC=/dev/null
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}

