#
# YLmf_OS package build script
#

DESCRIPTION="A set of backgrounds packaged with the ylmfos"
HOMEPAGE="http://www.ylmf.com"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="desktop-file-utils gnome-desktop"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

