#!/bin/sh
# Begin /etc/init.d/osinstaller
#
# LastChangedBy: Zhongxin Huang <huangzhongxin@ivali.com>
#

XINITRC="/root/.xinitrc"

case "$1" in
	start)
	for x in $(cat /proc/cmdline); do
		case $x in 
		install-automatic|install-nodesktop)
			cat >$XINITRC <<"OOO"
[ -f /etc/environment ] && . /etc/environment
[ -f /etc/default/locale ] && . /etc/default/locale
export LANGUAGE LANG PATH
/usr/libexec/gnome-settings-daemon &
mutter &
OOO
		[ "$x" = "install-automatic" ] && echo 'osinstaller --wubi-dir=/isodevice/startos-loop' >>$XINITRC
		[ "$x" = "install-nodesktop" ] && echo 'osinstaller' >>$XINITRC
		STARTX="y" 
		break		
	esac
	done
	
	if [ "x$STARTX" = "xy" ]; then
		[ -f /etc/environment ] && . /etc/environment
		export PATH
		/usr/bin/systemctl disable gdm.service || true
		export HOME=/root
		/usr/bin/startx 
	fi
		;;
	*)
		echo "Usage: $0 start"
		exit 1
esac

# End of file
