#
# Ylmf OS package build script
#

DESCRIPTION="ICE authority file utility"
HOMEPAGE="http://xorg.freedesktop.org/"
 
SRC_URI="http://www.x.org/releases/X11R7.5/src/app/$N-$V$R.tar.bz2"

RDEPEND="libICE glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	install -m755 -d "$destdir"/usr/share/doc/"$N-$V$R"
	cp -a AUTHORS ChangeLog COPYING INSTALL NEWS README   "$destdir"/usr/share/doc/"$N-$V$R"
}
