#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Command line utilities to work with desktop menu entries"
HOMEPAGE="http://www.freedesktop.org/wiki/Software/desktop-file-utils"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://www.freedesktop.org/software/"$N"/releases/"$N-$V".tar.xz"
CHECKSUM="cbb2427593b7f6d36e52e9d221fce82f"

RDEPEND="glib2 glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	cd "$destdir"
	docp "$filesdir"/defaults.list usr/share/applications/
}


