#
# YLmf_OS package build script
#

DESCRIPTION="Command line utilities to work with desktop menu entries"
HOMEPAGE="http://freedesktop.org/wiki/Software/desktop-file-utils"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
SRC_URI="http://freedesktop.org/software/desktop-file-utils/releases/$N-$V.tar.gz"

RDEPEND=""
BDEPEND=" glib2 gdk-pixbuf"
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/desktop-file-utils"

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	config+=" --prefix=/usr "
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
