#
# YLmf_OS package build script
#

DESCRIPTION="Command line utilities to work with desktop menu entries"
HOMEPAGE="http://www.freedesktop.org/wiki/Software/desktop-file-utils"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://www.freedesktop.org/software/"$N"/releases/"$N-$V$R".tar.bz2"

RDEPEND="glib2 glibc"
BDEPEND="glib2-dev glibc-dev"
RECOMMENDED=""

NOTES="http://wiki.linuxfromscratch.org/blfs/wiki/desktop-file-utils"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_patch no_xdirectory_warning.patch
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_docp "$FILES_PATH"/files/defaults.list "$YPPATH_DEST"/usr/share/applications
}
