#
# YLmf_OS package build script
#

DESCRIPTION="Extensible Python-based build utility"
HOMEPAGE="http://www.scons.org/"
REPO=""
LICENSE="GPL"
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://downloads.sourceforge.net/project/"$N"/"$N"/"$V$R"/"$N-$V$R".tar.gz"

RDEPEND="python"
BDEPEND="${RDEPEND} "
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
