
info_files=gnuplot.info

post_install() {
    cat << EOF
* To add the gnuplot mode in Emacs, add the content of /usr/share/emacs/site-lisp/dotemacs to your ~/.emacs file.
EOF
    if [ -f /usr/bin/mktexlsr ]; then
        echo "Updating TeX tree ..."
        mktexlsr
    fi
    doinstall_info $info_files ||true
}

pre_remove() {
    doremove_info $info_files ||true
}

post_remove() {
    if [ -f /usr/bin/mktexlsr ]; then
        echo "Updating TeX tree ..."
        mktexlsr
    fi
}

post_upgrade() {
    post_install $1 $3
}

post_downgrade() {
    post_upgrade
}
