#
# Ylmf OS package build script
#

DESCRIPTION="Use Perl::Critic in test programs"
HOMEPAGE="http://search.cpan.org/~thaljef/Test-Perl-Critic-1.02/"
LICENSE="GPL PerlArtistic"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
YARCH="any"

SRC_URI="http://mirrors.sohu.com/CPAN/authors/id/T/TH/THALJEF/Test-Perl-Critic-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

