#
# YLmf_OS package build script
#

DESCRIPTION="eazy browser"
HOMEPAGE="http://code.google.com/p/okgo/"
REPO="testing"
LICENSE="GPL"
PRIORITY=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://okgo.googlecode.com/files/eazy_20110331-0.4.6_i386.deb"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_install() {
	ypkg_docp data/*  "$YPPATH_DEST"
}

pbs_postinst() {
	gnome2_desktop_database_update
}
