#
# YLmf_OS package build script
#

DESCRIPTION="GNOME 2 default icon themes"
HOMEPAGE="http://www.gnome.org/"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.30/2.30.2/sources/"$N-$V$R".tar.bz2 "

RDEPEND="hicolor-icon-theme"
BDEPEND="icon-naming-utils desktop-file-utils xml-parser"

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--enable-icon-mapping"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
