#
# Ylmf OS package build script
#

DESCRIPTION="GNOME 2 default icon themes"
HOMEPAGE="http://www.gnome.org/"
 
SRC_URI="http://ftp.gnome.org/pub/gnome/desktop/2.30/2.30.2/sources/"$N-$V$R".tar.bz2 "

RDEPEND="hicolor-icon-theme"
BDEPEND="icon-naming-utils desktop-file-utils xml-parser"

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--enable-icon-mapping"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
