#
# Ylmf OS package build script
#

DESCRIPTION="X.org video driver for SiS 670 / 671 cards"
HOMEPAGE="http://gitorious.org/chakra-packages/platform/trees/master/xf86-video-sismedia"
REPO=""
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://chakra-project.org/sources/xf86-video-sismedia/xf86-video-sis-"$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	patches=" xf86-video-sis-0.9.1-20102701.patch
	    	  0002-Remove-XFree86-Misc-PassMessage-support.patch
	   	  0003-Fix-build-with-Werror-format-security.patch
	  	  xf86-video-sis-0.9.1-dump-regs-after-video-init.patch
		  0005-Fix-backlight-off-on-SiS30x.-video-bridges.patch
		  0006-Add-IgnoreHotkeyFlag-driver-option.patch
		  0007-Remove-useless-loader-symbol-lists.patch
		  0008-update-to-xextproto-7-1-support.patch
		  0009-update-for-rac-removal.patch
		  0010-change-to-use-abi-version-check.patch
		  0011-more-rac-removal.patch"
	dopatch $patches
	pwd
	exit
	config+="--enable-dri"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc $filesdir/LICENSE
}
