#
# Ylmf OS package build script
#

DESCRIPTION="Standard GNU compressor"
HOMEPAGE="http://www.gnu.org/software/gzip/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="ftp://ftp.gnu.org/gnu/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

