#
# YLmf_OS package build script
#

DESCRIPTION="The GDK Pixel Buffer package is the GTK+ pixel buffer library."
HOMEPAGE="http://www.gnome.org"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"
REPO="testing"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/"$N"/2.21/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
