#!/bin/sh
########################################################################
# Begin $rc_base/init.d/
#
# Description : eth0 configuration
#
# Authors : Sword	
#
# Version : 00.00
#
# Notes :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}

prog_dhcp=/sbin/dhcpcd
pidfile=/var/run/dhcpcd-eth0.pid

case "${1}" in
start)
	boot_mesg "* Bring up eth0 via DHCP.." 
	#link up.
	ip link set eth0 up > /dev/null 
	if [ ${?} != 0 ]; then
		echo_failure
		boot_mesg -n "ip link failed." ${FAILURE}
		exit 1
	fi

	boot_mesg "get address via dhcp.."
	loadproc $prog_dhcp eth0
	evaluate_retval

	#set route.
	#ip route add default dev eth0 via $ROUTADDR > /dev/null 
	#evaluate_retval
	;;
stop)
	boot_mesg "* Bring down eth0..."
	ip link set eth0 down > /dev/null 
	killall -9 dhcpcd
	#[ $? -eq 0 ] && rm -f "$pidfile"
	rm -f "$pidfile"
	;;
restart)
	${0} stop
	sleep 1
	${0} start
	;;
status)
	statusproc
	;;
*)
	echo "Usage: ${0} {start|stop|restart|status}"
	exit 1
	;;
esac

# End $rc_base/init.d/

