#!/bin/sh
# Begin $rc_base/init.d/gdm
#

. /etc/sysconfig/rc
. $rc_functions

pidfile=/var/run/gdm.pid

case "$1" in
	start)
		boot_mesg "* Starting GDM..."
		# Check kernel command-line for inhibitors
	        for ARG in $(cat /proc/cmdline); do
			case "${ARG}" in
				text|single)
					plymouth quit || :  # We have the ball here
					exit 0 ;;
			esac
		done
		plymouth quit || :
		[ -r /etc/environment ] && . /etc/environment
		[ -r /etc/default/locale ] && . /etc/default/locale
		export PATH LANG LANGUAGE
		loadproc gdm &
		;;

	stop)
		boot_mesg "* Stopping GDM..."
		if [ -f $pidfile ]; then
			loadproc gdm-stop
		fi
		;;

	reload)
		boot_mesg "* Reloading GDM..."
		loadproc gdm-safe-restart
		;;

	restart)
		boot_mesg "* Restarting GDM..."
		loadproc gdm-restart
		;;

	*)
		echo "Usage: $0 {start|stop|reload|restart}"
		exit 1
		;;
esac

# End $rc_base/init.d/gdm

