#!/bin/sh
########################################################################
# Begin $rc_base/init.d/mountkernfs
#
# Description : Mount proc,sysfs,/dev/shm
#
# Authors : Gerard Beekmans - gerard@linuxfromscratch.org
#
# Version : 00.00
#
# Notes :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
start)
	boot_mesg -n "Mounting kernel-based file systems:" ${INFO}
	if ! mountpoint -q /proc; then
		boot_mesg -n " /proc" ${NORMAL}
		mount -n /proc || failed=1
	fi

	if ! mountpoint -q /sys; then
		boot_mesg -n " /sys" ${NORMAL}
		mount -n /sys || failed=1
	fi
	
	if ! mountpoint -q /dev/shm; then
		mkdir -p /dev/shm
		boot_mesg -n " /dev/shm" ${NORMAL}
		mount -t tmpfs none /dev/shm -o rw,nosuid,nodev || failed=1
	fi

	boot_mesg "" ${NORMAL}
	(exit ${failed})
	evaluate_retval
	;;
*)
	echo "Usage: ${0} {start}"
	exit 1
	;;
esac

# End $rc_base/init.d/mountkernfs

