#!/bin/sh
# Begin $rc_base/init.d/plymouth

. /etc/sysconfig/rc
. $rc_functions

#
[ -r /etc/environment ] && . /etc/environment
[ -r /etc/default/locale ] && . /etc/default/locale
case $LANG in
	zh_CN.UTF-8|zh)
		TEXT_START="正 在 启 动 Ylmf OS"
		TEXT_STOP="正 在 关 机"
				;;
		*)
		TEXT_START="Ylmf OS starting"
		TEXT_STOP="Ylmf OS halting"
esac

case "$1" in
        start)	
		/bin/plymouth message --text=" $TEXT_START "
                ;;

        stop)
		# Check kernel command-line for inhibitors
		for ARG in $(cat /proc/cmdline); do
			case "${ARG}" in
				text|single)
					plymouth quit || :
					exit 0 ;;
			esac
		done
                boot_mesg "* Starting plymouth show splash..."
		plymouth --ping || plymouthd   #--mode=shutdown
		plymouth show-splash
		plymouth message --text=" $TEXT_STOP "
                ;;
        *)
                echo "Usage: $0 {start|stop}"
                exit 1
                ;;
esac

# End $rc_base/init.d/plymouth
