#!/bin/sh
########################################################################
# Begin $rc_base/init.d/
#
# Description :
#
# Authors :
#
# Version : 00.00
#
# Notes :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}

prog_daemon=/usr/bin/slim

case "${1}" in
start)
	loadproc  $prog_daemon -d
	;;
stop)
	boot_mesg "Stopping ${prog_daemon} ..."
	killproc $prog_daemon
	;;
reload)
	;;
restart)
	;;
status)
	statusproc $prog_daemon
	;;
*)
        echo "Usage: $0 {start|stop|restart|status}"
	exit 1
	;;
esac

# End $rc_base/init.d/
