#!/bin/sh
#Begin $rc_base/init.d/ylmfcenter
#
# ylmfos application center backend
#

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		boot_mesg "* Starting the Ylmfcenter Daemon..."
		loadproc /usr/share/ylmfcenter/PkgDbusDaemon
	       ;;
       status) 
       		statusproc /usr/share/ylmfcenter/PkgDbusDaemon
	       ;;
            *)
	        echo "Usage: $0 {start|status}"
		exit 1
esac

# End $rc_base/init.d/ylmfcenter

