#
# YLmf_OS package build script
#

DESCRIPTION="Shared library to access the contents of an iPod"
HOMEPAGE="http://www.gtkpod.org/libgpod/"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="git://gtkpod.git.sourceforge.net/gitroot/gtkpod/libgpod"

RDEPEND=""
BDEPEND="libplist"
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	make -j1
}

pbs_install() {
	ypkg_mkinstall
	[ -d "$YPPATH_DEST"/tmp ] && rm -rf "$YPPATH_DEST"/tmp
}
