#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="dbus polkit for Ylmf OS"
HOMEPAGE="http://www.ylmf.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="dbus dbus-glib eggdbus glib2 glibc polkit zlib"
BDEPEND=""

pbs_unpack() {
	dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

