#
# Ylmf OS package build script
#

DESCRIPTION="video4linux driver"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://xorg.freedesktop.org/archive/individual/driver/"$N-$V".tar.bz2"
CHECKSUM="2251ae2a0a905764941cd7b098e85ad1"

RDEPEND="glibc xorg-server(>=1.10.4)"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

