. /usr/lib/ybs/funcs

files="/etc/mateconf/schemas/atril-thumbnailer.schemas /etc/mateconf/schemas/atril-thumbnailer-ps.schemas /etc/mateconf/schemas/atril-thumbnailer-djvu.schemas /etc/mateconf/schemas/atril-thumbnailer-comics.schemas"

post_install() {
    mate_install_schema $files
    gnome2_icon_cache_update 
    glib_compile_schemas
}

pre_remove() {
    mate_uninstall_schema $files
}

post_upgrade() {
    post_install
}

post_downgrade() {
    post_install
}

