#
# YLmf_OS package build script
#

DESCRIPTION="choose a variant to serve"
HOMEPAGE="http://search.cpan.org/"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://mirrors.ustc.edu.cn/CPAN/authors/id/G/GA/GAAS/HTTP-Negotiate-"$V".tar.gz"

RDEPEND="perl http-message-perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

