#
# YLmf_OS package build script
#

DESCRIPTION="Simplifies the usage of decorators for the average programmer"
HOMEPAGE="http://pypi.python.org/pypi/decorator"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://pypi.python.org/packages/source/d/"$N"/"$N-$V$R".tar.gz"

RDEPEND="python"
BDEPEND="${RDEPEND} "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc documentation.html  documentation.pdf README.txt
}
