. /usr/lib/ybs/funcs

schemas=" 
	/etc/gconf/schemas/awnsystemmonitor.schemas
	/etc/gconf/schemas/awn-applet-weather.schemas
	/etc/gconf/schemas/awn-applet-volume-control.schemas
	/etc/gconf/schemas/awn-applet-to-do.schemas
 	/etc/gconf/schemas/awn-applet-sysmon.schemas
    	/etc/gconf/schemas/awn-applet-stacks.schemas
    	/etc/gconf/schemas/awn-applet-slickswitcher.schemas
    	/etc/gconf/schemas/awn-applet-shinyswitcher.schemas
	/etc/gconf/schemas/awn-applet-quit.schemas
	/etc/gconf/schemas/awn-applet-places.schemas
	/etc/gconf/schemas/awn-applet-pandora.schemas
	/etc/gconf/schemas/awn-applet-notification-daemon.schemas
	/etc/gconf/schemas/awn-applet-notification-area.schemas
	/etc/gconf/schemas/awn-applet-mount.schemas
	/etc/gconf/schemas/awn-applet-media-player.schemas
	/etc/gconf/schemas/awn-applet-media-control.schemas
	/etc/gconf/schemas/awn-applet-mail.schemas
	/etc/gconf/schemas/awn-applet-hardware-sensors.schemas
	/etc/gconf/schemas/awn-applet-garbage.schemas
	/etc/gconf/schemas/awn-applet-file-browser-launcher.schemas
	/etc/gconf/schemas/awn-applet-feeds.schemas
	/etc/gconf/schemas/awn-applet-digital-clock.schemas
	/etc/gconf/schemas/awn-applet-dialect.schemas
	/etc/gconf/schemas/awn-applet-cpufreq.schemas
	/etc/gconf/schemas/awn-applet-comics.schemas
	/etc/gconf/schemas/awn-applet-calendar.schemas
	/etc/gconf/schemas/awn-applet-cairo-menu.schemas
	/etc/gconf/schemas/awn-applet-cairo-clock.schemas
 	/etc/gconf/schemas/awn-applet-battery.schemas
	/etc/gconf/schemas/awn-applet-bandwidth-monitor.schemas
	/etc/gconf/schemas/awn-applet-awnterm.schemas"

post_install() {
	gnome2_install_schema "$schemas"
	gnome2_gconfd_reload
}

pre_remove() {
	gnome2_uninstall_schema 
	return 0
}

