#
# YLmf_OS package build script
#

DESCRIPTION="X.Org GL protocol headers"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"
REPO="testing"

SRC_URI="http://cgit.freedesktop.org/xorg/proto/glproto/snapshot/glproto-1.4.14.tar.bz2"

RDEPEND=""
BDEPEND=""
OPINION="nodev"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {	
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
