#
# YLmf_OS package build script
#

DESCRIPTION="utility for modifying keymaps and pointer_button mappings in X"
HOMEPAGE="http://www.x.org/wiki"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.x.org/releases/X11R7.6/src/app/"$N-$V".tar.bz2"

RDEPEND="glibc libX11 libXau libxcb libXdmcp"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

