#
# YLmf_OS package build script
#

DESCRIPTION="Audio compression format designed for speech."
HOMEPAGE=" http://www.speex.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://downloads.xiph.org/releases/"$N"/"$N-$V"rc1.tar.gz"

RDEPEND="glibc libogg"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

