#
# YLmf_OS package build script
#

DESCRIPTION="Ylmf OS configuration defaults for firefox extensions/plugins."
HOMEPAGE="www.ylmf.net"
REPO="stable"
LICENSE=""
PACKAGER="<ylmfos@115.com>"
PRIORITY=""

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND=""
BDEPEND="zip"

pbs_unpack() {
	ypkg_unpack
}

pbs_build() {
	zip -r usr/share/xul-ext/ubufox/chrome/ubufox.jar content locale skin
}

pbs_install() {
	ypkg_docp etc usr "$YPPATH_DEST"/
}
