#
# YLmf_OS package build script
#

DESCRIPTION="KDE Terminal"
HOMEPAGE="http://www.kde.org"
LICENSE="GPL,LGPL,FDL"
PACKAGER="StartOS Developers<>"
GROUP="kde"

SRC_URI="http://download.kde.org/stable/"$V"/src/"$N-$V".tar.xz"

RDEPEND="kde-baseapps"
BDEPEND="cmake"

INSTALL="$N.install"

pbs_unpack() {
       dounpack
}

pbs_config() {
	doconfig -DCMAKE_BUILD_TYPE=Release
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

