#
# YLmf_OS package build script
#

DESCRIPTION="A collection of classes to simplify loading, compiling and using GLSL vertex shaders, geometry shaders and fragment shaders."
HOMEPAGE="http://www.clockworkcoders.com/oglsl/	"
REPO="testing"
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.clockworkcoders.com/oglsl/"$N-$V$R".zip"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

#build
pbs_build() {
	#make "$MAKEOPTS"
	ypkg_make
}

#check
pbs_check() {
	:
	#make check
}

#install
pbs_install() {
	#install everything to $YPPATH_DEST
	#make DESTDIR="$YPPATH_DEST" install
	ypkg_mkinstall
	#ypkg_doinit "$FILES_PATH/files/slim"
	#ypkg_dodesktop "*.desktop" "*.png"
	#ypkg_dodoc AUTHORS ChangeLog COPYING INSTALL NEWS README 
	#ypkg_docp "$FILES_PATH/files/XXXX" "dirname"
	#ypkg_domv "$FILES_PATH/files/XXXX" "dirname"
	#ypkg_docp_rename "$1" "$2"
	#ypkg_domv_rename "$1" "$2"
	#ypkg_doln "$1 "$2"
	#*****************
	#when SRC_URI is deb or rpm package
	#ypkg_docp data/*  "$YPPATH_DEST"
}
