#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A minimal libc subset for use with initramfs."
HOMEPAGE="http://www.zytor.com/mailman/listinfo/klibc"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://www.kernel.org/pub/linux/libs/"$N"/1.5/"$N-$V".tar.xz"

RDEPEND=""
BDEPEND="linux-kernel-headers"
RECOMMENDED=""

pbs_unpack() {
	dounpack
}

pbs_build() {
	doln /usr/src/linux linux
	domake
}

pbs_install() {
	sed -i '/SHLIBDIR = \/lib/aINSTALLROOT = '"$destdir"'' scripts/Kbuild.install
	domkinstall
	cd "$destdir"
	docp "$filesdir"/klibc.m4 /usr/share/aclocal
	domv  usr/man usr/share/
}

