#
# Ylmf OS package build script
#

DESCRIPTION="A minimal libc subset for use with initramfs."
HOMEPAGE="http://www.zytor.com/mailman/listinfo/klibc"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.kernel.org/pub/linux/libs/"$N"/1.5/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""

NOTES=""

pbs_unpack() {
	dounpack
}

pbs_build() {
	ln -sf /usr/src/linux linux
	domake
}

pbs_install() {
	sed -i '/SHLIBDIR = \/lib/aINSTALLROOT = '"$destdir"'' scripts/Kbuild.install
	domkinstall
	docp $filesdir/klibc.m4 /usr/share/aclocal
}
