#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A minimal libc subset for use with initramfs."
HOMEPAGE="http://www.zytor.com/mailman/listinfo/klibc"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://www.kernel.org/pub/linux/libs/"$N"/2.0/"$N-$V".tar.xz"

RDEPEND=""
BDEPEND="linux-kernel-headers"
RECOMMENDED=""

pbs_unpack() {
	dounpack
}

pbs_config() {
	doln /usr/src/linux linux
}

pbs_build() {
	domake
}

pbs_install() {
	domake INSTALLROOT="$destdir" install
	cd "$destdir"
	find -type f -name "..install.cmd" -exec rm -f {} \;
	find -type f -name ".install.cmd" -exec rm -f {} \;
	find -type f -name ".install" -exec rm -f {} \;
	docp "$filesdir"/klibc.m4 usr/share/aclocal
	domv  usr/man usr/share/
}

