#
# YLmf_OS package build script
#

DESCRIPTION="A minimal libc subset for use with initramfs."
HOMEPAGE="http://www.zytor.com/mailman/listinfo/klibc"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://www.kernel.org/pub/linux/libs/"$N"/1.5/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""

NOTES=""

pbs_unpack() {
	ypkg_unpack
}

pbs_build() {
	ln -sf /usr/src/linux linux
	ypkg_make
}

pbs_install() {
	sed -i '/SHLIBDIR = \/lib/aINSTALLROOT = '"$YPPATH_DEST"'' scripts/Kbuild.install
	ypkg_mkinstall
	ypkg_docp "$FILES_PATH"/files/klibc.m4 /usr/share/aclocal
}
