#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A minimal libc subset for use with initramfs."
HOMEPAGE="http://www.zytor.com/mailman/listinfo/klibc"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>
          chenqixing@ivali.com"

SRC_URI="http://www.kernel.org/pub/linux/libs/"$N"/2.0/"$N-$V".tar.xz"
CHECKSUM="59af2c01dc1b0fc1edaed0a9c470adf4"

RDEPEND="perl"
BDEPEND="linux-kernel-headers"
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
    dounpack
}

pbs_config() {
    doln /usr/src/linux linux
}

pbs_build() {
    domake
}

pbs_install() {
    make prefix="$destdir"/usr \
         mandir="$destdir"/usr/share/man \
         INSTALLDIR="$destdir"/usr/lib"$LIBDIRSUFFIX"/klibc \
         install
    cd "$destdir"
    find -type f -name "..install.cmd" -exec rm -f {} \;
    find -type f -name ".install.cmd" -exec rm -f {} \;
    find -type f -name ".install" -exec rm -f {} \;
    docp "$filesdir"/klibc.m4 usr/share/aclocal
    # For initramfs-tools
    docp "$filesdir"/klibc usr/share/initramfs-tools/hooks/
}

