#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl bindings to the GtkImageView image viewer widget "
HOMEPAGE="http://search.cpan.org/~ratcliffe/Gtk2-ImageView-0.05/ImageView.pm"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://search.cpan.org/CPAN/authors/id/R/RA/RATCLIFFE/Gtk2-ImageView-"$V".tar.gz"

RDEPEND="cairo-perl glib-perl gtkimageview gtk2-perl"
BDEPEND="extutils-depends extutils-pkgconfig"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

