#
# YLmf_OS package build script
#

DESCRIPTION="a portable, high level programming interface to various calling conventions."
HOMEPAGE="http://sourceware.org/libffi/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
 
SRC_URI=" http://sources-redhat.mirrors.airband.net/"$N"/"$N-$V".tar.gz "

RDEPEND="glibc"
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build(){
	domake
}

pbs_install() {
	domkinstall
}

