#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="a portable, high level programming interface to various calling conventions."
HOMEPAGE="http://sourceware.org/libffi/"
LICENSE="MIT"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
 
SRC_URI="ftp://sourceware.org/pub//"$N"/"$N-$V".tar.gz"
CHECKSUM="463dcb4ae9aea4c52bba12b67fbe4d91ed1e21fd"

RDEPEND="glibc"
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+="--disable-static"
    doconfig
}

pbs_build(){
    domake
}

pbs_install() {
    domkinstall
    dodoc LICENSE
}
