#
# YLmf_OS package build script
#

DESCRIPTION="Perl bindings to the 2.x series of the GNOME libraries"
HOMEPAGE="http://search.cpan.org/~tsch/Gnome2-1.042/Gnome2.pm"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/Gnome2-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" extutils-depends extutils-pkgconfig glib-perl gtk2-perl pango-perl cairo-perl gnome2-canvas-perl gnome2-vfs-perl"
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
