#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Support library for syslog-ng"
HOMEPAGE="http://www.balabit.com/products/syslog_ng/"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://www.balabit.com/downloads/files?path=/syslog-ng/sources/3.2.2/source/"${N}_$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
