#
# YLmf_OS package build script
#

DESCRIPTION="X.Org Bitstream bitmap fonts"
HOMEPAGE="http://www.x.org/wiki/"

SRC_URI="http://www.x.org/releases/X11R7.6/src/font/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND=" font-util mkfontdir mkfontscale"

pbs_unpack() {	
        ypkg_unpack
}

pbs_config() {
	
	YPB_CONFIG+="  
	              
		       
	              
		       
		      --with-fontrootdir=/usr/share/fonts "
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
