#
# YLmf_OS package build script
#

DESCRIPTION="Perl interface to the cairo library "
HOMEPAGE="http://search.cpan.org/~tsch/Cairo-1.061/lib/Cairo.pm"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"
YVERSION="2"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/Cairo-"$V".tar.gz"

RDEPEND="perl cairo"
BDEPEND="extutils-depends extutils-pkgconfig"
RECOMMENDED=""
CONFLICT="cairo_perl"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config INSTALLDIRS=vendor
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

