#
# YLmf_OS package build script
#

DESCRIPTION="Perl interface to the cairo library "
HOMEPAGE="http://search.cpan.org/~tsch/Cairo-1.061/lib/Cairo.pm"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://search.cpan.org/CPAN/authors/id/T/TS/TSCH/Cairo-"$V$R".tar.gz"

RDEPEND=""
BDEPEND="${RDEPEND} "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
