#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="grub2 background images"
HOMEPAGE="www.ylmf.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
YARCH="any"

SRC_URI="git://git.ylmf.com/"$N".git"

RDEPEND="grub2"
BDEPEND=""
RECOMMENDED=""

INSTALL="$N.install"

pbs_unpack() {
	dounpack
}

pbs_install() {
	docp usr "$destdir"/
}

