#
# YLmf_OS package build script
#

DESCRIPTION="GNOME Clock applet with added Chinese lunar calendar support"
HOMEPAGE=""
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="git://git.debian.org/git/chinese/lunar-applet.git"

RDEPEND="gnome-panel"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
