#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="GObject collection library"
HOMEPAGE="http://live.gnome.org/Libgee"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://download.gnome.org/sources/"$N"/0.6/"$N-$V".tar.bz2"

RDEPEND="glib2 glibc"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

