#
# YLmf_OS package build script
#

DESCRIPTION="GObject collection library"
HOMEPAGE="http://live.gnome.org/Libgee"
REPO=""
LICENSE=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://download.gnome.org/sources/"$N"/0.6/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND="${RDEPEND} "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
