#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Glade-like GUI designer which can generate Python, Perl, C++ or XRC code"
HOMEPAGE="http://wxglade.sourceforge.net/"
LICENSE="MIT"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://sourceforge.net/projects/wxglade/files/"$N"/"$V"/wxGlade-"$V".tar.gz"
CHECKSUM="983715e105e53a0d82efbe1fa8cf4361"

RDEPEND="wxpython(>=2.8.0)"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_patch() {
    dopatch wxglade-0.6.3-wxversion.patch \
            modules-path.patch
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodesktop "$N".desktop icons/icon.xpm
}

