#
# YLmf_OS package build script
#

DESCRIPTION="X.Org libdrm library"
HOMEPAGE="http://dri.freedesktop.org/"
 
SRC_URI="http://dri.freedesktop.org/libdrm/$N-$V.tar.bz2"

RDEPEND=""
BDEPEND=" libpthread-stubs"

pbs_unpack()
{
        ypkg_unpack
}

pbs_config()
{
	
	YPB_CONFIG+=" --enable-radeon-experimental-api "
	ypkg_config
}

pbs_build()
{
	ypkg_make
}

pbs_check()
{
	make check
}

pbs_install()
{
	ypkg_mkinstall
}
