#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A perfect hash function generator"
HOMEPAGE="http://www.gnu.org/software/gperf/gperf.html"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gnu.org/gnu/"$N"/"$N-$V".tar.gz"

RDEPEND="gcc-lib glibc"
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

