#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A perfect hash function generator"
HOMEPAGE="http://www.gnu.org/software/gperf/gperf.html"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://ftp.gnu.org/gnu/"$N"/"$N-$V".tar.gz"
CHECKSUM="e32d4aff8f0c730c9a56554377b2c6d82d0951b8"

RDEPEND="gcc-libs glibc"
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
