#
# Ylmf OS package build script
#

DESCRIPTION="Assistive Technology Service Provider Interface - Python bindings."
HOMEPAGE="www.gtk.org"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.acc.umu.se/pub/gnome/bindings/2.32/2.32.1/sources/python/"$N-$V".tar.bz2"

RDEPEND="python"
RECOMMENDED=""
BDEPEND=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}


