#
# YLmf_OS package build script
#

DESCRIPTION="MPEG2 transport stream muxing library"
HOMEPAGE="http://core.fluendo.com/gstreamer/src/gst-fluendo-mpegmux/"
REPO=""
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://core.fluendo.com/gstreamer/src/gst-fluendo-mpegmux/"$N-$V$R".tar.bz2"

RDEPEND=""
BDEPEND="${RDEPEND} "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
