#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="C++ port of the high-performance text search engine Lucene"
HOMEPAGE="http://clucene.sourceforge.net"
LICENSE="LGPL,APACHE"
PACKAGER="StartOS Developers"

SRC_URI="http://downloads.sourceforge.net/"$N"/"$N"-core-"$V".tar.gz"
CHECKSUM="ddfdc433dd8ad31b5c5819cc4404a8d2127472a3b720d3e744e8c51d79732eab"

RDEPEND="gcc-lib zlib"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""
REPLACE=""

pbs_unpack() {
        dounpack
}

pbs_patch() {
	# Add missing contrib-libs needed by LibO 3.6, patch by FC
	dopatch clucene-core-2.3.3.4-install_contribs_lib.patch
	
	# Pkgconfig file is missing clucene-shared (upstream ID: 3461512), patch by FC
	dopatch clucene-core-2.3.3.4-pkgconfig.patch
	
	# One upstream postrelease commit for proper zlib detection
	dopatch fix_zlib_detections.diff
	
	# LibreOffice patches http://cgit.freedesktop.org/libreoffice/core/tree/clucene/patches
	dopatch clucene-warnings.patch clucene-gcc-atomics.patch \
		clucene-debug.patch clucene-narrowing-conversions.patch \
		clucene-multimap-put.patch
}

pbs_config() {
	mkdir build
	pushd build
	cmake .. \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DENABLE_ASCII_MODE=OFF \
		-DENABLE_PACKAGING=OFF \
		-DBUILD_CONTRIBS_LIB:BOOL=ON \
		-DLIB_DESTINATION:PATH=/usr/lib \
		-DLUCENE_SYS_INCLUDES:PATH=/usr/lib \
		-DDISABLE_MULTITHREADING=OFF
	popd
}

pbs_build() {
	domake -C build
}

pbs_install() {
	domkinstall -C build
	rm -rf "$destdir"/usr/lib/CLuceneConfig.cmake
}

