#
# YLmf_OS package build script
#

DESCRIPTION="Used to generate Makefile.in from Makefile.am"
HOMEPAGE="http://www.gnu.org/software/automake/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://ftp.gnu.org/gnu/automake/"$N-$V$R".tar.bz2"

RDEPEND="autoconf"
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
