#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="dbus polkit for StartOS"
HOMEPAGE="http://www.startos.org"
LICENSE="GPL"
PACKAGER="StartOS Developers"

SRC_URI="git://git.ylmf.com/ylmfos-dbus-polkit.git"

RDEPEND="dbus-glib polkit ypkg2"
BDEPEND=""
REPLACE="ylmfos-dbus-polkit"

pbs_unpack() {
	dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

