#
# YLmf_OS package build script
#

DESCRIPTION="bundle of mingw32, including binutils(2.19.1) headers gcc(3.4.5-20060117-2) w32api( mingwrt(3.15.2)"
HOMEPAGE="http://mingw.sf.net http://sourceforge.net/projects/mingw/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://nchc.dl.sourceforge.net/project/mingw/Cross-Hosted%20MinGW%20Build%20Tool/x86-mingw32-build-1.0/x86-mingw32-build-1.0-sh.tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=" GCC_VERSION                   3.4.5-20060117-2
	BINUTILS_VERSION              2.19.1
	RUNTIME_VERSION               3.15.2
	W32API_VERSION                3.13 
  This script will build and install a locally hosted cross-compiler for the
  i386-mingw32 target.  This comprises the following components:--

  binutils    assembler, linker and library management tools; these
              must be built for the i386-mingw32 target, and should be
              installed prior to building GCC itself.
  headers     the header files for the mingw-runtime and the w32api
              libraries; these too, are best installed before GCC
              is built.
  gcc         the GCC compiler itself, complete with all supported
              source language packages.
  w32api      the runtime libraries supporting the Win32 API.
  mingwrt (a.k.a. mingw-runtime)
              additional libraries specific to the i386-mingw32 target. "

pbs_unpack() {
        ypkg_unpack
}

pbs_build() {
	ypkg_patch ylmfos-dir-hack.patch
	unset CFLAGS 
	unset CXXFLAGS 
	unset CC
	unset CXX
	bash x86-mingw32-build.sh
}

pbs_install() {
	#make DESTDIR="$YPPATH_DEST" install
	ypkg_domv "$HOME"/mingw32/*  "$YPPATH_DEST"/usr/
}

pbs_post() {
	ypkg_domv "$HOME"/packages/mingw-3.4.5/*  /var/ybs/sources/
}
