#!/bin/bash
#
#make 
#modinfo

echo "package hw-3g-ndis_driver"

echo "
module hw_cdc_driver.ko
description    Huawei ether driver for 3G data card ether device
alias          usb:v12D1p*d*dc*dsc*dp*ic02isc0Dip00*
alias          usb:v12D1p*d*dc*dsc*dp*ic02isc0DipFF*
alias          usb:v12D1p*d*dc*dsc*dp*icFFisc02ip46*
alias          usb:v12D1p*d*dc*dsc*dp*icFFisc02ip16*
alias          usb:v12D1p*d*dc*dsc*dp*icFFisc02ip37*
alias          usb:v12D1p*d*dc*dsc*dp*icFFisc02ip07*
alias          usb:v12D1p*d*dc*dsc*dp*icFFisc01ip39*
alias          usb:v12D1p*d*dc*dsc*dp*icFFisc01ip09*
alias          usb:v12D1p*d*dc*dsc*dp*ic02isc06ipFF*
alias          usb:v12D1p*d*dc*dsc*dp*ic02isc06ip00*
"
