#
# YLmf_OS package build script
#

DESCRIPTION="Python MSN IM protocol implementation forked from pymsn"
HOMEPAGE="http://telepathy.freedesktop.org/"
LICENSE="GPL"
YARCH="any"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.freedesktop.org/software/"$N"/releases/"$N-$V".tar.gz"

RDEPEND="python pyopenssl pycrypto"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc AUTHORS COPYING NEWS README
}

