#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python MSN IM protocol implementation forked from pymsn"
HOMEPAGE="http://telepathy.freedesktop.org/"
LICENSE="GPL"
YARCH="any"
PACKAGER="StartOS Developers"

SRC_URI="http://www.freedesktop.org/software/"$N"/releases/"$N-$V".tar.gz"

RDEPEND="python pyopenssl pycrypto"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

