#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python MSN IM protocol implementation forked from pymsn"
HOMEPAGE="http://telepathy.freedesktop.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://telepathy.freedesktop.org/releases/"$N"/"$N-$V$R".tar.gz"

RDEPEND="python pyopenssl pycrypto"
BDEPEND=""
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc AUTHORS COPYING NEWS README
}
