#
# YLmf_OS package build script
#

DESCRIPTION="Python MSN IM protocol implementation forked from pymsn"
HOMEPAGE="http://telepathy.freedesktop.org/"
LICENSE="GPL-2"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://telepathy.freedesktop.org/releases/"$N"/"$N-$V$R".tar.gz"

RDEPEND="python pyopenssl pycrypto"
BDEPEND=""
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc AUTHORS COPYING NEWS README
}
