#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An Open Source Implementation of the GDI+ API"
HOMEPAGE="http://www.mono-project.com"
LICENSE="MPL,LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://download.mono-project.com/sources/$N/$N-$V.tar.bz2"
CHECKSUM="451966e8f637e3a1f02d1d30f900255d"

RDEPEND="cairo giflib libexif libtiff"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_patch() {
    dopatch libpng15.patch
}

pbs_config() {
    config+="--with-cairo=system"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

