#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An Open Source Implementation of the GDI+ API"
HOMEPAGE="http://www.mono-project.com"
LICENSE="MPL,LGPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://ftp.novell.com/pub/mono/sources/"$N"/"$N-$V$R".tar.bz2"

RDEPEND="cairo expat fontconfig freetype giflib glib2 gdk-pixbuf glibc libexif libICE libjpeg-turbo libpng libSM libtiff libX11 libXau libxcb libXdmcp libXrender pixman util-linux-ng zlib"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--with-cairo=system"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

