#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An Open Source Implementation of the GDI+ API"
HOMEPAGE="http://www.mono-project.com"
LICENSE="MPL,LGPL"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.novell.com/pub/mono/sources/"$N"/"$N-$V".tar.bz2"

RDEPEND="cairo giflib libexif libtiff"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+="--with-cairo=system"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

