#
# YLmf_OS package build script
#

DESCRIPTION="Windows header files fro mingw32 C cross-compile"
HOMEPAGE="http://www.mingw.org/"
REPO="testing"
LICENSE="LGPL"
PACKAGER="<ylmfos@115.com>"
SRC_URI="http://downloads.sourceforge.net/mingw/w32api-$V$R-mingw32-src.tar.gz 
         http://downloads.sourceforge.net/mingw/mingwrt-3.15.2-mingw32-src.tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
	mkdir "$N-$V$R"
	
        ypkg_unpack
        ypkg_unpack
}

pbs_config() {
	target="i586-mingw32msvc"
	mkdir -p include
	cp -r mingwrt-3.15.2-mingw32/include/*  include/
	
	cd w32api-$V$R-mingw32
	export CFLAGS="-mms-bitfields -I"$N-$V$R"/include -I"$N-$V$R"/w32api-$V$R-mingw32/include"
	
	./configure --prefix=/usr/$target --target=$target --host=$target   # --build=$CHOST \
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	make install prefix="$YPPATH_DEST"/usr/$target
	find $YPPATH_DEST -name '*.a' | xargs -rtl1 $target-strip -g
}
