#
# YLmf_OS package build script
#

DESCRIPTION="provides high performance and highly flexible algorithms for routine tasks"
HOMEPAGE="http://www.atheme.org/Projects/Libmowgli"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://distfiles.atheme.org/"$N-$V$R".tgz"

RDEPEND=""
BDEPEND="${RDEPEND} "

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
