#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="provides high performance and highly flexible algorithms for routine tasks"
HOMEPAGE="http://www.atheme.org/Projects/Libmowgli"
LICENSE="GPL-2"
PACKAGER="StartOS Developers"

SRC_URI="http://distfiles.atheme.org/"$N-$V$R".tgz"

RDEPEND="glibc"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
