#
# Ylmf OS package build script
#

DESCRIPTION="Userspace utilities for storing and processing auditing records"
HOMEPAGE="http://people.redhat.com/sgrubb/audit/"
REPO=""
LICENSE="GPL"
PRIORITY=""
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://people.redhat.com/sgrubb/"$N"/"$N-$V$R".tar.gz"

RDEPEND=""
BDEPEND=" swig"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
