#
# YLmf_OS package build script
#

DESCRIPTION="a line-oriented text editor"
HOMEPAGE="http://www.gnu.org/software/ed/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://ftp.gnu.org/gnu/"$N"/"$N-$V".tar.gz"

RDEPEND="glibc"
BDEPEND=""

INSTALL="$N.install"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--bindir=/bin"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

