#
# YLmf_OS package build script
#

DESCRIPTION="The MAD id3tag library"
HOMEPAGE="http://www.underbit.com/products/mad/"
REPO=""
LICENSE=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://downloads.sourceforge.net/project/mad/"$N"/"$V$R"/"$N-$V$R".tar.gz "

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
