#
# YLmf_OS package build script
#

DESCRIPTION="Windows 32-bit binary codecs for video and audio playback support"
HOMEPAGE="http://www.mplayerhq.hu/"
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.mplayerhq.hu/MPlayer/releases/codecs/all-"$V$R".tar.bz2"

RDEPEND=""
BDEPEND=""

pbs_unpack() {
        ypkg_unpack
}

pbs_install() {
	ypkg_docp * "$YPPATH_DEST"/usr/lib/win32
}
