#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A library which provides a uniform interface to several symmetric encryption algorithms"
HOMEPAGE="http://mcrypt.sourceforge.net"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://downloads.sourceforge.net/mcrypt/"$N-$V".tar.bz2"
CHECKSUM="c4f491dd411a09e9de3b8702ea6f73eb"

RDEPEND="glibc"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

