#
# YLmf_OS package build script
#

DESCRIPTION="Utils to help with the transition to the new freedesktop.org naming scheme."
HOMEPAGE="http://tango.freedesktop.org"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI=" http://tango.freedesktop.org/releases/"$N-$V$R".tar.gz "

RDEPEND="xml-simple"
BDEPEND="${RDEPEND}"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+="--disable-gtk-doc"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
