#
# YLmf_OS package build script
#

DESCRIPTION="Tool for conversion of MSWord doc and rtf files to something readable"
HOMEPAGE="http://www.abisource.com/downloads/wv/"
 
SRC_URI="http://www.abisource.com/downloads/"$N"/"$V$R"/"$N-$V$R".tar.gz"

RDEPEND="libgsf bzip2 libxml2 libpng"
BDEPEND="${RDEPEND} gnome-extra/libgsf"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
