#
# YLmf_OS package build script
#

DESCRIPTION="Abstracts the storage of configuration settings away from applications."
HOMEPAGE="http://sacredspiral.co.uk/~nenolod/mcs/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://distfiles.atheme.org/"$N-$V$R".tgz"

RDEPEND="glibc libmcs libmowgli "
BDEPEND="${RDEPEND} libmowgli"

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc README
}
