#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Abstracts the storage of configuration settings away from applications."
HOMEPAGE="http://sacredspiral.co.uk/~nenolod/mcs/"
LICENSE="BSD"
PACKAGER="StartOS Developers"

SRC_URI="http://distfiles.atheme.org/"$N-$V".tgz"

RDEPEND="libmowgli"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    config+="--disable-gconf --disable-kconfig"
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    dodoc COPYING
}

