#
# YLmf_OS package build script
#

DESCRIPTION="tools for using the Ogg Vorbis sound file format"
HOMEPAGE="http://www.vorbis.com"
REPO=""
LICENSE=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://downloads.xiph.org/releases/vorbis/"$N-$V$R".tar.gz"

RDEPEND=""
BDEPEND="${RDEPEND} libvorbis"
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
