#
# Ylmf OS package build script
#

DESCRIPTION="The GLib library of C routines"
HOMEPAGE="http://www.gtk.org/"
REPO=""

SRC_URI="http://ftp.gnome.org/pub/gnome/sources/glib/2.26/glib-"$V$R".tar.bz2"

RDEPEND="gamin glibc zlib"
BDEPEND="pkgconfig   "

NOTES="Gamin requires GLib in order to compile; therefore, you must first install GLib, then compile Gamin, and recompile GLib against it.
--with-pcre=system: This parameter causes the build to use a system-provided version of the PCRE library instead of an internal version."

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	config+=" --prefix=/usr " #--with-pcre=system
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	install -d -m755 "$destdir"/etc/profile.d
	cat > "$destdir"/etc/profile.d/glib2-locale.sh << "EOF"
export G_FILENAME_ENCODING=@locale
EOF
}
