#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="The GLib library of C routines"
HOMEPAGE="http://www.gtk.org/"

SRC_URI=" http://ftp.gnome.org/pub/gnome/mobile/2.30/2.30.2/sources/glib-"$V$R".tar.bz2 "

RDEPEND="glibc zlib"
BDEPEND=" pkgconfig sys-libs/zlib"
RECOMMEDNED="libpcre"
OPIONAL="attr gamin gtk-doc python"

NOTES="Gamin requires GLib in order to compile; therefore, you must first install GLib, then compile Gamin, and recompile GLib against it.
--with-pcre=system: This parameter causes the build to use a system-provided version of the PCRE library instead of an internal version."

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	config+=" --prefix=/usr " #--with-pcre=system
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	cd "$destdir"
	install -d -m755 etc/profile.d
	cat > etc/profile.d/glib2-locale.sh << "EOF"
export G_FILENAME_ENCODING=@locale
EOF
}
