#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Extra Plasma applets and engines."
HOMEPAGE="http://www.ginac.de/CLN/"
LICENSE="GPL,LGPL"
PACKAGER="StartOS Developers"
GROUP="kde"

SRC_URI="http://download.kde.org/stable/"$V"/src/"$N-$V".tar.xz"

RDEPEND="kde-workspace libkexiv2 marble qjson qoauth qwt"
BDEPEND="cmake automoc4"
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig -DCMAKE_BUILD_TYPE=Release 
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

