#
# YLmf_OS package build script
#

DESCRIPTION="LibRaw is a library for reading RAW files obtained from digital photo cameras"
HOMEPAGE="http://www.libraw.org/"
LICENSE="CDDL LGPL custom"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.libraw.org/data/LibRaw-"$V".tar.gz"

RDEPEND="gcc glibc lcms"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

