#!/bin/sh
#
# A script so that
#    1) we read the standard system env vars
#    2) syadmins/integrators can add their own private options etc...

test -f /etc/profile && . /etc/profile

# Check kernel command-line for inhibitors
for ARG in $(cat /proc/cmdline); do
	case "${ARG}" in
		text|single|recovery)
			plymouth quit || :  
			exit 0 ;;
        esac
done

[ -r /etc/environment ] && . /etc/environment
[ -r /etc/default/locale ] && . /etc/default/locale

export PATH LANG LANGUAGE

exec /usr/sbin/lightdm "$@"

