#
# Ylmf OS package build script
#

DESCRIPTION="Mutagen is a Python module to handle audio metadata. "
HOMEPAGE="http://code.google.com/p/mutagen/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://mutagen.googlecode.com/files/mutagen-1.20.tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

