#
# YLmf_OS package build script
#

DESCRIPTION="Mutagen is a Python module to handle audio metadata. "
HOMEPAGE="http://code.google.com/p/mutagen/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://mutagen.googlecode.com/files/mutagen-1.20.tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}

