. /usr/lib/ybs/funcs

post_install() {
	SCHEMAS="
	/etc/gconf/schemas/compiz-tile.schemas
	/etc/gconf/schemas/compiz-snow.schemas
	/etc/gconf/schemas/compiz-mswitch.schemas
	/etc/gconf/schemas/compiz-fakeargb.schemas
	/etc/gconf/schemas/compiz-elements.schemas
	/etc/gconf/schemas/compiz-cubemodel.schemas
	/etc/gconf/schemas/compiz-atlantis.schemas"

	gnome2_install_schema "$SCHEMAS"
	gnome2_desktop_database_update
	gnome2_gconfd_reload
}
