#
# Ylmf OS package build script
#

DESCRIPTION="vmware tools kernel modules and init script for kernel 2.6.38.3-ylmfos"
HOMEPAGE="www.vmware.com"
REPO=""
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="vmware-tools-8.4.6-385536.tar.bz2"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

INSTALL="$N.install"
OPTIONS="nodev"

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_install() {	
	docp * "$destdir"
}
