#
# YLmf_OS package build script
#

DESCRIPTION="Perl extension for the DBus message system"
HOMEPAGE="http://search.cpan.org/dist/Net-DBus/"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"

SRC_URI="http://search.cpan.org/CPAN/authors/id/D/DA/DANBERR/Net-DBus-"$V".tar.gz"

RDEPEND="dbus glibc xml-twig"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	export PERL_MM_USE_DEFAULT=1
	doconfig INSTALLDIRS=vendor
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
        perl_cleanup
}

