#
# YLmf_OS package build script
#

DESCRIPTION="Perl extension for the DBus message system"
HOMEPAGE="http://search.cpan.org/dist/Net-DBus/"
LICENSE="GPL-2"
PACKAGER="hzx@115.com"

SRC_URI="http://search.cpan.org/CPAN/authors/id/D/DA/DANBERR/Net-DBus-"$V$R".tar.gz"

RDEPEND=""
BDEPEND="${RDEPEND} "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
}
