#
# YLmf_OS package build script
#

DESCRIPTION="Perl extension for the DBus message system"
HOMEPAGE="http://search.cpan.org/dist/Net-DBus/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/D/DA/DANBERR/Net-DBus-"$V".tar.gz"

RDEPEND="dbus glibc"
BDEPEND=" "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}
