#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="a toolkit to convert between various different translation formats"
HOMEPAGE="http://translate.sourceforge.net/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
GROUP="python"
YARCH="any"

SRC_URI="http://downloads.sourceforge.net/translate/translate-toolkit-$V.tar.bz2"

RDEPEND="py-lxml"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""
OPTIONAL="py-iniparse: to use ini2po script"

pbs_unpack() {
    dounpack
}

pbs_patch() {
    dopatch fix-locale.patch
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}
