#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="free implementation of Windows(tm) on Unix"
HOMEPAGE="http://www.winehq.org/"

SRC_URI="http://ibiblio.org/pub/linux/system/emulators/"$N"/"$N-$V".tar.bz2"

RDEPEND="alsa-lib audiofile cyrus-sasl  gcc-libs gettext glib2 gdk-pixbuf2 glibc gst-plugins-base gstreamer lcms libdrm libexif libgphoto2 libICE libSM libtool libX11 libXau libxcb libXdamage libXdmcp libXext libXfixes libxml2 libXxf86vm mesa mpg123 openal openldap openssl util-linux zlib"
BDEPEND="gsm sane-backends v4l-utils prelink"

pbs_unpack() {
    dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    #
    cd "$PKGDIR"
    docp $FILESDIR/menu/wine.menu          etc/xdg/menus/applications-merged/
    docp $FILESDIR/desktop/*.desktop       usr/share/applications/
    docp $FILESDIR/desktop-directories/*   usr/share/desktop-directories/
    docp $FILESDIR/icon/*                  usr/share/icons/hicolor/  
    docp $FILESDIR/pixmaps/*               usr/share/pixmaps/
}

