#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Cyrus Simple Authentication Service Layer (SASL) Library."
HOMEPAGE="http://asg.web.cmu.edu/sasl/"
LICENSE="custom"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>
          chenqixing@ivali.com"
 
SRC_URI="ftp://ftp.andrew.cmu.edu/pub/cyrus-mail/cyrus-sasl-"$V".tar.gz"
CHECKSUM="341cffe829a4d71f2a6503d669d5a946"

RDEPEND="glibc berkeley-db openssl zlib"
BDEPEND=""
RECOMMENDED=""

OPTIONS="nolibtool"

pbs_unpack() {
    dounpack
}

pbs_patch() {
    dopatch 0027_db5_support.patch
}

pbs_config() {
    config+="--with-plugindir=/usr/lib$LIBDIRSUFFIX/sasl2
             --with-pam
             --enable-ldapdb
             --with-ldap
             --disable-static
             --with-saslauthd=/run/saslauthd
             --with-devrandom=/dev/urandom"
    doconfig
}

pbs_build() {
    make 
}

pbs_install() {
    for dir in include lib sasldb plugins utils; do
        pushd ${dir}
        domkinstall sasldir=/usr/lib"$LIBDIRSUFFIX"/sasl2
        popd
    done
    dodoc COPYING
    cd "$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/sasl2
    # Provided by other packages
    rm -f libsql.* libgssapiv2.* libldapdb.* libgs2.*
}
