#!/bin/bash
#
# wrapper of systemctl start
#
echo " This is a wrapper of systemctl, e.g:"
echo " \"restart gdm\" to restart gdm"
echo

if [ "x$1" != "x" ]; then
	dm=${1%%.service}
	systemctl restart "$(basename $dm)".service
	systemctl status "$(basename $dm)".service
fi

exit 0

