#!/bin/sh

main() {
	#	
	filename="$1" 
	grep PCI_ANY_ID, $filename |while read line; do 
		echo $line |sed 's/PCI_ANY_ID.*//g' |sed 's/{ //g' |sed 's/,//g' |sed 's/0x//g'
	done  |while read a b; do
		printf "alias pci:v%08Xd%08Xsv*sd*bc*sc*i* %s %s\n" 0x$a "0x$b"
	done

}

#
echo "package madwifi-driver"
echo "module ath_pci.ko"
echo "description Support for Atheros 802.11 wireless LAN cards."
main ath/if_ath_pci.c

exit 0

