#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="MySQL database connector for C++ (mimics JDBC 4.0 API)"
HOMEPAGE="http://dev.mysql.com/downloads/"
LICENSE="custom"
PACKAGER="StartOS Developers"

SRC_URI="http://ftp.gwdg.de/pub/misc/mysql/Downloads/Connector-C++/"$N-$V".tar.gz"

RDEPEND="libmysqlclient"
BDEPEND="cmake"
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
    cmake . -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
            -DMYSQLCPPCONN_BUILD_EXAMPLES=OFF
}

pbs_build() {
    make -j1
}

pbs_install() {
    domkinstall
    cd "$PKGDIR"/usr
    domv README COPYING ANNOUNCEMENT share/doc/"$N"
}

