#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# klibc
cp -pL /usr/lib#LIBDIRSUFFIX#/klibc/bin/* ${DESTDIR}/bin
cp -pL /usr/lib#LIBDIRSUFFIX#/klibc/lib/klibc-*.so ${DESTDIR}//usr/lib#LIBDIRSUFFIX# 

rm -f ${DESTDIR}/bin/kinit* ${DESTDIR}/bin/zcat ${DESTDIR}/bin/gzip

if [ "${BUSYBOX}" = "n" ] || [ ! -e ${BUSYBOXDIR}/busybox ]; then
	mv ${DESTDIR}/bin/sh.shared ${DESTDIR}/bin/sh
fi
