#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# klibc
case $(uname -m) in
 i?86) 
    cp -pL /usr/lib/klibc/bin/* ${DESTDIR}/bin
  	cp -pL /usr/lib/klibc/lib/klibc-*.so ${DESTDIR}/lib ;;
 x86_64)		
  	cp -pL /usr/lib64/klibc/bin/* ${DESTDIR}/bin
	cp -pL /usr/lib64/klibc/lib/klibc-*.so ${DESTDIR}/lib 
esac

rm -f ${DESTDIR}/bin/kinit* ${DESTDIR}/bin/zcat ${DESTDIR}/bin/gzip

if [ "${BUSYBOX}" = "n" ] || [ ! -e ${BUSYBOXDIR}/busybox ]; then
	mv ${DESTDIR}/bin/sh.shared ${DESTDIR}/bin/sh
fi

