#
# Ylmf OS package build script
#

DESCRIPTION="The Boehm-Demers-Weiser conservative garbage collector"
HOMEPAGE="http://www.hpl.hp.com/personal/Hans_Boehm/gc/"
REPO=""
LICENSE=""
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.hpl.hp.com/personal/Hans_Boehm/"$N"/"${N}"_source/"$N-$V$R".tar.gz"

RDEPEND=""
BDEPEND=" "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc ChangeLog
}
