#
# YLmf_OS package build script
#

DESCRIPTION="Read and write meta information"
HOMEPAGE="http://search.cpan.org/~exiftool/Image-ExifTool-8.50/lib/Image/ExifTool.pod"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"
LICENSE="GPL PerlArtistic"
YARCH="any"

SRC_URI="http://search.cpan.org/CPAN/authors/id/E/EX/EXIFTOOL/Image-ExifTool-"$V".tar.gz"

RDEPEND="perl"
BDEPEND=" "
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	ypkg_config INSTALLDIRS=vendor
} 

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

