#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A sophisticated object-relational DBMS"
HOMEPAGE="http://www.postgresql.org/"
LICENSE="custom:PostgreSQL"
PACKAGER="StartOS Developers"

SRC_URI="ftp://ftp.postgresql.org/pub/source/v"$V"/"$N-$V".tar.bz2"
CHECKSUM="7dbff52221954c46595313eb7f92c3e0"

PROVIDE="postgresql postgresql-libs postgresql-docs"

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=" --datadir=/usr/share/postgresql
	          --with-libxml 
		  --with-openssl 
		  --with-perl 
		  --with-python 
		  --with-pam
	          --with-system-tzdata=/usr/share/zoneinfo 
		  --enable-nls 
		  --enable-thread-safety "
	doconfig
}

pbs_build() {
	domake world
}

postgresql_install() {
	DESCRIPTION="A sophisticated object-relational DBMS"
	RDEPEND="postgresql-libs libxml2 readline(>=6.0) openssl(>=1.0.0)"
	
	INSTALL="$N".install

        # install
	domkinstall
	make -C contrib DESTDIR="$destdir" install
	make -C doc/src/sgml DESTDIR="$destdir" install-man

	# we don't want these, they are in the -libs package
	for dir in src/interfaces src/bin/pg_config src/bin/psql; do
		make -C "${dir}" DESTDIR="$destdir" uninstall
	done
	
	# install license
	dodoc COPYRIGHT

        # clean up unneeded installed items
	cd "$destdir"
	rm -rf usr/share/man usr/include usr/share/doc/postgresql/html

	# install conf file
	docp_rename "$filesdir"/postgresql.confd     etc/conf.d/postgresql
	docp_rename "$filesdir"/postgresql.pam       etc/pam.d/postgresql
	docp_rename "$filesdir"/postgresql.logrotate etc/logrotate.d/postgresql
	cd -
}

postgresql-libs_install() { 
	DESCRIPTION="libraries and client of PostgreSQL"
	RDEPEND="openssl(>=1.0.0) readline(>=6.0)"
	
	# install license
	dodoc COPYRIGHT

        # install libs
        for dir in src/interfaces src/bin/pg_config src/bin/psql; do
		domkinstall -C "${dir}"
	done

	doman doc/src/sgml/man1/pg_config.1
	doman doc/src/sgml/man1/psql.1

	cd src/include

	# these headers are needed by the public headers of the interfaces
	docp pg_config.h pg_config_os.h postgres_ext.h pg_config_manual.h "${destdir}"/usr/include/
	docp libpq/libpq-fs.h                                             "${destdir}"/usr/include/libpq/

	# these headers are needed by the not-so-public headers of the interfaces
	docp c.h port.h postgres_fe.h  "$destdir"/usr/include/postgresql/internal/
	docp libpq/pqcomm.h            "$destdir"/usr/include/postgresql/internal/libpq/

	cd -
}

postgresql-docs_install() {
	DESCRIPTION="HTML documentation for PostgreSQL"
      
      	# install license
        dodoc COPYRIGHT

	make -C doc/src/sgml DESTDIR="$destdir" install-html
	
	cd "$destdir"
	chown -R root:root usr/share/doc/postgresql/html/
	rm -rf usr/share/man
	cd -
}


