#
# YLmf_OS package build script
#

DESCRIPTION="An interpreted, interactive, object-oriented programming language."
HOMEPAGE="http://www.python.org/"
REPO=""
LICENSE=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://www.python.org/ftp/"$N"/"$V"/Python-"$V$R".tar.bz2"

RDEPEND="berkeley-db expat fontconfig freetype gdbm glibc libX11 libXau libxcb libXdmcp libXext libXft libXrender libXScrnSaver ncurses openssl readline sqlite tcl tk zlib"
BDEPEND="berkeley-db-dev expat-dev fontconfig-dev freetype-dev gdbm-dev glibc-dev libX11-dev libXau-dev libxcb-dev libXdmcp-dev libXext-dev libXft-dev libXrender-dev libXScrnSaver-dev ncurses-dev openssl-dev readline-dev sqlite-dev tcl-dev tk-dev zlib-dev"

pbs_unpack() {
        ypkg_unpack
}

pbs_config(){
	#YPB_CONFIG+="--enable-shared"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	make DESTDIR="$YPPATH_DEST" install
}
