#
# Ylmf OS package build script
#

DESCRIPTION="An interpreted, interactive, object-oriented programming language."
HOMEPAGE="http://www.python.org/"
LICENSE="custom"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://www.python.org/ftp/"$N"/"$V"/Python-"$V".tar.bz2"

RDEPEND="berkeley-db bzip2 expat fontconfig freetype gdbm glibc libX11 libXau libxcb libXdmcp libXext libXft libXrender libXScrnSaver ncurses openssl readline sqlite tcl tk zlib"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config(){
	config+="--enable-shared 
	         --with-threads 
		 --with-system-expat 
		 --with-system-ffi"
	doconfig
}

pbs_build() {
	make "$MAKEOPTS"
}

pbs_install() {
	make "$MAKEOPTS" DESTDIR="$destdir" install
}

