#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="An interpreted, interactive, object-oriented programming language."
HOMEPAGE="http://www.python.org/"
LICENSE="PSF"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://www.python.org/ftp/python/"$V"/Python-"$V".tar.xz"
CHECKSUM="b2b0ada7ebed4a8204a855193afbdb3aa3308357"

RDEPEND="bzip2 gdbm openssl zlib expat sqlite libffi readline"
BDEPEND="tk"
OPTIONAL="tk: for IDLE" 

pbs_unpack() {
    dounpack
}

pbs_patch() {
    #
    dopatch startos_add-platform-2.7.2.patch
    #
    dopatch python-2.7-010-change-pyconfig-h-location.patch
    # Change the libdir that Python is going to use to lib64:
    dopatch python-2.7.3-multilib.patch
    sed -i -e "s|@@MULTILIB_DIR@@|lib"$LIBDIRSUFFIX"|g" Lib/distutils/command/install.py \
           Lib/distutils/sysconfig.py \
               Lib/pydoc.py \
                  Lib/site.py \
                  Lib/sysconfig.py \
               Lib/test/test_dl.py \
                  Lib/test/test_site.py \
                 Lib/trace.py \
                 Makefile.pre.in \
                 Modules/getpath.c \
                 setup.py
    # Temporary workaround for 
    # See http://bugs.python.org/issue10835 for upstream report
    sed -i "/progname =/s/python/python2.7/" Python/pythonrun.c
    # Enable built-in SQLite module to load extensions
    sed -i "/SQLITE_OMIT_LOAD_EXTENSION/d" setup.py
    # FS#23997
    sed -i -e "s|^#.* /usr/local/bin/python|#!/usr/bin/python|" Lib/cgi.py

    # Ensure that we are using the system libraries (expat, zlib and libffi), rather than copies shipped in the tarball.
    rm -r Modules/expat
    rm -r Modules/zlib
    rm -r Modules/_ctypes/{darwin,libffi}*
}

pbs_config(){
    export OPT="${CFLAGS}"
    config+="--enable-shared 
             --with-threads 
             --enable-ipv6
             --enable-unicode=ucs4
             --with-system-expat
             --with-system-ffi
             --with-dbmliborder=gdbm:ndbm"
    doconfig
}

pbs_build() {
    make "$MAKEOPTS"
}

pbs_install() {
    make DESTDIR="$PKGDIR" install #altinstall maninstall
    dodoc LICENSE
    cd "$PKGDIR"/usr/lib"$LIBDIRSUFFIX"/    
    doln python2.7 python  
}

