#
# YLmf_OS package build script
#

DESCRIPTION="An interpreted, interactive, object-oriented programming language."
HOMEPAGE="http://www.python.org/"
REPO=""
LICENSE=""
PACKAGER="Zhongxin Huang, hzx@115.com"

SRC_URI="http://www.python.org/ftp/"$N"/"$V"/Python-"$V$R".tar.bz2"

RDEPEND=""
BDEPEND="${RDEPEND}"

pbs_unpack() {
        ypkg_unpack
}

pbs_config(){
	#YPB_CONFIG+="--enable-shared"
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	make DESTDIR="$YPPATH_DEST" install
}
