#
# Ylmf OS package build script
#

DESCRIPTION="Python bindings for the CUPS API"
HOMEPAGE="http://cyberelk.net/tim/data/pycups/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"

SRC_URI="http://cyberelk.net/tim/data/"$N"/"$N-$V".tar.bz2"

RDEPEND="avahi cups dbus e2fsprogs gcc-lib glibc gnutls keyutils krb5 libgcrypt libgpg-error libtasn1 python zlib"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
        dounpack
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc ChangeLog COPYING NEWS README 
}

