#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Python bindings for the CUPS API"
HOMEPAGE="http://cyberelk.net/tim/data/pycups/"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://cyberelk.net/tim/data/"$N"/"$N-$V".tar.bz2"

RDEPEND="cups python"
BDEPEND=""
RECOMMENDED=""

pbs_unpack() {
    dounpack
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall --optimize=1
}



