#
# YLmf_OS package build script
#

DESCRIPTION="Python bindings for the CUPS API"
HOMEPAGE="http://cyberelk.net/tim/data/pycups/"
LICENSE="GPL-2"
PACKAGER="<ylmfos@115.com>"

SRC_URI="http://cyberelk.net/tim/data/"$N"/"$N-$V$R".tar.bz2"

RDEPEND="cups e2fsprogs glibc gnutls keyutils krb5 libgcrypt libgpg-error libtasn1 python zlib"
BDEPEND="          "
RECOMMENDED=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
	ypkg_dodoc ChangeLog COPYING NEWS README 
}
