#
# Ylmf OS package build script
#
# Copyright 2005-2012 Ylmf OS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Userspace access to USB devices"
HOMEPAGE="http://libusb.org/"
 
SRC_URI="http://downloads.sourceforge.net/libusb/$N-$V.tar.bz2"

RDEPEND=""
BDEPEND=""

pbs_unpack()
{
        dounpack
}

pbs_config()
{
	
	config+=" --prefix=/usr "
	doconfig
}

pbs_build()
{
	domake
}

pbs_install()
{
	domkinstall
}
