#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl Module: Easy manipulation of IPv4 and IPv6 addresses"
HOMEPAGE="http://search.cpan.org/dist/Net-IP"
LICENSE="GPL,PerlArtistic"
GROUP="perl"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
YARCH="any"

SRC_URI="http://www.cpan.org/authors/id/M/MA/MANU/Net-IP-$V.tar.gz"
CHECKSUM="a49c0b02a9b793ff60191cdafc0c202e"

RDEPEND="perl"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1 PERL5LIB="" \
           PERL_AUTOINSTALL=--skipdeps \
           PERL_MM_OPT="INSTALLDIRS=vendor" \
           PERL_MB_OPT="--installdirs vendor" \
           MODULEBUILDRC=/dev/null
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}
