#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Provide https support for LWP::UserAgent"
HOMEPAGE="http://search.cpan.org/~gaas/LWP-Protocol-https"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
LICENSE="GPL,PerlArtistic"
GROUP="perl"
YARCH="any"

SRC_URI="http://search.cpan.org/CPAN/authors/id/G/GA/GAAS/LWP-Protocol-https-$V.tar.gz"
CHECKSUM="2a9341732172da290fe1b5af98a015a7"

RDEPEND="perl-io-socket-ssl perl-libwww perl-mozilla-ca perl-net-http"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1 PERL5LIB="" \
           PERL_AUTOINSTALL=--skipdeps \
           PERL_MM_OPT="INSTALLDIRS=vendor" \
           PERL_MB_OPT="--installdirs vendor" \
           MODULEBUILDRC=/dev/null
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}
