#
# Ylmf OS package build script
#

DESCRIPTION="Larry Wall's Practical Extraction and Report Language"
HOMEPAGE="http://www.perl.org/"
 
SRC_URI="http://www.cpan.org/src/5.0/"$N-$V$R".tar.bz2"

RDEPEND="berkeley-db gdbm glibc zlib"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	#This version of Perl now builds the Compress::Raw::Zlib module. 
	#By default Perl will use an internal copy of the Zlib source 
	#for the build. Issue the following command so that Perl 
	#will use the Zlib library installed on the system: 
	sed -i -e "s|BUILD_ZLIB\s*= True|BUILD_ZLIB = False|" 		\
	       -e "s|INCLUDE\s*= ./zlib-src|INCLUDE    = /usr/include|" \
	       -e "s|LIB\s*= ./zlib-src|LIB        = /usr/lib|"         \
       		cpan/Compress-Raw-Zlib/config.in
	config="-des -Dprefix=/usr 	      
		    -Dvendorprefix=/usr       
  		    -Dman1dir=/usr/share/man/man1 
		    -Dman3dir=/usr/share/man/man3 "
	sh Configure $config -Dpager="/usr/bin/less -isR"
	#config+=" -Dpager=\"/usr/bin/less -isR\""
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}
