#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="create an X cursor file from a collection of PNG images"
HOMEPAGE="http://xorg.freedesktop.org/"
GROUP="x11-apps"
 
SRC_URI="http://www.x.org/releases/X11R7.5/src/app/$N-$V$R.tar.bz2"

RDEPEND="libX11 libXcursor libpng libxcb libXrender libXfixes libXau libXdmcp zlib"
BDEPEND=" x11-libs/libXcursor media-libs/libpng x11-libs/libXcursor"

pbs_unpack() {
        dounpack
}

pbs_config() {
    
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    install -m755 -d "$destdir"/usr/share/doc/"$N-$V$R"
    cp -a AUTHORS ChangeLog COPYING INSTALL NEWS README   "$destdir"/usr/share/doc/"$N-$V$R"
}
