#
# Ylmf OS package build script
#

DESCRIPTION="create an X cursor file from a collection of PNG images"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@ylmf.com>"
 
SRC_URI="http://www.x.org/releases/X11R7.6/src/app/"$N-$V".tar.bz2"

RDEPEND="glibc libpng libX11 libXau libxcb libXcursor libXdmcp libXfixes libXrender zlib"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

