#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="create an X cursor file from a collection of PNG images"
HOMEPAGE="http://xorg.freedesktop.org/"
GROUP="x11-apps"
LICENSE="GPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"
 
SRC_URI="http://www.x.org/releases/X11R7.6/src/app/"$N-$V".tar.bz2"

RDEPEND="glibc libpng libX11 libXau libxcb libXcursor libXdmcp libXfixes libXrender zlib"
BDEPEND=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

