#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="create an X cursor file from a collection of PNG images"
HOMEPAGE="http://xorg.freedesktop.org/"
LICENSE="custom"
PACKAGER="StartOS Developers"
GROUP="x11-apps"
 
SRC_URI="http://xorg.freedesktop.org/releases/individual/app/"$N-$V".tar.bz2"

RDEPEND="libpng libXcursor"
BDEPEND=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	dodoc COPYING
}

