#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl module IPC-Run3"
HOMEPAGE="http://search.cpan.org/~adamk/File-Which-1.09/"
REPO=""
LICENSE="GPL-2"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://search.cpan.org/CPAN/authors/id/R/RJ/RJBS/IPC-Run3-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=" test-script"

pbs_unpack() {
        dounpack
}

pbs_config() {
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
        perl_cleanup
}
