#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Library to enable user space application programs to communicate with USB devices"
HOMEPAGE="http://libusb.sourceforge.net/"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://downloads.sourceforge.net/libusb/"$N-$V".tar.bz2"
CHECKSUM="2ca521fffadd0c28fdf174e6ec73865b"

RDEPEND="libusbx"
BDEPEND="pkgconfig"

pbs_unpack() {
    dounpack
}

pbs_config() {
	config+="--disable-static"
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
}

