#
# YLmf_OS package build script
#

DESCRIPTION="OpenSSL extension to Tcl"
HOMEPAGE="http://tls.sourceforge.net/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://downloads.sourceforge.net/tls/tls"$V$R"-src.tar.gz"

RDEPEND="glibc openssl zlib"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
        dounpack
}

pbs_config() {
	config+=""
	doconfig
}

pbs_build() {
	domake
}

pbs_install() {
	domkinstall
	doln /usr/lib/tls1.6/libtls1.6.so "$destdir"/usr/lib/libtls1.6.so
}

