#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="Perl extension for the SANE (Scanner Access Now Easy) Project"
HOMEPAGE="http://search.cpan.org/~ratcliffe/Sane"
LICENSE="GPL,PerlArtistic"
GROUP="perl"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://mirrors.ustc.edu.cn/CPAN/authors/id/R/RA/RATCLIFFE/Sane-"$V".tar.gz"

RDEPEND="perl sane-backends cups"
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    export PERL_MM_USE_DEFAULT=1
    doconfig INSTALLDIRS=vendor
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
    perl_cleanup
}
