
gname="xbmc"

post_install() {
    gtk-update-icon-cache -qtf /usr/share/icons/hicolor
    update-desktop-database -q /usr/share/applications
    dogroupadd "$gname"
    douseradd -m -d /var/lib/xbmc -g "$gname" "$gname"
    usermod -a -G xbmc,audio,video,power,network,optical,storage,disk "$gname"
}

post_remove() {
    douserdel "$gname"
    dogroupdel "$gname"
}

post_upgrade() {
    post_install
}
