#
# YLmf_OS package build script
#

DESCRIPTION="Interface to zlib compression library  "
HOMEPAGE="http://search.cpan.org/~pmqs/Compress-Zlib/"
REPO=""
LICENSE="GPL"
PACKAGER="Ylmf OS Developers <ylmfos@115.com>"

SRC_URI="http://mirrors.sohu.com/CPAN/authors/id/P/PM/PMQS/Compress-Zlib-"$V$R".tar.gz"

RDEPEND=""
BDEPEND=""
RECOMMENDED=""
CONFLICT=""

NOTES=""

pbs_unpack() {
        ypkg_unpack
}

pbs_config() {
	YPB_CONFIG+=""
	ypkg_config
}

pbs_build() {
	ypkg_make
}

pbs_install() {
	ypkg_mkinstall
        perl_cleanup
}

