#
# StartOS package build script
#
# Copyright 2012 StartOS
# Distributed under the terms of the GNU General Public License v2
#

DESCRIPTION="A C++ API for gtksourceview2"
HOMEPAGE="http://projects.gnome.org/gtksourceviewmm"
LICENSE="LGPL"
PACKAGER="Zhongxin Huang <huangzhongxin@ivali.com>"

SRC_URI="http://ftp.gnome.org/pub/GNOME/sources/"${N%?}"/2.10/"${N%?}-$V".tar.xz"
CHECKSUM=""

RDEPEND="gtkmm gtksourceview2"
RECOMMENDED=""
BDEPEND=""
OPTIONAL=""
CONFLICT=""

pbs_unpack() {
    dounpack
}

pbs_config() {
    config+=""
    doconfig
}

pbs_build() {
    domake
}

pbs_install() {
    domkinstall
}

